### ISSUE TITLE
bug: Error installing the lts version

### ISSUE THREAD

**Issue by gui1612** [asdf-vm/asdf#1006]
### Describe the Bug

The lts alias doesn't seem to be redirecting to the right path. I can proceed with installing `nodejs latest` and also typing manually the lts version (`asdf install nodejs 14.17.3`), however when I try to install lts from the alias I get the error:
`Installing alias lts as 14.17.3`
`bash: /home/$USER/.asdf/plugins/../bin/install: No such file or directory`
`Could not install version 14.17.3`

You can check the error in [here](https://i.stack.imgur.com/h65Qs.png).

### Steps to Reproduce

1. ``asdf plugin-add nodejs``
2. ``asdf install nodejs lts``

### Expected Behaviour

This should start the install process

### Actual Behaviour

`Installing alias lts as 14.17.3`
`bash: /home/$USER/.asdf/plugins/../bin/install: No such file or directory`
`Could not install version 14.17.3`

### Environment

```shell
OS:
Linux pcgui 5.13.4-arch1-1 #1 SMP PREEMPT Tue, 20 Jul 2021 16:58:51 +0000 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-pc-linux-gnu)

ASDF VERSION:
v0.8.1-a1ef92a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/gui1612/.asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
```

**Comment by jthegedus** [comment]
Thanks for reporting, but this issue is specific to the [`asdf-nodejs`](https://github.com/asdf-vm/asdf-nodejs) plugin so should be raised there.
