### ISSUE TITLE
bug: go plugin doesn't set GOPATH and also seems to install packages as root

### ISSUE THREAD

**Issue by lifeiscontent** [asdf-vm/asdf#1027]
### Describe the Bug

```bash
asdf install golang 1.16.6
export GO111MODULE=on
go get -u github.com/viaduct-ai/kustomize-sops
cd ~/.asdf/installs/golang/1.16.6/packages/pkg/mod/pkg/mod/github.com/viaduct-ai/kustomize-sops@v0.0.0-20210810170524-6eb81aa0af47
make kustomize
```

make kustomize should not error, but does due to how asdf installs go packages

### Steps to Reproduce

asdf install golang 1.16.6
export GO111MODULE=on
go get -u github.com/viaduct-ai/kustomize-sops
cd ~/.asdf/installs/golang/1.16.6/packages/pkg/mod/pkg/mod/github.com/viaduct-ai/kustomize-sops@v0.0.0-20210810170524-6eb81aa0af47
make kustomize

### Expected Behaviour

go installs packages as the current user

### Actual Behaviour

go installs packages as root user

### Environment

```shell
OS:
Linux aaronreisman-XPS-13-9310 5.10.0-1044-oem #46-Ubuntu SMP Wed Aug 11 09:50:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.8.1-a1ef92a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/aaronreisman/.asdf

ASDF INSTALLED PLUGINS:
golang                       https://github.com/kennyp/asdf-golang.git
```

### asdf plugins affected (if relevant)

asdf-golang

**Comment by jthegedus** [comment]
This sounds specific to the golang plugin, can you raise this issue on the plugin repo and work with the author to identify if it is the `asdf` core before re-opening? Thanks

**Comment by lifeiscontent** [comment]
@jthegedus I have, but it seems like the maintainer is M.I.A.

**Comment by jthegedus** [comment]
That's unfortunate. We don't really have the expertise in the core to cover all bugs in all plugins. You can check GitHub/GitLab etc for other Go plugins as there may be others more well maintained.
