### ISSUE TITLE
bug: incorrect help for plugin extensions of hyphenated named plugin

### ISSUE THREAD

**Issue by yacchi** [asdf-vm/asdf#1034]
### Describe the Bug

When a plugin with a hyphen in its name contains an extension command (lib/commands/commands-*), the `-` in the plugin name displayed by `asdf help` will be blank.

However, the extension command cannot be executed unless the correct plugin name is specified.

### Steps to Reproduce

1. Install a plugin whose name contains a hyphen and has an extension command (e.g. go-sdk)
2. Display the asdf help and review the list of extension commands.
3. If you run the extension commands of the installed plug-in as shown, you will get an error.

### Expected Behaviour

```shellscript
> asdf help
version: v0.8.1-a1ef92a

... asdf's help messages

PLUGIN go-sdk
  asdf go-sdk sync

"Late but latest"
-- Rajinikanth
> asdf go-sdk sync
```

### Actual Behaviour

```shellscript
> asdf help
version: v0.8.1-a1ef92a

... asdf's help messages

PLUGIN go sdk
  asdf go sdk sync

"Late but latest"
-- Rajinikanth
> asdf go sdk sync
Unknown command: `asdf go sdk sync`
No plugin named go
```

### Environment

```shell
OS:
Linux 0e59374131a1 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.8.1-a1ef92a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/root/.asdf

ASDF INSTALLED PLUGINS:
go-sdk                       https://github.com/yacchi/asdf-go-sdk.git
```

**Comment by yacchi** [comment]
I modified it as in the following commit, and it now works as expected for both hyphenated and non-hyphenated plugins.

https://github.com/yacchi/asdf/commit/8768cc06d1056d04f1ad2df682426c57a5ef0a6e

**Comment by jthegedus** [comment]
Good catch, thanks for investigating. Feel free to submit a PR!

That new `sed` looks a bit hard to understand (not that the current is much better), is there a way to combine the `sed` search and replace with named vars as placeholders?

**Comment by yacchi** [comment]
@jthegedus

Thank you for looking at the code.

I did find the new `sed` usage hard to understand too.
Since you said that the current sed is not very good either, I thought of another way.

To compare the clarity of the different ways of writing, I rewrote it to use a bash loop.
The code is longer, but I think it will be easy for everyone to understand.
https://github.com/yacchi/asdf/commit/7f45e8fcf1f0572ed70fe9afdadb24f18408581a

Also, you can include functions such as displaying the usage of extension commands while maintaining readability.
(The code is a sample for explanation purposes only.)
https://github.com/yacchi/asdf/commit/d55ed75c494d2604bc47261e1feec855e71af27e

```shellscript
...
asdf update                             Update asdf to the latest stable release
asdf update --head                      Update asdf to the latest on the master branch

RESOURCES
GitHub: https://github.com/asdf-vm/asdf
Docs:   https://asdf-vm.com

PLUGIN direnv
  asdf direnv
  asdf direnv hook asdf

PLUGIN go-sdk
  asdf go-sdk sync                      Synchronize installed or uninstalled go sdk without using asdf
...
```
