### ISSUE TITLE
asdf list could return the latest version available vs what's installed locally

### ISSUE THREAD

**Issue by scalp42** [asdf-vm/asdf#1036]
### Is your feature request related to a problem? Please describe

While setting versions in `.tool-versions` is awesome, it'd be great to have a way to know when a new version is available.

### Describe the proposed solution

When typing `asdf list`, it'd print the latest version available:

```
$> asdf list

ruby (latest is 3.0.2)
  2.7.3
  3.0.1
terraform (latest is 1.0.5)
  0.14.4
  0.15.5
  1.0.4
```

### Describe similar `asdf` features and why they are not sufficient

`asdf latest X` work but it becomes cumbersome when the list starts growing.

### Describe other workarounds you've considered

Just scripting using `asdf list`, `asdf info` and `asdf latest`

PS: thank you very much and no matter what, `asdf` is awesome!

**Comment by jthegedus** [comment]
Hmm, this would add a call to `asdf latest <plugin>` per plugin in the list, slowing down the currently local-only command. We want to avoid network calls if we can.

Perhaps if we capture this under a flag `asdf list --show-latest` or an `.asdfrc` config value it would preserve existing local-only behaviour.

**Comment by scalp42** [comment]
Yes, totally agree re keeping it local.

**Comment by jthegedus** [comment]
Just thinking out loud, perhaps a command `asdf latest --all` which calls `asdf latest <plugin>` for each plugin you have installed and a marker for if you have that latest version installed?

```
$> asdf list

ruby
  2.7.3
  3.0.1
terraform
  0.14.4
  0.15.5
  1.0.4

$> asdf latest --all

ruby      3.0.1    installed
terraform 1.0.5    missing
```

Would this grant you the information you are after?

**Comment by scalp42** [comment]
yes, it'd be perfect!
