### ISSUE TITLE
bug: Don't work reshim for NPM dependencies

### ISSUE THREAD

**Issue by Vmelnikoff** [asdf-vm/asdf#1043]
### Describe the Bug

I install node 16.8.0, add a global dependency of lite-server, then install node 16.9.0, do reshim

### Steps to Reproduce

asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs 16.8.0
asdf global nodejs 16.8.0
user:~
└─ ▶ node -v
v16.8.0
user:~
└─ ▶ npm -v
7.21.0
npm i -g lite-server
user:~
└─ ▶ which lite-server
/home/user/.asdf/shims/lite-server

asdf install nodejs 16.9.0
asdf global nodejs 16.9.0
asdf reshim nodejs 16.9.0

user:~
└─ ▶ which lite-server
/home/user/.asdf/shims/lite-server
user:~
└─ ▶ lite-server
No preset version installed for command lite-server
Please install a version by running one of the following:

asdf install nodejs 16.9.0

or add one of the following versions in your config file at /home/user/.tool-versions
nodejs 16.8.0
user:~
└─ ▶ asdf install nodejs 16.9.0
nodejs 16.9.0 is already installed

### Expected Behaviour

I expect that the lite-server will work in the new version of node without additional installation (using reshim).

### Actual Behaviour

user:~
└─ ▶ lite-server
No preset version installed for command lite-server
Please install a version by running one of the following:

asdf install nodejs 16.9.0

or add one of the following versions in your config file at /home/user/.tool-versions
nodejs 16.8.0
user:~
└─ ▶ asdf install nodejs 16.9.0
nodejs 16.9.0 is already installed

P.s. When switching back to 16.8.0, everything works.

### Environment

```shell
OS:
Linux user 5.11.0-34-generic #36-Ubuntu SMP Thu Aug 26 19:22:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.8.1-a1ef92a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/user/.asdf
```

### asdf plugins affected (if relevant)

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git

**Comment by jthegedus** [comment]
This is specific to the `asdf-nodejs` plugin, can you raise the issue on that repo? After ruling out an issue with the specific plugin you can reopen this issue in the core.
