### ISSUE TITLE
circleci orb

### ISSUE THREAD

**Issue by pvinis** [asdf-vm/asdf#1065]
### Is your feature request related to a problem? Please describe

It's so good to use asdf locally, but it's so annoying to figure out how to set up circleci's tools.

I would love it if I could import an orb and have asdf installed, and do `- asdf/install` to install all the things, and done!

### Describe the proposed solution

Adding an orb
https://circleci.com/orbs/

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

N/A

**Comment by jthegedus** [comment]
An "official" CircleCI Orb is not something the asdf core team has the knowledge or time to develop.

This is perfect for a community solution.

We are happy to link to community projects in our documentation to direct people how to utilise asdf in CI systems not officially supported by the core team (we have official support for [GitHub Actions](https://github.com/asdf-vm/actions)).

Closing this as we are not going to implement it ourselves.

**Comment by rynkowsg** [comment]
@jthegedus @pvinis I started working recently on orb to support asdf.
At this moment it only provides command to install asdf, but more comming soon:
- cache, restore
- support for installation of plugin/s with specific url and version/sha
- support for selective installation of tools

Link to repo: https://github.com/rynkowsg/asdf-orb

Link to job showing how you could use it: https://github.com/rynkowsg/asdf-orb/blob/main/.circleci/config.yml#L20
