### ISSUE TITLE
Flag to force asdf-plugins update

### ISSUE THREAD

**Issue by mathew-fleisch** [asdf-vm/asdf#1081]
### Is your feature request related to a problem? Please describe

I have been developing a few asdf plugins recently and I think there should be a way to force the update of the asdf-plugins repo. When I listed all repos, I think I didn't meet the criteria to fetch latest from master to see my newly merged plugin.

### Describe the proposed solution

It would be nice if there was a flag or argument that allows a user to update this repo on-demand, if they want to verify all new plugins have been added to their list.

### Describe similar `asdf` features and why they are not sufficient

I'm not exactly sure how this part works, but it looks like it doesn't always pull the latest from asdf-plugins
Perhaps adding another flag to the list-all command that would force an update first
https://github.com/asdf-vm/asdf/blob/master/lib/utils.bash#L382-L420

### Describe other workarounds you've considered

Manually navigating to the asdf-plugins repo and running `git pull`

**Comment by jthegedus** [comment]
This should do what you wish - https://asdf-vm.com/manage/configuration.html#plugin-repository-last-check-duration

**Comment by mathew-fleisch** [comment]
Nice. thanks!

**Comment by jthegedus** [comment]
I think this is only available on `asdf update --head` as we are/were waiting to close out the remaining `0.9.x` goals - https://github.com/asdf-vm/asdf/milestone/2
