### ISSUE TITLE
Document comments for `.tool-versions` files

### ISSUE THREAD

**Issue by kenny-evitt** [asdf-vm/asdf#1091]
### Is your feature request related to a problem? Please describe

I would like to comment my `.tool-versions` file. Apparently this is possible:

- [Comments in .tool-versions file · Issue #489 · asdf-vm/asdf](https://github.com/asdf-vm/asdf/issues/489)

### Describe the proposed solution

Add text to the existing docs about comments in these files:

- [Configuration | asdf](http://asdf-vm.com/manage/configuration.html#tool-versions)

### Describe similar `asdf` features and why they are not sufficient

I can record comments elsewhere, i.e. NOT in the `.tool-versions` file, and `asdf` seems to support comments anyways, but the docs don't mention that or provide any examples, so it seemed like there was no comment support.

### Describe other workarounds you've considered

I now know that comments are supported, but it'd be nice to mention this too in the docs.

**Comment by Stratus3D** [comment]
PR welcome! No reason this wasn't added to the docs, it just got overlooked.

**Comment by kenny-evitt** [comment]
@Stratus3D I figured as much but the issue template kinda 'forced' me to be a little 'stiffer' describing this than I would have been otherwise!
