### ISSUE TITLE
bug: Incorrect auto assignment of ASDF_DATA_DIR breaks PATH for shims

### ISSUE THREAD

**Issue by jaclu** [asdf-vm/asdf#1104]
### Describe the Bug

Edit: I hadn't noticed that v0.9.0 was available, so I updated my env, but the bug remains.

In the v0.9.0  version of asdf,  /asdf.sh line 26: ``` ASDF_USER_SHIMS="${ASDF_DATA_DIR:-$HOME/.asdf}/shims" ```
should be: ``` ASDF_USER_SHIMS="$ASDF_DIR/shims" ``` similar to when  ASDF_BIN is assigned at the line above. Since ASDF_DIR is correctly detected on line 15 based on where this script is run.

If you want to still honor ASDF_DATA_DIR, it should be used when assigning ASDF_DIR however, since you autodetect the correct ASDF_DIR,  ASDF_DATA_DIR does not seem to serve any meaningful purpose inside asdf, since the user used the correct path to trigger /asdf.sh is enough to set ASDF_DIR, and it does not seem to be the task of asdf to dictate what variable name if any the user uses to locate asdf :)

### Steps to Reproduce

1. Move .asdf to any other location
2. Disable calling ~/.asdf/asdf.sh in your init scripts to be able to ensure clean env before initiating asdf
3. login to that system ssh localhost or similar, starting a subshell even with -l inherits ASDF env settings from parent shell so will not give correct info, based on the current status of things.
4.  ``` env |grep -i asdf ```   - should not give any output related to PATH or ASDF_DIR at this point, if it does, just do that login, starting a new shell in tmux etc is not a valid replacement for a login. Repeat until no PATH or ASDF_DIR stuff is listed
5.  ``` .  /correct/location/for/asdf/asdf.sh ```
6. ``` env |grep -i asdf ```    - observe PATH and ASDF_DIR

### Expected Behaviour

```
PATH=/correct/location/for/asdf/shims:/correct/location/for/asdf/bin:
ASDF_DIR=/correct/location/for/asdf
```

### Actual Behaviour

```
PATH=/home/username/.asdf/shims:/correct/location/for/asdf/bin:
ASDF_DIR=/correct/location/for/asdf
```

### Environment

```shell
1. There is no asdf-info ... I assume you meant: asdf info
as in the "asdf plugins affected" section below :)

2. Can't actually be done if asdf is not located at ~/.asdf without tweaking the asdf env manually.

If I move it to ~/.asdf I get the following, personal info excluded.

OS:
Darwin XXX.XXX.XXX 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.1.0)

ASDF VERSION:
v0.9.0-9ee24a3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/foobar/.asdf

ASDF INSTALLED PLUGINS:
direnv                       https://github.com/asdf-community/asdf-direnv.git
meson                        https://github.com/asdf-community/asdf-meson.git
ninja                        https://github.com/asdf-community/asdf-ninja.git
python                       https://github.com/danhper/asdf-python.git
tmux                         https://github.com/aphecetche/asdf-tmux.git
```

**Comment by jthegedus** [comment]
Probably related to #1108 @ericbn

**Comment by jaclu** [comment]
That does not seem to be the case, after digging a bit it turns out that this incorrect assignment was introduced Sep 16, 2018

The reason I didn't get bit by it before was that this is the first time I experimented with not bothering to do a soft link to ~/.asdf when having asdf in a different location. After noticing ASDF_DIR is correctly picked up as one of the very first thing happening when asdf.sh is run. I decided to try to get rid of ~/.asdf due to it not being really needed, and wanting to reduce the amount of .dotfiles that serve no real purpose.

If you do set ASDF_DATA_DIR it works as intended in my usage case. However,  forcing the usage of an env variable whose only purpose seems to be to overcome a mistaken approach to assign the shim location when asdf.sh already assigns the correct path for /bin just seems kind of backward and prone to errors.

I might obviously miss something, but to me, it seems my suggested fix is trivial and it would get rid of ASDF_DATA_DIR entirely, since once asdf.sh sets ASDF_DIR, the actually correct location is already being stored in an easy-to-use way.
Avoiding any potential errors if ASDF_DATA_DIR is incorrectly assigned.

Since this fix is a one-liner I thought it to be more convenient to file it as a bug report, instead of cloning then doing a pull request. If I am wrong about that I could of course refile it as a pull request instead.

**Comment by jaclu** [comment]
The same failed approach is present in the fish init script, and the fix would be the same, ASDF_DIR is set first, then the /shim path goes through the same mistaken foobar by trying to trust ASDF_DATA_DIR. Whereupon ASDF_DIR is used to correctly assign the /bin path

**Comment by jaclu** [comment]
If the reason for this approach is that one would potentially want the shim dir elsewhere. I guess the variable used should be called ASDF_SHIM_DIR and asdf.sh should check for the presence of that dir before trusting it.

**Comment by jaclu** [comment]
After digging around and getting an understanding of the purpose of ASDF_DATA_DIR I realize the above was mistaken and misguided, so I am closing this and instead attempting a Pull Request that should be more in line with it's intended usage
