### ISSUE TITLE
bug:  Bug Report form gives incorrect instructions for how to provide required data in the Environment section

### ISSUE THREAD

**Issue by jaclu** [asdf-vm/asdf#1105]
### Describe the Bug

We are requested to run the following to gather env info.
```
asdf-info
```
Just as it does for the section "asdf plugins affected (if relevant)" it should read
```
asdf info
```
As late as in #1069 the bug reporter failed to comply with this obligatory step due to this incorrect requirement. Not implying that this failure had any major significance, just trying to point out that same as I an hour ago got confused for a while trying to figure out what I did wrong, it seems others also struggle with this faulty request.

### Steps to Reproduce

File a bug report and follow the instructions for providing your asdf environment.

### Expected Behaviour

Instructions to be relevant.

### Actual Behaviour

They are not.

### Environment

This bug is not asdf code relevant, so such info does not seem likely to assist in investigating this. If I am incorrect and it is indeed relevant, notify me in a comment, ideally explaining how this information will help in the investigation. That is not meant as any kind of demand, just me being curious. I will promptly supply this info if it will help you to track what caused this.

**Comment by jthegedus** [comment]
Thanks for the report @jaclu
