### ISSUE TITLE
bug: Command 'asdf' not found in WSL2 (Ubuntu)

### ISSUE THREAD

**Issue by danielneto5858** [asdf-vm/asdf#1119]
### Describe the Bug

I have problem running asdf, when I run  Command 'asdf' not found, did you mean:

I don't quite understand how to use WSL2, but I followed the instalation guide (https://asdf-vm.com/guide/getting-started.html#_1-install-dependencies)
I also tried to fix using theses following issues:

- https://github.com/asdf-vm/asdf/issues/954 
- https://github.com/asdf-vm/asdf/issues/743

### like this your installation, your .bashrc file
my `.bashrc` file contains at the very bottom this:

"""
$HOME/.asdf/asdf.sh
$HOME/.asdf/completions/asdf.bash
"""

### Steps to Reproduce

I did the installation through the guide to the third step which is at https://asdf-vm.com/guide/getting-started.html#_1-install-dependencies.

### Expected Behaviour

run the asdf command

### Actual Behaviour

Command 'asdf' not found, did you mean:

### Environment

```shell
Win 10 + WSL2 (Ubuntu v2004.2021.825.0)
asdf: 0.8.0
```

**Comment by jthegedus** [comment]
```
$HOME/.asdf/asdf.sh
$HOME/.asdf/completions/asdf.bash
```

If this is what you have in your `.bashrc` then it is incorrect. From the docs

> Bash & Git
> Add the following to ~/.bashrc:

	. $HOME/.asdf/asdf.sh
	. $HOME/.asdf/completions/asdf.bash

the `.` is extremely important

**Comment by Stratus3D** [comment]
Closing due to lack of a response.

**Comment by ferrisoxide** [comment]
@danielneto5858 It looks like `.bashrc` isn't automatically sourced any more. See https://github.com/Microsoft/WSL/issues/2612

The hacky workaround appears to be setting up `asdf` per the instructions and then added this to the end of your `~/.bash_profile`:

```
source ~/.bashrc
```
