### ISSUE TITLE
bug: No such file or directory for installed plugin commands

### ISSUE THREAD

**Issue by bcardarella** [asdf-vm/asdf#1144]
### Describe the Bug

I updated asdf via homebrew, currently on `v0.9.0`. When I run `asdf help` I see all of the plugins listed as such:

```
find: /Users/thatsme/.asdf/plugins/elixir/lib/commands: No such file or directory
```

I ran `asdf plugin remove <plugin_name>` for each plugin and confirmed via `asdf help` that the missing plugin commands are no longer listed. I then reinstall the plugins with `asdf plugin install elixir` and the same error as described above is being listed.

### Steps to Reproduce

1. Update to 0.9.0 via homebrew
2. See the errors in `asdf help` about the missing plugin commands

### Expected Behaviour

I wouldn't expect there to be any error messages from any of the asdf plugins

### Actual Behaviour

The installed plugins are showing as errors in `asdf help`

### Environment

```shell
MacOS 12.0.1
```

**Comment by bcardarella** [comment]
I just did a complete removal of `asdf` in homebrew, closed my terminal session, and reinstalled. Then immediately added the `erlang` plugin and am getting the same error.

**Comment by bcardarella** [comment]
I uninstalled from homebrew and reinstalled via Git. This appears to have resolved the issue. However I'm on asdf version `v0.9.0-87137e4` for Git install and I don't know if the version difference is the real reason or if Brew/Git install is the difference maker.

**Comment by bcardarella** [comment]
I believe this has been fixed already with https://github.com/asdf-vm/asdf/pull/1102

Considering the confusion around this issue, as I've seen a few others issues about it reported and others out there are also dealing with it, I'd suggest minting a patch release of `v0.9.1` for homebrew.

**Comment by mactkg** [comment]
As @bcardarella says, I installed the head version of `asdf` and it fixes this bug.

```bash
brew unlink asdf
brew install asdf --head
```

**Comment by alecho** [comment]
> As @bcardarella says, I installed the head version of `asdf` and it fixes this bug.
> 
> ```shell
> brew unlink asdf
> brew install asdf --head
> ```

Confirming this worked for me as well.
