### ISSUE TITLE
bug: Couldn't download docker-compose release 2.2.2 because of wrong url to git

### ISSUE THREAD

**Issue by vokomod** [asdf-vm/asdf#1148]
### Describe the Bug

Try to install docker-compose-v1 2.2.2 but take error

curl: (22) The requested URL returned error: 404 
asdf-docker-compose: Could not download https://github.com/docker/compose/releases/download/2.2.2/docker-compose-Linux-x86_64

I suppose it's because letter "v" is missing in url 
Right url is https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-Linux-x86_64 

### Steps to Reproduce

asdf install docker-compose-v1 2.2.2

### Expected Behaviour

It should install docker-compose-v1 2.2.2

### Actual Behaviour

Platform 'Linux' supported!
curl: (22) The requested URL returned error: 404 
asdf-docker-compose: Could not download https://github.com/docker/compose/releases/download/2.2.2/docker-compose-Linux-x86_64
asdf-docker-compose: Expected /home/andy/.asdf/installs/docker-compose-v1/2.2.2/bin/docker-compose to be executable.
asdf-docker-compose: An error ocurred while installing docker-compose 2.2.2.

### Environment

```shell
OS:
Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, версия 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
Лицензия GPLv3+: GNU GPL версии 3 или более поздней <http://gnu.org/licenses/gpl.html>

ASDF VERSION:
v0.9.0-9ee24a3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/andy/.asdf

ASDF INSTALLED PLUGINS:
docker-compose-v1            https://github.com/kompiro/asdf-docker-compose-v1
docker-slim                  https://github.com/everpeace/asdf-docker-slim.git
```

**Comment by vokomod** [comment]
Actually, when I type v2.2.2, asdf install it normally, but when type "latest" I have same problem

**Comment by Stratus3D** [comment]
This appears to be caused by the https://github.com/kompiro/asdf-docker-compose-v1 plugin. Please report this issue there.
