### ISSUE TITLE
[Feature Request] Add plugin description to `asdf plugin list`

### ISSUE THREAD

**Issue by jdinunzio** [asdf-vm/asdf#1170]
### Is your feature request related to a problem? Please describe

asdf is excellent to install the supported applications you already know, but it doesn't provide an easy way to explore which of the available plugins you might be interested in install.

As a user I want to get a small description of what every plugin/application does so that I can decide if I want to install it.

### Describe the proposed solution

* Add to the plugin definition a mechanism to describe it. It might be as simple as a `DESCRIPTION.md` on the root of each plugin repository with a single line with a short description of the application plus a paragraph with a long description. Then asdf might read and cache those description.

### Describe similar `asdf` features and why they are not sufficient

The current information provided by `asdf plugin list all` only gives the name of the plugin and the url of the plugin repo. Plugin repos don't contain information about the applications themselves, just for the plugin, so there's no way provided by asdf itself to discover what the ecosystem is capable to provide.

### Describe other workarounds you've considered

If I want to know if a particular plugin I don't already know might be useful for me, the only alternative is to make a web search.

**Comment by jthegedus** [comment]
`asdf plugin list` only prints from plugins you already have installed.

The functionality behind `asdf plugin list all` which does print just URLs from the Plugin Repo (https://github.com/asdf-vm/asdf-plugins) is data that is pulled and cached locally, though it does not fetch data from each of these plugins as there are very very many, 493 at the time of writing this:

```
asdf on  master [!] took 1s 
➜ asdf plugin list all | wc -l
493
```

Current discussion around the plugin repo is about removing it as it requires a lot of maintenance from the asdf core team and is increasingly a cause of design problems.

Most plugin README files link to the site for the actual tools they manage.

Discovery of plugins is certainly an area will we need to tackle if/when we remove the plugin repo, but what tools those plugins manage is an exercise for the user as with tools like aptitude, Homebrew or any other tool installation/manager.

>If I want to know if a particular plugin I don't already know might be useful for me, the only alternative is to make a web search

There are two types of questions here:
1. "I know I need X, does asdf have a plugin for X"
2. "I want a tool that does A,B & C, is there a tool in the entire world that does A,B & C AND is there an asdf plugin for it?"

We can answer 1. but not 2. Web searching is built for 2. Once you find a tool that does what you need, then you can search our resources to see if a plugin exists for it.

These are relevant links from our Documentation site:
* https://github.com/asdf-vm/asdf-plugins
* https://github.com/topics/asdf-plugin
* https://github.com/asdf-community
