### ISSUE TITLE
Add one or more options in configuration file to disable plugin hooks

### ISSUE THREAD

**Issue by henry40408** [asdf-vm/asdf#1173]
### Is your feature request related to a problem? Please describe

No.

### Describe the proposed solution

I'd like to implement an option like `disable_plugin_hooks` or `disable_plugin_{add,update,remove}_hook` or both in `.asdfrc`:

```
disable_plugin_hooks = true
```

or

```
disable_plugin_add_hook = true
disable_plugin_update_hook = true
disable_plugin_remove_hook = true
```

...so I can review plugin before I `asdf plugin add` them

No breaking changes will be introduced.

### Describe similar `asdf` features and why they are not sufficient

There is no method or option to disable plugin hooks as for [v0.9.0](https://github.com/asdf-vm/asdf/tree/v0.9.0)

`asdf plugin add`

https://github.com/asdf-vm/asdf/blob/9ee24a3a75e28ca0757d0b99fa00ce49466777a8/lib/commands/command-plugin-add.bash#L45-L51

`asdf plugin update`

https://github.com/asdf-vm/asdf/blob/9ee24a3a75e28ca0757d0b99fa00ce49466777a8/lib/commands/command-plugin-update.bash#L50-L57

`asdf plugin remove`

https://github.com/asdf-vm/asdf/blob/9ee24a3a75e28ca0757d0b99fa00ce49466777a8/lib/commands/command-plugin-remove.bash#L13-L18

### Describe other workarounds you've considered

Create a plugin to clone and checkout plugin repositories.

**Comment by weihanglo** [comment]
Second this feature. It is really useful!

**Comment by Stratus3D** [comment]
Why is disabling plugin hooks necessary? I'm not sure what you mean by "so I can review plugin before I `asdf plugin add` them". Plugins are just a set of shell script callbacks that can be reviewed prior to `asdf plugin add`.

**Comment by henry40408** [comment]
Hi @Stratus3D

What I actually want is version lock on plugins. Currently only repository URLs are recorded in https://github.com/asdf-vm/asdf-plugins , so generally when I `asdf plugin add [plugin]`, asdf will clone the plugin repository on the recent commit of default branch. If maintainer's account got breached and malicious code might be injected into plugin hooks, sensitive data e.g. SSH keys on user's machine might be stolen.

I can review plugin hooks every time before I add the plugin, but I might get careless and miss the step at any moment. However, if we record commit SHA1 in https://github.com/asdf-vm/asdf-plugins , then we will have to update asdf-plugins when the downstream plugin updated, which is a lof of work. Freshness and stability are mutually exclusive.

So I maintain a clone of asdf-plugins myself, which is a set of submodules of plugin repositories. Every time I clone the repository, I can be absolutely sure that the plugin has already been reviewed by myself.

I will close this issue since what I want is different feature.

related issue: https://github.com/asdf-vm/asdf/issues/166

**Comment by jthegedus** [comment]
Related https://github.com/asdf-vm/asdf/pull/1204
