### ISSUE TITLE
bug(getting-started): Step #4 references dependencies not described 

### ISSUE THREAD

**Issue by bencodesall** [asdf-vm/asdf#1176]
### Describe the Bug

[https://asdf-vm.com/guide/getting-started.html#plugin-dependencies](https://asdf-vm.com/guide/getting-started.html#plugin-dependencies)
... in the "Getting Started" says
>Each plugin has dependencies so we need to check the plugin repo where they should be listed. For `asdf-nodejs` they are:
... not listed.

Seems that there should be some facility to enforce this or at least document how to discover dependencies prior to install so that `post-install` hooks don't fail arbitrarily.

### Steps to Reproduce

1. Go to https://asdf-vm.com/guide/getting-started.html#_4-install-a-plugin
2. Read about "Plugin Dependencies"
3. Go to `asdf-nodejs` repo
4. Find the pre-install dependencies to install

### Expected Behaviour

Dependencies listed so that one might install prior to plugin install

### Actual Behaviour

Many repos, `asdf-nodejs` in particular, don't have the requisite dependencies clearly listed.

### Environment

```shell
N/A
```

### asdf plugins affected (if relevant)

asdf nodejs

**Comment by jthegedus** [comment]
This is really an issue for the plugins themselves. We have encouraged plugin authors to list dependencies clearly in their READMEs. The core asdf specifically supports calling a plugin script to list out the dependencies when the `asdf help <plugin>` command is run. Additionally, plugin authors can implement checks to ensure the required deps are available on the machines.

All of this falls on the plugin authors. Even if the core required that the dependencies callback script `bin/help.deps` was required, it cannot determine whether the plugin has correctly listed the dependencies or not. Unfortunately this state is a requirement of the plugin model.

I have raised your issue with the `asdf-nodejs` plugin.

**Comment by sschuberth** [comment]
> Even if the core required that the dependencies callback script `bin/help.deps` was required, it cannot determine whether the plugin has correctly listed the dependencies or not.

Actually, this could probably be solved by PR checks on the [plugin repository](https://github.com/asdf-vm/asdf-plugins): No plugin should be accepted there if it does not provide a working `bin/help.deps` for the TBD basic platform(s).

**Comment by jthegedus** [comment]
@sschuberth 
>provide a working `bin/help.deps`

My point before was that even if a plugin does populate `bin/help.deps` we can't know if what tools they put in the `help.deps` file is actually the list of tools required. We could check for the existence of the `help.deps` file, but that could just be empty or list `echo`.

The pressure to improve a plugins quality should come from the users to the plugin author. There is only so much we can do in the core.

I am also hesitant to spend too much time with codifying rules in the plugins repo as I want to deprecate it in favour of a search mechanic. Certainly, the measures you're suggesting could be used to determine feedback to users in search results.

**Comment by sschuberth** [comment]
> we can't know if what tools they put in the `help.deps` file is actually the list of tools required.

By "*working* `bin/help.deps`" I was trying to imply that there should be CI checks in place that verify that the given tools actually work in a basic list of distributions.

> The pressure to improve a plugins quality should come from the users to the plugin author. There is only so much we can do in the core.

I disagree. The users have to lever towards the plugin author to comply. But the core has, as otherwise the plugin will simply not be listed.

**Comment by jthegedus** [comment]
>I disagree. The users have to lever towards the plugin author to comply. But the core has, as otherwise the plugin will simply not be listed.

The plugin repo was created for convenience, none of the plugins in there are sanctioned by us in any official capacity. This is, in my opinion, why the plugin repo is actually a liability to the asdf core team. Individuals should vet the code they run on their systems. We could automate some checks, of course, but I think the effort outweighs the benefit.

Are you suggesting the CI of the asdf-plugin repo should run tests or the repos for the individual plugins themselves? If you mean the plugins themselves, then I am open to working with you on my plugin https://github.com/jthegedus/asdf-v to concretely understand your proposal(s).

Realistically though, we are limited by whatever the dependencies of the plugins themselves actually are, which themselves may not be easy to install, hence the `help.deps` listing them should at least inform the users of what they are, not necessarily how to install them.

**Comment by sschuberth** [comment]
> Are you suggesting the CI of the asdf-plugin repo should run tests or the repos for the individual plugins themselves?

I was meaning the former. The asdf-plugin repo CI should basically "pretend to be a user" and install the plugin on various test platforms while taking `help.deps` into account, and only if the installation and use of the plugin succeeds, it should get listed.

**Comment by Stratus3D** [comment]
> > Are you suggesting the CI of the asdf-plugin repo should run tests or the repos for the individual plugins themselves?
> 
> I was meaning the former. The asdf-plugin repo CI should basically "pretend to be a user" and install the plugin on various test platforms while taking `help.deps` into account, and only if the installation and use of the plugin succeeds, it should get listed.

That would be a VERY challenging thing to do. Many plugins have distinct dependencies that may not be available on every platform, or may only be installed by manual compilation or are propriety software. These are things that would take an enormous amount of work we are not interested in doing right now.

> The plugin repo was created for convenience, none of the plugins in there are sanctioned by us in any official capacity. This is, in my opinion, why the plugin repo is actually a liability to the asdf core team. Individuals should vet the code they run on their systems. We could automate some checks, of course, but I think the effort outweighs the benefit.

I'm of the same opinion as @jthegedus, the index was created for convenience, and it gives a false sense of security to some users. I think we should do away with it.

**Comment by sschuberth** [comment]
> Many plugins have distinct dependencies that may not be available on every platform

My understanding of `help.deps` is that the script should detect the platform it's running on, and output dependencies for that platform only (if supported; if not, the script would simply output nothing on a platform).

But anyway, I accept that this level of convenience will not be available.
