### ISSUE TITLE
Check if version available before install

### ISSUE THREAD

**Issue by StephanMeijer** [asdf-vm/asdf#118]
Would be nice to check if version exists first before trying to install.

Bash: `asdf install elixir aa`

```                                                                                                          git:master*
/tmp/elixir_build_rPfqPC/elixir-precompiled-aa.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21    0    21    0     0     41      0 --:--:-- --:--:-- --:--:--    41
[/tmp/elixir_build_rPfqPC/elixir-precompiled-aa.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/elixir_build_rPfqPC/elixir-precompiled-aa.zip or
        /tmp/elixir_build_rPfqPC/elixir-precompiled-aa.zip.zip, and cannot find /tmp/elixir_build_rPfqPC/elixir-precompiled-aa.zip.ZIP, period.
```

**Comment by Stratus3D** [comment]
I think one benefit to leaving things the way they are is that a plugin might be able to install a new version of a language, even if it's returned from the `list-all` command. Users should find the version they want to install in the output from `list-all` and then run the install command with one of the versions listed if they want to ensure a version is available and supported by an asdf plugin. Scripts should do the same.

Is there a scenario where the current behavior causes a problem?

I suppose we could have an interactive variation of the install command, where you would first choose a plugin, then asdf would list the versions and you would chose one from the list of options. This would guard against copy-paste and user errors.
