### ISSUE TITLE
bug: Installing Anaconda breaks curl

### ISSUE THREAD

**Issue by eugriner** [asdf-vm/asdf#1182]
### Describe the Bug

The issue was [described on Stack,](https://stackoverflow.com/questions/71431607/error-no-preset-version-installed-for-command-curl-but-its-installed/71431608#71431608) but it might be important to notify here.

The error as:
`No preset version installed for command curl
Please install a version by running one of the following:

asdf install python 3.10.2

or add one of the following versions in your config file at 
python anaconda3-5.3.1`

The solution was to uninstall anaconda.

### Steps to Reproduce

1. I'm not sure here, because was functioning well with anaconda until a little bit
2. I use asdf + direnv + pyenv (my last change to the environment)

### Expected Behaviour

```
$ which curl
/usr/bin/curl
```

```
$ curl
curl: try 'curl --help' for more information
```

### Actual Behaviour

```
$ which curl
/home/noki/.asdf/shims/curl
```

```
$ curl
No preset version installed for command curl
Please install a version by running one of the following:

asdf install python 3.10.2

or add one of the following versions in your config file at /home/noki/.tool-versions
python anaconda3-5.3.1
```

### Environment

```shell
OS:
Linux noki-artix 5.15.26-1-lts #1 SMP Wed, 02 Mar 2022 22:36:50 +0000 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.9.0-9ee24a3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/noki/.asdf

ASDF INSTALLED PLUGINS:
direnv                       https://github.com/asdf-community/asdf-direnv.git master 1ee7d01
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 364c078
python                       https://github.com/danhper/asdf-python.git master 57a4d72
```

**Comment by Stratus3D** [comment]
This is an issue with asdf-python (https://github.com/danhper/asdf-python) (or pyenv or direnv) and not asdf core. Please open a ticket on the asdf-python issue tracker to get this resolved. asdf-core itself does not touch `curl`.
