### ISSUE TITLE
bug: ASDF_DIR: unbound variable

### ISSUE THREAD

**Issue by mugioka** [asdf-vm/asdf#1183]
### Describe the Bug

The following command installs asdf in the container.
```
set -e
set -u
set -o pipefail
set -x
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch $VERSION
PATH="${PATH}:/asdf/.asdf/shims:/asdf/.asdf/bin"
source "$HOME"/.asdf/asdf.sh
```
However, after upgrading asdf to version 0.9.0, I get the following error
```
/root/.asdf/asdf.sh: line 6: ASDF_DIR: unbound variable
```

### Steps to Reproduce

```
set -e
set -u
set -o pipefail
set -x
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0
PATH="${PATH}:/asdf/.asdf/shims:/asdf/.asdf/bin"
source "$HOME"/.asdf/asdf.sh
```

### Expected Behaviour

Can be installed without unbound errors.

### Actual Behaviour

Getting above error.

### Environment

```shell
none
```

**Comment by mugioka** [comment]
Is this behavior expected?

**Comment by PenTagaris** [comment]
Confirmed this is happening in 0.9.0 and not 0.8.1. My workaround is currently:

```
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.8.1
. $HOME/.asdf/asdf.sh
$HOME/.asdf/bin/asdf update
```

**Comment by Kurt-von-Laven** [comment]
I also started noticing this upon updating from 0.8.1 to 0.9.0.

**Comment by Stratus3D** [comment]
I just released version `0.10.0`. Can you try updating to the latest version and see if that fixes this issue? I believe we did merge a fix related to this variable, but I'm not sure it is the exact issue reported here.

**Comment by PenTagaris** [comment]
Appears to be fixed now, thanks!

**Comment by Stratus3D** [comment]
Closing now. If anyone still has this problem I'll re-open this issue.
