### ISSUE TITLE
bug: asdf not installed on WSL Ubuntu

### ISSUE THREAD

**Issue by jctadios** [asdf-vm/asdf#1187]
### Describe the Bug

Can't Install asdf

### Steps to Reproduce

Installing asdf on WSL ubuntu 

sudo apt-get update
sudo apt install autoconf bison build-essential libssl-dev libyaml-dev libreadline-dev zlib1g-dev libncurses-dev libffi-dev libgdbm-dev
sudo apt install curl git
git clone [https://github.com/asdf-vm/asdf.git](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbUh0eVpBTVd5Vm0yNm1pZXlqZUp4N0NPdGxyd3xBQ3Jtc0tuR19IZ1hhTFBka1NjU0NIWFBlRkFnS01GTmdhdTZXaEpIWmNiS0lNYW1Kb214OVRSZ2NQS0hHRXUxNEdnak1WTjQ3SXRyQWxFV2FxQUpnajU3UEUtcGFuQ3ptQkRUdTBZb2h4Rmd5YzlZYmtJRHJIRQ&q=https%3A%2F%2Fgithub.com%2Fasdf-vm%2Fasdf.git) ~/.asdf --branch v0.9.0
Call code ~/.bashrc in your terminal
Add . $HOME/.asdf/asdf.sh and . $HOME/.asdf/completions/asdf.bash in the end of .bashrc file

exec $SHELL

### Expected Behaviour

```
bash: /home/USER/.asdf/asdf.sh: line 9: syntax error near unexpected token `elif'
'ash: /home/USER/.asdf/asdf.sh: line 9: `  elif [[ "$_under" == *".sh" ]]; then
bash: /home/USER/.asdf/completions/asdf.bash: line 1: syntax error near unexpected token `$'{\r''
'ash: /home/USER/.asdf/completions/asdf.bash: line 1: `_asdf() {
```

### Actual Behaviour

It should be Successfully installed!

### Environment

```shell
Command 'asdf' not found, did you mean:

  command 'sdf' from deb sdf (2.001+1-7)
  command 'asdfg' from deb aoeui (1.7+20160302.git4e5dee9-2)
  command 'adsf' from deb ruby-adsf (1.4.3+dfsg1-1)
  command 'sadf' from deb sysstat (12.2.0-2ubuntu0.1)

Try: sudo apt install <deb name>
```

**Comment by sheldonhull** [comment]
@jctadios 

- Are you using WSL2 or WSL? 
- What does `realpath . ` show for current directory? 
- What does `bash --version` show in WSL? 

I'm curious as I use WSL2 in a limited capacity for home purposes and by default if you don't change it the normal home directory is actually a mounted windows path instead of your ubuntu path. I use `cd $HOME` and see the path change to the home directory in WSL2 instead of the windows mounted home directory and much of the odd issues go away for me there. If I see anything I can help point out I will.

**Comment by holtalanm** [comment]
I am getting this same error on a fresh install of Xubuntu 20.04 (not WSL).

**Comment by holtalanm** [comment]
if anyone else is running into this issue on Xubuntu 20.04, it looks like the asdf install works through homebrew.

What I did: 

installed homebrew:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

sudo apt install -qy build-essential
source ~/.profile
```

then install asdf

```
brew install asdf
echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ~/.profile
echo -e "\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash" >> ~/.profile
```

**Comment by jthegedus** [comment]
I suspect this is an issue with particular machines or setup issues as we are only seeing 3 people reporting issues here, if this was an issue with the main entrypoint to asdf having a typo or illegal chars then there would be hundreds of people reporting this issue.

Anecdotal, but I am actively developing asdf on WSL2 Ubuntu22.04.

**Comment by jthegedus** [comment]
So two things to keep in mind when using WSL2 environment:

1. From our [FAQ](https://asdf-vm.com/learn-more/faq.html)
>Importantly, WSL2 is only expected to work properly when the current working directory is a Unix drive and not a bound Windows drive.

2. The error reported shows:
```
bash: /home/USER/.asdf/asdf.sh: line 9: syntax error near unexpected token `elif'
'ash: /home/USER/.asdf/asdf.sh: line 9: `  elif [[ "$_under" == *".sh" ]]; then
bash: /home/USER/.asdf/completions/asdf.bash: line 1: syntax error near unexpected token `$'{\r''
'ash: /home/USER/.asdf/completions/asdf.bash: line 1: `_asdf() {
```

The 3rd line here shows an unexpected token `\r` which is likely due to this repository being cloned to a non-Unix location or by using Git in a Windows environment. Changing your line endings to LF from CRLF might fix this.

Nonetheless, I am going to close this issue as OP has not responded and other participants have used other solutions.

**Comment by Jenishk56** [comment]
Facing the same issue. I believe, this is an issue. Did anyone find any solution ?

**Comment by rargueso** [comment]
Before clone:
`git config --global core.autocrlf true`

**Comment by jthegedus** [comment]
You shouldn't need to set `git config --global core.autocrlf false` to false. You just need to clone the repo from a Unix environment and it will get the correct line endings. As I said in my previous comment, you will only end up in this situation if you clone from the Windows view into the filesystem, not the WSL Unix view.

**Comment by vdqvdw** [comment]
> `git config --global core.autocrlf false`
> 
> This did the trick before clone.

this worked for me.
at wsl2 environment.
then i rollback autocrlf true !!

**Comment by punchcafe** [comment]
Tried cloning from the WSL environment but no luck.
The global config hack did it for me.
