### ISSUE TITLE
Allow configuring `asdf` to use a custom plugin repository

### ISSUE THREAD

**Issue by shakefu** [asdf-vm/asdf#1194]
### Is your feature request related to a problem? Please describe

Yes, right now `asdf` has hard coded the plugin repository which maps names to repository URLs.

https://github.com/asdf-vm/asdf/blob/master/lib/utils.bash#L36

This means it cannot be used in high-security or airgapped environments.

### Describe the proposed solution

Allowing the plugin repository to be configured through environment variable would be trivial, or perhaps through a new setting in `~/.asdfrc`.

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

Create a fork of `asdf-vm/asdf` and edit it directly.

**Comment by hmnd** [comment]
Though I know this doesn't entirely solve the issue, you can already provide your own Git URL to a plugin without having to go through the centralized repo. See [here](https://asdf-vm.com/manage/plugins.html#add).

**Comment by shakefu** [comment]
> here

This is true, but my specific use case includes being able to specify `.tool-versions`, without knowing ahead of time which tools are going to be installed, and which repository URIs should be added for the plugins. This means it will use the default plugin name mapping instead, which is what I'd like to override. 

Of course, it would be fairly trivial to `cat .tool-versions | awk '{print $1}' | xargs -I{} asdf plugin add {} github.com/myorg/asdf-{}` but ... that's exactly what the default plugin repository is doing...

**Comment by hmnd** [comment]
This might interest you too :) https://github.com/asdf-vm/asdf/issues/240#issuecomment-1048680932

**Comment by shakefu** [comment]
TBH my biggest problem with `asdf` as a user (use cases above not withstanding) is actually finding plugins for various tools that aren't in the short-name "plugin repo".  Regular search engines and 

I still think there's a strong use case in high security/air-gapped environments to _only_ allow short-name plugins from a pre-approved/security vetted "plugin repo" list, but if it's not part of the intended long term road map, obviously you can close this.

Thanks for the replies. 👍

**Comment by jthegedus** [comment]
>I still think there's a strong use case in high security/air-gapped environments to only allow short-name plugins from a pre-approved/security vetted "plugin repo" list, but if it's not part of the intended long term road map, obviously you can close this.

You could have a single internal repo at an org that is used as the approved, high-security plugin repo, you would just need to use `asdf plugin add <name> <url>` pattern to install. The shortname saves you typing the URL. The only benefit to the shortname repo is discoverability and to save on typing. Neither of which should impact an approved, high-security plugin repo.

**Comment by jthegedus** [comment]
Discoverability is an area of improvement without the plugin repo, but I assure you this will be a primary concern with any alternative solutions. However, we do not intend to make the plugin repo an public API. I will close as with https://github.com/asdf-vm/asdf/issues/952

**Comment by jthegedus** [comment]
#1227 added support to disable the plugin repo for those who wish to force explicit use of `asdf plugin add <name> <url>` workflows.
