### ISSUE TITLE
Release 0.9.1 

### ISSUE THREAD

**Issue by pre** [asdf-vm/asdf#1196]
### Is your feature request related to a problem? Please describe

Homebrew installation of asdf on a fresh MacBook succeeds but asdf fails for non-installed components with a mystical error:
```
> asdf help
Unknown command: `asdf help`
/opt/homebrew/Cellar/asdf/0.9.0/libexec/bin/asdf: line 82: /opt/homebrew/opt/asdf/lib/commands/command-help.bash: No such file or directory
```

This has been fixed at December 4th 2021
* https://github.com/asdf-vm/asdf/pull/1102
* https://github.com/asdf-vm/asdf/issues/1144
* https://github.com/asdf-vm/asdf/issues/1161#issuecomment-1013751242

Newest release is 0.9.0 from December 3th 2021.

At the moment, `asdf` fails with a fresh Homebrew installation.

### Describe the proposed solution

Release 0.9.1

### Describe similar `asdf` features and why they are not sufficient

Release 0.9.0 does not contain the fix.

### Describe other workarounds you've considered

Google around for a solution until you find out the current asdf release is too old.

Install the latest version
```
brew unlink asdf
brew install asdf --head
```

**Comment by Stratus3D** [comment]
Thanks for the reminder @pre , I will work tagging a new release and should have something out within the next several days. The next version will be `0.10.0` - https://github.com/asdf-vm/asdf/pull/1111
