### ISSUE TITLE
No version set for elixir

### ISSUE THREAD

**Issue by ipatch** [asdf-vm/asdf#120]
I recently came across the asdf package manager, so I am sure this warning / error message has to do with how my system is set up, but I'm getting the following messages when running either `erl` / `iex` outside of my local home directory on my dev box.

_No version set for erlang
No version set for elixir_

However, if I run `erl` or `iex` within the home directory the appropriate interactive shell opens.

My `.bash_profile` looks like the following,

```
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# set the size of the command history for BASH
HISTSIZE=1000000

alias l='ls -lah'

source /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-completion.bash
source /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=true
PS1='\[\033[32m\]\u@\h\[\033[00m\]:\[\033[34m\]\w\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '
# export PS1='\u@\h:\w$(__git_ps1)$ '

# the below line is required to get 'nvm' Node version manager working
source ~/.bashrc

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
```

And the `.tool-versions` looks like,

```
elixir 1.3.4
erlang 19.1
```

Finally, all of my dot files can be found within a repo on Github,

https://github.com/ipatch/dotfiles

**Comment by tuvistavie** [comment]
Hi,
Looking at your dotfiles, your `.tool-versions` file seems to be at `$HOME/.asdf/.tool-versions` while it should be at `$HOME/.tool-versions`, could you please check?
Thanks!
