### ISSUE TITLE
bug: Failed to parse asdf.elv after installation

### ISSUE THREAD

**Issue by st-clair-clarke** [asdf-vm/asdf#1212]
### Describe the Bug

I get the following result when starting elvish terminal after installation of asdf:

```
Exception: Multiple parse errors:
  should be ',' or '}'
    /home/stclair/.config/elvish/lib/asdf.elv, line 18:
      fn asdf {|command @args|
  unexpected rune '}'
    /home/stclair/.config/elvish/lib/asdf.elv, line 31:
      }
/home/stclair/.config/elvish/rc.elv, line 241: use asdf _asdf; var asdf~ = $_asdf:asdf~

```

### Steps to Reproduce

1. Follow the instructions at [asdf Installation](https://asdf-vm.com/guide/getting-started.html#_1-install-dependencies)
2. Open the terminal
3. enter command elvish

### Expected Behaviour

asdf.elv to be parsed without errors

### Actual Behaviour

No parsing of file - no command can be executed

### Environment

```shell
Linux Mint
```

**Comment by Stratus3D** [comment]
What version of the Elvish shell are you running @st-clair-clarke ?

**Comment by Stratus3D** [comment]
This was recently merged - https://github.com/asdf-vm/asdf/pull/1200

**Comment by st-clair-clarke** [comment]
The version being used was 0.16.*. I changed it to 0.18.0 and it now works

**Comment by Stratus3D** [comment]
Thanks for the info @st-clair-clarke !
