### ISSUE TITLE
bug: unknown command despite binary and shim existing

### ISSUE THREAD

**Issue by jacobbednarz** [asdf-vm/asdf#1216]
### Describe the Bug

Up until recently, I've been using asdf without any issues but lately, I'm getting the following errors when trying to run the acceptance test suite of the [Cloudflare provider](https://github.com/cloudflare/terraform-provider-cloudflare).

```
$ make testacc
=== RUN   TestAccCertificatePack_AdvancedDigicert
    resource_cloudflare_certificate_pack_test.go:52: Error setting test config: exit status 1
        unknown command: terraform. Perhaps you have to reshim?
    testing_new.go:72: Error retrieving state, there may be dangling resources: terraform show -json was added in 0.12.0: exit status 1
        unknown command: terraform. Perhaps you have to reshim?
--- FAIL: TestAccCertificatePack_AdvancedDigicert (0.34s)
=== RUN   TestAccCertificatePack_AdvancedLetsEncrypt
    resource_cloudflare_certificate_pack_test.go:94: Error setting test config: exit status 1
        unknown command: terraform. Perhaps you have to reshim?
    testing_new.go:72: Error retrieving state, there may be dangling resources: terraform show -json was added in 0.12.0: exit status 1
        unknown command: terraform. Perhaps you have to reshim?
--- FAIL: TestAccCertificatePack_AdvancedLetsEncrypt (0.09s)
=== RUN   TestAccCertificatePack_DedicatedCustom
    resource_cloudflare_certificate_pack_test.go:131: Pending investigation into ACM entitlements
--- SKIP: TestAccCertificatePack_DedicatedCustom (0.00s)
FAIL
FAIL	github.com/cloudflare/terraform-provider-cloudflare/cloudflare	0.829s
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/changelog-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/maintainer-only-file-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/tf-log-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/version	[no test files]
FAIL
make: *** [testacc] Error 1
```

I've attempted to reshim to no avail. Removing the asdf plugin has this working as expected.

installed via Homebrew.

```
$ brew info asdf
asdf: stable 0.9.0 (bottled), HEAD
Extendable version manager with support for Ruby, Node.js, Erlang & more
https://asdf-vm.com/
/usr/local/Cellar/asdf/0.9.0 (150 files, 627.4KB) *
  Poured from bottle on 2022-04-27 at 14:15:21
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/asdf.rb
License: MIT
==> Dependencies
Required: autoconf ✔, automake ✔, coreutils ✔, libtool ✔, libyaml ✔, openssl@1.1 ✔, readline ✔, unixodbc ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To use asdf, add the following line to your ~/.zshrc:
  . /usr/local/opt/asdf/libexec/asdf.sh

Restart your terminal for the settings to take effect.

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 20,794 (30 days), 48,945 (90 days), 155,625 (365 days)
install-on-request: 20,784 (30 days), 48,904 (90 days), 155,420 (365 days)
build-error: 0 (30 days)
```

asdf is sourced in config.fish

```
$ cat ~/.config/fish/config.fish | grep asdf
      # source asdf-vm
      source /usr/local/opt/asdf/libexec/asdf.sh
```

the binaries exist and my PATH is setup to find them

```
$ which terraform
/Users/jacob/.asdf/shims/terraform

$ asdf which terraform
/Users/jacob/.asdf/installs/terraform/1.1.9/bin/terraform

$ asdf where terraform 1.1.9
/Users/jacob/.asdf/installs/terraform/1.1.9
```

also, my shell is actually fish, not zsh.

### Steps to Reproduce

1. Clone `https://github.com/cloudflare/terraform-provider-cloudflare` 
2. Attempt to run the acceptance tests (note, these will require actual resources). Guides can be found at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/development.md#quick-start
3. See issue

NOTE: I'm happy to do thesew steps on your behalf as I have a working acceptance test config already.

### Expected Behaviour

Tests should run without `unknown command: terraform. Perhaps you have to reshim?` being shown.

### Actual Behaviour

Tests are littered with warnings of missing `terraform` binary.

### Environment

```shell
OS:
Darwin C02DG4A3ML85 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.9.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
golang                       git@github.com:kennyp/asdf-golang.git master cc8bc47
terraform                    git@github.com:asdf-community/asdf-hashicorp.git master d91aced
```

### asdf plugins affected (if relevant)

terraform - git@github.com:asdf-community/asdf-hashicorp.git master d91aced

**Comment by jacobbednarz** [comment]
to ensure this wasn't a Homebrew inflicted issue, i've also just jumped to the git installation, cleaned out everything from the old install and still experiencing the issue @ 
a9caa5b on master.

**Comment by Stratus3D** [comment]
I'm not sure if this is an issue with asdf or the terraform plugin. Does this issue happen with any of the `go` shims on your path?

**Comment by jacobbednarz** [comment]
I don't have the issue with other plugins however, the "perhaps you need to reshim" message is in core so I thought I would start here. happy to love it if you have a suspicion of it caused by the Terraform plug-in

**Comment by chris-at-work** [comment]
Upgrading from 0.9.0 to 0.10.0 broke all my shims on every language/tool I'm using.  I've been deleting my shims.  `asdf reshim foo` doesn't work.  Try rm'ing whatever command isn't working and then reshim your language.  I might just delete all shims soon.

**Comment by squarism** [comment]
Upgrading from 0.9.0 to 0.10.0 broke all my shims on every language/tool I'm using.  I've been deleting my shims.  `asdf reshim foo` doesn't work.  Try rm'ing whatever command isn't working and then reshim your language.  I might just delete all shims soon.

**Comment by jakedipity** [comment]
I had the same issue on a different provider plugin. Upgrading `github.com/hashicorp/terraform-plugin-sdk/v2` to `>= v2.14.0` fixed the issue.

`v2.13.0` didn't work and it seems like the Cloudflare provider was updated from that version only 25 days ago. Haven't tested earlier versions.

**Comment by jacobbednarz** [comment]
this started working consistently again for me in the last few weeks. unsure of what changed (I wasn't paying close enough attention to the libraries) but this is resolved for me now.
