### ISSUE TITLE
Compile Redis with TLS support

### ISSUE THREAD

**Issue by tarragon** [asdf-vm/asdf#1219]
### Is your feature request related to a problem? Please describe

Redis requires TLS to be enabled at compile time. We've been testing Redis with TLS and have had to resort to another package manager because asdf doesn't compile in TLS out of the box. It would be great if TLS support were added.

### Describe the proposed solution

TLS enabled at compile time as described here: https://redis.io/docs/manual/security/encryption/

### Describe similar `asdf` features and why they are not sufficient

There is no alternative to Redis that suits our current environment, and changing would require rearchitecting parts of our stack, which is not practical in the short to medium term.

### Describe other workarounds you've considered

We've used another package manager that does add TLS support, but this is of course not ideal.

**Comment by Stratus3D** [comment]
@tarragon unfortunately this is out of scope for asdf-core. Please raise this issue on the Redis plugin's issue tracker (https://github.com/smashedtoatoms/asdf-redis perhaps?) or install the dependencies for Redis manually.

Let me know if you have any other questions. Thanks!

**Comment by bdrupieski** [comment]
@tarragon Do you have this problem for `redis-cli` or `redis` (or both)?

I ran into this issue when installing `redis-cli` using asdf. I was able to resolve it by setting `BUILD_TLS=yes` as an environment variable before installing `redis-cli`. After doing that, I was able to run `redis-cli` with the `--tls` flag.

I think this same solution might apply to both `redis-cli` and `redis`.

**Comment by tarragon** [comment]
> @tarragon Do you have this problem for `redis-cli` or `redis` (or both)?
> 
> I ran into this issue when installing `redis-cli` using asdf. I was able to resolve it by setting `BUILD_TLS=yes` as an environment variable before installing `redis-cli`. After doing that, I was able to run `redis-cli` with the `--tls` flag.
> 
> I think this same solution might apply to both `redis-cli` and `redis`.

It was `redis` specifically, we were setting up some testing against TLS. We'd since worked out another way to test it but I did wonder if the `BUILD_TLS` env would work, but we hadn't got around to testing it. Great to know it works! Thanks.
