### ISSUE TITLE
Homebrew pinning

### ISSUE THREAD

**Issue by fmmoret** [asdf-vm/asdf#1222]
### Is your feature request related to a problem? Please describe

My team installs asdf through homebrew, but homebrew doesn't have old asdf versions & gets bumped to latest. For 2 of the last 3 releases, people with new machines have gotten bitten by brew installing new versions of asdf that are incompatible with some plugins until the plugins get updated.

### Describe the proposed solution

Can this project support brew versions instead of just a latest so we can pin in our install scripts?

It would be awesome if the 8+ versions could get republished to brew as part of this. I expect the task to be a bit tedious, but it would save us a ton of hours

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

N/A

**Comment by chenrui333** [comment]
Yeah, homebrew always ship the latest release. But in case if there is maintained old release, we also support the old releases as well.

**Comment by jthegedus** [comment]
>Can this project support brew versions instead of just a latest so we can pin in our install scripts?

We strongly recommend using the Git method of installation. As `asdf `is written as Shell scripts it is not really "installed". Even Homebrew is just essentially downloading a snapshot of this repo. The "installation" is when you hook the scripts up to your shell. It is much more simple to use specific versions via the Git model as you can just checkout a Git tag in your `~/.asdf` directory (or wherever you ended up cloning it).

I recognise these are not ideal responses with your request being further Homebrew support, but we (core asdf team) do not maintain the Homebrew Cask(?) for `asdf`, that is community managed in the Homebrew repos. I am not certain but this sounds like something that should be handled in the Homebrew repos (if possible, I'm not sure how that works).

For all these reasons I am going to close this Issue. Please reopen with further context if I have misunderstood anything or my reasoning incorrect.

**Comment by Stratus3D** [comment]
I agree with @jthegedus on this. It's important to know that we'd love to make it easier to install asdf on Homebrew, but we do not have the resources to invest in developing a better Homebrew formula.

I lack experience building and packaging software for distribution via OS package managers, but I'd love to make things easier on those packaging asdf. This is something to be considered if we rewrite asdf in another language (see: https://github.com/asdf-vm/asdf/issues/1242).

**Comment by fmmoret** [comment]
> > Can this project support brew versions instead of just a latest so we can pin in our install scripts?
> 
> We strongly recommend using the Git method of installation. As `asdf `is written as Shell scripts it is not really "installed". Even Homebrew is just essentially downloading a snapshot of this repo. The "installation" is when you hook the scripts up to your shell. It is much more simple to use specific versions via the Git model as you can just checkout a Git tag in your `~/.asdf` directory (or wherever you ended up cloning it).
> 
> I recognise these are not ideal responses with your request being further Homebrew support, but we (core asdf team) do not maintain the Homebrew Cask(?) for `asdf`, that is community managed in the Homebrew repos. I am not certain but this sounds like something that should be handled in the Homebrew repos (if possible, I'm not sure how that works).
> 
> For all these reasons I am going to close this Issue. Please reopen with further context if I have misunderstood anything or my reasoning incorrect.

@jthegedus do you know who maintains the homebrew repo? 

Last I checked, the asdf homebrew script effectively just nukes the homebrew repo and fully replaces it with the latest git release.

**Comment by jthegedus** [comment]
>@jthegedus do you know who maintains the homebrew repo?

I do not know, but you could look at the Git history of the file and tag those people when you suggest a change to the script in the Homebrew repo.
