### ISSUE TITLE
Backronym

### ISSUE THREAD

**Issue by kupych** [asdf-vm/asdf#1226]
### Is your feature request related to a problem? Please describe

My coworkers and I rely heavily on `asdf` for our development processes and it is one of my favourite dev tools. In the tradition of many well-loved pieces of software (e.g. Pine, GNU, etc.) it's in dire need of an acronym.

### Describe the proposed solution

asdf: **A** **S**oftware **D**eveloper's **F**riend

### Describe similar `asdf` features and why they are not sufficient

`asdf` is easy to type, but it doesn't quite roll off the tongue like it could with a handy backronym.

### Describe other workarounds you've considered

I thought of pronouncing it "azz-duff" but that's awkward too.

**Comment by nafg** [comment]
On the one hand I think it should stand for something more specific, but on the other hand it has to fit into asdf-vm.

**Comment by hyperupcall** [comment]
While a backronym would be cute, I think the time that this issue has been opened for shows the difficulty of finding such an initialism that is memorable, relevant, and specific. If one is destined for this project, I'm sure the community will organically share and spread the name around.

I think addressing #1369 is enough, and my vote is to close this issue to keep the issue queue small and manageable. @jthegedus @Stratus3D thoughts on closing?

**Comment by Stratus3D** [comment]
Closing now. We may re-evaluate branding in the future.
