### ISSUE TITLE
Evaluate rewriting core utilties to increase performance

### ISSUE THREAD

**Issue by oxr463** [asdf-vm/asdf#1242]
### Is your feature request related to a problem? Please describe

So far, everything is implemented in shell script.

### Describe the proposed solution

It would be interesting to explore using a compiled language to speed things up.

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

N/A

**Comment by offbyone** [comment]
See also #290 which has pointers to at least one instance of this being done.

**Comment by Stratus3D** [comment]
Published http://stratus3d.com/blog/2022/08/11/asdf-performance/ which shows some benchmarks of the current system. This should serve as a baseline.

**Comment by Stratus3D** [comment]
@oxr463 asdf has been rewritten in Golang. The Go code hasn't been released yet, but from my early testing it's 2x-15x faster than the Bash implementation for all operations. Once I've got the first release out with the new Go code I'll do more thorough benchmarking and publish another blog post. I'm the meantime I'm going to close this issue as we've moved to Go.
