### ISSUE TITLE
Ability to install and use in airgapped environments

### ISSUE THREAD

**Issue by micahlmartin** [asdf-vm/asdf#1244]
### Is your feature request related to a problem? Please describe

I want to be able to use `asdf` to install and manage multiple versions of Terraform in an environment where there is no access to the internet. The binaries need to be installed from my internal artifactory or other repository.

### Describe the proposed solution

I need to be able to either specify an alternate location for binaries to be installed from, or I need the ability to pre-install the binaries and have asdf automatically recognize they are installed.

### Describe similar `asdf` features and why they are not sufficient

From what I can tell there is no documentation around how this can be achieved today.

### Describe other workarounds you've considered

There are no alternatives I can think of.

**Comment by jthegedus** [comment]
Hi @micahlmartin

You are right that we do not have documentation of how this would work. We should probably add this to the docs site FAQ or a recipes/cookbook section.

`asdf` can install plugins from any location, URL or local path, not just the plugin repo. The plugin needs to be a Git repository. For example, `asdf plugin add <name> <git_url>` can be used as:

```shell
# install from disk
asdf plugin add terraform ~/local-plugins/terraform
# install from your own git repo
asdf plugin add terraform https://my-enterprise-git.com/asdf-plugins/terraform.git
```

This will install the plugin located at `~/local-plugins/terraform` and associate it with the `terraform` tool name in `asdf`, allowing:

```shell
asdf list all terrafrom
```

Now, if you write your own plugin you can tell it where to download Terraform binaries from. You can have a local cache on a webserver or local cache on the machines disk, it's really up to you.

**Comment by Stratus3D** [comment]
Thanks for the thorough reply @jthegedus ! I'm going to close this issue due to inactivity.
