### ISSUE TITLE
Support installation of asdf on Windows

### ISSUE THREAD

**Issue by bmitc** [asdf-vm/asdf#1246]
### Is your feature request related to a problem? Please describe

I would like to be able to install asdf on Windows.

### Describe the proposed solution

Provide installation instructions for asdf and support installation of asdf on Windows. An installation path could be accomplished either through [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/) or [Chocolatey](https://chocolatey.org/).

### Describe similar `asdf` features and why they are not sufficient

asdf can be installed in Docker containers and in Windows Subsystem for Linux (WSL) Linux distributions but not directly on Windows. While those can be useful options, having asdf run directly on Windows would be great and much more convenient at times. For example, if I want to develop in Erlang and Elixir, asdf is very handy if not required when dealing with multiple projects. Things can get slowed down if having to deal with Docker or WSL.

### Describe other workarounds you've considered

None that I know of.

**Comment by AhmedvHashem** [comment]
When ppl talk about windows support I assume they mean "native" support becuz WSL2 does not mean windows exactly it just mean linux with extra tweaks, so how this is closed !?

**Comment by jthegedus** [comment]
> When ppl talk about windows support I assume they mean "native" support becuz WSL2 does not mean windows exactly it just mean linux with extra tweaks, so how this is closed !?

Please read the thread in #450 We have discussed the parameters under which we want to support asdf on Windows endlessly
