### ISSUE TITLE
bug: Actions abandoned?

### ISSUE THREAD

**Issue by afirth** [asdf-vm/asdf#1255]
### Describe the Bug

https://github.com/asdf-vm/actions/pulls repo seems to be abandoned. CI broken and no reviews?

This is a real shame, because asdf is totally awesome at making developer friendly, fast, reproducible builds.

### Steps to Reproduce

..

### Expected Behaviour

Fix CI and review PRs

### Actual Behaviour

No PR review, CI broken :(

### Environment

```shell
github actions
```

**Comment by jthegedus** [comment]
I intend to do a rewrite the Action soon to simplify the codebase and make it easier to accept contributions from externals. I am watching the repo, I get notifications daily from Dependabot trying to bump the tooling, some of which requires manual intervention.

All is not lost.

**Comment by afirth** [comment]
thank you for the update! and the software, it's had a profound impact on our team and helped us move away from purely container-based workflows to something much faster and more dev friendly.
