### ISSUE TITLE
bug: No version is set for command which

### ISSUE THREAD

**Issue by azone** [asdf-vm/asdf#1285]
### Describe the Bug

When I use some system command like `which` asdf shows the following error message:
```
No version is set for command which
Consider adding one of the following versions in your config file at /Users/<my_name>/.tool-versions
nodejs 16.14.0
```

### Steps to Reproduce

execute `which xxx` in terminal

### Expected Behaviour

shows the right path of the command, e.g.:
```bash
which which #input
/usr/bin/which #output
```

### Actual Behaviour

asdf replaced some system commands

### Environment

```shell
OS:
Darwin Logans-MacBook-Pro-2.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

SHELL:
fish, version 3.5.0

ASDF VERSION:
v0.10.2

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/homebrew/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master f9957f3
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 47d327f
```

**Comment by Stratus3D** [comment]
In zsh:

```
$ which which
which: shell built-in command          
```

In Bash:

```
$ which which
/usr/bin/which
```

**asdf does not replace the `which` command.** However we have received reports of an nodejs NPM package replacing the `which` command. See https://github.com/asdf-vm/asdf/issues/584 https://github.com/asdf-vm/asdf/issues/505 If I were you I'd uninstall the nodejs plugin and re-generate shims and verify that fixes the issue. The root cause of this problem is the npm package replacing the `which` system command with it's own command. No package should ever do this in my opinion.

**Comment by azone** [comment]
Here are the commands under the shims, obviously some system commands was replaced by asdf:
```bash
11:28:23 ❯ ls ~/.asdf/shims/
bin-proxy  corepack  fastlane            gitbook     mkdirp    npm     racc    rdoc              rimraf       sshpk-conv         uuid       xcpretty                   yarn
bundle     dotenv    fuzzy_match         httpclient  node      npx     racc2y  read_manifest.rb  rougify      sshpk-sign         which      xcpretty-travis-formatter  yarnpkg
bundler    erb       gem                 irb         node-gyp  opener  rake    resolve           ruby         sshpk-verify       ww         xcversion                  🎉
commander  errno     get_app_version.rb  JSONStream  nopt      pod     rc      ri                sandbox-pod  terminal-notifier  xcodeproj  y2racc
```

**Comment by azone** [comment]
I was also doing the following steps:
1. remove the shims folder
2. re-generate the shims
