### ISSUE TITLE
Support a config that can install all my tool plugins and multiple versions per tool

### ISSUE THREAD

**Issue by nitrocode** [asdf-vm/asdf#1298]
### Is your feature request related to a problem? Please describe

I switch laptops frequently and when I'm on a new laptop, I need to install versions of my favorite tools. My current script is something like this.

```
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs latest
asdf install nodejs 15
asdf install nodejs 14
asdf install nodejs 13
asdf global nodejs latest
```

### Describe the proposed solution

https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f
https://docs.brew.sh/Manpage

A configuration file similar to homebrew's `Brewfile` where

- Run `brew bundle dump > Brewfile` to dump the full list of installed items from Brew
- Copy the file to another machine
- Run `brew bundle install` and it will install all my formula

I think the same workflow can be used in asdf (unless this already exists?).

e.g. 

`asdf bundle dump > Asdffile`

```ini
# Asdffile
plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs latest 15 14 13
asdf global nodejs latest
```

Then `asdf bundle install --file Asdffile` or just `asdf bundle install` (implicit `Asdffile`)

### Describe similar `asdf` features and why they are not sufficient

Create a script that runs `asdf plugin add` for each tool and then `asdf <tool> install <version>` for each tool and version. It works but I can forget to update the script, forget to add a tool, or forget to add a version.

### Describe other workarounds you've considered

I cannot think of another workaround

**Comment by jthegedus** [comment]
If we are ever going to implement automatic install of plugins we will utilise the existing file `.tool-versions` file format, if anything.

In the meantime, you can write your own Shell script make what you want easier, you've essentially written the script in your description, just put it in a file `setup-nodejs` and run `bash setup-nodejs`.

This topic has been discussed extensively in these related issues:

- #1254
- #968
- #829
- #240
- #313

So I am going to close this in favour of continuing this conversation there.
