### ISSUE TITLE
bug: asdf install python not working

### ISSUE THREAD

**Issue by OuYangJinTing** [asdf-vm/asdf#1316]
### Describe the Bug
asdf install python not working
<img width="573" alt="image" src="https://user-images.githubusercontent.com/33079237/184493872-e0b0c04b-63ec-406d-a397-cda01811c1cd.png">

### Steps to Reproduce

Execute `asdf install python xxx` command

### Expected Behaviour

Execute `asdf install python xxx` command success

### Actual Behaviour

not working

### Environment

```shell
OS:
Linux 8a0708c33dbf 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-debian-linux-gnu)

ASDF VERSION:
v0.10.2-7e7a1fa

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/my/.asdf

ASDF INSTALLED PLUGINS:
golang                       https://github.com/kennyp/asdf-golang.git master cc8bc47
minio                        https://github.com/aeons/asdf-minio.git master 113b19d
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 05f99c3
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git master e0cb84c
python                       https://github.com/danhper/asdf-python.git master c9dc753
redis                        https://github.com/smashedtoatoms/asdf-redis.git master bf1276e
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 368792a
rust                         https://github.com/code-lever/asdf-rust.git master 0c88f99
yarn                         https://github.com/twuni/asdf-yarn.git main 376c540
```
```


### asdf plugins affected (if relevant)

python                       https://github.com/danhper/asdf-python.git master c9dc753

**Comment by pedromss** [comment]
Seems to be an issue with the plugin https://github.com/danhper/asdf-python/issues/140 not `asdf`. If you target a specific version it works (i.e. 3.7.2)

**Comment by OuYangJinTing** [comment]
> Seems to be an issue with the plugin [danhper/asdf-python#140](https://github.com/danhper/asdf-python/issues/140) not `asdf`. If you target a specific version it works (i.e. 3.7.2)

Thank you for the reply
