### ISSUE TITLE
Make asdf work inside a Docker image

### ISSUE THREAD

**Issue by quilicicf** [asdf-vm/asdf#1334]
### Is your feature request related to a problem? Please describe

# Summary

While trying to run `asdf` in a Jenkins kubernetes agent, we noticed the following error:

```
/home/jenkins/.asdf/bin/asdf: line 5: ./lib/utils.bash: No such file or directory
/home/jenkins/.asdf/bin/asdf: line 28: asdf_dir: command not found
/home/jenkins/.asdf/bin/asdf: line 81: asdf_dir: command not found
Unknown command: `asdf current`
```

We noticed that this stems from using `dirname "$0"` to find the path to the current script.

Depending on the context in which the script is run, `$0` seems to return different values.

Changing all occurrences by `${BASH_SOURCE[0]}` or directly using `${ASDF_DIR}` seems to fix this.

You can reproduce this by:

* creating the Dockerfile below
    ```Dockerfile
    FROM ubuntu

    RUN apt update \
      && apt install git -y \
      && git clone https://github.com/asdf-vm/asdf.git ~/.asdf

    ENV BASH_ENV=/root/.asdf/asdf.sh
    ```
* building the Docker image like with:
    ```bash
    docker buildx build --tag asdf .
    ```
* run the following command:
    ```bash
    docker run -it --rm "$IMAGE" bash asdf current
    ```

### Describe the proposed solution

The solutions I think about are to replace the usage of `$0` when linking asdf` scripts to either `${BASH_SOURCE[0]}` or `$ASDF_DIR`.

I'm not sure which is the safest:
* the first might not be super portable (not sure what the target is in terms of portability for `asdf`)
* the second depends on being sure that the variable is always set (I think it's correct, not sure though)

### Describe similar `asdf` features and why they are not sufficient

The only way I found to support this (new?) use-case is to source `asdf` in the `.bashrc` which forces one to run `asdf` with `bash --login`. 

That is a footgun I'd gladly avoid as the Docker image should hold the `asdf`-related complexity and not the image user IMO.

### Describe other workarounds you've considered

No other workarounds tested, I really need this to work.

**Comment by quilicicf** [comment]
Hey @Stratus3D
Do you think there's any chance to get this looked at? 
I have opened a PR that solves the issue on my side so this should be relatively straight-forward. 
(sorry for the ping)

**Comment by amrox** [comment]
This issue caught my eye because I use asdf in docker frequently and haven't had this problem.

If I run the image produced by the Dockerfile above like the following, it works:

```
❯ docker run -it --rm "$IMAGE" bash -c 'asdf current'
No plugins installed
```

Your patch still may be an improvement, but I just thought I'd pass that along. :)

**Comment by quilicicf** [comment]
Hum, so my example is probably busted since I do have the error on Jenkins :thinking: 
I'll try to fix the example first then.

**Comment by quilicicf** [comment]
In fact, this was a chair-keyboard-interface issue. 
Thanks @amrox, you saved me quite some time :rocket:

**Comment by Stratus3D** [comment]
Glad you were able to get this working @quilicicf . Sorry for the lack of a response here.
