### ISSUE TITLE
bug: Not able to download etcd

### ISSUE THREAD

**Issue by vvsudhir** [asdf-vm/asdf#1337]
### Describe the Bug

etcd is failing to download; I have tried a couple of versions but got the same error

 ✘  ~  asdf list all etcd
3.2.31
3.2.32
3.3.24
3.3.25
3.3.26
3.3.27
3.4.11
3.4.12
3.4.13
3.4.14
3.4.15
3.4.16
3.4.17
3.4.18
3.4.19
3.4.20
3.4.21
3.5.0-alpha.0
3.5.0-rc.0
3.5.0-beta.1
3.5.0-rc.1
3.5.0-beta.3
3.5.0-beta.4
3.5.0
3.5.1
3.5.2
3.5.3
3.5.4
3.5.5
3.6.0-alpha.0
 ~  asdf install etcd 3.5.5
Downloading etcdctl version 3.5.5 from
Error: etcdctl version 3.5.5 not found
 ✘  ~  asdf install etcd 3.5.4
Downloading etcdctl version 3.5.4 from
Error: etcdctl version 3.5.4 not found
 ✘  ~  asdf install etcd 3.5.3
Downloading etcdctl version 3.5.3 from
Error: etcdctl version 3.5.3 not found
 ✘  ~  asdf install etcd 3.4.21
Downloading etcdctl version 3.4.21 from
Error: etcdctl version 3.4.21 not found
 ✘  ~  asdf install etcd 3.2.31
Downloading etcdctl version 3.2.31 from
Error: etcdctl version 3.2.31 not found

### Steps to Reproduce

 ✘  ~  asdf list all etcd
3.2.31
3.2.32
3.3.24
3.3.25
3.3.26
3.3.27
3.4.11
3.4.12
3.4.13
3.4.14
3.4.15
3.4.16
3.4.17
3.4.18
3.4.19
3.4.20
3.4.21
3.5.0-alpha.0
3.5.0-rc.0
3.5.0-beta.1
3.5.0-rc.1
3.5.0-beta.3
3.5.0-beta.4
3.5.0
3.5.1
3.5.2
3.5.3
3.5.4
3.5.5
3.6.0-alpha.0
 ~  asdf install etcd 3.5.5
Downloading etcdctl version 3.5.5 from
Error: etcdctl version 3.5.5 not found
 ✘  ~  asdf install etcd 3.5.4
Downloading etcdctl version 3.5.4 from
Error: etcdctl version 3.5.4 not found
 ✘  ~  asdf install etcd 3.5.3
Downloading etcdctl version 3.5.3 from
Error: etcdctl version 3.5.3 not found
 ✘  ~  asdf install etcd 3.4.21
Downloading etcdctl version 3.4.21 from
Error: etcdctl version 3.4.21 not found
 ✘  ~  asdf install etcd 3.2.31
Downloading etcdctl version 3.2.31 from
Error: etcdctl version 3.2.31 not found

### Expected Behaviour

etcd should be downloaded

### Actual Behaviour

failed to install etcd

### Environment

```shell
✘  ~  asdf info
OS:
Darwin P7PLF7D6HN 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

SHELL:
zsh 5.8.1 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.10.2

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/homebrew/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
etcd                         https://github.com/particledecay/asdf-etcd.git master d265ec6
helm                         https://github.com/Antiarchitect/asdf-helm.git master a39e17b
kotlin                       https://github.com/asdf-community/asdf-kotlin.git master af9ab2c
maven                        https://github.com/halcyon/asdf-maven.git master add7c1c
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
python                       https://github.com/danhper/asdf-python.git master c9dc753
terraform                    https://github.com/asdf-community/asdf-hashicorp.git master bc4dec6
```

### asdf plugins affected (if relevant)

NA

**Comment by Stratus3D** [comment]
This is not an issue with asdf core but rather with asdf-etcd (https://github.com/particledecay/asdf-etcd). Please open an issue on the https://github.com/particledecay/asdf-etcd issue tracker.
