### ISSUE TITLE
bug: set global version and version is not recognized in subfolders

### ISSUE THREAD

**Issue by alexdauenhauer** [asdf-vm/asdf#1339]
### Describe the Bug

setting global version does not set the version globally

### Steps to Reproduce

```sh
~
> asdf global kubectl 1.20.15

~
> asdf current kubectl
kubectl         1.20.15         /Users/alexdauenhauer/.tool-versions

~
> cd $PROJECT

$PROJECT
> asdf current kubectl
kubectl         1.19.13         Not installed. Run "asdf install kubectl 1.19.13"

$PROJECT
> ls -l | grep .tool-versions

```

I have not set a local `kubectl` version and additionally this does not even match my system kubectl version (which is 1.25) so I have no idea where it is getting 1.19.13 or how to make it use 1.20.15

### Expected Behaviour

asdf would globally use the version that is set globally

### Actual Behaviour

asdf uses some version that I don't even have installed (maybe had installed at some point)

### Environment

```shell
OS:
Darwin USERNAME 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

SHELL:
zsh 5.9 (x86_64-apple-darwin21.3.0)

ASDF VERSION:
v0.10.2

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
kubectl                      https://github.com/asdf-community/asdf-kubectl.git master 68a5cf9
```

### asdf plugins affected (if relevant)

kubectl

**Comment by asampal** [comment]
What does `which kubectl` return in $PROJECT? BTW, I would also install the asdf version from the master branch, as there've been quite a number of commits since v0.10.2.

**Comment by alexdauenhauer** [comment]
hmmmm not sure what changed, I did `which kubectl` and got `kubectl: aliased to kubecolor` so I removed that alias to test and everything worked as expected. Then I put the alias back and everything still worked as expected. Not sure what to say... I guess you can close this. Thanks @asampal

**Comment by alexdauenhauer** [comment]
I had a .tools-version in a parent folder below $HOME but above $PROJECT that was causing the disconnect... 🤦
