### ISSUE TITLE
bug: `Too many args for cd command` error in fish

### ISSUE THREAD

**Issue by txxxxc** [asdf-vm/asdf#1344]
### Describe the Bug

I followed the documentation to build the asdf environment and my terminal prompts `Too many args for cd command

### Steps to Reproduce

```
in zsh
$ brew install asdf
$ echo -e "\nsource "(brew --prefix asdf)"/libexec/asdf.fish" >> ~/.config/fish/config.fish
$ fish
Too many args for cd command
```

### Expected Behaviour

The terminal don't prompt any error.

### Actual Behaviour

The terminal prompts `Too many args for cd command` error

### Environment

```shell
❯ asdf info
OS:
Darwin tt.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

SHELL:
zsh 5.8.1 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.10.2

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/homebrew/Cellar/asdf/0.10.2/libexec

ASDF INSTALLED PLUGINS:
golang                       https://github.com/kennyp/asdf-golang.git master cc8bc47
java                         https://github.com/halcyon/asdf-java.git master 2df9a2e
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 65441d3
python                       https://github.com/danhper/asdf-python.git master 8505457
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 09cd4a5

❯ fish --version
fish, version 3.5.1

❯ brew -v
Homebrew 3.6.4
Homebrew/homebrew-core (git revision 026be1f98de; last commit 2022-10-08)
Homebrew/homebrew-cask (git revision 7293d2ec45; last commit 2022-10-08)

```

### asdf plugins affected (if relevant)
Maybe, asdf plugins are irrelevant.

**Comment by jthegedus** [comment]
@txxxxc Is this still an issue for you?

The `git` installation method might solve your issues, the Homebrew method has many, many problems.

**Comment by txxxxc** [comment]
@jthegedus 
Yes, I will ignore this error for now. asdf was installed via git.
I am going to reinstall asdf using another installation method.
Which method would you recommend to install?

**Comment by jthegedus** [comment]
If you installed `asdf` via git, why in your reproduction did you `brew install asdf`?

>Which method would you recommend to install?

In the [getting started guide](https://asdf-vm.com/guide/getting-started.html):
1. Install deps for your OS with your package manager
2. Official Download - which is a git clone
3. Follow the "Fish & Git" guide.

**Comment by txxxxc** [comment]
> why in your reproduction did you brew install asdf?

I must install asdf via Homebrew. That was my typo.
Thank you recommend. I will try it later.

**Comment by jthegedus** [comment]
Okay, I will close this for now. If you see the issue in future, please feel free to open an new Issue.
