### ISSUE TITLE
Add documentation for Linux Homebrew installs need asdf.sh added to .bashrc not .bash_profile

### ISSUE THREAD

**Issue by richtong** [asdf-vm/asdf#1347]
### Is your feature request related to a problem? Please describe

In the current documentation, there is no entry for how to set up Homebrew on Linux (aka linuxbrew). I used the instructions for the Mac but in looking at it, there seem to be two instructions that are relevant for Git and Linux and then for Homebrew and Linux.

The net is that with Ubuntu (not sure about other versions of linux), The windowing manager Gnome will source .profile and then for each Gnome Terminal with run .bashrc, it will never actually run .bash_profile unless you are logging with ssh or a terminal shell (with CTRL-ALT-F3) for instance.

So the documentation should probably change. Since there is no /bin/sh installer for asdf, (which is too bad because it means on Linux, you always have to run asdf.sh from .bashrc just to set the PATH which is pretty inefficient.

### Describe the proposed solution

The quick solution is in the documentation site, add an entry for Linux and Homebrew which meshes together the Git and Linux and Homebrew and Mac instructions that is you should source

add to your .bashrc under Linux:

source "$(brew --prefix asdf)/libexec/asdf.sh"

### Describe similar `asdf` features and why they are not sufficient

The problem with the current documentation is that it does not include the linuxbrew case.

### Describe other workarounds you've considered

You really need the shim path to be set properly.

**Comment by jthegedus** [comment]
Hi @richtong This is a setup none of the core team use, we're happy to accept a PR with your suggested changes.
