### ISSUE TITLE
asdf devcontainer

### ISSUE THREAD

**Issue by iloveitaly** [asdf-vm/asdf#1354]
### Is your feature request related to a problem? Please describe

No.

### Describe the proposed solution

I built a docker image to be used with github codespaces. Is there a place where a link to it would fit into the asdf docs?

https://github.com/iloveitaly/asdf-devcontainer

### Describe similar `asdf` features and why they are not sufficient

No asdf-based devcontainer I could find. All of the devcontainers were locked to a single programming language, which was frustrating. 

### Describe other workarounds you've considered

n/a

**Comment by jthegedus** [comment]
I created a community projects section and added this there. Thanks!

**Comment by Stratus3D** [comment]
Thanks for creating asdf-devcontainer @iloveitaly !

**Comment by Alegrowin** [comment]
I've been using my own since a while now. 

It supports pre 0.16.0 and 0.16.0+, it also has a flag so the user can opt-in to add plugins, install and set the tools versions from `.tool-versions`

https://github.com/Alegrowin/devcontainer-features/
