### ISSUE TITLE
Import and export of states, envs, plugin etc

### ISSUE THREAD

**Issue by muhamedsalih-tw** [asdf-vm/asdf#1373]
### Is your feature request related to a problem? Please describe

No

### Describe the proposed solution

A command to export and import all states, config, plugin , env, etc.., to/from a file 

### Describe similar `asdf` features and why they are not sufficient

I only use brew which offer dumping current installed tap and cask 
but it's hard to manage work dependencies such as node version and plugins so I have recently switched to asdf

### Describe other workarounds you've considered

asdf list and manually install all language and manually do config

**Comment by muhamedsalih-tw** [comment]
If the feature already existing let me know it in this issue and close it.
If this feature not exist I shall insist this feature soon so that ppl can manage and migrate work dependencies very easily.
Thanks!

**Comment by jthegedus** [comment]
Plugins are system managed. We do not support managing plugins via a config file.

`asdf install` will install all versions of tools defined in the `.tool-versions` of the same directory the command is executed. If you don't have a plugin for the tool already installed, it will tell you to install one.

`.tool-versions` the file which should be shared in your project, other configuration is specific to your machine, so should be managed by the user of the machine, typically with dotfiles.

There are many existing discussions open regarding tracking plugins via a config file, so if you mean this, then this ticket is a duplicate.

I am going to close, but if you think I have misunderstood your question please comment with more information, thanks.
