### ISSUE TITLE
bug: Interaction between `asdf`, `flutter`, `pre-commit`, and `git-worktree` cause `flutter` to forget its version information

### ISSUE THREAD

**Issue by prestontw** [asdf-vm/asdf#1416]
### Describe the Bug

When using a combination of `asdf`, `asdf-flutter`, `pre-commit`, and `git-worktree`, the official `flutter` channels are missing and are replaced by branches in the git worktree. I've tried reproducing this without `asdf` and it works, making me think this is an issue with `asdf` or an issue with `pre-commit` or `flutter` raised through `asdf`. A minimal repo is available at https://github.com/prestontw/flutter-asdf-git_worktree-minimal-repo/tree/main

### Steps to Reproduce

- Check out https://github.com/prestontw/flutter-asdf-git_worktree-minimal-repo/tree/main
- Install pre-commit (https://pre-commit.com/)
- Install the hooks in this repo (`pre-commit install`)
- Install `asdf` (https://asdf-vm.com/guide/getting-started.html)
- Install `asdf-flutter` plugin (https://asdf-vm.com/guide/getting-started.html#_4-install-a-plugin (`asdf plugin add flutter`))
- Install version through `asdf`: `asdf install`
- Verify that everything works by making a dummy change and committing. If you run into flutter errors, `cd` to where `flutter` was installed (something like `~/.asdf/installs/flutter/3.3.10-stable` then checkout beta channel with `git checkout beta`)
- Make a git-worktree branch as a sibling of the main repo (`git worktree add sample-for-pre-commit`) and `cd` there
- Make a dummy change and commit it---watch the pre-commit output and how it doesn't know which channel it is on

### Expected Behaviour

Information on the actual flutter version being used should be displayed:
```
...
Flutter 3.7.0-1.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision c29b09b878 (2 weeks ago) • 2022-12-19 18:30:12 -0600
Engine • revision 8c99b0feaf
Tools • Dart 2.19.0 (build 2.19.0-444.2.beta) • DevTools 2.20.0
...
```

### Actual Behaviour

Information about the current repo is displayed instead. Flutter is very confused!
```
Flutter • channel pre-commit-in-worktree • git@github.com:prestontw/flutter-asdf-git_worktree-minimal-repo.git
Framework • revision 8e93fdcde9 (22 minutes ago) • 2023-01-05 00:09:28 -0600
Engine • revision 8c99b0feaf
Tools • Dart 2.19.0 (build 2.19.0-444.2.beta) • DevTools 2.20.0
```
In the above snippet, `pre-commit-in-worktree` is the name of the branch/git worktree folder I'm in. The repo information is for the repository I'm running in, not flutter. The framework revision is a git commit local to the repository I'm running in, not flutter.

### Environment

```shell
OS:
Linux fedora 6.0.15-300.fc37.aarch64 #1 SMP PREEMPT_DYNAMIC Wed Dec 21 18:09:20 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

SHELL:
GNU bash, version 5.2.9(1)-release (aarch64-redhat-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.10.2-7e7a1fa

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/ptw/.asdf

ASDF INSTALLED PLUGINS:
flutter                      https://github.com/oae/asdf-flutter.git master d108efd
```

I've run into this on my work Mac as well.

### asdf plugins affected (if relevant)

`asdf-flutter` (https://github.com/oae/asdf-flutter)

**Comment by Stratus3D** [comment]
This sounds like an issue specific to asdf-flutter. What leads you to believe this is a bug caused by asdf core?

>  If you run into flutter errors, cd to where flutter was installed (something like ~/.asdf/installs/flutter/3.3.10-stable then checkout beta channel with git checkout beta)

You shouldn't change anything in your `.asdf` directory manually. You should only use `asdf` commands to manipulate versions.

**Comment by prestontw** [comment]
> This sounds like an issue specific to asdf-flutter. What leads you to believe this is a bug caused by asdf core?

I went back to double-check that this was specific to `asdf` at all by using `flutter` downloaded via `git` and ran into the same issue. I now think that this isn't caused by `asdf`. Well, time to see if it's either `pre-commit` or `flutter` itself!

Thank you for the response!
