### ISSUE TITLE
bug: run `asdf local <name> <version>` in a directory without .tool-versions, see error messages

### ISSUE THREAD

**Issue by h3y6e** [asdf-vm/asdf#1417]
### Describe the Bug

If `asdf local <name> <version>` is run with no `.tool-versions` in the current directory, then the following error message is printed.
```text
tail: <$PWD>/.tool-versions: No such file or directory
```

This is not a fatal bug because a `.tool-versions` file is generated.

### Steps to Reproduce

1. Go to the directory where a `.tool-versions` file does not exist.
2. Run `asdf local <name> <version>`.
3. See error message.

### Expected Behaviour

`tail: <$PWD>/.tool-versions: No such file or directory` is not displayed and a `.tool-versions` file is created.

### Actual Behaviour

`tail: <$PWD>/.tool-versions: No such file or directory` is displayed. (a `.tool-versions` file is created.)

### Environment

```shell
OS:
Darwin mbp2019 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8.1 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.11.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
elixir                       https://github.com/asdf-vm/asdf-elixir.git master 1693b35
erlang                       https://github.com/asdf-vm/asdf-erlang.git master 0d402e6
flutter                      https://github.com/oae/asdf-flutter.git master d108efd
julia                        https://github.com/rkyleg/asdf-julia.git master 1788f0f
kubectl                      https://github.com/asdf-community/asdf-kubectl.git master 3d00592
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master c9e5df4
php                          https://github.com/asdf-community/asdf-php.git master 306793c
python                       https://github.com/danhper/asdf-python.git master 8505457
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 4eb815c
rust                         https://github.com/code-lever/asdf-rust.git master 0c88f99
terraform                    https://github.com/asdf-community/asdf-hashicorp.git master 3122c04
zig                          https://github.com/cheetah/asdf-zig.git master d88f6db
```

**Comment by h3y6e** [comment]
I thought perhaps this is caused by the following code evaluating `-n "$(tail -c1 "$file")"` first. 

https://github.com/asdf-vm/asdf/blob/60d4494d5d21f9d7bdd0778ca962ddb44280aff7/lib/functions/versions.bash#L67-L68

May I submit a PR to correct this?

**Comment by Stratus3D** [comment]
Thanks for the bug report @h3y6e ! And thanks for pinpointing the issue!

**Comment by h3y6e** [comment]
Thank you for your swift response!
