### ISSUE TITLE
bug: asdf can't find .tool-versions files

### ISSUE THREAD

**Issue by seanpascoe** [asdf-vm/asdf#1419]
### Describe the Bug

I used the documented installation process for git/bash on an amazon workspaces machine running ubuntu.
asdf is unable to find local nor global .tool-versions files for getting or setting. So running `asdf install` in a dir with a .tool-versions file results in "Either specify a tool..." and running `asdf global nodejs latest` results in:
``` bash
/home/user.name2/.asdf/lib/functions/versions.bash: line 67: /home/user.name2//home/user.name2/.tool-versions: No such file or directory
```
(I've changed the user name but it's the same format)

By that error the problem seems obvious; asdf is outputting $HOME twice when resolving the .tool-versions path. I've been looking through the source but I just don't know bash well enough to figure out why it's doing that. I've used asdf on several other physical machines and never had a problem. I'm assuming the aws workspaces environment must have something to do with it.

### Steps to Reproduce

1. Install asdf on aws workspace machine running Ubuntu
2. execute `asdf global nodejs latest`
3. get error: `/home/user.name2/.asdf/lib/functions/versions.bash: line 67: /home/user.name2//home/user.name2/.tool-versions: No such file or directory`

### Expected Behaviour

Should be able to use local and global .tool-versions files as documented.

### Actual Behaviour

asdf can't resolve .tool-versions file locations.

### Environment

```shell
OS:
Linux U-1GAITPLDZDR88 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 14:15:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.10.2-7e7a1fa

ASDF ENVIRONMENT VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=/home/user.name2/.tool-versions
ASDF_DATA_DIR=/home/user.name2/.asdf
ASDF_DIR=/home/user.name2/.asdf
ASDF_CONFIG_FILE=/home/user.name2/.asdfrc

ASDF INSTALLED PLUGINS:
elixir                       https://github.com/asdf-vm/asdf-elixir.git master 1693b35
erlang                       https://github.com/asdf-vm/asdf-erlang.git master 0d402e6
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master c9e5df4
```

**Comment by Stratus3D** [comment]
This looks similar, but not identical to, https://github.com/asdf-vm/asdf/issues/1417, which was fixed this morning.

Since you are not on the latest version of asdf, can you try upgrading and see if that fixes your issue? If you installed via git you can run `asdf update` to update to latest stable (`0.11.0`) or `asdf update --head` to update to latest master.

**Comment by seanpascoe** [comment]
Ok, updated to latest master, `v0.11.0-4125d2b`, but same issue.

**Comment by seanpascoe** [comment]
I figured out the bug (for me, at least) was introduced in `v0.10.2`. All versions before that resolve the paths fine.

**Comment by seanpascoe** [comment]
Ok, my bad. The issue was that `ASDF_DEFAULT_TOOL_VERSIONS_FILENAME` was erroneously set to `/home/user.name2/.tool-versions` by a third party ansible module. So when `file_name` was set to that env var in versions.bash, it was screwing everything up. 
So if anybody else has a similar issue, check to make sure that var isn't set to some unintended value.

**Comment by pythoninthegrass** [comment]
Thanks for the fix @seanpascoe! Forked bespoke ansible module and [fixed it](https://github.com/pythoninthegrass/ansible-role-asdf/commit/f8b8ecd9453c59c13a49f4d6a1e310df49bb98e3) 🙏
