### ISSUE TITLE
bug: Installing asdf without sourcing shell

### ISSUE THREAD

**Issue by GZLiew** [asdf-vm/asdf#1426]
### Describe the Bug

Hi

I have a server which runs amazon linux and I can only upload a bootstrap script to install the tools I need on the machine

That means I dont have access to sourcing the bashrc 

is there a way to install asdf by copying the bin files or symlink the files to the already available PATH environment?

thanks

### Steps to Reproduce

1. install asdf 
2. asdf command not found after script ends

### Expected Behaviour

asdf command should run

### Actual Behaviour

asdf command not found

### Environment

```shell
OS:
Linux 9a5a81343953 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

SHELL:
GNU bash, version 4.2.46(2)-release (aarch64-koji-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.11.0-6a4f51a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/root/.asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master c9e5df4
```

**Comment by hyperupcall** [comment]
Are you able to source your `"$HOME/.asdf/asdf.sh"` file (or wherever it is located) after you install `asdf`, but before you invoke `asdf`?
