### ISSUE TITLE
Installation shorthand

### ISSUE THREAD

**Issue by bopjesvla** [asdf-vm/asdf#143]
It would be nice to have something like:

```
asdf quick-install erlang asdf-vm/asdf-erlang <version>
```

Which is equivalent to:

```
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf install erlang <version>
asdf global erlang <version>
```

**Comment by Stratus3D** [comment]
I am not in favor of adding another installation command. Being that it only takes three command to do this now I don't think it's a big enough win to justify the addition of another command. With my workflow I'm rarely adding new plugins, and we I do I'm usually updating the setup script in [my dotfiles](https://github.com/Stratus3D/dotfiles) to automatically install the plugin and the default versions. I'm only using 6 plugins right now and I've been using asdf exclusively for almost a year. 

Are the three existing commands a pain point for you? Is there a scenario where this gets tedious?

**Comment by bopjesvla** [comment]
I do often install new languages, but I can see why this might not be broadly useful.
