### ISSUE TITLE
support R, racket, sml

### ISSUE THREAD

**Issue by nverno** [asdf-vm/asdf#144]
Here a few plugins for [Racket](https://github.com/nverno/asdf-racket), [R](https://github.com/nverno/asdf-R), and [SML/NJ](https://github.com/nverno/asdf-sml).  I don't know anything about macs though, so they are only tested on linux.  Let me know if I should add them/pull request.

**Comment by Stratus3D** [comment]
If you set up travis builds for the plugins and get them passing on at least one linux distro and OSX definitely create PRs for them. Thanks!
