### ISSUE TITLE
Switch runtime versions when changing branches in git

### ISSUE THREAD

**Issue by quilicicf** [asdf-vm/asdf#1466]
### Is your feature request related to a problem? Please describe

When upgrading a runtime tool's version in a git repository, people can get tripped because they `git checkout` from a branch with the old version to a branch with the new one and `asdf` doesn't pick that.

We're so accustomed to having tools up-to-date when `cd`ing and `git checkout`ing is so similar that it's very easy to get tripped. Even more so because the branch one checks out can have been changed by another developer and one might no even be aware that a tool was upgraded.

This often leads to issues that are painful to debug.

### Describe the proposed solution

It would be nice to have `asdf` react to `git checkout/switch` as for `cd`.

In practice, I'm not sure whether it's as easy to do as for `cd` but I know it can be done using git hooks (specifically, [the post-checkout hook](https://www.git-scm.com/docs/githooks#_post_checkout)).

### Describe similar `asdf` features and why they are not sufficient

No `asdf` feature that I know of can help for this.

### Describe other workarounds you've considered

I've considered writing a global `post-checkout` script on my machine but:

1. I think other people get tripped by this and it'd would be nice to have a more integrated solution
2. I have no idea how to tell `asdf` to switch runtime versions, can't find how it's done for `cd`. Would've used `asdf reshim` but it takes a noticeable time on my machine and `cd` commands don't hang that amount of time so I figured it's probably not what's done under the hood?

**Comment by jthegedus** [comment]
asdf doesn't do anything on `cd`. It is when you execute the commands managed by asdf that it resolves the version, dynamically, based on your current working directory. `asdf current` will show what asdf resolves from your current working directory. It looks for `.tool-versions` files from current dir walking up the directory tree to root `/`.

>When you try and run one of these executables, the shim is run instead, allowing asdf to identify which version of the tool is set in .tool-versions and execute that version.
>
> https://asdf-vm.com/guide/introduction.html#how-it-works

I wasn't aware Git Hooks were able to be set globally. [It seems it is possible](https://stackoverflow.com/questions/1977610/change-default-git-hooks/37293001#37293001). We (asdf core team) are opposed to automatically installing tools or messing with people's system configurations, so I doubt we would implement a feature for this.

With that said, we could have documentation for utilising the post-checkout hook to automatically run `asdf install` etc.

**Comment by quilicicf** [comment]
It would be nice to have some documentation about running `asdf install` on `git checkout` indeed :+1:.

Something like putting this in `~/.git/hooks/post-checkout`:

```bash
set -e

main() (
  oldRef="$1"
  newRef="$2"
  checkoutType="$3"

  localHookPath="$(git rev-parse --show-toplevel)/.git/hooks/post-checkout"

  if [[ -f "${localHookPath}" ]]; then
    "${localHookPath}" "$@" # Run local hooks if any
  fi


  if [[ "${checkoutType}" == '1' ]] && hasToolVersionsChanges "${oldRef}" "${newRef}" ; then
    printf 'Tool versions have changed, running asdf install\n'
    asdf install
  fi
)

hasToolVersionsChanges() (
  git diff --name-only "$1..$2" | grep --quiet '\.tool-versions$'
)

main "$@"
```

**Comment by hyperupcall** [comment]
I'm closing this from #1661. Partially because the the issue queue is growing and there aren't enough contributors to match - this is a "nice to have" feature and does not strictly need to be in core and does not strictly need to be included in the docs either.

The other reason - we don't currently have a dedicated "spot" for asdf recepies in the documentation. There is the usual usage and reference section, but it would be awkward to have this single code-snippet in a separate section (that has a single page).
