### ISSUE TITLE
Compiling c or c++ based plugins

### ISSUE THREAD

**Issue by ghanima** [asdf-vm/asdf#147]
I was wondering if there is anyway after a plugin is executed if I can pass an option to make
specifically te jobs function and the number of jobs I want to execute in parallel.

My use case is that I have an 8 core machine and want to compile all files with available resources instead of serially. 

cmd: make -j \#(number of cores)

If this is a feature that has not been thought about I would be happy to volunteer.

**Comment by tuvistavie** [comment]
Hi @ghanima, 
We set the `ASDF_CONCURRENCY` to the number of cores before calling the plugin,
so you would need to ask the plugin author to use it while compiling.

**Comment by Stratus3D** [comment]
Added the details on the `ASDF_CONCURRENCY` variable to the plugin guide in https://github.com/asdf-vm/asdf/commit/957c6307c6944495cadda0454645c8f243285e54. 

Closing this ticket. If there is anything else that needs to be addressed here please reopen the ticket.
