### ISSUE TITLE
bug: error installing python in asdf

### ISSUE THREAD

**Issue by 2004Lucas** [asdf-vm/asdf#1477]
### Describe the Bug

error installing python in asdf

### Steps to Reproduce

I'm using archwsl

`[lucaslinux@lucasPC ~]$ asdf install python latest
python-build 3.11.2 /home/lucaslinux/.asdf/installs/python/3.11.2
Downloading Python-3.11.2.tar.xz...
-> https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tar.xz
Installing Python-3.11.2...

BUILD FAILED (Arch Linux using python-build 2.3.13-1-g86a4423b)

Inspect or clean up the working tree at /tmp/python-build.20230215220228.5116
Results logged to /tmp/python-build.20230215220228.5116.log

Last 10 log lines:
checking for pkg-config... no
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... "linux"
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/tmp/python-build.20230215220228.5116/Python-3.11.2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details`

### Expected Behaviour

asdf should install python, but it's giving an error, I've already researched it, tried everything possible, and I can't solve it

### Actual Behaviour

asdf should install python, but it's giving an error, I've already researched it, tried everything possible, and I can't solve it

### Environment

```shell
[lucaslinux@lucasPC ~]$ asdf info
OS:
Linux lucasPC 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.11.1

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/asdf-vm

ASDF INSTALLED PLUGINS:
python                       https://github.com/danhper/asdf-python.git master 8505457
```

### asdf plugins affected (if relevant)

ASDF INSTALLED PLUGINS:
python                       https://github.com/danhper/asdf-python.git master 8505457

**Comment by GabrielTMartinez** [comment]
try running `pacman -S --needed base-devel openssl zlib xz tk` and then running `asdf install python latest` again
it may be because python is built from source, and it need these dependencies

**Comment by 2004Lucas** [comment]
> try running `pacman -S --needed base-devel openssl zlib xz tk` and then running `asdf install python latest` again it may be because python is built from source, and it need these dependencies


now it's an infinite installation, and no installing python

**Comment by 2004Lucas** [comment]
[lucaslinux@lucasPC ~]$ python -v
No version is set for command python
Consider adding one of the following versions in your config file at
python 3.11.2

**Comment by jthegedus** [comment]
@2004Lucas Please raise issues in the repos for the plugins you are having problems with. Once it has been determined it is not the plugin and indeed the asdf core, then raise the issue. It sounds like either an unsupported environment of the plugin or incorrect plugin setup as mentioned by @GabrielTMartinez .
