### ISSUE TITLE
Update functionality

### ISSUE THREAD

**Issue by Quintasan** [asdf-vm/asdf#148]
While fixing code-lever/asdf-rust#2 is relatively simple I can't help but notice we could use `asdf update` functionality to allow users to keep their nightlies up-to-date. Any ideas on how to implement this?

**Comment by vic** [comment]
Hm, so if I'm understanding it well, is this a proposal to have `asdf update rust <version>` that would just uninstall and install again that specific rust version?  How about naming it `reinstall`? How others feel about this, do you think there is any *real* advantage of having a command like this?

**Comment by Quintasan** [comment]
@vic Some Rust projects require nightly Rust toolchain. Due to its nature it will be getting out of date rather frequently so a way of keeping it up-to-date is desirable. 

As for naming it `reinstall`. I'm not going to be adamant about it or anything but for me `reinstall` means "uninstall X.Y.Z and install X.Y.Z back". I can imagine you realise it won't work that way with nightly since what works today might be broken beyond recognition in tomorrow's nightly.

**Comment by ShaneKilkelly** [comment]
> take my version X.Y.Z and replace it with the newer one

I suspect the issue with the `update` name is that updating from version 1.2.3 to version 1.2.3 is nonsensical, and only makes sense in the context of a `nightly` version.

Perhaps the `install` command should take a `--force` flag, which would force re-installation (or whatever you want to call it) of the version.

So in the case of Rust it would be something like `asdf install rust nightly --force`.

**Comment by tuvistavie** [comment]
I agree a `--force` flag to `install` would make sense.
I sometime recompile the same version of a language (for example when I forgot an optional dependency) and such a flag would help even though it is exactly the same version I am installing.

**Comment by Stratus3D** [comment]
I'm closing this issue in favor of #244. If there is anything else that needs to be addressed here please reopen this issue.
