### ISSUE TITLE
Permission denied when trying to install a Ruby

### ISSUE THREAD

**Issue by ipatch** [asdf-vm/asdf#149]
Hello, last night I set up another user account on my box (OS X 10.10.5) for pair programming sessions.  And today, I tried installing ruby 2.3.1 with the following command, `asdf install ruby 2.3.1` but I'm getting the following errors / output when I run the above mentioned command.

pair at rogue in /Users/pair
╰─λ asdf install ruby 2.3.1                                                              0 < 11:45:08
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file /ruby-2.3.1.tar.gz: Permission denied
curl: (23) Failed writing body (0 != 184)
tar: Error opening archive: Failed to open '/ruby-2.3.1.tar.gz'

Some helpful notes for my situation, the user account `pair` is a "standard user" on my box with NO administrative privileges.  I'm using `fish` shell with this user account.  I'm logging into this user account and testing the command(s) with `su - pair`.

From the above mentioned error messages it looks like `asdf` is trying to download ruby 2.3.1 but does not have the permissions to download the files (ruby) to where ever it is trying to download them to.

I know this is a long shot, but would it not be more appropriate for `asdf` to download source files into the users home dir to avoid these permission issues? (I could be totally wrong on this issue, just trying to lend a helpful hand, and thanks for reading.)

**Comment by ipatch** [comment]
For the record, I feel stupid.  This issue was related to me doing `su - pair`

**Comment by vic** [comment]
Oh sorry, just got home and saw your issue. So good you figured it out :)

**Comment by mcandre** [comment]
Need more details. Getting the same error with default zsh on macOS.
