### ISSUE TITLE
bug: Can't install php 8.0.0  

### ISSUE THREAD

**Issue by carlosonrails** [asdf-vm/asdf#1494]
### Describe the Bug

Trying to install PHP 8.0.0 locally but I get error in line the Makefile 785

### Steps to Reproduce

asdf plugin-add php https://github.com/asdf-community/asdf-php.git/
asdf install php 8.0.0

### Expected Behaviour

I think it should have install the version of php in the folder

### Actual Behaviour

error: make waiting for unfinished jobs

### Environment

```shell
OS:
Linux winterfell 6.2.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 Feb 2023 03:39:23 +0000 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.11.1

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/asdf-vm

ASDF INSTALLED PLUGINS:
php                          https://github.com/asdf-community/asdf-php.git master 1eaf4de
```

### asdf plugins affected (if relevant)

php

**Comment by Stratus3D** [comment]
@carlosonrails this issue should reported in the issue tracker for https://github.com/asdf-community/asdf-php/ as it is specific to the asdf-php plugin and is not an issue with asdf core.

**Comment by carlosonrails** [comment]
Ok. I'll do that.
