### ISSUE TITLE
Pip doesn't get the correct version when virtualenv is activated

### ISSUE THREAD

**Issue by fcrespo82** [asdf-vm/asdf#150]
# System:
asdf 0.2.1
Python plugin installed with 2.7.10 and 3.6.0 versions

# Steps to reproduce:
```
$ asdf global 2.7.10
$ mkdir version3
$ cd version3
$ asdf local python 3.6.0
$ pip -V
```
Outputs the correct version 
`pip 9.0.1 from /Users/<username>/.asdf/installs/python/3.6.0/lib/python3.6/site-packages (python 3.6)`

```
$ virtualenv new
$ . new/bin/activate
$ pip -V
```
Outputs the WRONG version 
`pip 9.0.1 from /Users/<username>/version3/new/lib/python2.7/site-packages (python 2.7)
`

# Conclusion
I don't know if I'm doing something wrong, but I expected `pip` to get the version of the current local config.

If its by virtualenv's design, please add a command `asdf which python` to get the path of the current python so we can pass to virtualenv's `-p` flag.

**Comment by Stratus3D** [comment]
@fcrespo82 `asdf current python` may give you the information you need to pass to `-p`. I'm not too familiar with Python, but that behavior may be intended. @tuvistavie is this the way pip and asdf-python are suppose to work?

**Comment by tuvistavie** [comment]
`-p` option requires the path, so `asdf current` will not do for this case.

I explicitly pass the path to python when I create a new virtualenv:

```
virtualenv -p ~/.asdf/installs/python/3.5.2/bin/python myenv
```

it could also be done with

```
virtualenv -p $(asdf where python 3.5.2)/bin/python myenv
```

but this also requires to explicitly pass the version,
so I agree being able to change this into

```
virtualenv -p $(asdf which python) myenv
```

would be an improvement.

What do you guys think?

**Comment by fcrespo82** [comment]
For workaround I am doing 

```
virtualenv -p $(asdf where python $(asdf current python))/bin/python myenv
```

**Comment by Stratus3D** [comment]
@tuvistavie I think the addition of a `which` command would be a good idea. That would give us three related commands:

* `current` - print the current version and the path to the tool-version file
* `where` - show the path to the root of a specific version
* `which` - show the path to the current version of the specified executable

**Comment by fcrespo82** [comment]
Related to #72

**Comment by Stratus3D** [comment]
Closing since I don't think there is anything else asdf can do to make this easier. If anyone thinks of anything else that could be done to make this easier please create another issue here or on asdf-python (https://github.com/tuvistavie/asdf-python).

**Comment by Stratus3D** [comment]
I think the equivalent for asdf would be:

```
asdf install ruby 2.5.1
asdf reshim ruby 2.5.1
asdf local ruby 2.5.1
gem install rails
```

**Comment by look4regev** [comment]
Thanks @fcrespo82 for the workaround.
Another even shorter option we eventually found (just adding here for future references) is:
`$(asdf where python)/bin/virtualenv myvenv`
It will use the correct python version just as well.

**Comment by danhper** [comment]
If using Python3, I usually do

```
python -m venv myvenv
```

I never had any issue with this.

**Comment by look4regev** [comment]
@danhper That's actually an even better solution, thanks!
I tested it and it's working also for python2. Have you seen specific case in python2 that it doesn't work?

**Comment by danhper** [comment]
For `python -m virtualenv myenv` to work, you need to have the virtualenv pip package installed. AFAIK, this is indeed the only way to get it to work for Python 2.
For Python >= 3.3, the module `venv` is part of the standard library so `python -m venv myenv` will work out of the box. But `-m virtualenv` would of course also work provided that the `virtualenv` package is installed.

**Comment by morenoh149** [comment]
@danhper I don't follow. That command would not create the virtualenv right? that looks like a way to prefix you python invocations (after you have activated the virtualenv).

**Comment by danhper** [comment]
`python -m venv venv` would indeed create a virtual environment in the `venv` directory relative to the current directory.
Unless using whatever shell hook, you would need to activate it using `source venv/bin/activate` or so though.

**Comment by morenoh149** [comment]
interesting, never heard of that and it works! Maybe you can edit your original comment to say `makes a virtualenv using whatever is the current python`.

**Comment by mlavi** [comment]
I solved this by following [asdf-community/asdf-direnv](https://github.com/asdf-community/asdf-direnv#setup) instructions, which caused me to amend my .bashrc and the following in my .envrc:

```
source "$(asdf direnv hook asdf)"
use asdf
layout python3
```

Then I got exactly what I expected with `pip3 --version`
