### ISSUE TITLE
Nushell `asdf plugin list --urls` regex is broken

### ISSUE THREAD

**Issue by acidghost** [asdf-vm/asdf#1503]
### Describe the Bug

Nushell's `asdf plugin list --urls` has the wrong regex and does not display anything. The regex expects an url of the form `git@[...].git`: https://github.com/asdf-vm/asdf/blob/0adc6c11fb4f87dbb476f8b61e4cf8fb7613599b/asdf.nu#L82

### Steps to Reproduce

Just run `asdf plugin list --urls` in Nushell with plugins installed from a repo url that starts with `https`.

### Expected Behaviour

It shows the table of plugins.

### Actual Behaviour

Does not display anything.

### Environment

```shell
OS:
Darwin acidghost-MBP.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

SHELL:
zsh 5.8.1 (x86_64-apple-darwin22.0)

ASDF VERSION:
v0.11.3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/acidghost/.dotfiles/asdf-vm

ASDF INSTALLED PLUGINS:
clojure                      https://github.com/asdf-community/asdf-clojure.git master 490074c
golang                       https://github.com/kennyp/asdf-golang.git master f006a12
java                         https://github.com/halcyon/asdf-java.git master 54b7426
julia                        https://github.com/rkyleg/asdf-julia.git master 1788f0f
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master c9e5df4
perl                         https://github.com/ouest/asdf-perl.git master 4edc8ab
python                       https://github.com/danhper/asdf-python.git master 8505457
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 7a671a2
```

**Comment by jthegedus** [comment]
Hey @acidghost now you have an idea of what the test cases look like from #1502 , I would love the help here for another PR to resolve this, if you have the capacity :pray:
