### ISSUE TITLE
bug: When working with Nix, `cd /` will cause `nix command not found` error.

### ISSUE THREAD

**Issue by nyngwang** [asdf-vm/asdf#1520]
### Describe the Bug

As title.

### Steps to Reproduce

1. Run `cd /`
2. Type `nix`

### Expected Behaviour

nix should always be there since I have put the following lines at the end of `~/.zshrc@`: (these lines are auto-generated by Nix I just copy-paste it into my zsh config)

```zsh
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
```

### Actual Behaviour

nix command not found

### Environment

```shell
v0.11.3
```

**Comment by jthegedus** [comment]
So what part of this relates to asdf?

**Comment by jthegedus** [comment]
So you followed the uninstall guide https://asdf-vm.com/manage/core.html#uninstall and then now are having issues?

**Comment by jthegedus** [comment]
I'm confused. Are you using asdf or not?

**Comment by jthegedus** [comment]
@nyngwang it's just a matter of needing more information mate. This is what I would need to understand to help further:

1. now you have removed asdf are you no longer intending on using it?
2. would you like to use asdf but this issue stopping you?
3. if you are wanting to use asdf, are you able to help triage the problem further?
4. when in a broken state, what is your setup?
	a. is asdf installed?
    b. does asdf work as expected?
    c. are other tools broken or is it just nix which is broken?
    d. how have you setup nix? was it through a tool managed by asdf?
    e. what is your `asdf info` output

**Comment by jthegedus** [comment]
Thanks for the info.

If you suspect this is related to the `asdf-direnv` integration, then it would be best to raise this issue in the `asdf-direnv` repository. Once the integration is determined NOT to be the issue, then it would make sense to raise it here with further investigation in the core.

I agree that this sounds like a direnv integration issue. I will close for now and you can raise the issue in `asdf-direnv`. If it is found not to be an issue there we can reopen this Issue.
