### ISSUE TITLE
Outputting only a version number with some flag variation on the ASDF current <name> command

### ISSUE THREAD

**Issue by dlinch** [asdf-vm/asdf#1541]
### Is your feature request related to a problem? Please describe

I have a custom shell script to reassign my command line prompt to output some key version numbers in case I'm switching around repos or between branches.

In other version managers it's easy to display just a version number from a `which version` command, however the output of the asdf version command is:

```bash
# erlang          17.3          /Users/kim/.tool-versions
```

I'm forced to write a bunch of regex to pull just the version number out, but I figure there has to be a use case where we only want to print the version number if I've already specified the plugin name.

### Describe the proposed solution

I see the value in keeping the original command with all the relevant context, I wonder if we can pass a flag to the command to specify version number only as a return value.

Perhaps some kind of `-r/--return` flag and you can specify which values to return:

```bash
asdf current erlang -r version
# 17.3

asdf current erlang -r version path
# 17.3          /Users/kim/.tool-versions
```

I'd be more than happy with a simpler syntax for only returning version though -> `-v/--version-only`

```bash
asdf current erlang -v
# 17.3
```

### Describe similar `asdf` features and why they are not sufficient

`asdf current <name>` is the feature I'd like to extend. It returns way more information than simply the version number.

### Describe other workarounds you've considered

I have added a custom REGEX, but as someone less familiar with Bash I've found it difficult to actually test and Google for reasonable syntax, so I've spun my wheels on this for quite a while. I don't think Bash is exactly the most user friendly syntax we have available to us as programmers.

**Comment by jthegedus** [comment]
I believe this is a duplicate of #1469 

If you agree, please close and watch the other thread.

**Comment by dlinch** [comment]
@jthegedus It is! Thanks!
