### ISSUE TITLE
Core Infrastructure Initiative (CII) Best Practices

### ISSUE THREAD

**Issue by ypid** [asdf-vm/asdf#155]
I would like to point you to the [CII Best Practices Badge Program](https://bestpractices.coreinfrastructure.org). Could you go thought the [criteria](https://bestpractices.coreinfrastructure.org/criteria), [add the project](https://bestpractices.coreinfrastructure.org/projects/new) and keep it up-to-date there?

Refs:
- https://bestpractices.coreinfrastructure.org
- https://twit.tv/shows/floss-weekly/episodes/389

**Comment by Stratus3D** [comment]
Can you provide some clear examples of how the current behavior of asdf should be changed to address this? It's not clear what action needs to be taken here (hence why this ticket has sat here for over a year unaddressed).

**Comment by ypid** [comment]
The actions are also not clear to me because I am not as deeply involved in the project. But there is a way to find out :) Just [add the project](https://bestpractices.coreinfrastructure.org/projects/new) and we will see. Sounds good?

**Comment by Stratus3D** [comment]
I'm not going to add the project myself because there isn't any clear need to or benefit in doing so. If you or anyone else wants to add asdf yourself feel free to. I'm not opposed to having it done, I'm just not sure it would be a good use of my time right now (40+ other issues need tending to).
