### ISSUE TITLE
bug: `asdf global ... system` needs write access to the entire HOME directory when `.tool-versions` already exists there

### ISSUE THREAD

**Issue by lestephane** [asdf-vm/asdf#1556]
### Describe the Bug

I removed write access on my $HOME a long time ago, to explicitly allowlist the files / directories required by the tools I use, and to avoid the tools that have weird or unenforcable writing habits.

Asdf looks like it needs write access to the home directory because it uses `sed -i` to modify `.tool-versions` when `.tool-versions` exists
 
```
$ asdf global python system
sed: couldn't open temporary file /home/lestephane/sedWp3RW1: Permission denied
```

I'd expect write access to `.tool-versions` is all asdf needs for me to run this command.

### Steps to Reproduce

```
$ truncate -s 0 $HOME/.tool-versions
$ chmod a-w $HOME
$ asdf global python system
$ asdf global python system
sed: couldn't open temporary file /home/lestephane/sediRUEgd: Permission denied
```

### Expected Behaviour

No error on the second call to `asdf global python system`

### Actual Behaviour

Second call fails

### Environment

```shell
...
ASDF VERSION:
v0.11.3
...
```

### asdf plugins affected (if relevant)

N/A

**Comment by hyperupcall** [comment]
When #1351 is fully implemented (right now it isn't), this will be addressed because the global `.tool-versions` will be in a asdf-specific directory (with only a few files).
