### ISSUE TITLE
3.7.8 & 3.8.8 sucess but install fail 3.6.8

### ISSUE THREAD

**Issue by BK-Go-Python** [asdf-vm/asdf#1557]
### Describe the Bug

(base) BKdeMacBook-Pro:~ bk$ asdf install python 3.6.8
python-build --patch 3.6.8 /Users/bk/.asdf/installs/python/3.6.8
with patch file from: https://github.com/python/cpython/commit/8ea6353.patch?full_index=1
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.8.tar.xz...
-> https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tar.xz
Installing Python-3.6.8...
patching file Misc/NEWS.d/next/macOS/2020-06-24-13-51-57.bpo-41100.mcHdc5.rst
patching file configure
Hunk https://github.com/asdf-community/asdf-python/pull/1 succeeded at 3375 (offset -51 lines).
patching file configure.ac
Hunk https://github.com/asdf-community/asdf-python/pull/1 succeeded at 495 (offset -15 lines).
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.5.1 using python-build 2.3.17-9-g528d10e9)

Inspect or clean up the working tree at /var/folders/td/chkt1d7s7px_t7x3nk0v3c3w0000gn/T/python-build.20230511012026.31179
Results logged to /var/folders/td/chkt1d7s7px_t7x3nk0v3c3w0000gn/T/python-build.20230511012026.31179.log

Last 10 log lines:
checking for --with-cxx-main=... no
checking for clang++... no
configure:

By default, distutils will build C++ extension modules with "clang++".
If this is not intended, then set CXX on the configure command line.

checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found. Stop.
(base) BKdeMacBook-Pro:~ bk$ asdf list python
3.10.8
3.11.3
3.7.8
3.8.8
3.9.8

### Steps to Reproduce

log:
`1 /var/folders/td/chkt1d7s7px_t7x3nk0v3c3w0000gn/T/python-build.20230511012026.31179 ~
2 /var/folders/td/chkt1d7s7px_t7x3nk0v3c3w0000gn/T/python-build.20230511012026.31179/Python-3.6.8 /var/folders/td/chkt1d7s7px_t7x3nk0v3c3w0000gn/T/python-build.20230511012026.31179 ~
3 checking build system type... x86_64-apple-darwin21.6.0
4 checking host system type... x86_64-apple-darwin21.6.0
5 checking for python3.6... no
6 checking for python3... python3
7 checking for --enable-universalsdk... no
8 checking for --with-universal-archs... no
9 checking MACHDEP... darwin
10 checking for --without-gcc... no
11 checking for --with-icc... no
12 checking for gcc... clang
13 checking whether the C compiler works... yes
14 checking for C compiler default output file name... a.out
15 checking for suffix of executables...
16 checking whether we are cross compiling... no
17 checking for suffix of object files... o
18 checking whether we are using the GNU C compiler... yes
19 checking whether clang accepts -g... yes
20 checking for clang option to accept ISO C89... none needed
21 checking how to run the C preprocessor... clang -E
22 checking for grep that handles long lines and -e... /usr/bin/grep
23 checking for a sed that does not truncate output... /usr/bin/sed
24 checking for --with-cxx-main=... no
25 checking for clang++... no
26 configure:
27
28 By default, distutils will build C++ extension modules with "clang++".
29 If this is not intended, then set CXX on the configure command line.
30
31 checking for the platform triplet based on compiler characteristics... darwin
32 configure: error: internal configure error for the platform triplet, please file a bug report
33 make: *** No targets specified and no makefile found. Stop.`

### Expected Behaviour

install sucess

### Actual Behaviour

install fail

### Environment

```shell
OS:
Darwin BKdeMacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

SHELL:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.

ASDF VERSION:
v0.10.2

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
python                       https://github.com/danhper/asdf-python.git master 8505457
```

**Comment by BK-Go-Python** [comment]
log:
`  1 /var/folders/td/chkt1d7s7px_t7x3nk0v3c3w0000gn/T/python-build.20230511012026.31179 ~
  2 /var/folders/td/chkt1d7s7px_t7x3nk0v3c3w0000gn/T/python-build.20230511012026.31179/Python-3.6.8 /var/folders/td/chkt1d7s7px_t7x3nk0v3c3w0000gn/T/python-build.20230511012026.31179 ~
  3 checking build system type... x86_64-apple-darwin21.6.0
  4 checking host system type... x86_64-apple-darwin21.6.0
  5 checking for python3.6... no
  6 checking for python3... python3
  7 checking for --enable-universalsdk... no
  8 checking for --with-universal-archs... no
  9 checking MACHDEP... darwin
 10 checking for --without-gcc... no
 11 checking for --with-icc... no
 12 checking for gcc... clang
 13 checking whether the C compiler works... yes
 14 checking for C compiler default output file name... a.out
 15 checking for suffix of executables...
 16 checking whether we are cross compiling... no
 17 checking for suffix of object files... o
 18 checking whether we are using the GNU C compiler... yes
 19 checking whether clang accepts -g... yes
 20 checking for clang option to accept ISO C89... none needed
 21 checking how to run the C preprocessor... clang -E
 22 checking for grep that handles long lines and -e... /usr/bin/grep
 23 checking for a sed that does not truncate output... /usr/bin/sed
 24 checking for --with-cxx-main=<compiler>... no
 25 checking for clang++... no
 26 configure:
 27 
 28   By default, distutils will build C++ extension modules with "clang++".
 29   If this is not intended, then set CXX on the configure command line.
 30 
 31 checking for the platform triplet based on compiler characteristics... darwin
 32 configure: error: internal configure error for the platform triplet, please file a bug report
 33 make: *** No targets specified and no makefile found.  

> Stop.`

**Comment by hyperupcall** [comment]
It looks like this is Python-specific and should be posted in [asdf-python](https://github.com/asdf-community/asdf-python)
