### ISSUE TITLE
Add copy to clipboard option on in the installation guide

### ISSUE THREAD

**Issue by ArslanYM** [asdf-vm/asdf#1558]
### How can we improve the documentation?

# add a copy to clip board option on these code lines
![copy tocb](https://github.com/asdf-vm/asdf/assets/104521101/c820601d-6c6d-477b-89d9-ae611d0d4799)

**Comment by hyperupcall** [comment]
This sounds like a useful feature, but my vote is to close this issue as a wontfix. With over 110+ open issues and with the low resources this project has, it's probably best to forgo this in favor of higher-impact enhancements and bug-fixes.

**Comment by ArslanYM** [comment]
@hyperupcall You can put this on hold, Maybe sometime in the future you might wanna add this feature.

**Comment by jthegedus** [comment]
@ArslanYM I have been waiting for [Vitepress](https://vitepress.dev/) beta to migrate the docs site from Vuepress. Vitepress has this feature out of the box, so this will be implemented once I get to the docs migration (sometime this coming weekend)

**Comment by hyperupcall** [comment]
til! I guess implementing this is relatively straight forward then.

**Comment by jthegedus** [comment]
This is now live.
