### ISSUE TITLE
Show `plugin update` path

### ISSUE THREAD

**Issue by abitrolly** [asdf-vm/asdf#1573]
### Is your feature request related to a problem? Please describe

It is not clear where `asdf` persists plugin updates.
```
$ asdf plugin update ruby
Updating ruby to master
From https://github.com/asdf-vm/asdf-ruby
   cfc5fb1..5e2eded  master     -> master
   cfc5fb1..5e2eded  master     -> origin/master
Already on 'master'
Your branch is up to date with 'origin/master'.
```

For Gitpod workflow, all changes that need to be persisted should be stored in `/workspace` - everything else is being reset on restarts, and `asdf` doesn't show where it stores updates.

### Describe the proposed solution

```
$ asdf plugin update ruby
Plugin ruby location: /whatever
Updating ruby to master
From https://github.com/asdf-vm/asdf-ruby
   cfc5fb1..5e2eded  master     -> master
   cfc5fb1..5e2eded  master     -> origin/master
Already on 'master'
Your branch is up to date with 'origin/master'.
```

### Describe similar `asdf` features and why they are not sufficient

I don't know any.

### Describe other workarounds you've considered

Can't think of UX workarounds.

**Comment by edvardsanta** [comment]
hello, do you want somethin like this?
![image](https://github.com/asdf-vm/asdf/assets/75655486/6b8061d5-334e-4939-b98b-47f09b8ff6de)

**Comment by abitrolly** [comment]
@edvardsanta hi. Yes, that's it.
