### ISSUE TITLE
Incorrect call signature on bin/latest-stable script

### ISSUE THREAD

**Issue by kamontat** [asdf-vm/asdf#1576]
### How can we improve the documentation?

From code: query never be empty as it set default value once it is empty.

https://github.com/asdf-vm/asdf/blob/5b7d0fea0a10681d89dd7bf4010e0a39e6696841/lib/functions/versions.bash#L136

But on document said 

> Call signature from asdf core
> The script should accept a single argument, the filter query.
> 
> "${plugin_path}"/bin/latest-stable ""
> "${plugin_path}"/bin/latest-stable "$query"

ref: https://asdf-vm.com/plugins/create.html#bin-latest-stable

**Comment by hyperupcall** [comment]
Thanks for feedback! I've made a PR to fix this
