### ISSUE TITLE
Support per package OpenPGP keyring

### ISSUE THREAD

**Issue by ypid** [asdf-vm/asdf#159]
I would propose to standardize a way to manage a per package OpenPGP keyring. The keyring could be maintained in `$HOME/.asdf/keyrings/nodejs`. Maybe it makes also sense to include the commands which are needed to setup the keyring into this repo?

Ref: https://github.com/asdf-vm/asdf-nodejs/pull/25

**Comment by danhper** [comment]
I will close this issue, as it has been inactive for a long time now.
If there is still interest, please feel free to open a new issue.
Thank you!
