### ISSUE TITLE
Automatically install tool's specified version if not present

### ISSUE THREAD

**Issue by marcwrobel** [asdf-vm/asdf#1606]
### Is your feature request related to a problem? Please describe

Currently when running a tool that is not installed, but has its version specified in the `.tool-versions` file, the command fails with a message such as:

```
$ mvn
No preset version installed for command mvn
Please install a version by running one of the following:

asdf install maven 3.9.2
...
```

### Describe the proposed solution

Instead of having an error, the tool could be automatically installed using the provided command. This would be really great for:

- teams working on a project having a dedicated committed `.tool-versions`, as there would be no need for them to install the new version before re-running the command,
- continuous integration, as it would remove the need to have a dedicated step to make sure the correct tool's version is installed before using it (when the installed tool are cached).

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

N/A

**Comment by Stratus3D** [comment]
Unfortunately we don't have any plans to support this in the future. However, it's very easy to work around this. As shown in the output you pasted above:

```
...
asdf install maven 3.9.2
...
```

This can be shortened to `asdf install`. Still not quite as convenient as auto install, but hopefully not too bad :pray:
