### ISSUE TITLE
Ability to temporarily keep installation source code when installation fails to reinstall later.

### ISSUE THREAD

**Issue by bnsv** [asdf-vm/asdf#1612]
### Is your feature request related to a problem? Please describe

Not really a big deal but I keep on redownload the source-codes everytime my compilation fails. I did install php on ubuntu that turns out my pc missing some subtle libs. First it was libgd-dev then failed, reinstalling then missing libonig-dev (oniguruma) then failed again, next reinstall was missing libzip-dev. I must redownload  the sourcecode file everytime I  do reinstall. 

### Describe the proposed solution

It will be good to keep the sourcecode for a while untill the installation succeeds, or for a day, or until the user do clean/flush the cache.

### Describe similar `asdf` features and why they are not sufficient

asdf install

### Describe other workarounds you've considered

Just keep the downloaded SC for a while weather it succeeds or fails.

**Comment by hyperupcall** [comment]
We have an [`always_keep_download`](https://asdf-vm.com/manage/configuration.html#always-keep-download) option - is this what you're looking for?

**Comment by bnsv** [comment]
I believe it is. I am sorry for not loking carefully. Thank you hyperupcall .
