### ISSUE TITLE
Expand the requirements section for the Quickstart docs

### ISSUE THREAD

**Issue by AlpinDale** [asdf-vm/asdf#1620]
### How can we improve the documentation?

There are five packages that need to be installed on a fresh OS to allow building python, 3 of which are necessary while 2 are optional but highly recommended. The commands for installing each on Ubuntu are:

```sh
sudo apt-get install libffi-dev
sudo apt-get install libreadline-dev
sudo apt-get install libssl-dev
sudo apt-get install libsqlite3-dev    #optional
sudo apt-get install liblzma-dev    #optional

```

**Comment by hyperupcall** [comment]
This should be moved to [asdf-python](https://github.com/asdf-community/asdf-python). It might be worth standardizing where links to official build documentation (for languages that are built by asdf) across official asdf repositories. That way, it would be easier to see exactly what's needed.
