### ISSUE TITLE
[Proposal] Jruby Plugin

### ISSUE THREAD

**Issue by mjcloutier** [asdf-vm/asdf#165]
It would be awesome if someone was willing to add a jruby plugin.

**Comment by HashNuke** [comment]
@mjcloutier The ruby plugin supports jruby. Atleast 1 version AFAIK. Just needs to be updated probably. Could use help with that.

**Comment by Stratus3D** [comment]
I created https://github.com/asdf-vm/asdf-ruby/issues/30. Closing this issue.
