### ISSUE TITLE
bug: M2 Mac OS Sonoma (14.0) cannot install any version of python

### ISSUE THREAD

**Issue by sephethus** [asdf-vm/asdf#1666]
### Describe the Bug

asdf plugin add python
Plugin named python already added

asdf install python 3.10
python-build 3.10 /Users/username/.asdf/installs/python/3.10
python-build: definition not found: 3.10

.tool-versions content
python 3.10

### Steps to Reproduce

1. m2 Mac
2. Update to Sonoma
3. brew install asdf
4. asdf plugin add
5. asdf install python 3.10

### Expected Behaviour

Should have installed python 3.10

### Actual Behaviour

Gets above error: no definitions found
python-build 3.10 /Users/nmckaskle/.asdf/installs/python/3.10
python-build: definition not found: 3.10

### Environment

```shell
OS:
Darwin MY_COMPUTER_NAME 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64

SHELL:
zsh 5.9 (x86_64-apple-darwin23.0)

BASH VERSION:
3.2.57(1)-release

ASDF VERSION:
v0.13.1

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/Users/username/.asdf
ASDF_DIR=/opt/homebrew/Cellar/asdf/0.13.1/libexec
ASDF_CONFIG_FILE=/Users/username/.asdfrc

ASDF INSTALLED PLUGINS:
python                       https://github.com/danhper/asdf-python.git master 5e277e2
```

### asdf plugins affected (if relevant)

python only

**Comment by sephethus** [comment]
Nevermind ChatGPT gave me an answer that Google couldn't, it needs 3 points i.e. 3.10.13

**Comment by jthegedus** [comment]
Yes, asdf requires full versions.
