### ISSUE TITLE
bug: exit code for a failure in terraform comamnd

### ISSUE THREAD

**Issue by anush0247** [asdf-vm/asdf#1668]
### Describe the Bug

I am not able get the error code when wrapping the terraform command with asdf 

### Steps to Reproduce

The below script is not working 

``` 
#!/bin/bash
set -e
exec /root/.asdf/bin/asdf exec "terraform" "$@"
# Capture the exit status of the Terraform command
exit_status=$?

# Check the exit status and display a message
if [ $exit_status -eq 0 ]; then
          echo "Terraform command succeeded"
  else
            echo "Terraform command failed with an error"
fi

# Exit with the captured exit status
exit $exit_status
```

where as below script is working 

The below script is not working,  I need to execute few more commands based on tf plan / any tf command is success or failure?

``` 
#!/bin/bash
set -e
exec "terraform" "$@"
# Capture the exit status of the Terraform command
exit_status=$?

# Check the exit status and display a message
if [ $exit_status -eq 0 ]; then
          echo "Terraform command succeeded"
  else
            echo "Terraform command failed with an error"
fi

# Exit with the captured exit status
exit $exit_status
```

### Expected Behaviour

give the exit_status

### Actual Behaviour

Its not giving the exit_status

### Environment

```shell
local / docker
```

**Comment by hyperupcall** [comment]
This isn't an issue with Terraform - it's an issue with your script. When you use `exec`, execution immediately began into the executable that you specify. The rest of the script is _never_ executed.

I think ShellCheck catches this case, I'd recommend using it to help find these kind of errors.
