### ISSUE TITLE
version 1:erlang is not installed for erlang

### ISSUE THREAD

**Issue by StevenXL** [asdf-vm/asdf#168]
Hi folks,

Not sure if this is the correct repo to post this in, but I am having trouble using `asdf` and `erlang`.

```
asdf list erlang
=> 18.3

asdf local erlang 18.3

asdf current erlang
=> version 1:erlang is not installed for erlang

erl
=> erlang 1 not installed
```
Also, I can run the **erl** binary located here: `~/.asdf/installs/erlang/18.3/bin/erl`. 
I am using **iTerm**, **zsh**, and I'm on **macOS Siera 10.12.3**. 

I am using the thoughtbot dotfiles located here: `https://github.com/thoughtbot/dotfiles`, with the following in my `.zshrc.local`, which is loaded last:

```
# History
setopt extendedhistory  # store timestamps use history -<option> command to read
setopt histignoredups   # ignore consecutive dupes
setopt histreduceblanks # compact consecutive whitespace chars

# Integration with direnv
eval "$(direnv hook zsh)"

# Stack needs following dir in PATH env
export PATH=$PATH:/Users/stevenleiva/.local/bin:/Users/stevenleiva/.mix/escripts

# Mix needs following path
export PATH=$PATH:/Users/stevenleiva/.mix/escripts

# Racket needs following path
export PATH=$PATH:/Applications/Racket\ v6.7/bin

#kiex
# test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

# Support 256 color schemes
export TERM="xterm-256color"
setopt RM_STAR_WAIT

# ASDF
source $HOME/.asdf/asdf.sh
source $HOME/.asdf/completions/asdf.bash
```

**Comment by Stratus3D** [comment]
@StevenXL very odd. Can you include the contents of `.tool-versions` file in the directory you ran those asdf commands in? It appears as if `1:erlang` is set as the Erlang version, which is of course wrong. When I run that sequence of commands I do not get that error.

You could also try commenting out direnv in your `.zshrc.local`. I'm not familiar with it but there is always the chance it could be affecting asdf.

**Comment by StevenXL** [comment]
@Stratus3D - thank you for the response. Below is the info you requested:

```
ls -al
=> drwxr-xr-x   3 stevenleiva  staff  102 Mar  7 10:06 .
=> drwx------+ 10 stevenleiva  staff  340 Mar  6 18:27 ..
=> -rw-r--r--   1 stevenleiva  staff   12 Mar  7 10:06 .tool-versions

cat .tools-versions
=> erlang 18.3
```

I've also commented out `direnv` such that `~/.zshrc.local` now contains:

```
# History
setopt extendedhistory  # store timestamps use history -<option> command to read
setopt histignoredups   # ignore consecutive dupes
setopt histreduceblanks # compact consecutive whitespace chars

# Integration with direnv
# eval "$(direnv hook zsh)"

# Stack needs following dir in PATH env
export PATH=$PATH:/Users/stevenleiva/.local/bin:/Users/stevenleiva/.mix/escripts

# Mix needs following path
export PATH=$PATH:/Users/stevenleiva/.mix/escripts

# Racket needs following path
export PATH=$PATH:/Applications/Racket\ v6.7/bin

#kiex
# test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

# Support 256 color schemes
export TERM="xterm-256color"
setopt RM_STAR_WAIT

# ASDF
source "$HOME/.asdf/asdf.sh"
source "$HOME/.asdf/completions/asdf.bash"
```

Unfortunately, I am still getting the same error:

```
erl
=> erlang 1 not installed
```

P.S. I made sure to exit out of `tmux`, completely quit `iTerm`, and then ran `erl` in the correct directory in `iTerm`.

**Comment by Stratus3D** [comment]
@StevenXL I realized I didn't have the latest version of asdf installed on my system. Upon updating it I get this:

    $ asdf local erlang 18.2
    $ asdf current erlang
    version erlang is not installed for erlang

So definitely a bug. Thanks for reporting!

I'll try to get a fix out this evening.

**Comment by StevenXL** [comment]
@Stratus3D thank you very much. Please let me know if I can be helpful (running commands / showing output) and I'll try to do my best.

**Comment by Stratus3D** [comment]
@StevenXL I started on a fix and realized the version string contained color codes, and that was breaking a sed command. Can you check your `$GREP_OPTIONS`? Mine was set to:

    --color=always

Changing it to auto fixed the issue for me:

    --color=auto

I'm working on a fix so we don't have to worry about `GREP_OPTIONS` breaking asdf.

**Comment by StevenXL** [comment]
@Stratus3D 

```
echo $GREP_OPTIONS
=> -n --color=auto
```

I've changed it to `--color=auto` and it works! 

Thank you.
