### ISSUE TITLE
bug: nushell `def-env` is deprecated

### ISSUE THREAD

**Issue by acidghost** [asdf-vm/asdf#1680]
### Describe the Bug

Version 0.87 of nushell deprecates the use of `def-env` nushell/nushell#10715. It will be removed in the next version.

This is the only place where it's used: https://github.com/asdf-vm/asdf/blob/fad23bc9f4d38747f28d6708ab01689749030063/asdf.nu#L1

AFAIK just replacing it with `def --env` should work.

### Steps to Reproduce

Just use asdf from nushell.

### Expected Behaviour

No deprecation warnings should be issued with version 0.87.

### Actual Behaviour

Deprecation warnings with version 0.87.

### Environment

```shell
Not relevant.
```

**Comment by hyperupcall** [comment]
thanks for the report. this has been fixed in #1681
