### ISSUE TITLE
Repo README lint test status badges affect anchor URL

### ISSUE THREAD

**Issue by sparr** [asdf-vm/asdf#1688]
### How can we improve the documentation?

https://github.com/asdf-vm/asdf#asdf--

This URL has a trailing `--` due to the inclusion (or possibly the specific formatting) of the Lint and Test badges. I suggest either moving those to their own line, possibly above or below the title, or possibly changing their formatting, such that the anchor link becomes the more predictable https://github.com/asdf-vm/asdf#asdf

**Comment by hyperupcall** [comment]
Thank you for the report - this is a Good First Issue for anyone reading this and interested. A PR can simply be made, instead of "asking for assignment".

**Comment by ooooo-create** [comment]
I am interested in this, and open a pr for #1725
