### ISSUE TITLE
[Proposal] Command to update asdf itself?

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#172]
It might be nice to have a command that would allow users to update asdf itself to the latest tagged version or the latest on the master branch. Right now it's a manual process that requires the user to:

     cd $ASDF_DIR
     git pull origin master # Or a specific tag

Might be nice to have a command that would do this for the user:

    asdf update-asdf # Checkout the most recent tag
    asdf update-asdf --latest # Pull the latest from the master branch

It could also warn the user if they switch to an older commit (e.g. moving from the master branch to the most recent tag that lacks some changes on master). What do you guys think? I guess we are only saving a couple commands, but it still might be nice to have an official way to update asdf.

**Comment by tuvistavie** [comment]
I agree this would a good addition!

**Comment by HashNuke** [comment]
👍  This would be awesome. We could just use `update` and `update --head`
