### ISSUE TITLE
The startup guide doesn't mention how to set the PATH

### ISSUE THREAD

**Issue by ramiror** [asdf-vm/asdf#1731]
### How can we improve the documentation?

I didn't see any mention to the addition of `~/.asdf/bin` to the `PATH`. It's obvious but it is not mentioned before the warning _asdf scripts need to be sourced after you have set your `$PATH`_

**Comment by jthegedus** [comment]
I believe this is an issue specific to the Homebrew installation which we have no control over. 

For non-Homebrew, our documentation site "Getting Started" page has these steps outlined, with warnings about various installation methods.
