### ISSUE TITLE
can we have windos?

### ISSUE THREAD

**Issue by Cohawv** [asdf-vm/asdf#1761]
### Is your feature request related to a problem? Please describe

can we have windos?

### Describe the proposed solution

can we have windos?

### Describe similar `asdf` features and why they are not sufficient

can we have windos?

### Describe other workarounds you've considered

can we have windos?

**Comment by klippx** [comment]
Not very eloquently put, but yes, it would be nice with a tool that worked cross platform. Most devs at most companies can choose Mac or Windows, so asdf is only ever very useful if Windows is **not** in the picture.

**Comment by hyperupcall** [comment]
Duplicate of #465 and #450

**Comment by jthegedus** [comment]
Closing as duplicated as mentioned.

**Comment by airtonix** [comment]
Highly recommend you switch to using [Mise](https://mise.jdx.dev/) instead if you want to support `.tool-versions` on windows
