### ISSUE TITLE
Don't add python bin to PATH when executing pip-installed commands

### ISSUE THREAD

**Issue by juhoautio** [asdf-vm/asdf#1774]
### Is your feature request related to a problem? Please describe

I've installed some python CLI commands with `pip`. My `pip` is wrapped by `asdf` and so it points to a python version that was installed with `asdf`'s Python plugin.

Now, if I run any pip-installed command via asdf, `PATH` is modified so that the associated python installation's bin folder comes _before_ asdf shims. So, if I execute a system command inside this scope, the asdf shims don't apply, because the `{python-version}/bin` comes first in the `PATH`.

Would it be possible to avoid this?

My setup:
```shell
asdf which python
```

> /Users/juhoautio/.asdf_rosetta/installs/python/3.7.17/bin/python

The `PATH` rewriting by asdf Python plugin can be demonstrated with a python command.

Executed via asdf:
```shell
python -c "import os; print(os.environ['PATH'])"
```

> /Users/juhoautio/.asdf_rosetta/plugins/python/shims:**/Users/juhoautio/.asdf_rosetta/installs/python/3.7.17/bin**:/Users/juhoautio/.asdf_rosetta/shims:/usr/local/opt/asdf/libexec/bin:...

Which is the same as:
```shell
asdf exec python -c "import os; print(os.environ['PATH'])"
```

Executed directly:
```
/Users/juhoautio/.asdf_rosetta/installs/python/3.7.17/bin/python -c "import os; print(os.environ['PATH'])"
```
> /Users/juhoautio/.asdf_rosetta/shims:/usr/local/opt/asdf/libexec/bin:...

The same issue affects any pip-installed CLI commands. For example, I installed `poetry==1.1.8` with `pip` inside this python version. Now that version of poetry takes precedense over any asdf-managed version, when executing `poetry` from inside python.

As a practical example, I set:
```shell
asdf local poetry 1.5.1
```

With this asdf provides the expected version (not 1.1.8 which is the default in my case):
```
poetry --version
```
> Poetry (version 1.5.1)

Running python directly, I get the expected result:
```shell
/Users/juhoautio/.asdf_rosetta/installs/python/3.7.17/bin/python -c \
  "import subprocess; subprocess.check_call(['poetry', '--version'])"
```
> Poetry (version 1.5.1)

But via asdf the shim for `poetry` gets overridden by the version from the chosen python's bin:
```shell
python -c "import subprocess; subprocess.check_call(['poetry', '--version'])"
```
> Poetry version 1.1.8

### Describe the proposed solution

I would like to see this when invoking via asdf:

Executed via asdf:
```shell
python -c "import os; print(os.environ['PATH'])"
```

> /Users/juhoautio/.asdf_rosetta/plugins/python/shims:/Users/juhoautio/.asdf_rosetta/shims:/usr/local/opt/asdf/libexec/bin:...

So otherwise the same as currently, but with this part removed: `/Users/juhoautio/.asdf_rosetta/installs/python/3.7.17/bin:`

Is there some valid reason why pip-installed commands should behave differently when executed via asdf vs. directly?

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

N/A

**Comment by RobLoach** [comment]
May want to create an issue in the asdf-python queue: https://github.com/asdf-community/asdf-python/issues

**Comment by juhoautio** [comment]
Indeed. Sorry I didn't realize that plugins are not part of this repo. However, I opted for using pyenv directly, so this is not an issue for me any more.
