### ISSUE TITLE
suggest rewrite in rust to avoid slow startup time

### ISSUE THREAD

**Issue by GopherJ** [asdf-vm/asdf#1776]
### Is your feature request related to a problem? Please describe

I'm thinking of switching to use asdf but it's written in shell, so I assume it'll be super slow in slow shell like zsh.

### Describe the proposed solution

fnm is fast, you can rewrite asdf in rust

### Describe similar `asdf` features and why they are not sufficient

nvm, goenv, pyenv turn to slow down the shell startup time like crazy so I avoid as much as possible things written in shell

### Describe other workarounds you've considered

N/A

**Comment by GopherJ** [comment]
https://github.com/asdf-vm/asdf/issues?q=startup+time

**Comment by hyperupcall** [comment]
I'm pretty sure work is already being done to re-write the project in Rust, but there isn't much public information on that. There is a project called [mise](https://github.com/jdx/mise) which is pretty stable and is written in RUst

**Comment by jthegedus** [comment]
There are ongoing works to modernise asdf. It had a small scope during it's initial design and so has a lot of issues planned to be solved. If you desire a Rust implementation now, there are a couple of asdf-plugin compatible Rust managers in existence as suggested above.

**Comment by Stratus3D** [comment]
@GopherJ this week I'm preparing to release asdf 0.16.0 which will be implemented in Golang. PR is #1805 if you are curious.
