### ISSUE TITLE
`asdf which -a`

### ISSUE THREAD

**Issue by nmccamish** [asdf-vm/asdf#1783]
### Is your feature request related to a problem? Please describe

If multiple versions have the same tool installed (or tools with the same name), you can only see the path to the executable installed in the current version.

### Describe the proposed solution

I would like a feature similar to Unix's `which -a`, where it would "print all matching pathnames," but for all versions.

### Describe similar `asdf` features and why they are not sufficient

`asdf which` is good enough, if there only is one version of some tool installed.

### Describe other workarounds you've considered

Iterating through `asdf list`, executing `asdf shell`, then `asdf which` for each version.

**Comment by jthegedus** [comment]
Does this do what you need it to do?

https://asdf-vm.com/manage/core.html#shim-versions

**Comment by nmccamish** [comment]
Indeed, it does! I missed that, apologies!
