### ISSUE TITLE
bug: ASDF_DIR always bring 0.14.0 after upgrade

### ISSUE THREAD

**Issue by agungwas** [asdf-vm/asdf#1784]
### Describe the Bug

i'm upgrading from 0.14.0 to 0.14.1 using homebrew. after upgrade it it give this
`╰─>$ asdf
Unknown command: `asdf `
/opt/homebrew/Cellar/asdf/0.14.1/libexec/bin/asdf: line 120: /opt/homebrew/Cellar/asdf/0.14.0/libexec/lib/commands/command-help.bash: No such file or directory`
the asdf

### Steps to Reproduce

1. brew uninstall asdf --zap
2. `echo $ASDF_DIR`  got `/opt/homebrew/Cellar/asdf/0.14.0/libexec`
3. brew install asdf
4. asdf got `Unknown command: `asdf `
/opt/homebrew/Cellar/asdf/0.14.1/libexec/bin/asdf: line 120: /opt/homebrew/Cellar/asdf/0.14.0/libexec/lib/commands/command-help.bash: No such file or directory`

### Expected Behaviour

the env var for $ASDF_DIR should upgraded too

### Actual Behaviour

when call asdf, got different version in

### Environment

```shell
cannot do that
```

**Comment by jthegedus** [comment]
Have you checked the Homebrew repo to see if this been raised over there? We don't control how Homebrew upgrades software or maintain the Homebrew stuff.

**Comment by Stratus3D** [comment]
I'm going to close this as this isn't an issue with the code in this repository.
