### ISSUE TITLE
[Proposal] Create a simple plugin repository for easier installation of plugins

### ISSUE THREAD

**Issue by doughsay** [asdf-vm/asdf#181]
I recently switched to oh-my-fish, and also wrote a simple plugin for it easily get started with asdf in fish: https://github.com/doughsay/omf-asdf

While working on my plugin, I learned of how oh-my-fish handles packages, and it's very simple and elegant.  I think asdf could maybe benefit from something similar.

In oh-my-fish, you just run `omf install <package>` to install new packages. It accomplishes this because they have a simple package repository here: https://github.com/oh-my-fish/packages-main. The installation command clones / updates that repo and checks for the given plugin name in the list of packages.  Packages are described by simple text files that looks like this:

```
type = plugin
repository = YOUR-PACKAGE-URL
maintainer = YOUR-NAME <YOUR-EMAIL>
description = YOUR-PACKAGE-DESCRIPTION
```

So, I'm proposing creating a new repository where we can create files for each plugin that exists right now, with the tool name being the filename and the repository field in the file being used when installing the plugin.  This would allow for a quick and easy:

```
asdf plugin-install elixir
```

Which would get the plugin repo url from the plugins repository.

Backwards compatibility with specifying a url should of course be maintained. This would just be an enhancement to the plugin-install command if no url is provided.

The benefits I see are mostly for more user adoption.  The easier it is for users to get started, the happier they'll be using asdf! :)

Thoughts?

**Comment by Stratus3D** [comment]
That definitely would make it easier to use, but I'm not sure it would be worth the effort at this point. Installing plugins is usually a one time thing, so it's pretty minimal barrier to entry. It also makes it clear to the end user that Git is really what's doing all the work behind the scenes. 

@asdf-vm/maintainers what do you guys think?

**Comment by Jwashton** [comment]
For what it's worth, I find myself installing plugins once a month or so. This could be because I'm setting up a new VM, or trying to learn a new language. Every time I have pull up the asdf readme so I can copy/pasta the appropriate link. I don't see this as a one-time thing, and I would absolutely appreciate this change.

I have only minimal bash experience, but I would be willing to contribute some time for this if that would help.

**Comment by tuvistavie** [comment]
It would definitely be useful, but I do not really have time to work on this right now.
If somebody is willing to work on it and send a PR, I will be glad to review it.
If we are going to add this, I think we should also have a `plugin-list-all` command to show the user all the available plugins.

**Comment by doughsay** [comment]
Since it's my proposal after all, I would like to take a stab at the implementation of this.  I'm working on a basic idea for it now, I'll open a pull as soon as I'm ready to get some feedback on it.

**Comment by tuvistavie** [comment]
Great, thank you very much!

**Comment by changalberto** [comment]
I would like to also propose an update to the commands. I find this to be more intuitive and easier to remember for someone new using this tool, especially someone like me, coming from the `nvm` world:

```bash
MANAGE PLUGINS
asdf plugin list                       List all local plugins
asdf plugin list --remote              List plugins available from central registry
asdf plugin add <name>                 Install remote plugin
asdf plugin remove <name>              UnInstall a plugin from local machine
asdf plugin update <name>              To update a plugin to the latest stable release
asdf plugin update -a, --all           To update all of your plugins to the latest stable release

MANAGE PACKAGES
asdf package list             List all locally installed packages
asdf package list --default       List all packages that currently being used
asdf package list <plugin>            List all installed packages for a plugin
asdf package list <plugin> --remote    To list all available package versions for a plugin
asdf package install <plugin> <version>
asdf package uninstall <plugin> <version>

asdf use <package> <version>            Set this package and version for current session
asdf use <package> <version> --default  Set this as your default package
asdf use <package> --system             Use system default
```

You add/remove plugins, and install/uninstall packages.

Would love to hear everyone's thoughts and comments.

**Comment by tuvistavie** [comment]
While I am not against using sub-commands, I do not really want to break backwards compatibility without a very good reason to do so.
People coming from `nvm` will probably find `asdf use ~~` better, while people from `rbenv` will probably find `asdf global ~~` better, and same goes with most commands, so I don't think this is a strong enough argument to break compatibility.
This is open to discussion, but please open a new issue if you want to continue discussing this issue.

**Comment by changalberto** [comment]
@tuvistavie Thanks for sharing the argument. I think that is very reasonable. Then I don't believe it's worth the hassle in making those changes. I'll get used to it in time =)
