### ISSUE TITLE
Unintentional releases?

### ISSUE THREAD

**Issue by jsejcksn** [asdf-vm/asdf#1818]
Prior to 24 hours ago, every release was named with a semantic version and included documented changes in the form of release notes ([example](https://github.com/asdf-vm/asdf/releases/tag/v0.14.0)). However, today there were several releases named after truncated commit hashes, for example:

- https://github.com/asdf-vm/asdf/releases/tag/9c12b79
- https://github.com/asdf-vm/asdf/releases/tag/54d15e3
- https://github.com/asdf-vm/asdf/releases/tag/753c0b7
- https://github.com/asdf-vm/asdf/releases/tag/d5f0214

Is this intentional? If I missed a discussion about this then I'm sorry about the noise — feel free to link me to it — but the new behavior seems very odd based on the project history.

**Comment by Stratus3D** [comment]
Hi @jsejcksn,

Thanks for opening this issue. Yes, the releases are unintentional. They are actually dev builds introduced by https://github.com/asdf-vm/asdf/pull/1805. We're preparing for an eventual release of a Golang version of asdf, and that requires actually building binaries for those that choose the binary download install method.

I will disable the `release-build` workflow right now. I'll also delete all most recent of the bad releases, and mark it as a pre-release.
