### ISSUE TITLE
bug: asdf update command removed in v0.15.0

### ISSUE THREAD

**Issue by talha5389** [asdf-vm/asdf#1824]
### Describe the Bug

`asdf update` now gives output 

```
Upgrading asdf via asdf update is no longer supported. Please use your OS
package manager (Homebrew, APT, etc...) to upgrade asdf or download the
latest asdf binary manually from the asdf website.

Please visit https://asdf-vm.com/ or https://github.com/asdf-vm/asdf for more
details.
```

but docs still refer to use `asdf update` to update it https://asdf-vm.com/guide/getting-started.html

### Steps to Reproduce

1. Install asdf version v0.15.0
2. run `asdf update`

### Expected Behaviour

It should update or documentation should be updated to reflect the new behavior

### Actual Behaviour

It gives error without any prior notice

### Environment

```shell
Ubuntu 24.04
```

**Comment by Stratus3D** [comment]
Thanks for pointing this out @talha5389 , I forgot to update the documentation. The command has been removed in preparation for version 0.16.0 which is a rewrite of the codebase in Golang (see #1805). This is fixed in PR #1825

**Comment by Stratus3D** [comment]
PR #1825 has been merged. The website should be updated in a few minutes.

**Comment by bmulholland** [comment]
The website still highly recommends installing asdf via git ([ref](https://asdf-vm.com/guide/getting-started.html#_2-download-asdf)) while the `asdf upgrade` error seems to recommend a package manager instead (since that'll manage upgrades). I guess the installation method of choice is now via a package manager?

**Comment by bmulholland** [comment]
And, in that case, can I suggest a migration guide from the old to the new recommended installation method? e.g. uninstalling the git version, installing via homebrew, and especially doing that in the least disruptive way possible.

**Comment by Stratus3D** [comment]
Hi @bmulholland , sorry for the mess with the current docs. We are in the process of moving asdf from being a bunch of Bash scripts installed via asdf to a Golang binary installed via `go install` or OS package manager. I've got the updates for the docs here: https://github.com/asdf-vm/asdf/pull/1826 Unfortunately I can't merge these doc changes until the Go code is released, and I've still got a few things I need to do before the Go code is ready.

In the meantime, know that `asdf upgrade` is gone forever, it was our own homebrewed solution and we think it's better to use more mainstream distribution mechanisms.

**Comment by bmulholland** [comment]
Thanks @Stratus3D! No apologies necessary, I know migrations are hard. Just sharing areas you might want to cover as you go through it, to be hopefully helpful. Good luck with the changes!
