### ISSUE TITLE
Unable to install ruby 2.1.1

### ISSUE THREAD

**Issue by OndrejKu** [asdf-vm/asdf#184]
Only this version doesn't work. Others do work. 
`gzip: stdin: not in gzip format
tar: Child returned status 1`

**Comment by Stratus3D** [comment]
@OndrejKu versions not listed by `asdf list-all ruby` may not be supported by asdf-ruby. I forget where it tries to download them from, but it's quite likely the URL that was constructed based off that version wasn't valid, and a 404 page was downloaded instead.

**Comment by Stratus3D** [comment]
Closing this issue it's an asdf-ruby issue and not an asdf issue. Also the cause of this is the same as https://github.com/asdf-vm/asdf-ruby/issues/29.
