### ISSUE TITLE
yaourt and "No version set for nodejs"

### ISSUE THREAD

**Issue by 4ndv** [asdf-vm/asdf#186]
I'm using ArchLinux and every time i'm trying to install something via yaourt, that requires installed nodejs, i'm facing this:

![image](https://cloud.githubusercontent.com/assets/10115449/24595163/2299c574-185e-11e7-8522-6b36b33ef314.png)

OS: ArchLinux
Shell: zsh

**Comment by 4ndv** [comment]
```shell
cd ~/.asdf && git pull origin master
```
Fixed this for me

**Comment by Stratus3D** [comment]
@4ndv from now on you should be able to use `asdf update` to update to the latest asdf release.
