### ISSUE TITLE
asdf still shows version at 0.2.1 after update to 0.3.0

### ISSUE THREAD

**Issue by sobbybutter** [asdf-vm/asdf#189]
I just ran `asdf update` and got the following output:

`HEAD is now at d3a66d7... Merge pull request #173 from asdf-vm/prepare-for-0.3.0
Updated asdf to release v0.3.0`

After restarting the shell, `asdf --version` still displays 0.2.1

**Comment by Jwashton** [comment]
I suspect that if you go to your asdf install directory and run `git describe --tags` you will find a `v0.3.0--n-nnnnnnnn` version number of some sort. The version returned by `--version` appears to be hardcoded [here](https://github.com/asdf-vm/asdf/blob/5ec5a747fff93d12dd8e297139feb707d57161fb/lib/utils.sh#L6-L8) and it just didn't get updated with the latest release.

Beyond the obvious next step of updating the version number, I'd recommend actually referring to the git tag when querying the version. That way the two numbers always stay in sync, and the project maintainers have less work to do on release. The downside being that this solution makes assumptions about the release process. I'll go ahead an put together a pull request with that solution, but the project maintainers should decide whether or not that's the solution they want.

Also, sorry for jumping in. I was actually checking for something else and saw an issue I understood! :)

**Comment by Stratus3D** [comment]
That is definitely wrong, and definitely my mistake. When I tagged the 0.3.0 release I forgot to update the version in lib/utils.sh. Since it's already tagged it may be best to wait until the next tag to correct the version. I've corrected the version on master in 934a5bd228b4a4421529d0f8f1e70f4947536317.

**Comment by sobbybutter** [comment]
Thanks! :)
