### ISSUE TITLE
.asdf/lib/utils.sh: line 71: [: !=: unary operator expected

### ISSUE THREAD

**Issue by yangzhichina** [asdf-vm/asdf#191]
After installation of `erlang` v19.3 on `CentOS 7`, there is an issue `~/.asdf/lib/utils.sh: line 71: [: !=: unary operator expected` when I run `asdf current erlang`. Has everybody seen it before? Thanks.

**Comment by yangzhichina** [comment]
`check_if_version_exists() {
  local plugin_name=$1
  local version=$2
  local version_dir=$(asdf_dir)/installs/$plugin_name/$version

  # if version starts with path: use that directory
  if [ "${version/path:}" != "$version" ]; then
      version_dir=$(echo $version | cut -d: -f 2)
  fi

  check_if_plugin_exists $plugin_name

  **if [ $version != "system" ] && [ ! -d $version_dir ]; then**
    display_error "version $version is not installed for $plugin_name"
    exit 1
  fi
}
`
Please check the bold line for this issue.

**Comment by yangzhichina** [comment]
This issue had been fixed after running `asdf global erlang 19.3`. But I still thought `asdf current erlang` should've worked even if the `global` cmd is not run yet.

**Comment by Stratus3D** [comment]
Reopening this since I think this is a bug that manifests when `$version` isn't set. I tested it on my machine and was able to replicate it by removing a tool from the `.tool-versions` file and then running `asdf current <tool>`. Thanks for reporting @yangzhichina !

**Comment by Stratus3D** [comment]
@yangzhichina I believe this has been fixed by @henrik PRs (https://github.com/asdf-vm/asdf/commit/d7ceb38b060d1dcf41cf9537da5d20e9c4e7a451). Can you test this again on the latest commit (`asdf update --head`)?

**Comment by padi** [comment]
I recently installed asdf with the kennyp/asdf-golang plugin. Tried the following:

```sh
$ asdf install go 1.8.3
# clones successfully
$ asdf current go
~/.asdf/lib/utils.sh: line 71: [: !=: unary operator expected
No version set for go
```
