### ISSUE TITLE
Missing execution permission

### ISSUE THREAD

**Issue by evandrojr** [asdf-vm/asdf#197]
Please add execution permission for

$HOME/.asdf/asdf.sh and  $HOME/.asdf/completions/asdf.bash

Thanks!

**Comment by Stratus3D** [comment]
@evandrojr I'll look into the permissions. Is there a bug this is causing?

**Comment by evandrojr** [comment]
Hi Trevor,

I was running the scripts without the dot at the begining.

I.e.  not like the way you recommend

 . ~/.asdf/asdf.sh

But only
~/.asdf/asdf.sh


 Maybe it is not a bug after all. Sorry for that. I will try now withot the
permission and check if it is working. Then I will close the issue in case
it works.

Em 28/05/2017 21:51, "Trevor Brown" <notifications@github.com> escreveu:

@evandrojr <https://github.com/evandrojr> I'll look into the permissions.
Is there a bug this is causing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/asdf-vm/asdf/issues/197#issuecomment-304551471>, or mute
the thread

**Comment by evandrojr** [comment]
Not a bug! closing the issue!
