### ISSUE TITLE
`--version` is doing something odd

### ISSUE THREAD

**Issue by vicendominguez** [asdf-vm/asdf#198]
Hello guys...

Working on the [asdf brew formula](https://github.com/Homebrew/homebrew-core/pull/14058)  I saw the next points:

* when you **clone** or **download** the `v0.3.0` tag then the `--version` argument always says: `0.2.1`
* when you download `master` from a **zip file** (`wget https://github.com/asdf-vm/asdf/archive/master.zip`) then the ``--version`` ouput is not there:

```
$ asdf --version
fatal: Not a git repository (or any of the parent directories): .git
```

Perhaps [this approach](https://github.com/asdf-vm/asdf/blob/master/lib/utils.sh#L6-L12) is not the better one when you are downloading the zip file :

```
asdf_version() {
  # Move to the asdf repo, then report the current tag
  (
  cd $(asdf_dir)
  git describe --tags
  )
}
```
Zip file downloading let us to download a concrete tag version.....so, any recommendation?

**Comment by Stratus3D** [comment]
Thanks for reporting this. The version discrepancy was my mistake, I forgot to update the hardcoded version in utils.sh when I tagged. After which we moved to using `git describe --tags`. We felt it was easier and assumed everyone would have installed asdf via `git clone`. It may be better to go back to hardcoded values, and I can write a quick shell script to increment the versions (readme and utils.sh) and do the tag all at once.

Another issue here is likely updates - `asdf update` does a `git pull`, so if we want to support asdf without it's git repo we will have to change that function as well.

**Comment by vicendominguez** [comment]
Hello Trevor, thx for answering.... I understand your point. 

I only would like to add some information here:

Updating action will not work via `brew` due to two good reasons:
 * philosophy: you are using `brew` to manage it and the updating makes sense with `brew` right? . Anyway this doesn't avoid the updating action but the next point is harder.
 * code: to achieve some formula rules I had to move `bin/private` folder while `brew` installs `asdf`. The native  "`update`" could break `asdf` then. 😢

**Comment by Stratus3D** [comment]
@vicendominguez It would be nice if you didn't have to modify asdf to get it working with brew, but maybe we don't have a choice. Is there something we can do to make the brew formula simpler?

**Comment by vicendominguez** [comment]
oh @Stratus3D 👋 , I would like it and I tried it but, as you see in the [PR](https://github.com/Homebrew/homebrew-core/pull/14058), the CI and the core manager didn't agree with that....

`asdf` is already available in `brew` by the way..... thanks for your time working on this amazing tool and don't forget to tag the next release 😉

**Comment by Stratus3D** [comment]
@vicendominguez just wrote a release script that automates everything that needs to happen when we release a new version. This should help reduce mistakes when releasing new versions.

I'm also going to revert back to hardcoding the version in utils.sh since the new release script will be able to automate that now. I also need to fix the `asdf update` function to print a helpful message when asdf is unable to upgrade itself due to the lack of a git repository.

**Comment by eproxus** [comment]
If you add a mechanism to disable `update` that could be used in Homebrew. For example, touching a file called `asdf_upgrades_disabled` somewhere in the script directory or something, and then checking for it in the upgrade command.

**Comment by Stratus3D** [comment]
@eproxus thanks, that is a better approach.

**Comment by josacar** [comment]
cool!
