### ISSUE TITLE
Opt-in for XDG base directory support

### ISSUE THREAD

**Issue by franklinyu** [asdf-vm/asdf#201]
This is a feature request. If `$ASDFRC` is set, use `$ASDFRC` instead of `$HOME/.asdfrc`. Do the same to `$HOME/.tool-version`.

Alternatively, if `$ASDF_CONF_DIR` is set, use `$ASDF_CONF_DIR/config` as `.asdfrc`, and `$ASDF_CONF_DIR/tool-version` as `.tool-version`.

Reference: [Arch Linux Wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support)

**Comment by hugopeixoto** [comment]
Right now it seems that you're able to specify the location of `asdfrc` through a variable named `$AZDF_CONFIG_FILE`. Not sure why the `Z` in the name. Could/should this be renamed to `$ASDF_CONFIG_FILE` or `$ASDFRC`? This is an undocumented feature, but renaming might break existing usages.

I was able to patch asdf to use a variable `$ASDF_TOOL_VERSIONS`. It doesn't affect in any way legacy files lookup, but I don't think it needs to. I created a PR, but I still need to add some tests.
