### ISSUE TITLE
Make `which` command work with any binary included in a plugin installation.

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#205]
It would be nice if we could pass any arbitrary name to this command. For example:

```
$ asdf which ruby
/home/trevor/.asdf/installs/ruby/2.3.0/bin/ruby
$ asdf which irb
No such plugin
```
It would be better if the second command returned `/home/trevor/.asdf/installs/ruby/2.3.0/bin/irb`.

This is related to #178

**Comment by nmenag** [comment]
I have an issue similar, the irb not working

I have installed Ruby
`asdf which ruby
/home/nmenag/.asdf/installs/ruby/2.6.2/bin/ruby
` 

But Irb not load
```irb
Traceback (most recent call last):
	1: from /home/nmenag/.asdf/installs/ruby/2.6.2/bin/irb:23:in `<main>'
/home/nmenag/.asdf/installs/ruby/2.6.2/bin/irb:23:in `load': cannot load such file -- /home/nmenag/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb (LoadError)```

Asdf version is: 

```asdf version   
v0.7.8-4a3e3d6
```
some solution for that, thanks.
