### ISSUE TITLE
Fail on inststall elixir

### ISSUE THREAD

**Issue by jhonathas** [asdf-vm/asdf#206]
$ asdf install elixir 1.4.2

/var/folders/h_/6v1myq556nd58yrl567k7gjh0000gn/T//elixir-precompiled-1.4.2.zip
** Resuming transfer from byte position 3796516
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

This error occurs in any version of the elixir. I already installed erlang, node and postgres without problem.

**Comment by Stratus3D** [comment]
The command `asdf install elixir 1.4.2` works for me on Ubuntu:
```
elixir --version                                                                                                                                                                   !10011
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2
```
Was there any other output that indicated the installation failed?

**Comment by kalbir** [comment]
I get a very similar failure on Mac OSX:

`$ asdf install elixir 1.4.2
/var/folders/yz/tg544g011f3__p2vyy7gw8s40000gn/T//elixir-precompiled-1.4.2.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3707k  100 3707k    0     0   536k      0  0:00:06  0:00:06 --:--:--  982k`

No other output from the terminal. Interestingly, when I try to install Erlang I get a different error:

`$ asdf install erlang 18
** Resuming transfer from byte position 287
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    272      0 --:--:-- --:--:-- --:--:--   272
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.`

**Comment by Stratus3D** [comment]
@kalbir `18` isn't a valid Erlang version, so that behavior is expected. And for Elixir, are you sure it didn't install? That output looks exactly like the output I see, but it works for me. How do you know it failed?

**Comment by kalbir** [comment]
@Stratus3D Yep you are right - Elixir did install. I didn't realise about the Erlang version - I thought that the behaviour was that it would either error or suggest a point version. Maybe one to think about for the future but all is well with my install now.

Thanks.

**Comment by Stratus3D** [comment]
@kalbir @jhonathas Perhaps we should hide the curl output when installing plugins? Feel free to create PRs/issues to hide the curl output in the asdf-elixir and asdf-erlang projects.
