### ISSUE TITLE
asdf doesn't auto switch while using tmuxinator to set up panes

### ISSUE THREAD

**Issue by pachonk** [asdf-vm/asdf#207]

**Comment by Stratus3D** [comment]
Can you provide a list of the steps necessary to replicate this behavior? I regularly use asdf-installed programs in tmux and I have never experienced any issues (and I use tmuxinator too).

Also, asdf really doesn't do any sort of "auto-switch", all it really does is look at the directory you are currently in and invokes the correct executable.

**Comment by pachonk** [comment]
No problem. I'll make a workflow after I test it a second time.

**Comment by pachonk** [comment]
Step 1: Have a directory/repo with `.tool-versions` set up here's mine:

```
ruby 2.3.4                             
nodejs 6.10.3
```
Step 2: Make a default tmuxinator with `tmuxinator new my-project` and change only line 3: (the root) to be your project root
Step 3: `tmuxinator my-project`
Step 4: `ruby -v` and see the Ruby version is the version of the GLOBAL version, not the .tool-versions version.

**Comment by pachonk** [comment]
If I open a new pane, it is using correct ver.

**Comment by Stratus3D** [comment]
@pachonk I've tried that and I'm still not able to replicate it. Can you verify that it's the global version set by asdf? It's possible for a system or brew installed version to take precedence if the paths come first in `$PATH`. `which ruby` should point to the asdf shim if it's the asdf installed version.

**Comment by pachonk** [comment]
This might help a ton:
![image](https://user-images.githubusercontent.com/6721355/28384902-e992f318-6c8b-11e7-909e-80a9d49f05a0.png)

**Comment by pachonk** [comment]
Looks like the new pane (working) is using the asdf shim and the other pane is NOT using the shim.

**Comment by pachonk** [comment]
@Stratus3D I was trying to save terminal load time by moving it from my 'rc to my `.profile`. Fixed with installing as per recommended: https://github.com/pachonk/.dotfiles/commit/a3abb436d3c4228ef12d5b3d95aa68cb30685558

**Comment by Stratus3D** [comment]
@pachonk great. Glad it was something simple. When testing your issue earlier I realized I had the loading of asdf in the wrong place, which was causing system ruby to be preferred over asdf in tmuxinator. https://github.com/Stratus3D/dotfiles/commit/4530c8f3fef5a308f14b863a1d2848a649296162

**Comment by pachonk** [comment]
#alltherealdevshavedotfileshostedpublicly

**Comment by pachonk** [comment]
Thanks for your help, sir.

**Comment by crivotz** [comment]
I am also stuck in the exact same problem with the difference that I use `zinit` to load `asdf`
https://github.com/crivotz/dot_files/blob/70a8d19c10c4d29054e4519a084d7c97c03d534f/linux/zinit/zshrc#L152-L153

I tried to source at the end of everything but I can't solve it
