### ISSUE TITLE
Automatically fetch plugins

### ISSUE THREAD

**Issue by danhper** [asdf-vm/asdf#210]
@vic 
> Just wondering, once this gets merged, would it be possible to tell people, to just install asdf and afterwards go directly with asdf list-all elixir or even to asdf install elixir 1.4.5 without having to be explicit about plugin-add elixir ? I mean, once we have the plugins repo, plugin-add is looks to me like only really useful for non-official plugins.

This would probably work as follow:
Check if the plugin is available locally, if not, check if the plugin is in the registry. If the plugin is available in the registry, fetch it before running the command.

**Comment by danhper** [comment]
I will close this issue, as it has been inactive for a long time now.
If there is still interest, please feel free to open a new issue.
Thank you!

**Comment by jthegedus** [comment]
Related https://github.com/asdf-vm/asdf/pull/313
