### ISSUE TITLE
Interrupted downloads are being treated as complete installs

### ISSUE THREAD

**Issue by seleem1337** [asdf-vm/asdf#214]
If you start installing a version of a language (e.g. Erlang) and for some reason it gets interrupted (e.g. Ctrl-C), it will be treated as a complete installation, meaning:
```
$ asdf install erlang 20.0
erlang 20.0 is already installed
```
But
```
$ iex
No such command in 20.0 of erlang
```
And `.asdf/installs/erlang/20.0/` path is empty.

The workaround is simple: uninstall erlang and reinstall it again but that's not ideal unless you are previously aware of this issue.

**Comment by tuvistavie** [comment]
We are actually checking for the return code in `asdf`, so this is more of a per-plugin issue.
I know some plugins do have this issue, let's open an issue in `asdf-erlang` to start with.

**Comment by Stratus3D** [comment]
I see the bug in asdf-erlang. Thanks for reporting!

**Comment by tuvistavie** [comment]
There is indeed an issue in the `asdf-erlang` plugin, but I just realized that the situation is a little when receiving the sigint signal. We do need to trap it somewhere if we want to cleanup cleanly, so I added the logic to do so inside the `install` command.
We still need to handle download failures in `asdf-erlang`.
