### ISSUE TITLE
Add possibility to upgrade asdf itself

### ISSUE THREAD

**Issue by vdolgishev** [asdf-vm/asdf#222]
I would like to get the latest version of `asdf`  by some command, e.g `asdf upgrade` or specific version `asdf upgrade <name>`

**Comment by Stratus3D** [comment]
@vdolgishev a command for this already exists. `asdf update` should upgrade asdf to the latest tagged release. I will say I made a mistake during the last tag, and so the version appears incorrect. The tag however is correct. Also, `asdf update --head` will update to the latest commit on master. Hope this helps!

**Comment by vdolgishev** [comment]
@Stratus3D thanks, I was using version `0.1`, so there was no possibility to update. Just checked the last version - everything is working.
