### ISSUE TITLE
Implement a stdlib to simplify plugin creation

### ISSUE THREAD

**Issue by nikolay** [asdf-vm/asdf#230]
Some ideas:
- (SemVer-compatible) version sort;
- Get all GitHub releases;
- Download a specific release from GitHub.

**Comment by tuvistavie** [comment]
I agree with this.
We could maybe expose the functions with a `_asdf_` prefix or something like this.

**Comment by danhper** [comment]
I will close this issue, as it has been inactive for a long time now.
If there is still interest, please feel free to open a new issue.
Thank you!
