### ISSUE TITLE
Support for monorepos

### ISSUE THREAD

**Issue by nikolay** [asdf-vm/asdf#232]
I have 4 plugins, which are 99% identical and there's way too much effort to keep both in sync and Git submodules are a big pain in the neck. Would it be possible to have an optional path in the plugin URL as well? Or is this already possible?

**Comment by nikolay** [comment]
Maybe a simple fallback mechanism could be used:

1. `asdf` will attempt `./<plugin-name>/` in the root of the repo. If it exists, that will be used.
2. If not, the root of the repo will be used instead.

**Comment by nikolay** [comment]
For example, in https://github.com/Banno/asdf-hashicorp I implemented six plugins with a single piece of code. It would be good if this can be done less hacky though.

**Comment by tomdavidson** [comment]
Another use case for the path could be app repos that include their own asdf plugin. I could have a project such as:

```
/
- asdf
- - list-all
- - install
- LICENSE  
- src/
- - lolaus.sh  
- package.json
- README.md
```
and register the plugin url as:
`git@gitlab.com:td7x/lolaus.git//asdf` (similar to terraform's [module source](https://www.terraform.io/docs/modules/sources.html#github))

asdf can split on the '//' and then do a sparse checkout of only right of the '//':

* https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository
* http://schacon.github.io/git/git-read-tree.html#_sparse_checkout

@nikolay would you need to follow symlinks? I'm not sure if sparse check is right for a mono repo of asdf plugins that are sharing code. Perhaps if asdf could install plugins from releases instead?

**Comment by nikolay** [comment]
@tomdavidson Not necessarily as instead of symlinks, a `source` command with a relative path could be used.

**Comment by danhper** [comment]
I will close this issue, as it has been inactive for a long time now.
If there is still interest, please feel free to open a new issue.
Thank you!
