### ISSUE TITLE
Improve OS and packaging support

### ISSUE THREAD

**Issue by nikolay** [asdf-vm/asdf#235]
asdf could be installed via various means on various OSes, and there's no universal way to find the location of the include file, or, let's put it differently, installing it via Homebrew on macOS vastly differs from the rest. As I often use asdf along with [direnv](https://direnv.net/), so, I suggest adding `asdf shell` similarly, which would cat the applicable `asdf.sh`, so, the whole thing could be:

```bash
eval "$(asdf shell)"
```

or, alternatively:

```bash
source "$(asdf shell-include)"
```

**Comment by Stratus3D** [comment]
Where would the source for such a command be stored? `asdf` won't be available in the shell until `asdf.sh` is sourced.

**Comment by tuvistavie** [comment]
@nikolay I suppose this is mostly for the case where `$ASDF_DIR/bin`is already added to the path by a package manager?

While It is not completely related, there are a few points I would like to discuss about packaging support.

1. Homebrew formula
Has anyone actually using asdf with brew?
One of my friends gave it a try and the experience seemed quite awful.
For some reason `ASDF_DIR` was seems to be set to `/usr/local`, polluting the directory completely and making `brew uninstall` incapable of properly cleaning the install.
If this is the case, we should really do something about it.

2. We should be allow to split `asdf` core files and installed files
When installing asdf with package manager which require `sudo`, users might want to ask `asdf` to install files where the user has write permission.
For example, `asdf.sh` would be in `/usr/local/asdf` while `installs` and `plugins` directory would be under `~/.asdf`.

Any opinions?

**Comment by Stratus3D** [comment]
Closing this issue as it is being addressed in #275 and #335.
