### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by Rup1** [asdf-vm/asdf#238]
Hi sorry for the newbie request but one of the devs at my job saddled me with this and unfortunately, I've only run into problems,  (it's also overkill since I only use node). This time, the problem is it can't find my bower install, no matter if I use npm or asdf to install it globally or locally.

So I rather get rid of all version managers altogether, but have not found a safe, proper explanation on how to remove from my machine. Help?

**Comment by tuvistavie** [comment]
Hi, sorry to hear you had troubles. 

asdf is self contained in `$HOME/.asdf` so you can simply remove the directory and remove the relevant lines from your shell init (.bashrc or whichever you are using).

We should document that.

**Comment by Stratus3D** [comment]
Addressed this in 8946fbd3c33e4818aedcadbb9dcb9e72e8713509.

**Comment by devinrhode2** [comment]
THANK YOU @Stratus3D  :)

**Comment by sparkycloud** [comment]
Thanks I would like to also get rid of asdf and better use pyenv due to its unstablility

**Comment by gabrielbmoro** [comment]
Thank you @Stratus3D !
