### ISSUE TITLE
v0.4.0 brokes nodejs plugin's reshim

### ISSUE THREAD

**Issue by taiansu** [asdf-vm/asdf#239]
### Steps to reproduce

1. Check out the stable version by `asdf update`
2. Change nodejs version, either by `asdf local nodejs version`,  `asdf global nodejs version` or trigger by a .tool-versions file.

### Expected behavior

`npm -v` should print the npm version.

### Actual behavior

It prints `No such command in 8.4.0 of nodejs`. However, when I checkout the _v0.3.0_ branch in .asdf folder, it works correctly.

https://github.com/asdf-vm/asdf-nodejs/issues/22

### Environment

**OS**:
macOS 10.13

**asdf version**:
v0.4.0

**Comment by sublimecoder** [comment]
Confirm I had the same issue 4.0.0 breaks the reshim functionality. But after checking out the 3.0 tag and reinstalling nodejs under 3.0 followed by running `asdf update` seems to have "fixed it" for now but their might be something wrong with the installation/shimming in 4.0 or could be a quirk of upgrading.

**Comment by tuvistavie** [comment]
Thanks for reporting. Do you have the latest version of `asdf-nodejs`?
Please try `asdf plugin-update nodejs` and let me know if `reshim` is still broken.
Version 0.4 could be incompatible with old versions of `asdf-nodejs`.
We really need versioning for plugins, but this is another topic.

**Comment by taiansu** [comment]
@tuvistavie While I reported the issue I do have the lastest version of `asdf-nodejs` at the moment. But I just pull the `master` branch of `asdf`, install a new nodejs version, reshim seems like correctly works. Thanks!

**Comment by sublimecoder** [comment]
Yes latest version of nodejs and asdf seem to work fine. So probably an issue related to small changes during the interim between updates. Versioning of the plugins wouldn't be a bad idea at all.

**Comment by taiansu** [comment]
Confirm. After pulling the latest master branch of `asdf`, the `npm` command  works. Although `npm install -g npm` follow by `asdf reshim` doesn't update the npm module, but it might be a different issue.

**Comment by fpauser** [comment]
Same error here with asdf 0.4.0 and nodejs 6.11.4 (LTS). Imho the latest LTS version of node should be supported.

**Comment by taiansu** [comment]
@fpauser Wondering have you try to pull the master branch in the `~/.asdf` directory? That's how it works for me.

**Comment by fpauser** [comment]
My `~/.asdf` sits on current master @ 8946fbd3. I tried it with LTS `node 6.11.4` and latest `node-8.7.0` without success. Just found out that `nodejs-6.11.1` works for me.

**Comment by fpauser** [comment]
Deleting the `~/.asdf/shims` directory and doing a `asdf reshim nodejs` fixed the issue for me.

**Comment by Stratus3D** [comment]
I'm closing this issue since both seem to be the same issue as #284.
