### ISSUE TITLE
metered internet connection detection

### ISSUE THREAD

**Issue by adamdecaf** [asdf-vm/asdf#241]
I'm sometimes working off my phone's tether which has data caps and throttling after going over certain usage during a month. Is there a way I could tell asdf about this? (Easily detected by the SSID) I'd like asdf to either ask for confirmation or not download files when I'm on the metered connection.

**Comment by tuvistavie** [comment]
We could add an option to `.asdfrc` to ask for confirmation, but I am not sure it is really desirable. I have never seen any package manager do this, and I really think this is something that should rather be done at the OS level (i.e. limiting the network traffic per process).
@asdf-vm/maintainers Any thoughts?

**Comment by adamdecaf** [comment]
Alright, I'll look around elsewhere. Thanks!
