### ISSUE TITLE
Realpath: command not found

### ISSUE THREAD

**Issue by tristandruyen** [asdf-vm/asdf#248]
### Steps to reproduce
Pull newest master into `~/.asdf` on OS X

### Expected behavior

asdf works as expected

### Actual behavior

`/Users/tristandruyen/.asdf/lib/utils.sh: line 246: realpath: command not found`

found a brewtab which adds realpath although i would prefer not to have this dependency or at least tell people about it in the README.md

### Environment

**OS**: OS X

**asdf version**: master

**Comment by tuvistavie** [comment]
Oh, completely forgot `realpath` is not available by default on OS X.
Thanks for the catch, I just reverted the commit for now.
