### ISSUE TITLE
Prefer extensible to extendable?

### ISSUE THREAD

**Issue by vemv** [asdf-vm/asdf#249]
While _extendable_ appears in the dictionary, in programming contexts I've practically always read _extensible_.

First impressions matter!

Cheers - Victor

**Comment by Stratus3D** [comment]
Good question. I assume you are talking about the tag line displayed at the top of the page on the project homepage on Github. @HashNuke any thoughts on this?

I think either are fine, and both convey the meaning well enough.

**Comment by Stratus3D** [comment]
Closing this since I don't think this is something we need to address right now. Either word is sufficient.
