### ISSUE TITLE
how to set path when using asdf with other package managers? 

### ISSUE THREAD

**Issue by zhaoyi0113** [asdf-vm/asdf#252]
I am using Mac OS `10.13.1 ` and have installed asdf based on the instruction. After that I installed python plugin and downloaded 2.7 version. I can see below version are currently installed on my system:

```
joeys-MacBook-Pro:~ joey$ asdf list python
2.7
3.5
3.6.3
3.6
```

But I can't change python to 2.7, see below output:

```
joeys-MacBook-Pro:~ joey$ asdf global python 2.7
joeys-MacBook-Pro:~ joey$ asdf current python
2.7 (set by /Users/joey/.tool-versions)
joeys-MacBook-Pro:~ joey$ which python
/anaconda/bin/python
```

From above output I can see the current python version has been set to 2.7 based on the output from `asdf current python`. But it doesn't change my python on my PATH. It still points to the python managed by anaconda.

**Comment by tuvistavie** [comment]
I suppose conda comes before `asdf/shims` in your path. Could you show us your `.bashrc` or whatever file you are using to configure conda and asdf please?

**Comment by zhaoyi0113** [comment]
Below is my ~/.bash_profile


#!/bin/bash
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/joey/.sdkman"
#[[ -s "/Users/joey/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/joey/.sdkman/bin/sdkman-init.sh"

alias ll="ls -l"
alias mvnbuild="mvn clean install"
alias vnc='java -jar ~/tools/tvnjviewer-2.8.3-bin-gnugpl/tightvnc-jviewer.jar'

export ANT_HOME=/Users/joey/tools/apache-ant-1.9.7

export DBENVY_HOME=/Users/joey/dev/dbenvy-che
export CHE_ASSEMBLY=$DBENVY_HOME/assembly/assembly-main/target/eclipse-che-5.0.0-M8/eclipse-che-5.0.0-M8
export CHE_LOCAL_BINARY=$DBENVY_HOME/assembly/assembly-main/target/eclipse-che-5.0.0-M8/eclipse-che-5.0.0-M8

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/
export PATH=$JAVA_HOME/bin:$PATH

export AWS_MONGO=ec2-13-54-17-227.ap-southeast-2.compute.amazonaws.com
export AWS_CI=ec2-13-54-181-208.ap-southeast-2.compute.amazonaws.com

export MAVEN_OPTS="-Xms512m -Xmx2048m"
export M2_HOME=/Users/joey/tools/apache-maven-3.3.9
export MONGO_HOME=/Users/joey/tools/mongodb-osx-x86_64-3.4.0/
export PATH=$PATH:$M2_HOME/bin:$MONGO_HOME/bin:/Users/joey/Library/Android/sdk/platform-tools/:/usr/local/mysql/bin:$ANT_HOME/bin:/usr/local/opt/coreutils/libexec/gnubin
export CHE_EXTRA_VOLUME_MOUNT=/Users/joey/dev/che_data:/home/user/che
export CHE_DATA=DBENVY_HOME/che_data

export DRONE_SERVER=https://drone.hoth.southbanksoftware.com/
export DRONE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXh0Ijoiam9leXpoYW8wMTEzIiwidHlwZSI6InVzZXIifQ.UR1EXjJpgrKtAB2GinNtmNF5rDs-iyw-FZMmjXZDsgE

alias chenative="/Users/joey/bin/che_start.sh"
alias buildms="cd $DBENVY_HOME/assembly/assembly-wsagent-war;mvnbuild;cd $DBENVY_HOME/assembly/assembly-wsagent-server;mvnbuild; cd $DBENVY_HOME/assembly/assembly-main; mvn install"

export ANDROID_HOME=/Users/joey/Library/Android/sdk/

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/joey/tools/apache-maven-3.3.9/bin:/Users/joey/Library/Android/sdk/platform-tools/:/usr/local/mysql/bin:/Users/joey/.vimpkg/bin:$ANDROID_HOME/build-tools/24.0.2:$ANDROID_HOME/tools:$PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export NVM_DIR="/Users/joey/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# added by Anaconda3 4.3.1 installer
export PATH="/anaconda/bin:$PATH"

# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH


### HADOOP CONFIGURATION ###
export HADOOP_HOME="/usr/local/opt/hadoop"
export HBASE_HOME=/usr/local/opt/hbase
export HIVE_HOME=/usr/local/opt/hive/libexec/
export HCAT_HOME=$HIVE_HOME/hcatalog


. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

export ASDF_DIR=/Users/joey/.asdf
export PATH=$PATH:$ASDF_DIR/bin

**Comment by ipatch** [comment]
I'd run `echo $PATH` in your current shell session to see all your path entries.  You should only try to set your PATH once in your `.bash_profile` or `.bashrc`.  Shameless plug, you can see how I set up my PATH for the BASH shell [here](https://github.com/ipatch/dotfiles/blob/master/bash/bashrc#L19).

You can also run the below command in your shell session to see the list of all the python's on your local box.
```
type -a python
```
which should print the version of python that your system is using at the top of the outputted list.

cheers 🍺

**Comment by Stratus3D** [comment]
@zhaoyi0113 did you ever get this figured out? Looking at your `~/.bash_profile` I don't see a problem (aside from sourcing the asdf files twice, and manually adding `$ASDF_DIR/bin` to your PATH).

**Comment by Stratus3D** [comment]
Closing this since I do not think this is a bug in asdf.
