### ISSUE TITLE
Keep changing to .asdf directory if oh-my-zsh last_working_dir plugin on

### ISSUE THREAD

**Issue by mracos** [asdf-vm/asdf#255]
### Steps to reproduce

On `zsh`:
- Install `oh-my-zsh`
- Add to your `.zshrc` a `plugins=(last_working_dir)`

### Expected behavior

When creating a new shell, change to the last directory automatically 

### Actual behavior

Keeps changing to `.asdf`

### Environment

**OS**: ArchLinux

**asdf version**: v0.4.0

**shell**: zsh

**Comment by Stratus3D** [comment]
I believe this has been fixed by https://github.com/asdf-vm/asdf/pull/334.

**Comment by mracos** [comment]
Fixed here for me! Awesome, thanks!
Feel free to close it. :D
