### ISSUE TITLE
another plugins maintainer

### ISSUE THREAD

**Issue by tomdavidson** [asdf-vm/asdf#259]
I would like to volunteer to be a asdf-maintainer if that would help with the open PRs that are not getting much attention.

**Comment by Stratus3D** [comment]
@asdf-vm/maintainers it looks I was not following PRs on the asdf-plugins repo. It's probably best go there are make sure you are following it so you get notifications when new PRs come in (https://github.com/asdf-vm/asdf-plugins).

Sorry about the delay @tomdavidson. I'm guessing several of us weren't even getting the notifications.

**Comment by HashNuke** [comment]
@Stratus3D Thank you. Just saw the pending PRs. Looking at them.
