### ISSUE TITLE
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

### ISSUE THREAD

**Issue by mconigliaro** [asdf-vm/asdf#260]
### Steps to reproduce

`asdf install`

### Expected behavior

If it can't resume the download, don't give up. Just start the download from scratch. Now I'm stuck with no ability to run `asdf install`.

### Actual behavior

```
** Resuming transfer from byte position 289
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    576      0 --:--:-- --:--:-- --:--:--   577
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
```

### Environment

**OS**: OSX

**asdf version**: v0.4.0

**Comment by Stratus3D** [comment]
Individual plugins are responsible for downloading source code. Please open an issue on the repository for the affected plugin(s).

If this is something asdf itself can help with please reopen this issue.
