### ISSUE TITLE
Failing builds to due errors reported by lint.sh

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#265]
The builds fail for the latest version of asdf due to errors reported by lint.sh. I haven't made code changes to the files it's complaining about, so I'm not sure why it just started failing. Previously builds were succeeding. Perhaps a newer version of shellcheck is being used by Travis CI?

**Comment by jonknapp** [comment]
Looks like it: https://github.com/koalaman/shellcheck/blob/master/CHANGELOG.md

Not sure if there's a way to lock the shellcheck version used so upgrades can be handled separately from testing project commits.

**Comment by Stratus3D** [comment]
There aren't too many errors, so I may just try to address a couple every week as I have time, should only be a week or two before the build is passing again.

**Comment by Stratus3D** [comment]
Fixed those that needed to be addressed and ignored the warnings for the others.
