### ISSUE TITLE
`asdf install` should read versions from legacy version files

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#269]
When determining what versions need to be installed `asdf install` should pay attention to legacy version files on the path when it is configured to do so. Right now the command disregards any legacy files that maybe in the search path.

We could optionally add a flag here for reading legacy version files, but I don't think it's necessary since the user has to manually configure asdf to read legacy version files anyway. And all the other commands do read legacy version files by default when configured to do so.

**Comment by samneely** [comment]
I'm new to `asdf` and noticed this as well. I'm really hoping that this becomes a feature with `asdf install`. Is this something that could be added in the near-ish future?
