### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by jthegedus** [asdf-vm/asdf#274]
Hey all maintainers and contributors, thanks for the great tool!

I like the challenge of writing clear and concise docs and in an effort to learn this tool better I thought I would contribute to the docs.

The Contribution.md file states:

>The wiki exists but is in a state of disrepair. If you see something that can be improved please submit a pull request or edit the wiki.

I *like* projects that use the Wiki page for GitHub as instructions are in a single place and not spread across GitHub and some docs site. Having said that, there are drawbacks to using GitHub's Wikis and many pros to a separate docs site. So before starting, I would like to get an idea of your intentions/wants for the docs and list some of my thoughts on doc layout and docs from other projects.

### Docs in README
* docs immediately seen on GitHub. Most people look here first for docs.
* in sync with the main repo. Easier to maintain docs coverage of new feats or bug fixes as they're added.
* README becomes very large as commands, options etc increase
* some repos use the README to link to the docs and just explain how to contribute here.

### Docs in Wiki
* can be easily linked from the top of the README
* removes a lot of noise from README so README can be used to explain where to find info - [Prettier's README](https://github.com/prettier/prettier) is the best example of this IMO.
* do you include Contribution guidelines in Wiki or in repo/contributing.md?
* where does "Development" guidelines go? Do they get merged with Contribution guidelines?

### Docs on website (say asdf.io)
SAME as above 'Docs in Wiki" except:
* Docs managed within the same repo as the tool and therefore easy to keep in sync 
* Easy to brand
* Easier to add docs searching
* Renders nicely everywhere (GitHub Wikis are not great on mobile)

### My suggestions
* the README should be short and to the point, like the [Prettier README](https://github.com/prettier/prettier).
* IMO a Docs website is the way to go if you maintain it within the same repo as the tool so you can keep the tool and docs in sync. I'd suggest, and happily create a https://www.gatsbyjs.org/ site for this. 
**EDIT** [
I know this seems like overkill but this would go along way with persuading new users. Especially if combined with gifs showing the perf of automatic version switching etc
]
* If you prefer the option where the docs are in a separate repo from the tool, then the Wiki would require less work to get going than creating a docs site.

@HashNuke
@tuvistavie
@Stratus3D
@vic

**Comment by tuvistavie** [comment]
@jthegedus Thank you very much for the issue.
While I personally do not really have time to help with a docs website, I am open to the idea.

**Comment by jthegedus** [comment]
@tuvistavie I'm happy to do the legwork here, I just wasn't sure which result you all would prefer to have. If there's no real strong opinion, then I will go with my suggestion and open a PR for feedback.

**Comment by Stratus3D** [comment]
@jthegedus thanks for writing this up!

So my wants as far as the docs go are:

* Keep docs in the repo so it's easy to version things
* Make it so no extra work has to be done when updating or adding to docs. I don't want to have to change things in multiple places, or have to deal with pushing out updates to the doc site when merging a PR. Maintainers already have enough to do (our open issues have grown from about 20 to 40 over the last 5 months).
* Have a way for users to contribute to the docs easily. One thing I liked about the wiki is that users can just add to it without having to get any approval from us. It's not being used that much, but I liked the idea of it. Right now we've got several PRs that probably need to get merged but need work before they are ready and the've been sitting there for weeks. I'd be fine with doing away with the wiki, but we'd still want to have a well documented way of contributing to the docs. Some docs are specific to OS, OS version, or shell.

**Comment by jthegedus** [comment]
@Stratus3D Thanks for your thoughts.

My goal for updating the docs would be as simple as editing the markdown files in `docs/` and running a build/deploy script on Travis CI.

The site can have an edit link allowing users to contribute to the docs via the GitHub website markdown editor, which forks and PRs the changes. The PR would require merging as with any other contribution and will, therefore, need _some_ maintenance effort. I know it adds noise to the issues list, but in my opinion, this extra step will result in more accurate and consistent docs, and I am happy to be involved in or pinged for, the triaging and maintenance of docs issues/PRs.

Given this feedback, I will start implementing something soon for your consideration.

**Comment by jthegedus** [comment]
Hey all,

this is an update to the search for the correct tool to create docs for `asdf-vm`. After trying almost every docs generator and their associated plugins systems I've settled on [Docsify](https://github.com/docsifyjs/docsify) as it is the most simple and easy solution to the below criteria:

Core
* just markdown - lowest barrier to entry for contributions
* no compilation/ci/deployment process - easier to maintain without knowledge of another (mainly JS) ecosystem or tooling
* client-side dev server - when a tool is installed globally devs can test their changes without it needing to be part of the main repo

Bonus
* themes - limited, but good enough
* code highlighting (prismjs)
* internationalization support
* search

Magic
* support tabbed content - we support a number of tools, it would be really nice to select your platform and terminal and have instructions just for them rendered
* external files - populate pages from external markdown. EG: include the asdf plugins list from that repos readme without cloning or syncing those files into this repo.

This has been a long path of discovery for me and I hope you share my enthusiasm for Docsify as our tool of choice for a docs site.

Hosting:
* https://asdf-vm.github.io/asdf
* https://asdf-vm.com

* we should use github pages for hosting - https://docsify.js.org/#/deploy?id=github-pages - (open to discussion, but anything else would require additional tooling just to manage the deployment).
* I already secured `asdf-vm.com`, so we just need to configure it. (I am happy to discuss transferring ownership to someone else if desired)

PR inbound

**Comment by jthegedus** [comment]
It's live! Checkout the readme and site!
