### ISSUE TITLE
I would like to be a maintainer.

### ISSUE THREAD

**Issue by Antiarchitect** [asdf-vm/asdf#281]
I have two dangling PR for plugins and see no attention to issues and PR. I would like to volunteer as I have solution based on ASDF and see this pure-bash version manager very perspective.

**Comment by tuvistavie** [comment]
Sorry for the delay and thank you for proposing to help.
I have been quite busy recently, so some help would definitely be welcome.
/cc @asdf-vm/maintainers

**Comment by vic** [comment]
Yep, +1 on having more eyes/hands, mostly if asdf is important to they, as it looks to be the case of @Antiarchitect.

**Comment by danhper** [comment]
I will close this issue, as it has been inactive for a long time now.
If there is still interest, please feel free to open a new issue.
Thank you!
