### ISSUE TITLE
Splitting config into multiple files to aide docker caching (.tool-versions.d/ or similar)

### ISSUE THREAD

**Issue by trinode** [asdf-vm/asdf#282]
if asdf supported that thing (I have no idea of the name) that a lot of config tools do in which you can have config in a config.d folder instead of a config file and each file in there is part of the config that way you could do something like:

Dockerfile:
```dockerfile
...
COPY .tool-versions.d/erlang .tool-versions.d/erlang 
RUN asdf install 
COPY .tool-versions.d/elixir .tool-versions.d/elixir
RUN asdf install 
COPY .tool-versions.d/nodejs .tool-versions.d/nodejs
RUN asdf install 
...
```

that way changing node would only require rebuilding node
changing elixir would require elixir and node
changing erlang would build all three

This would save rebuilding all asdf plugin managed languages everytime one changes - The erlang build in this example takes quite some time.

**Comment by Stratus3D** [comment]
I'm not familiar with Docker at all, but it sounds like you just need to a way to each version in it's own file, inside a directory with a special name (e.g. `.tool-versions.d/`)? That seems doable. Is this something that affects all Docker users, or is there a specific use case where this would be helpful?

**Comment by danhper** [comment]
I will close this issue, as it has been inactive for a long time now.
If there is still interest, please feel free to open a new issue.
Thank you!
