### ISSUE TITLE
JetBrains asdf support feature  request has too less votes

### ISSUE THREAD

**Issue by a4z** [asdf-vm/asdf#283]
I would love to see that JetBrains tools, pycharm, rubymine and webstorm, become asdf aware.

I found this ticket, but it has not that many votes, maybe asdf users that use IDEs want to vote for this.

https://youtrack.jetbrains.com/issue/RUBY-20370

**Comment by perchard** [comment]
Note that you can locate the ruby binary manually (~/.asdf/installs/ruby/...): https://www.jetbrains.com/help/ruby/configuring-available-ruby-interpreters.html

**Comment by a4z** [comment]
now implemented! 
at least for ruby, hope node will follow (for webstrom)

https://www.jetbrains.com/help/ruby/2018.2/ruby-version-managers.html

**Comment by renews** [comment]
Still doesn't work for me, sadly. By that I mean, it can't find my asdf.

**Comment by Stratus3D** [comment]
Does asdf work on the command line for you @renews? And is it installed in the default location? (`~/.asdf`).

**Comment by mark-jordanovic-lewis** [comment]
Also does not work for me, identifying the binary manually hangs Rubymine on version 2018.1.5 and can't even access the prefs in 2018.2.

Have reported to JetBrains, just adding my 2c

**Comment by Stratus3D** [comment]
Closing this since I don't think there is anything we can do to fix this.

**Comment by a4z** [comment]
this issue helped to get some activity done from JetBrains, they added asdf support in 2018.2 
asdf is now even in the documentation
https://www.jetbrains.com/help/ruby/2018.2/ruby-version-managers.html
however, since I use vs code these days I can not say how well this works
so I think closing is OK, thanks!

**Comment by renews** [comment]
> 
> 
> Does asdf work on the command line for you @renews? And is it installed in the default location? (`~/.asdf`).

Yes it does.
