### ISSUE TITLE
How to deal with PL's with support for 32 bit and 64 bit in asdf

### ISSUE THREAD

**Issue by m13m** [asdf-vm/asdf#285]
I'm working on this plugin for asdf but that particular programming language comes in two variant is there a mechanism in asdf which allows me to install packages.

if the user passes 
 ```asdf install foo 64 1.0.0```

here if you want to install 64-bit version then only have to pass the 64 otherwise it assume it's 32 bit

**Comment by tuvistavie** [comment]
I suggest you use an environment variable. For example, `YOUR_LANGUAGE_ARCH=amd64` or something like this.
