### ISSUE TITLE
Add tests for code in asdf.sh

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#286]
Our builds don't catch breaking changes in asdf.sh. We should be evalating this code during the build so we can have some assurance it's working properly.

#256

**Comment by Stratus3D** [comment]
Also need to add tests for behavior of shims so we can assert their exit codes and output.

**Comment by danhper** [comment]
I think we are now mostly testing for this. Let's open a new issue if at some point we think it is not enough.

**Comment by Stratus3D** [comment]
I do not believe the code in https://github.com/asdf-vm/asdf/blob/master/asdf.sh is tested in any of our unit tests. We need to write unit tests for the code in `asdf.sh` and `asdf.fish`. Specifically, we need to test:

* `PATH` is set properly
* Any other environment variables are set properly
* Functions like `asdf` are working as expected (e.g. providing the commands we've defined)

I think this is worth doing as this code for this has been broken on several occasions. I will create a PR for this as soon as I can.

**Comment by Stratus3D** [comment]
I still need to write tests for fish.
