### ISSUE TITLE
Improve output of `asdf which`

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#296]
The `asdf which` command doesn't work the same way other commands do when a tool version is not set. Refer to this screenshot for an example of how the output differs:

![screen shot 2018-02-25 at 1 16 43 pm](https://user-images.githubusercontent.com/1520926/36644960-c2f86b96-1a2f-11e8-9865-3c34c995fa3e.png)

I'm not sure how the command is implemented, but it should probably share the same error message printing code as the other commands. We should probably define a utility function somewhere that takes a tool name and prints the no version message. e.g. something like `print_no_version_set $plugin_name`. That way the no version message is defined in one place instead of being duplicated across the codebase.

#293

**Comment by aj-foster** [comment]
#297 addresses this issue, but I did not use the `Fixes` auto-close feature because there's still refactoring to be done. (Probably by someone with better understanding of the overall architecture than me.)
