### ISSUE TITLE
asdf versions config options

### ISSUE THREAD

**Issue by tomdavidson** [asdf-vm/asdf#299]
I have been using asdf has a version manager to keep my terraform version insync with my terraform plans (you can jack up your state file by using the wrong version). This type of functionality has been important to me, far beyond an installer.

Sometimes the .tool-versions file is insufficient such as when a build process wants to move source into a clean, temp dir. Rather than placing a copy of of the .tool-versions what about having an ordered  preference such as:

1. env var (such as ASDF_TERRAFORM_VERSION=0.10.8)
2. cwd .tool-versions file
3. walk the fs up looking for a .tool-versions file
4. home .tool-versions

**Comment by Stratus3D** [comment]
I believe this is the way asdf behaves currently. Have you observed something different? Env variables should override anything set in any version file.

**Comment by tomdavidson** [comment]
@Stratus3D  
I had tried to use $ASDF_DEFAULT_TOOL_VERSIONS_FILENAME (with full path), but had over looked the env var options in the usage section and instead had focused on the env vars section.

"Alternatively, if you want to set a version only for the current shell session or for executing just a command under a particular tool version, you can set an environment variable like ASDF_${TOOL}_VERSION."

Sorry for the noise.

**Comment by tomdavidson** [comment]
A feature that would help my case is an adfs command that exports the env vars from a provided .tool-versions file.

**Comment by vic** [comment]
You can use the following script

``` shell
cat ~/.tool-versions | (while read -d' ' a; do read b; echo export ASDF_$(echo $a | tr '[:lower:]' '[:upper:]')_VERSION=$b; done) | eval
```

for me it's something like

```
export ASDF_ELIXIR_VERSION=1.6.1-otp-20
export ASDF_JAVA_VERSION=9.0.4
export ASDF_RACKET_VERSION=6.12
export ASDF_NODEJS_VERSION=9.5.0
export ASDF_POSTGRES_VERSION=10.2
export ASDF_RUST_VERSION=stable
```
