### ISSUE TITLE
golang Plugin

### ISSUE THREAD

**Issue by kennyp** [asdf-vm/asdf#30]
I just create a asdf plugin for go https://github.com/kennyp/asdf-golang

**Comment by HashNuke** [comment]
Thank you @kennyp ~!
I'll try it out this week and add it to the readme. I'll keep this issue open until I do that.

**Comment by kennyp** [comment]
Hey @HashNuke, did you have any issues when trying to use it?

**Comment by HashNuke** [comment]
@kennyp Sorry never tried it. (Since I don't use golang anywhere I had less motivation to do so). I just got the golang docs on my dash to start reading about it :)

Thanks for the plugin. Will list this on readme.
