### ISSUE TITLE
Add ability to list all installed versions of all packages

### ISSUE THREAD

**Issue by rlipscombe** [asdf-vm/asdf#307]
I'd like to get a list of all installed versions of all packages.

```
$ asdf list
No plugin given
```

It'd be nice if it iterated through the installed plugins and listed the installed versions for each. I cobbled the following together:

```
$ asdf plugin-list | xargs -I{} sh -c "echo {}; asdf list {}"
elixir
No versions installed
erlang
19.3.6.7
golang
No versions installed
nodejs
No versions installed
python
No versions installed
ruby
2.2.7
2.3.4
```

It'd be nice if something like this was built in.

**Comment by Christopher-Bui** [comment]
Should this be closed now?

**Comment by Stratus3D** [comment]
Thanks @Christopher-Bui. Yes, this has been implemented.
