### ISSUE TITLE
Is it possible to enable multi version together?

### ISSUE THREAD

**Issue by hackrole** [asdf-vm/asdf#318]
### Steps to reproduce
I use python at work, I am not just switch between python2 and python3. indeed,  I need both active.
for example, neovim need install neovim package both on python2 and python3,
I not not willing to use system python package, cause it hard to manage after problem.
so is there any way to both to enable multi version active at once.

Tell us what actions you performed before the issue occurred

### Expected behavior
I can have both python2 and python3 active global.

### Actual behavior
it seems not possible now, and the local version not works well with virtualenv.

### Environment

**OS**: ubuntu 16.04

**asdf version**: 3.4.0

**Comment by tuvistavie** [comment]
Simply pass multiple versions to `local` or `global` commands

```
asdf global python 3.6.2 2.7.11
```

**Comment by Stratus3D** [comment]
Wow. I didn't even know this was possible. Nice! Now I can run rebar and rebar3 at the same time too.

Also, apparently other asdf commands do not know this is possible either. For example, if I run `asdf current` I see a line that says:

```
version 3.6.2 2.7.13 is not installed for python
```

But both of those versions are installed for Python. And If remember correctly this feature isn't covered in any of our unit tests. We should probably go through tests and add cases for multiple versions when it's relevant. My guess is most asdf commands don't actually handle this correctly.

**Comment by hackrole** [comment]
wow, this is so much wondful. I will #close this issue. @tuvistavie thanks for the message.

**Comment by rdrey** [comment]
this also seems to work in `.tool-versions` files for the record. :+1:
