### ISSUE TITLE
provide ASDF_INSTALL_VERSION_NAME to plugins

### ISSUE THREAD

**Issue by tverlaan** [asdf-vm/asdf#321]
The asdf-erlang plugin prints ASDF_INSTALL_VERSION to show the user which version can be used. However when using git this could be `master`, but the actual version you need to provide to `asdf` is still `ref:master`. The plugin is now concatenating this information itself, but I think it should be provided by asdf.

Can we add this feature? Is this an easy first PR, then I can take a look..

**Comment by Stratus3D** [comment]
Sorry for the extremely late reply. What would be the purpose of `ASDF_INSTALL_VERSION_NAME`? If we already have `ASDF_INSTALL_VERSION` the plugin should be able to construct `ref:master` right?

**Comment by tverlaan** [comment]
I had to lookup why I created this ticket, but I'm glad with your response so here goes reverse engineering the reasoning :-)

I made a [PR](https://github.com/asdf-vm/asdf-erlang/pull/69) for asdf-erlang and during making this change I think I ran into this and considered it a workaround. So yes the plugin can put it together itself (as done here https://github.com/asdf-vm/asdf-erlang/blob/master/bin/install#L21), but if every plugin has to do that then I think providing it from the framework is a cleaner approach.

I'm not aware of any other benefits at this very moment.

**Comment by Stratus3D** [comment]
I don't think it is worth the effort documenting and maintaining another variable for a couple reasons:

1. asdf doesn't have a concept of "version name". We could introduce such a concept, but I don't really think it is necessary. We already have concepts like version, tool name, and install type. Plugins can define their own concept of what a "version name" is if needed.
2. Such a variable would be a simple concatenation of version and install type. This can easily be done anywhere in the plugin code.
3. Introducing a new variable makes things more complicated.

I am going to close this issue. Thank you for taking the time to open this issue, if you feel like there is something I missed that merits this feature please let me know.

**Comment by Stratus3D** [comment]
If you see this pattern being duplicated a lot I suppose it may make sense to revisit this, but I've not seen it used in most plugins.
