### ISSUE TITLE
Add spacing in front of versions for "asdf list" to enhance readability

### ISSUE THREAD

**Issue by brennanfee** [asdf-vm/asdf#330]
### Steps to reproduce

Run "asdf list"

### Expected behavior

When the lines are written the versions are slightly indented to help make the output more readable.

### Actual behavior

At present all of the lines are written flush with the left of the screen making it more difficult to distinguish between plugins version versions.

### Environment

**asdf version**: v0.5.0

**Comment by Stratus3D** [comment]
Fixed by #331.

It might be worth while to eventual check and see if the output is being printed to screen or piped to another program. The whitespace is not needed when piping this info elsewhere.
