### ISSUE TITLE
How to reinstall already installed toolchains

### ISSUE THREAD

**Issue by NobbZ** [asdf-vm/asdf#34]
I used the erlang plugin to install several versions of erlang, but now I had to realize, that they are all installed without `wx` support, which I might need for the next project.

I made already sure, that everything `wx` relies on is in place, and I compiled an erlang manually just to see if the build process does realize it. Indeed it does.

So I'd like to have asdf to automatically reinstall all existing versions of the erlang toolchain, is this possible in an easy way?

**Comment by kennyp** [comment]
@NobbZ a little bash should do it for you

```bash
asdf list-all erlang | while read ver
do
  echo asdf uninstall erlang $ver
  echo asdf install erlang $ver
done
```

**Comment by NobbZ** [comment]
listing the installed ones will be enough 😊 I hoped there's a built in way
to do it like in RVM, kiex and others. In the meantime I did exactly this
by hand.

Kenny Parnell <notifications@github.com> schrieb am Fr., 18. März 2016
17:19:

**Comment by HashNuke** [comment]
@NobbZ Do the asdf-built erlang versions still come without `wx`? I remember fixing it.

**Comment by NobbZ** [comment]
They came wx included, after I installed wx libs. Exactly that was the
cause why I wanted to reinstall.

Akash Manohar <notifications@github.com> schrieb am Sa., 9. Apr. 2016 17:43:

**Comment by HashNuke** [comment]
@NobbZ Ah thank you for the quick reply.
Can you send a PR to add the wx libs install commands to the asdf-erlang readme for mac and ubuntu? https://github.com/asdf-vm/asdf-erlang

Nice to know you got it fixed. Closing this issue.

**Comment by nixpulvis** [comment]
Here's a nice little `fish` script that'll do it.

```fish
for plug in (asdf plugin-list)
    for ver in (asdf list $plug)
        set v (echo $ver | awk '{$1=$1};1')
        if not echo $v | grep 'No versions installed'
            asdf uninstall $plug $v
            asdf install $plug $v
        end
    end
end
```
