### ISSUE TITLE
 asdf command not found on Mac OSX

### ISSUE THREAD

**Issue by 7stud** [asdf-vm/asdf#342]
### Steps to reproduce

I installed afds according to the instructions for Mac OSX:

```
$ git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.5.0
$ echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bash_profile
$ echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bash_profile
```

But, after starting a new shell I tried to install the Elixir plugin, but I got:

```
$ asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
-bash: asdf: command not found

```

### Expected behavior

I expected the Elixir plugin to be installed.

### Actual behavior

I got the error:

```
$ asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
-bash: asdf: command not found
```

### Environment

**OS**: 
```
 OSX 10.13.4
```
**asdf version**:  
```
$ git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.5.0
```

I think the problem has to do with issue #98.  I echoed my PATH environment variable and I got a bunch of sessions statements in my PATH.  

I was able to fix the problem by deleting the lines that were added to .bash_profile, then I added couple of newlines to the end of the file, then I repeated the install instructions.

**Comment by nonnenmacher** [comment]
got same result here with output log prepended to PATH as 

```
/Users/whisky/.asdf Saving session... ...copying shared history... ...saving history... ...completed./shims:/Users/whisky/.asdf Saving session... ...copying shared history... ...saving history... ...completed.
```

**Comment by Stratus3D** [comment]
I just released v0.5.1 this morning? Can you try upgrading (`asdf update`) to see if that fixes the problem? I think the PATH issue has been fixed.

**Comment by vraravam** [comment]
I had the problem - but, after upgrading from 0.4.1 to 0.5.1. I did not have time - so, I blasted the whole asdf installation - and re-installed from scratch.

**Comment by nonnenmacher** [comment]
yes

updating to latest version from master branch, solved the issue

**Comment by weragoda** [comment]
:(
