### ISSUE TITLE
Error when using zsh and asdf

### ISSUE THREAD

**Issue by vraravam** [asdf-vm/asdf#344]
### Steps to reproduce

Install `asdf` on Mac OSX, with the default shell set to `zsh`. Opening a new terminal window or tab, this is the error that I get:
```bash
/usr/local/opt/asdf/asdf.sh:28: bashcompinit: function definition file not found
```

### Expected behavior

No error should be raised - just because I am not running `bash`

### Actual behavior

Error raised 

### Environment

**OS**: Mac OSX

**Default shell**: `zsh`

**asdf version**: 0.5.1

**Comment by Stratus3D** [comment]
We determine whether or not the user is using Zsh by checking for the `$ZSH_VERSION` variable. If it's not set we assume it's Bash, and proceed to use `bashcompinit`. Is `$ZSH_VERSION` set for you? I'd assume it's not because of the error you are getting.

 https://github.com/asdf-vm/asdf/blob/master/asdf.sh#L26

**Comment by vraravam** [comment]
Actually, I did see the code/file that you pointed out - and verified that `$ZSH_VERSION` *is* set. For me, it currently shows `5.3`.

**Comment by vraravam** [comment]
Would it be better to check for `ps $$` - and grep that to determine whether you are on bash or not? imo, `$ZSH_VERSION` will only give you whether its zsh or not - but, what about other shells?

**Comment by Stratus3D** [comment]
Actually I take that back. The only way line 28 in asdf.sh will be executed is if `$ZSH_VERSION` is not null, which yours is, and so is mine. So line 28 is being executed for both of us.

The difference is you get an error that says `bashcompinit` wasn't found. I'm not sure why that is the case.

**Comment by mcornella** [comment]
`bashcompinit` is the function that allows zsh to "read" bash completion files, so it's correct behavior that zsh looks for it. In your case, you might have a broken `$fpath` such that zsh can't find the `bashcompinit` file.

**Comment by Stratus3D** [comment]
Can you check if `bashcompinit` is on your path @vraravam ?

**Comment by vraravam** [comment]
This is what I see:
```bash
$ which bashcompinit
bashcompinit () {
        # undefined
        builtin autoload -XUz
}
```

**Comment by vraravam** [comment]
I'm not sure what I did - but, now the errors do not occur. It most likely has something to do with 
```
typeset -U fpath
```
which was in my `.zshrc` file.
