### ISSUE TITLE
Improve support for handling multiple versions

### ISSUE THREAD

**Issue by danhper** [asdf-vm/asdf#349]
A long time ago, when I wrote the [Python plugin](https://github.com/tuvistavie/asdf-python), I added support for multiple versions of a single plugin at the same time, so that `python3` and `python2` could be used together. Currently,

```
asdf global python 3.6.6 2.7.15 system
``` 

works quite fine, it tries to use Python 3.6.6 first, then 2.7.15 and finally fallbacks to system executables if the command is not found.

However, I am aware of at least three things that need to be improve:

1. `asdf current` command currently fails when multiple versions are used
    We currently get the following error message

    > `version 3.6.6 2.7.15 system is not installed for python`

    I totally understand why, but this needs to be fixed.
2. I do not think we have a single test covering this feature
3. This feature is not documented at all. It appears that even some core members did not know about it until recently.

I will finally have a little time to work on this, so I am planning on improving this in the next few weeks.
Please let me know if I missed something, and if you think there is anything else I should take into consideration.

Thanks!

**Comment by Stratus3D** [comment]
Yes! I only learned about this a couple months ago. It would be great to have documentation and tests around this feature!

**Comment by jayvdb** [comment]
This is really important for `tox` based Python projects, which need multiple versions.

**Comment by danhper** [comment]
Fixed
