### ISSUE TITLE
Cannot uninstall via command get "No build named asdf_" 

### ISSUE THREAD

**Issue by IanVaughan** [asdf-vm/asdf#357]
### Steps to reproduce

```
$ asdf uninstall erlang 20.1
No build named asdf_20.1

$ asdf list erlang | grep 20.1
  20.1
```

Happens with any uninstall version or lang.

### Environment

**OS**: OSX 10.13.6

**asdf version**: version: v0.5.1

**Comment by Stratus3D** [comment]
This is an issue with the asdf-erlang plugin, not asdf itself.

Are you using the latest version of asdf-erlang? (`asdf plugin-update erlang`) If you are using the latest version of it and this is still an issue please open on the [asdf-erlang issue tracker](https://github.com/asdf-vm/asdf-erlang/issues).
