### ISSUE TITLE
odbc check failed in OSX

### ISSUE THREAD

**Issue by zeroshree** [asdf-vm/asdf#363]
### Steps to reproduce
1. git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.5.1
I added following asdf in .zshrc 
echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshrc
and source .zshrc 

I installed following things
coreutils automake autoconf openssl libyaml readline libxslt libtool unixodbc

I added erlang using $ asdf add-plugin erlang and Installed as $ asdf  install erlang 20.0

### Expected behavior

It should install 20.0 TOP

### Actual behavior

but I am getting odbc check failed error.

### Environment

** OSX HIGH SIERRA 10.13.2**:

**latest**:

**Comment by Stratus3D** [comment]
Are you sure you had odbc installed and configured correctly on your machine? The build should be be able to find it (asdf-erlang uses kerl for builds). You might check the kerl docs and see if they say anything about odbc. This is not an issue with asdf itself so I am closing it. Please open an issue for asdf-erlang if this problem persists.
