### ISSUE TITLE
Plugin tests failing due to executable check in plugin-test command

### ISSUE THREAD

**Issue by alvarobp** [asdf-vm/asdf#373]
### Steps to reproduce

Run ```asdf plugin-test minikube https://github.com/alvarobp/asdf-minikube```

### Expected behavior

Tests should have passed, given there were not changes since last green build on Travis CI (https://travis-ci.org/alvarobp/asdf-minikube/builds/394482098)

### Actual behavior

Tests fail showing the following message:

```
FAILED: Incorrect permissions on /var/folders/0n/t0n9_sz17c94qqmqdp_lf_mh0000gn/T/asdf.XXXX.F1a5b816/plugins/minikube/bin/*. Must be executable by asdf
```

### Environment

**OS**: macOS 10.13.6 and Ubuntu 18.04.1

**asdf version**: 0.6.0

### Comments

This has started happening since version 0.6.0, tests were passing in my machines with 0.5.1. I see there are many other plugin test builds failing because of this. I tried golang manually and I saw Travis CI builds failing similarly for a bunch of plugins, for example asdf-ruby (https://travis-ci.org/asdf-vm/asdf-ruby/jobs/437232080#L634) and asdf-nodejs (https://travis-ci.org/asdf-vm/asdf-nodejs/jobs/430080200#L505)

**Comment by blimmer** [comment]
👍 we are also seeing this issue.

**Comment by alvarobp** [comment]
For the time being, I've decided to pin the asdf version used by asdf-minikube travis script to v0.5.0 which is the one that I found to be working for the plugin.

**Comment by Stratus3D** [comment]
Thanks for reporting this. There were changes in 0.6.0, but it's not apparent to me exactly what the cause of this behavior. This is definitely a bug though. I'll try to tag a patch version in the next day or two once I get this fixed.

**Comment by Stratus3D** [comment]
This should be fixed now. Valid plugins should now pass the executable test in the code.

**Comment by alvarobp** [comment]
It worked for me as well https://github.com/alvarobp/asdf-minikube/pull/6

Thank you!
