### ISSUE TITLE
Idea: asdf_exec helper?

### ISSUE THREAD

**Issue by blimmer** [asdf-vm/asdf#374]
First of all, thank you for this tool. I've been working in it for just a few days now and it's going to greatly slim down all the version managers I have installed 🍻 

Today I ran into a situation where a shell script was being executed outside the context of a login shell. This was causing the `bashrc` to not be sourced, which didn't shim the `PATH` variable.

Therefore, I created a simple script (I called it `asdf_exec`) that simply ensures that the setup script is called.

```bash
#!/bin/bash

. $HOME/.asdf/asdf.sh

exec "$@"
```

Is this something that the main `asdf` project would consider a useful addition for others? For instance, maybe a user could call:

```console
> $HOME/.asdf/asdf_exec <plugin> <command>
# or, more concretely
> $HOME/.asdf/asdf_exec ruby version
```

If this behavior seems desirable, I'd be happy to put together a PR.

**Comment by vic** [comment]
New shims (6da747b6cebcdd46269415654f24cc1db258e842) are just wrappers for `asdf exec tool args...` so you can now invoke tools by having only `asdf` available but not the shims directory in PATH.
