### ISSUE TITLE
prefix command?

### ISSUE THREAD

**Issue by mwean** [asdf-vm/asdf#375]
I'm writing some scripts that need to know where things like configuration or data files are stored, and rather than hard-code something like `"#{ENV["ASDF_DATA_DIR"]}/installs/redis/#{version}/data/"`, I thought it would be nice to add a `prefix` command to return the data directory of a specific version. Prefix probably isn't the best name, it's just what homebrew uses.

```
$ asdf prefix redis [VERSION]
> /Users/matt/.asdf/installs/redis/3.2.12/
```

What do you think?

**Comment by Stratus3D** [comment]
`asdf where redis` and `asdf which redis` should give you what you need:

```
$ asdf where ruby 2.4.2
~/.asdf/installs/ruby/2.4.2

$ asdf which ruby
~/.asdf/installs/ruby/2.4.2/bin/ruby
```

An issue already exists for improving the `which` command so it works with any shim in any plugin, see issue #205. I'm closing this since it is similar to #205.

**Comment by mwean** [comment]
Ah! Sorry, I thought `which` and `where` were both just returning the executable location. Thanks!
