### ISSUE TITLE
Which plugin/version the shim is available in?

### ISSUE THREAD

**Issue by tkossak** [asdf-vm/asdf#380]
Is it possible to find out quickly which plugin/version a shim is available in? All i get when running non-existent shim is:

```
> chardetect
No such command in 3.7.0 of python
```

Would be nice to display where it is availble or to search it via something like `asdf shim-search chardetect`

**Comment by tkossak** [comment]
Also the error text doesn't tell what command exactly is missing:

```
$ which git
/usr/bin/git

$ git --version
git version 2.7.4

$ git stash list
No such command in 3.6.2 of python
```

I have no idea what command `git` runs, that isn't available in current python.

**Comment by vic** [comment]
new `asdf shim-versions` command is in master now.
