### ISSUE TITLE
Name confusion.

### ISSUE THREAD

**Issue by jaccarmac** [asdf-vm/asdf#383]
Hey, forgive me as I haven't done a deep dive into the project yet. So first of all let me say a general-purpose version manager sounds like a *wonderful* simplifying step.

When I saw the link to this project, however, the name got my attention as it is shared with the [de facto Common Lisp build library](https://common-lisp.net/project/asdf/). It seems there may be some ambiguity given the overlap re: version management (albeit language versions vs. package versions).

**Comment by Stratus3D** [comment]
Closing since I don't think we want to rename asdf right now.
