### ISSUE TITLE
asdf install <name> [<version>]

### ISSUE THREAD

**Issue by RobLoach** [asdf-vm/asdf#39]
When installing a version of a plugin, you need to provide the version. Would be nice if the version became optional, so that it would select the latest version available.

```
asdf install nodejs
```

Would do a `asdf list-all nodejs`, and automatically select the latest one.

**Comment by HashNuke** [comment]
@RobLoach most plugins use a plain test file to store versions. Except nodejs. Hence the support for automatically picking version to install wasn't added. This way the user is forced to pick the version required.
