### ISSUE TITLE
After installing via homebrew shims aren't picked up

### ISSUE THREAD

**Issue by jsatk** [asdf-vm/asdf#393]
### Steps to reproduce

```sh
$ brew install asdf
$ echo 'source /usr/local/opts/asdf.fish' >> /usr/local/opts/fish/config.fish
$ asdf plugin-add nodejs
$ asdf install nodejs 8.12.0
$ asdf global nodejs 8.12.0
$ which node # I get nothing
```
### Expected behavior

I'd expect `which node` to return `/usr/local/opts/asdf/shims/nodejs/8.12.0/node`

### Actual behavior

It gives me nothing. 

### Environment

**OS**: macOS Mojave 10.14.1

**asdf version**: 0.6.0

**Comment by Stratus3D** [comment]
What do you mean by "it gives me nothing". Nothing is printed? If it does print something out can you include in that in the issue?

**Comment by jsatk** [comment]
@Stratus3D nothing is printed yes. It's the same as if you were to run `which foo` or some other non-existing binary. 

I see you updated the title. I think that's more accurate now that I know what's going on.

FWIW I did eventually get it to work. After doing the above steps (and a lot more mucking around in-between) I did the following and now it's working.

1. Forced a re-install of `asdf` via `brew`
2. Realized I'd moved the sourcing of the `asdf` file for up towards the top of my `~/.config/fish/config.fish`. I moved it to the very bottom. 
3. Re-ran the various steps to install things.

Suddenly `which node` returned `/usr/local/opt/asdf/shims/node`. 

I suspect it had something to do with my `$PATH` being wrong because of where `/usr/local/opts/asdf.fish` was being sourced? I looked at the source for that file and it prepends itself to the path so I'm guessing there was something related to that?

@Stratus3D would you be open to me submitting a PR that updates the docs with instructions for home-brew installers and caveats about need for the invocation of the asdf script to be after you set your path? I suspect most folks don't simply copy & paste the command in the README but rather go,"Oh I see what this is doing. I'll throw this in my `~/.bash_profile`!"

**Comment by Stratus3D** [comment]
Feel free to open a PR. I think we already say something similar for Zshell.
