### ISSUE TITLE
Homebrew install doesn't work

### ISSUE THREAD

**Issue by SeanRParker** [asdf-vm/asdf#394]
### Steps to reproduce

`brew install asdf`

### Expected behavior

`adsf -h` should return helpful commands

### Actual behavior

asdf command not found

### Environment

**OS**: Mac Mojave 10.14.1

**asdf version**: 0.6.0

**Comment by Stratus3D** [comment]
`adsf -h` isn't a command. Can you confirm you were in fact using the `asdf` command?

**Comment by humankindof** [comment]
To make homebrew's completions available in bash, you must source the definitions as part of your shell startup. They have to be in your PATH.

For me, on a Mac, this simply means running each of these commands
echo -e '\n. $(brew --prefix asdf)/asdf.sh' >> ~/.bash_profile
echo -e '\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash' >> ~/.bash_profile

The second command is unnecessary if you have configured completions for Homebrew in ~/.bash_profile

Homebrew bash configuration completion code:
https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash

asdf install instructions for each system here:
https://asdf-vm.com/#/core-manage-asdf-vm
