### ISSUE TITLE
enhancement: add current-unset

### ISSUE THREAD

**Issue by jfkw** [asdf-vm/asdf#400]
### Steps to reproduce

I had asdf managed golang versions installed. I want to temporarily remove any asdf managed go and resume using the system go version.

Uninstall current golang version, golang plugin gets into `version not installed` state.

### Expected behavior

After current version of golang (or other plugin managed language) is uninstalled, state should be `no version set`.

Better (requsted enhancement) would be an `current-unset <name>` command which retains the cached downloads, just forces the `no version set` state for that plugin

### Actual behavior

The unwanted state where no asdf go version is installed:

```
$ asdf current
clojure        No version set for clojure; please run `asdf <global | local> clojure <version>`
version 1.11.1 is not installed for golang
golang
java           No version set for java; please run `asdf <global | local> java <version>`
kotlin         No version set for kotlin; please run `asdf <global | local> kotlin <version>`
racket         No version set for racket; please run `asdf <global | local> racket <version>`
ruby           No version set for ruby; please run `asdf <global | local> ruby <version>`
```
Even deleting .asdf and recreating 
```
$ rm -rf ~/.asdf

$ git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.0

$ asdf plugin-list
Oohes nooes ~! No plugins installed

$ asdf plugin-add golang
(...)

$ asdf plugin-list
golang

(start new shell)
$ asdf current
version 1.11.1 is not installed for golang
golang
```

### Environment

**OS**:

`gentoo linux ~amd64`, `openSUSE Tumbleweed x86_64`

**asdf version**: 

`v0.6.0`

**Comment by jayvdb** [comment]
I've been trying to adopt asdf, and run into this problem quite a bit.

I've found that there is a "system" version, which I now see is mentioned in the README.md and in CHANGELOG.md a few times, which is supposed to undo the version managed/set by the asdf plugin.

```console
> asdf global golang system
> asdf current
cmake          No version set for cmake; please run `asdf <global | local> cmake <version>`
desk           No version set for desk; please run `asdf <global | local> desk <version>`
elm            No version set for elm; please run `asdf <global | local> elm <version>`
erlang         No version set for erlang; please run `asdf <global | local> erlang <version>`
golang         system   (set by /home/jayvdb/.tool-versions)
java           No version set for java; please run `asdf <global | local> java <version>`
link           No version set for link; please run `asdf <global | local> link <version>`
nodejs         No version set for nodejs; please run `asdf <global | local> nodejs <version>`
python         3.6.7    (set by /home/jayvdb/.tool-versions)
ruby           No version set for ruby; please run `asdf <global | local> ruby <version>`
rust           No version set for rust; please run `asdf <global | local> rust <version>`
vars           No version set for vars; please run `asdf <global | local> vars <version>`
> echo $GOPATH
/home/jayvdb/go:/usr/share/go/1.7/contrib
> echo $GOROOT
/usr/lib64/go/1.7
> which go
/home/jayvdb/.asdf/shims/go
> go version
go version go1.7.5 linux/amd64
```

It should be mentioned in the `--help` as it is not obvious that `system` is an option for `<version>`.  It took me a while to find it, by greping around in the source code of plugins.

Is this close enough to what you are wanting?

**Comment by vic** [comment]
Could you try using master (cc7886309271b21a7da3fccf8efc892b546ffbbb) and see if setting `system` (either on .tool-versions or as env-var) works now ?

`env ASDF_GOLANG_VERSION=system go version` # should execute your system's go without asdf-shims in PATH

`env ASDF_GOLANG_VERSION=system which go` # should print the asdf go shim.

**Comment by Stratus3D** [comment]
This should be fixed in the latest version(s) of asdf. Closing this issue.
