### ISSUE TITLE
ASDF_DATA_DIR or ASDF_DIR ?

### ISSUE THREAD

**Issue by AlJohri** [asdf-vm/asdf#405]
The documentation in the README states that the environment variable for the `~/.asdf` folder should be `ASDF_DATA_DIR` but locally, I only see `ASDF_DIR` defined.

Locally I see the following variables defined:

![screen shot 2018-11-16 at 11 58 14 am](https://user-images.githubusercontent.com/2790092/48636176-2fbcc000-e998-11e8-877d-a89a2f66b5a9.png)

What is the difference between ASDF_DATA_DIR and ASDF_DIR?

**Comment by Stratus3D** [comment]
`ASDF_DATA_DIR` is the directory that contains your plugins and installs. It's not necessary to set it, and asdf does not export it. If it is not set asdf will default to using `$HOME/.asdf` as your `ASDF_DATA_DIR`, which is probably what you want. `ASDF_DIR` is the directory containing the code for asdf itself (e.g. the `bin` and `lib` dirs). If you've installed asdf using the instructions on the readme `ASDF_DIR` will be set to `$HOME/.asdf` as well. If you've used brew to install asdf it will be a different directory. The directory brew installed the asdf code into.

These two variables exist so asdf code can be kept separate from asdf data like plugins and installed versions. This allows things like the brew upgrade process to work without destroying plugins and installed versions.

**Comment by AlJohri** [comment]
Thank you!
