### ISSUE TITLE
reshim all active plugins

### ISSUE THREAD

**Issue by jayvdb** [asdf-vm/asdf#407]
### Steps to reproduce

After running `pipenv install`, I need to run `asdf reshim python`

### Expected behavior

I should be able to run `asdf reshim` as there is only one active plugin in the current workspace

### Environment

**OS**: Linux

**asdf version**: v0.6.2

**Comment by vic** [comment]
Fixed in ed843f29f66a0cdb99ee0c2e731bbba79452839d
