### ISSUE TITLE
.asdfrc config file

### ISSUE THREAD

**Issue by HashNuke** [asdf-vm/asdf#41]
The expected path to the config file is `$HOME/.asdfrc`. It needs to be in the following format:

```
key1=value1
key2=value2
```

The only config option that is required to be supported right now is `legacy_version_file`. The possible values for this option should be `yes` or `no`. The default value should be `no`.

The config file is optional. If the file is not present, then all options will use the default values.

**Comment by lucaspiller** [comment]
@HashNuke I've just come across this project and it looks awesome, I'm going to spend some time playing with it over the weekend as having version managers for every language really slows down my terminal.

In terms of Ruby, almost all projects have a `.ruby-version` file (which is usually committed) as that's what other version managers expect. It should be mentioned in the readme that this option needs to be enabled to pick it up (I'll send a PR later). Is there any reason why this isn't enabled by default?

**Comment by HashNuke** [comment]
@lucaspiller Glad you like the project. This config file feature is all @tuvistavie's smart work.

Yes it needs to be added to the readme (was just playing around with the feature for a couple days in silence). Not enabled by default so that people don't get confused (so we intend to keep it that way). Currently only the ruby plugin supports reading the `.ruby-version` file. Could be added to the nodejs plugin too and read the `.nvmrc` file.
