### ISSUE TITLE
Missing few libraries in Dockerfile

### ISSUE THREAD

**Issue by zeroshree** [asdf-vm/asdf#415]
I am facing problem when trying to use asdf in Dockerfile in ubuntu server (it is t2.micro aws).

DOCUMENTATION INFORMATION (See: /asdf/plugins/erlang/kerl-home/builds/asdf_21.0.4/otp_build_21.0.4.log)
 * documentation  : 
 *                  xsltproc is missing.
 *                  fop is missing.
 *                  xmllint is missing.
 *                  The documentation can not be built.
Dockerfile Configuration 

`FROM ubuntu:18.04

*#install ubuntu packages*
RUN apt-get update -q \
 && apt-get install -y \
    git \
    curl \
    locales \
    build-essential \
    autoconf \
    libncurses5-dev \
    libwxgtk3.0-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libpng-dev \
    libssh-dev \
    unixodbc-dev \
 && apt-get clean

*#install asdf and its plugins*
ENV ASDF_ROOT /asdf
ENV PATH "${ASDF_ROOT}/bin:${ASDF_ROOT}/shims:$PATH"
RUN git clone https://github.com/asdf-vm/asdf.git ${ASDF_ROOT} --branch v0.5.0 \
 && asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang \
 && asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir \
 && asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs \
 && ${ASDF_ROOT}/plugins/nodejs/bin/import-release-team-keyring

*#set the locale*
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

*#install erlang*
ENV ERLANG_VERSION 21.0.4
RUN asdf install erlang ${ERLANG_VERSION} \
 && asdf global erlang ${ERLANG_VERSION}

*# install elixir*
ENV ELIXIR_VERSION 1.7.4
RUN asdf install elixir ${ELIXIR_VERSION} \
 && asdf global elixir ${ELIXIR_VERSION}
`

Then I add to install apt-get install -y xsltproc fop

but still   getting this *xmllint is missing.

**Comment by Stratus3D** [comment]
Are you using the latest version of asdf-erlang? I think we recently changed how it does documentation. By default it shouldn't build any docs.

**Comment by zeroshree** [comment]
I am using version asdf_21.0.4 for asdf-erlang.

**Comment by Stratus3D** [comment]
`asdf_21.0.4` isn't a version. I'm talking about the plugin itself, not the Erlang version. Are you using the latest version of asdf-erlang? You can verify you are by running `asdf plugin-update erlang`

**Comment by zeroshree** [comment]
Ok I ll check

**Comment by Stratus3D** [comment]
Closing this as I believe this is something that has been addressed in the latest version of asdf-erlang.

**Comment by zeroshree** [comment]
yes , please close it since I resolved it.
