### ISSUE TITLE
/usr/local/libexec/private/asdf-exec: No such file or directory

### ISSUE THREAD

**Issue by philippneugebauer** [asdf-vm/asdf#418]
I was following this tutorial: https://www.mitchellhanberg.com/post/2017/10/05/installing-erlang-and-elixir-using-asdf/

```
$ asdf plugin-list
elixir
erlang
ruby
$ asdf current
elixir         1.7.4    (set by /Users/me/.tool-versions)
erlang         21.2     (set by /Users/me/.tool-versions)
ruby           No version set for ruby; please run `asdf <global | local> ruby <version>`
$ elixir -v
/Users/me/.asdf/shims/elixir: line 4: /usr/local/libexec/private/asdf-exec: No such file or directory
/Users/me/.asdf/shims/elixir: line 4: exec: /usr/local/libexec/private/asdf-exec: cannot execute: No such file or directory
```

I could not find anything regarding my issue but I also did not find anything I might have missed in my installation

**OS**: macOs Sierra

**asdf version**: 0.6.2

**Comment by look4regev** [comment]
I had the same problem.
To fix simply edit `/Users/me/.asdf/shims/elixir` and change the `/usr/local/libexec/private/asdf-exec` to `/usr/local/Cellar/asdf/0.6.2/libexec/private/asdf-exec`.
I think it is caused because I had an old asdf 0.6.0 which was missing the `.zshrc` activation (`source /usr/local/opt/asdf/asdf.sh`).

**Comment by abumalick** [comment]
Thank you very much @look4regev it worked for me.

 I just installed asdf v0.6.2 from homebrew so it is not due to an old version for me

**Comment by abumalick** [comment]
I had the problem for nodejs and python

running this, avoids the edition of all shims:
```
sudo ln -s /usr/local/Cellar/asdf/0.6.2/libexec/ /usr/local/libexec
```

**Comment by tcoenraad** [comment]
> ln -s /usr/local/Cellar/asdf

By turning the command into

```sudo ln -s /usr/local/opt/asdf/libexec/ /usr/local/libexec```

you make it version unaware :wink:

**Comment by abumalick** [comment]
thank you very much @tcoenraad

**Comment by OldhamMade** [comment]
Happening for me also. Is there a fix planned so users don't have to hack around creating symlinks?

**Comment by JackHowa** [comment]
I ran into a similar error, using: ```
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash```

It seems to be working with homebrew using: ```
. $(brew --prefix asdf)/asdf.sh
```

**Comment by philippneugebauer** [comment]
I cannot reproduce this error anymore with 0.7.4

**Comment by SidOfc** [comment]
I had this issue just now on Ubuntu `19.04` using asdf `0.7.4`.

I was trying to run `rustc` version `1.35.0` which was installed properly but asdf could not find it:

```
/home/me/.asdf/shims/rustc: line 3: /usr/local/opt/asdf/bin/asdf: No such file or directory
```

asdf is installed in `$HOME/.asdf`, on my machine and the `/usr/local/opt` folder did not exist.
What I did to fix it was first create the directory `/usr/local/opt`, then symlink `$HOME/.asdf` to `/usr/local/opt/asdf`. After this the `rustc` command started working properly again.`

Unfortunately I am unsure from which version I actually upgraded but I believe it was `7.1.0`, in this version I did not have this issue without the `/usr/local/opt` directory.

If it is still broken after symlinking, check to see if the symlink itself isn't broken, the `file` command can be used to check: `file /usr/local/opt/asdf`. If the output states `broken symbolic link to...` try recreating it with absolute paths.

Hope this helps anyone, good luck!

**Comment by Stratus3D** [comment]
Closing this ticket because I don't believe this is an issue with the latest versions of asdf (`0.8.0-rc1` and `0.7.8`). Please upgrade if you encounter this issue.

**Comment by SidOfc** [comment]
Actually @Stratus3D I still do have this issue with `0.7.8` as well as `0.8.0-rc1`, this is what I did:

```bash
• ~/D/rust/some-project ⚑ ❯ asdf --version
v0.7.8-40c492b
• ~/D/rust/some-project ⚑ ❯ ls /usr/local/opt
asdf@
• ~/D/rust/some-project ⚑ ❯ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
• ~/D/rust/some-project ⚑ ❯ sudo rm -rf /usr/local/opt
[sudo] password:
• ~/D/rust/some-project ⚑ ❯ asdf reshim
• ~/D/rust/some-project ⚑ ❯ rustc --version
/home/sidofc/.asdf/shims/rustc: line 6: /usr/local/opt/asdf/bin/asdf: No such file or directory
• ~/D/rust/some-project ⚑ ❯ asdf reshim
• ~/D/rust/some-project ⚑ ❯ rustc --version
/home/sidofc/.asdf/shims/rustc: line 6: /usr/local/opt/asdf/bin/asdf: No such file or directory
• ~/D/rust/some-project ⚑ ❯ asdf --version
v0.7.8-4a3e3d6
• ~/D/rust/some-project ⚑ ❯ asdf reshim
• ~/D/rust/some-project ⚑ ❯ rustc --version
/home/sidofc/.asdf/shims/rustc: line 6: /usr/local/opt/asdf/bin/asdf: No such file or directory
• ~/D/rust/some-project ⚑ ❯ asdf --version
v0.8.0-rc1-e0142ee
• ~/D/rust/some-project ⚑ ❯
```

After re-symlinking to /usr/local/opt it started working again.
Should I completely reinstall an asdf plugin, or is it something else I missed perhaps?

**Comment by Stratus3D** [comment]
@SidOfc are you sure you installed asdf correctly? It seems like your `ASDF_DATA_DIR` or some other asdf path isn't corrrect on your system. Go to asdf-vm.com/ and select your OS and install type and verify you ran all the correct commands.

**Comment by SidOfc** [comment]
I noticed one instruction differs from what I've got, but it doesn't seem to change anything.
I use `fish_user_paths` to set up asdf like so:

```fish
set -U fish_user_paths $HOME/.asdf/bin $HOME/.asdf/shims
```

This works, and works for rust too as long as I have the symlink to `/usr/local/opt` in place.
According to the installation instructions I need to `source $HOME/.asdf/asdf.fish`, so I've changed my declaration to this:

```fish
set -U fish_user_paths $HOME/.asdf/asdf.fish
```

This still works, but when the symlink is removed I'm running into the same issue:
![image](https://user-images.githubusercontent.com/3225058/90623656-1143c280-e217-11ea-8fdd-a0c042ee69c3.png)

One interesting difference is that the ruby plugin does work correctly:
![image](https://user-images.githubusercontent.com/3225058/90623731-30425480-e217-11ea-982c-2ea7fa6dce4e.png)

I checked the [rust asdf plugin repo](https://github.com/code-lever/asdf-rust) but it does not contain any references to `/usr/local/opt` so I don't think the issue lives in that repo, though I could have missed something.

I also tried `asdf plugin-update --all` which did update some plugins, including rust. After that I ran `asdf reshim` and checked if the shim for `rustc` changed but alas, it is still the same.

Would another idea be to reinstall asdf from scratch?

**Comment by bbugh** [comment]
This happened to me, not sure why, but I found a fix for it. 

It was working fine until today, maybe because oh-my-zsh upgraded this morning? 
I installed asdf with homebrew and am using the `asdf` zsh plugin, which tries to load files that don't exist:

```
/Users/bbugh/.oh-my-zsh/custom/plugins/asdf/asdf.plugin.zsh:source:4: no such file or directory: /Users/bbugh/.asdf/asdf.sh
/Users/bbugh/.oh-my-zsh/custom/plugins/asdf/asdf.plugin.zsh:source:5: no such file or directory: /Users/bbugh/.asdf/completions/asdf.bash
```

If I look at the `~/.asdf/shims/ruby` shim for example, it's pointing to a folder that doesn't exist:

```bash
exec /opt/homebrew/Cellar/asdf/0.8.1_1/libexec/bin/asdf exec "ruby" "$@"
```

but my asdf is `/opt/homebrew/Cellar/asdf/0.9.0`. If I do `asdf reshim`, nothing changes:

```
» asdf reshim
» ruby -v
/Users/bbugh/.asdf/shims/ruby: line 4: /opt/homebrew/Cellar/asdf/0.8.1_1/libexec/bin/asdf: No such file or directory
/Users/bbugh/.asdf/shims/ruby: line 4: exec: /opt/homebrew/Cellar/asdf/0.8.1_1/libexec/bin/asdf: cannot execute: No such file or directory
```

Using `which`, the correct paths seems to be:

```bash
» which -a asdf
asdf () {
	local command
	command="$1"
	if [ "$#" -gt 0 ]
	then
		shift
	fi
	case "$command" in
		("shell") eval "$(asdf export-shell-version sh "$@")" ;;
		(*) command asdf "$command" "$@" ;;
	esac
}
/opt/homebrew/opt/asdf/libexec/bin/asdf ✅
/opt/homebrew/bin/asdf
```

### Solution

I removed `asdf` plugin from `~/.zshrc`, and then ran the command to add zsh to the file:

```bash
echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc
```

I started a new terminal session, and tried `ruby -v` again - no luck, same error.

Then I deleted *all* of the shims in `~/.asdf/shims` and then ran `asdf reshim` again, and it correctly set the shim paths:

```
exec /opt/homebrew/opt/asdf/libexec/bin/asdf exec "node" "$@"
```

Seems like there's an issue with asdf not reshimming correctly.

**Comment by rossvz** [comment]
Some rogue homebrew command bumped me from 0.8.1 to 0.9 today for asdf, and I ran into the same issue with Elixir/Erlang via asdf. @bbugh solution above ☝️ worked for me

**Comment by matschaffer** [comment]
Yep. Same here. Weird that `reshim` wouldn't recreate the files on a version mismatch.

```
❯ go version
/Users/matschaffer/.asdf/shims/go: line 3: /usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf: No such file or directory
/Users/matschaffer/.asdf/shims/go: line 3: exec: /usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf: cannot execute: No such file or directory

❯ rm -rf ~/.asdf/shims; asdf reshim

❯ go version
go version go1.17.3 darwin/amd64
```

**Comment by matschaffer** [comment]
Ah. Looks like https://github.com/asdf-vm/asdf/issues/531 is open to address that. But googling "shims asdf no such file or directory" led me to this issue first.

**Comment by morenoh149** [comment]
`rm -rf ~/.asdf/shims; asdf reshim` fixes the errors for me. I can run `yarn start` now.

**Comment by VikingPingvin** [comment]
Just commenting here that `rm -rf ~/.asdf/shims; asdf reshim` works for me as well. It broke kubectx and kubectl in my case.
