### ISSUE TITLE
Update command disabled

### ISSUE THREAD

**Issue by tkossak** [asdf-vm/asdf#436]
### Steps to reproduce
```
$ which asdf
/home/kossak/.asdf/bin/asdf
$ asdf --version
v0.6.3
$ asdf update
Update command disabled. Please use the package manager that you used to install asdf to upgrade asdf.
```

### Expected behavior

asdf was installed using `git clone` so I hoped `asdf update` would switch to proper commit. Does it mean I should checkout proper commit manually or should `asdf update` work?

### Actual behavior

Error: `Update command disabled. Please use the package manager that you used to install asdf to upgrade asdf.`
What is interesting, when I `cd` into asdf git dir it seems to be working:
```
$ cd ~/.asdf
$ asdf update
HEAD is now at 1886e00... Update version to 0.6.3
Updated asdf to release v0.6.3
$ cd /
$ asdf update
Update command disabled. Please use the package manager that you used to install asdf to upgrade asdf.
```

### Environment

**OS**: Linux Mint 18.3 Sylvia

**asdf version**: 0.6.3

**Comment by Stratus3D** [comment]
I am not able to reproduce this. Is your update command only working inside the `~/.asdf` directory? Or does it work in other places too?

**Comment by tkossak** [comment]
I just tried updating on my other computer and the same thing happened:

```
$ asdf --version
v0.6.0
$ asdf update
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (328/328), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 496 (delta 253), reused 310 (delta 244), pack-reused 168
Receiving objects: 100% (496/496), 133.03 KiB | 752.00 KiB/s, done.
Resolving deltas: 100% (270/270), completed with 41 local objects.
From https://github.com/asdf-vm/asdf
   f9bb44f..8ccfda2  master     -> origin/master
 * [new tag]         v0.6.1     -> v0.6.1
 * [new tag]         v0.6.2     -> v0.6.2
 * [new tag]         v0.6.3     -> v0.6.3
Previous HEAD position was aa5f7f1 Update version to 0.6.0
HEAD is now at 1886e00 Update version to 0.6.3
Updated asdf to release v0.6.3
$ asdf update
Update command disabled. Please use the package manager that you used to install asdf to upgrade asdf.
```

**Comment by Stratus3D** [comment]
This is the conditional for disabled updates:

```
if [ -f asdf_updates_disabled ] || ! git rev-parse --is-inside-work-tree &> /dev/null; then
```

One of those two expressions must be evaluating to true. Can you check if the `asdf_updates_disabled` file is present? And can you check the output of `git rev-parse --is-inside-work-tree` inside your `~/.asdf` directory?

**Comment by tkossak** [comment]
I don't have `asdf_updates_disabled` file anywhere in my $HOME directly or indirectly.

```
$ find ~ -name asdf_updates_disabled
$ git rev-parse HEAD
1886e00cf18f5e9d3c5ac1bd18426d04121d4472
$ git rev-parse --is-inside-work-tree
true
```

**Comment by tkossak** [comment]
I tried updating one more time:
```
$ pwd
/home/kossak/.asdf
$ which asdf
/home/kossak/.asdf/bin/asdf
$ asdf update
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 16 (delta 10), reused 16 (delta 10), pack-reused 0
Unpacking objects: 100% (16/16), done.
From https://github.com/asdf-vm/asdf
   8ccfda2..cdd8dc1  master     -> origin/master
HEAD is now at 1886e00... Update version to 0.6.3
Updated asdf to release v0.6.3

$ cd
$ asdf update
Update command disabled. Please use the package manager that you used to install asdf to upgrade asdf.
```

**Comment by Stratus3D** [comment]
I'm pretty sure in the context of the update code `$ASDF_DIR` is not set.

```
cd "${ASDF_DIR}" || exit 1
```

`cd` will navigate to your home directory when not given an argument, so I bet the code is running in your home directory. And of course it's not a Git repository so that check fails.

**Comment by tkossak** [comment]
Yes, `$ASDF_DIR` is not set. Should it be set by [asdf.fish](https://github.com/asdf-vm/asdf/blob/master/asdf.fish) file? Because it doesn't export `ASDF_DIR` for fish shell, it only uses local variable `asdf_dir` - with lowercase and initialized using `set -l`, so it's local variable (not exported). Maybe this file should use `set -x ASDF_DIR ...` instead?

**Comment by tkossak** [comment]
I can confirm that when I added `set -x ASDF_DIR (dirname (status -f))` to `asdf.fish` the `asdf update` works correctly (no matter the current directory).

**Comment by Stratus3D** [comment]
Yes it should, that's definitely a bug.
