### ISSUE TITLE
Project introduction not clear enough

### ISSUE THREAD

**Issue by coka** [asdf-vm/asdf#438]
Hi! :wave:

Your project was mentioned in a recent HN thread, and the [comments](https://news.ycombinator.com/item?id=18987739) included this bit:

>I have to read the README twice to see what is it about. What is extensible version manager? Managing what exactly. So I guess it's the reason asdf is not popular
>>It replaces gvm/rbenv/pyenv/nvm/etc. with a single CLI. Saves you from having to use multiple shell completion scripts, bashrc entries and CLIs. Useful if you work with multiple dev languages on your computer.
>>>And nowhere in the README tells me about that. Your first sentence immediately makes it clear

I have to admit that this person _does_ have a point. Maybe you could explicitly mention which tools this project replaces, what benefits does replacing them bring, as well as provide a comparison chart (mentioning features such as the one discussed in #367)? I understand that these things are clear to some people from the get-go, but I think that a better introduction would help onboard new asdf tinkerers.

**Comment by Stratus3D** [comment]
Thank you for reporting this. I do think the readme has recently changed, and the current wording doesn't really convey what asdf's strengths are. We need to update the first few lines of the readme. Looks like the Hacker News comments have some good suggestions on how to improve it.

**Comment by jthegedus** [comment]
@coka I believe this has been address appropriately in #440 and #441 

Please re-open this issue if you feel otherwise :smiley:

Please take a look at the new README and documentation site http://asdf-vm.github.io/asdf/#/ Feedback or additions are encouraged!

**Comment by coka** [comment]
Yeah, much better! :smiley: Good work!
