### ISSUE TITLE
Setup docs for Fedora seem to be wrong

### ISSUE THREAD

**Issue by davorbadrov** [asdf-vm/asdf#453]
The docs seem to be wrong for Fedora, more precisely the [Plugin dependencies](https://asdf-vm.github.io/asdf/#/core-manage-asdf-vm?id=plugin-dependencies) section.

### Steps to reproduce

Following these steps on the [documentation site](https://asdf-vm.github.io/asdf/#/core-manage-asdf-vm):

1 - clone the repo
```sh
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.3
```

2 - add scripts for autocompletion
```sh
echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
```
3 - **this step breaks** install plugin dependencies, shouldn't there be `sudo dnf install` before the plugins list
```sh
automake autoconf readline-devel \
ncurses-devel openssl-devel libyaml-devel \
libxslt-devel libffi-devel libtool unixODBC-devel
```

This works as expected (docs are missing `sudo dnf install`):
```sh
sudo dnf install automake autoconf readline-devel \
> ncurses-devel openssl-devel libyaml-devel \
> libxslt-devel libffi-devel libtool unixODBC-devel
```

### Expected behavior

I expected that the required dependencies will be installed for asdf.

### Actual behavior

I got this output

```sh
$ automake autoconf readline-devel \
> ncurses-devel openssl-devel libyaml-devel \
> libxslt-devel libffi-devel libtool unixODBC-devel

automake: error: no Automake input file found for 'autoconf'
automake: error: no Automake input file found for 'readline-devel'
automake: error: no Automake input file found for 'ncurses-devel'
automake: error: no Automake input file found for 'openssl-devel'
automake: error: no Automake input file found for 'libyaml-devel'
automake: error: no Automake input file found for 'libxslt-devel'
automake: error: no Automake input file found for 'libffi-devel'
automake: error: no Automake input file found for 'libtool'
automake: error: no Automake input file found for 'unixODBC-devel'
automake: error: no input file found among supplied arguments

```

### Environment

**OS**: Fedora 28

**asdf version**: v.0.6.3

**Comment by jthegedus** [comment]
Sorry, this is my bad. These previously used to be just a list of dependencies to install, not a direct command. Would you be able to PR a docs change?

```shell
sudo dnf install automake autoconf readline-devel \
  ncurses-devel openssl-devel libyaml-devel \
  libxslt-devel libffi-devel libtool unixODBC-devel
```

Is this the only change that needs to occur?

**Comment by davorbadrov** [comment]
Sure, my pleasure. The tool seems pretty handy.

The PR is here #454 

It should add correct commands for Fedora and macOS.
