### ISSUE TITLE
Cannot install ipython

### ISSUE THREAD

**Issue by JiniousChoi** [asdf-vm/asdf#476]
### Steps to reproduce

Tell us what actions you performed before the issue occurred
```
$ asdf current
python         3.7.2   (set by /Users/jinchoi/.tool-versions)

$ python -V
Python 3.7.2

$ pip -V
pip 19.0.3 from /usr/local/opt/asdf/installs/python/3.7.2/lib/python3.7/site-packages/pip (python 3.7)

$ pip install ipython
Requirement already satisfied: ipython in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (7.3.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (40.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (4.3.2)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (2.0.9)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (4.6.0)
Requirement already satisfied: decorator in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (4.3.2)
Requirement already satisfied: pygments in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (2.3.1)
Requirement already satisfied: appnope; sys_platform == "darwin" in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (0.1.0)
Requirement already satisfied: pickleshare in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (0.7.5)
Requirement already satisfied: jedi>=0.10 in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (0.13.3)
Requirement already satisfied: backcall in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from ipython) (0.1.0)
Requirement already satisfied: six in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from traitlets>=4.2->ipython) (1.12.0)
Requirement already satisfied: ipython-genutils in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from traitlets>=4.2->ipython) (0.2.0)
Requirement already satisfied: wcwidth in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython) (0.1.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython) (0.6.0)
Requirement already satisfied: parso>=0.3.0 in /usr/local/Cellar/asdf/0.5.1/installs/python/3.7.2/lib/python3.7/site-packages (from jedi>=0.10->ipython) (0.3.4)

$ which ipython
<nothing shows up>

$ ipython
-bash: ipython: command not found
```

### Expected behavior

`pip install ipython` should install actual executable `ipython` command.

### Actual behavior

Supposedly, some deps are installed/checked and that's all. The actual `ipython` doesn't exist nowhere

### Environment

**OS**:
MacOS MBP

**asdf version**:
version: v0.5.1

**Comment by Stratus3D** [comment]
Did you try running `asdf reshim` after the `pip install`? The shim might be missing. If that doesn't fix the issue you may want to report this on https://github.com/danhper/asdf-python/issues.

**Comment by JiniousChoi** [comment]
This command,`asdf reshim python 3.6.5`, resolved the issue. Thanks alot.
Before closing this issue, what does this `reshim` actually do?

**Comment by Stratus3D** [comment]
Shims are scripts asdf places in a special directory on your path. They are named the same as the executables your plugin have installed, but instead of being the actual executables, they contain some metadata and a small snippet of shell code. When you execute something, say `python`, you are actually invoking the shim named `python`. It then invokes some code to figure out the right version of python to use, and then gets out of the way by `exec`ing the right version of python for you.

**Comment by Stratus3D** [comment]
Sometimes shims aren't created or get removed, which is likely what happened here with `ipython`. In such cases a simple `asdf reshim` should fix your issue. Most likely shims are not created for python when the `pip` command is run, so going forward you'll probably want to run `asdf reshim` after installing something with `pip`.

**Comment by zachliu** [comment]
Just a note here, I had exact the same issue with pip-installing `bpython` under `asdf`, the solution is identical: 
```
asdf reshim python 3.7.4
```
:rocket:

**Comment by wes-brooks** [comment]
I had the same problem but a different solution. In my case, I was trying to install `ipython` and the shim was in the right place. I'm on a Mac, which now run `zsh`, and had to rehash the command location with `rehash`. See: [https://stackoverflow.com/questions/36543707/why-does-zsh-ignore-the-path-entry-order](https://stackoverflow.com/questions/36543707/why-does-zsh-ignore-the-path-entry-order)
