### ISSUE TITLE
Wrong ordering for versions

### ISSUE THREAD

**Issue by dc0d** [asdf-vm/asdf#478]
### Steps to reproduce

Anybody can help with `asdf`? Here is the problem:

We have:

```
$ asdf list
elixir
  1.5.3-otp-19
  1.5.3
  1.5
  1.7.3-otp-21
  1.7.4-otp-21
  1.7.4
erlang
  19.3
  20.2
  21.0
  21.1.1
  21.1
ruby
  2.3.1
```

And after doing this:

```
$ asdf local erlang 21.1
```

We have our tools set:

```
$ cat .tool-versions
elixir 1.7.4-otp-21
erlang 21.1
```

But it can not find the `erl` command:

```
$ iex -S mix
asdf: No version set for command erl
you might want to add one of the following in your .tool-versions file:

erlang 19.3
erlang 20.2
erlang 21.0
erlang 21.1.1
```

IMO this is a bug with `asdf` because if you look at the output of list sub-command, erlang `21.1` comes after erlang `21.1.1` and that can be the reason for this. And if erlang `2.1.1` is set, it works.

All I have done was `brew update`/`brew upgrade`.

### Expected behavior

Should work with erlang `21.1`.

### Actual behavior

It says it can not find the `erl` command, unless the erlang version is set to `21.1.1`.

Edit: Before `brew update`/`brew upgrade` it was working fine. But I had not checked the version. So most likely it is something introduced in this version.

### Environment

**OSX**:

asdf version: **0.7.0**:

**Comment by heydonovan** [comment]
Can you help me recreate the issue? I'm not familiar with erlang:

```
$ asdf local erlang 21.1

$ cat .tool-versions
erlang 21.1

$ asdf list
erlang
  21.1.1
  21.1

$ which erl
/Users/heydonovan/.asdf/shims/erl

$ erl
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Eshell V10.1  (abort with ^G)
1>
```

**Comment by dc0d** [comment]
Thanks for the reply!

Maybe I am missing something. But this behavior is consistent on my machine. I will try to play around with things and provide updates if found something new.

**Comment by danhper** [comment]
Hi! Did you try with the latest version, 0.7.1?

**Comment by dc0d** [comment]
Sorry for the late response.

Yes I have tried 0.7.1 and it did not work.

What did work was uninstalling all Erlang and Elixir via asdf and reinstall them.

Because I can not reproduce this, I close it.
