### ISSUE TITLE
Can't run iex

### ISSUE THREAD

**Issue by khipukamayuq** [asdf-vm/asdf#485]
### Steps to reproduce

Tell us what actions you performed before the issue occurred
I'm aware this might not be asdf, but posting just in case. Also, apologizing in advance in case it's actually not and anyone's time is wasted; I'm sorry. I've migrated my employer provided Ubuntu 18.10 device to another for an unrelated issue. I had working elixir, erlang, mix, iex, and other related such things working without issue previously. On the new device I had some issue getting asdf running from my migrated files and ended up re-cloning and succeed in using asdf for installing Erlang 21.0, and the Elixir 1.7.4 I was previously using. When I got around to trying to start `iex` I was met with:
```~/.asdf/installs/erlang/21.0/erts-10.0/bin/beam.smp: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory```
I've searched answers that point me toward installing the missing packages, but, in an unrelated issue, my system doesn't have(?!) the requisite `apt-file` package for hunting down where the above file came from (so that it might be reinstalled). 

### Expected behavior

Tell us what should have happened
`iex` should have started.

### Actual behavior

Tell us what happened instead
`home/adamurteaga/.asdf/installs/erlang/21.0/erts-10.0/bin/beam.smp: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory`

### Environment

**OS**:
Ubuntu 18.10

**asdf version**:
0.6.3

**Comment by danhper** [comment]
I suspect the package containing the shared object was upgraded and Erlang therefore needed to be reconfigured and recompiled to use the correct shared objects. 
Indeed, Ubuntu 18.10 only seems to have libtinfo6, which explains the issue.
I don't think this is really related to asdf so I think we can close. Please comment if you think there is anything we should improve on our side.
