### ISSUE TITLE
Comments in .tool-versions file

### ISSUE THREAD

**Issue by axelson** [asdf-vm/asdf#489]
### Steps to reproduce

With a `.tool-versions` like this:
```
# Note: Update Dockerfile and elixir_buildpack.config as well
elixir 1.8.1-otp-21
erlang 21.2.4
```

### Expected behavior

The specified elixir and erlang versions should be installed and lines beginning with `#` should be ignored.

### Actual behavior

Running `asdf install` fails
```
$ asdf install
No such plugin: #
```

But `asdf current` works:
```
jason@Jasons-MacBook-Pro-2 ~/n/messages> asdf current
elixir         1.8.1-otp-21(set by /Users/jason/my_app/.tool-versions)
erlang         21.2.4  (set by /Users/jason/my_app/.tool-versions)
```

### Environment

**OS**: 10.13.6

**asdf version**: `v0.7.0`

**Comment by danhper** [comment]
I think this is a good idea.
If someone would like to tackle this one, it would be great.
