### ISSUE TITLE
[improvement] shell command

### ISSUE THREAD

**Issue by troydm** [asdf-vm/asdf#49]
there are local and global commands that give you ability to set local or global version however sometimes we need to temporary set version for currently running shell session. 
So what I propose is addition of shell command

**Comment by tuvistavie** [comment]
I agree this is indeed a handy feature.
I am not sure what would be the best way to do it, but allowing an `ASDF_${PLUGIN}_VERSION` env variable seems pretty straightforward.

**Comment by HashNuke** [comment]
@tuvistavie had the same idea about ENV vars. Forgot somewhere along the way.
