### ISSUE TITLE
Shims are always used when command is run from another asdf environment

### ISSUE THREAD

**Issue by pmk1c** [asdf-vm/asdf#505]
### Steps to reproduce

Install plugin `asdf-ruby` and install any Ruby version.
Install plugin `asdf-nodejs` and install any npm version.
Run `npm install which` to install weirdly named `which` npm package
Run `irb` and type `` `which sh` ``

### Expected behavior

It should run `which sh` on the host which returns the path to the `sh` binary.

### Actual behavior

It runs `asdf exec which sh` and says: 

> asdf: No version set for command which
> you might want to add one of the following in your .tool-versions file:
> 
> nodejs 9.11.2

### Environment

**OS**: Fedora Linux

**asdf version**: 0.7.0 / head (tried both with reshimming inbetween)

This is a weird error, since running `which` in a terminal returns something else, than running `` `which` `` in an IRB.

I'm also not sure if it was a great idea to name a npm library `which` and provide a binary called that, but that's another topic :wink:

**Comment by robacarp** [comment]
related: https://github.com/danhper/asdf-python/issues/54

**Comment by DanCardin** [comment]
I have this problem in pyenv today as well. It would be ideal if you considered something like this solution https://github.com/pyenv/pyenv/pull/1185 (which is unfortunately not in pyenv) where shims are only available and only shadow binaries outside your env when you are actively in an env.

**Comment by Stratus3D** [comment]
@pmk1c if you have run `asdf reshim` and are in a directory with the nodejs version that has the `which` package installed you should see the same output when running `which sh` in your shell and in Ruby irb. Can you try upgrading to the latest version of asdf and see if you now get consistent behavior?

Unfortunately we can't really do anything about npm's `which` package. I'd certainly suggest not using it, and avoiding packages that rely on it. It's bad practice to replace commands that are pre-installed on the user's OS.

**Comment by pmk1c** [comment]
Yes I have consistent behaviour now.
