### ISSUE TITLE
plugin-test can't be run with asdf installed via brew

### ISSUE THREAD

**Issue by quiqua** [asdf-vm/asdf#509]
### Steps to reproduce

- Install via homebrew on mac os x: `brew install asdf`
- Add `source /usr/local/opt/asdf/asdf.sh` to `.zshrc` file
- Clone https://github.com/skotchpine/asdf-java 
- Run `asdf plugin-test java . 'java -version'

### Expected behavior

The command runs without errors

### Actual behavior

When installing via homebrew on mac os x: `brew install asdf` and adding `source /usr/local/opt/asdf/asdf.sh` to my `.zshrc` file, I am unable to run `asdf plugin-test` properly.

I am currently working on a fix for https://github.com/skotchpine/asdf-java and cloned that repo locally.
When testing I get the following output:

```
asdf plugin-test java . 'java -version'
fatal: repository '/usr/local/opt/asdf/.git' does not exist
/usr/local/opt/asdf/lib/commands/plugin-test.sh: line 49: /var/folders/5d/2m5v9bpx5fd6rc_fbfz1ffk80000gn/T/asdf.XXXX.78cJ5jmW/asdf.sh: No such file or directory
Cloning into '/var/folders/5d/2m5v9bpx5fd6rc_fbfz1ffk80000gn/T/asdf.XXXX.78cJ5jmW/plugins/java'...
done.
```

The errors here are I assume are due to not having a git repo available at that path:
```
➜ cd /usr/local/opt/asdf

local/opt/asdf
➜ ls -la
total 112
drwxr-xr-x  24 marcel  admin   768 Apr  5 09:39 .
drwxr-xr-x   3 marcel  admin    96 Apr  5 09:39 ..
drwxr-xr-x   3 marcel  admin    96 Apr  5 09:39 .brew
-rw-r--r--   1 marcel  admin  7998 Mar 31 22:15 CHANGELOG.md
-rw-r--r--   1 marcel  admin  1686 Mar 31 22:15 CONTRIBUTING.md
-rw-r--r--   1 marcel  admin   917 Apr  5 09:39 INSTALL_RECEIPT.json
-rw-r--r--   1 marcel  admin  1082 Mar 31 22:15 LICENSE
-rw-r--r--   1 marcel  admin  1574 Mar 31 22:15 README.md
-rw-r--r--   1 marcel  admin     7 Mar 31 22:15 VERSION
-rw-r--r--   1 marcel  admin  3027 Mar 31 22:15 Vagrantfile
-rw-r--r--   1 marcel  admin   723 Mar 31 22:15 asdf.fish
-rw-r--r--   1 marcel  admin  1586 Mar 31 22:15 asdf.sh
-rw-r--r--   1 marcel  admin   992 Mar 31 22:15 ballad-of-asdf.md
drwxr-xr-x   3 marcel  admin    96 Apr  5 09:39 bin
-rw-r--r--   1 marcel  admin   102 Mar 31 22:15 defaults
drwxr-xr-x  21 marcel  admin   672 Mar 31 22:15 docs
drwxr-xr-x   3 marcel  admin    96 Apr  5 09:39 etc
-rw-r--r--   1 marcel  admin  2261 Mar 31 22:15 help.txt
drwxr-xr-x   4 marcel  admin   128 Mar 31 22:15 lib
drwxr-xr-x   3 marcel  admin    96 Apr  5 09:39 libexec
-rwxr-xr-x   1 marcel  admin   257 Mar 31 22:15 lint.sh
drwxr-xr-x   4 marcel  admin   128 Mar 31 22:15 release
drwxr-xr-x   3 marcel  admin    96 Apr  5 09:39 share
drwxr-xr-x  23 marcel  admin   736 Mar 31 22:15 test
```

https://github.com/asdf-vm/asdf/blob/6e136a1d6d252cb9f5589a0d0a35e8b12cc55f9c/lib/commands/plugin-test.sh#L41-L44

### Environment

**OS**: mac OS 10.14.3 

**asdf version**: v0.7.1

**Comment by klundberg** [comment]
I ran into this while working on a new plugin the other day. Would an acceptable solution be to just run `cp -r "$ASDF_DIR/" "$TEST_DIR"` instead of doing a git clone? That allowed me to get past that issue, but i'm not certain if there's any other considerations that would make that not ideal (if it would copy all the installed packages as well, for instance)

**Comment by Stratus3D** [comment]
I think copying is fine, assuming we copy specifically what we need. I don't remember what files in the root dir are needed, but the source code is mostly contained to the `bin` and `lib` directories.
