### ISSUE TITLE
Make dependencies installation more straightforward 

### ISSUE THREAD

**Issue by danhper** [asdf-vm/asdf#512]
As discussed a little in #511, it is not always easy to get all the dependencies right for a plugin.

Although I have been using asdf and asdf-python for a while, I often forget to install tk or sqlite dev libraries before compiling Python and find myself having to recompile it later on.

I think this process could be improved, although I am not really sure how yet.
I agree with @Stratus3D that dependencies should be part of the plugin rather than asdf core.

Here are the main difficulties I can think about

* We have tons of plugins, so dependencies must be maintained at the plugin level
* Too many different platforms, so it is not reasonable to hope that every plugin maintainer will maintain a list as comprehensive as the one found in [pyenv deps page](https://github.com/pyenv/pyenv/wiki#suggested-build-environment). I do think it is fine if we focus on the most popular platforms though (macOS and Ubuntu?)
* Many plugins will have optional dependencies. For example [asdf-erlang](https://github.com/asdf-vm/asdf-erlang)
* Some plugins dependencies may, or may not, be handled by system package managers. For example, in the case of [adsf-elixir](https://github.com/asdf-vm/asdf-elixir), some people might want to install Erlang through their package manager while others might want to do so with asdf.

Most of these are not major blockers but things that I think we should at least consider if we are going to try to do something about this issue.

**Comment by jthegedus** [comment]
On this topic and in case other find this useful, my plugins (eg [`asdf-gcloud`](https://github.com/jthegedus/asdf-gcloud)) have a `check_dependencies` function that loops over a text file of my dependencies and runs `command -v` for each. On `plugin add` it warns of missing dependencies. On `install` it exits if there are missing dependencies.

- https://github.com/jthegedus/asdf-gcloud/blob/5a74763ba33731c076b615827f67a9e4ed5cf658/lib/utils.bash#L28
- https://github.com/jthegedus/asdf-gcloud/blob/master/lib/dependencies.txt

The main motivation was to stop failures on installation leaving a bad state, though I think this can be a better way for people to find the dependencies than what is usually a partial list in the README.

Originally posted by @jthegedus in #511 [(comment)](https://github.com/asdf-vm/asdf/issues/511#issuecomment-605539567)

**Comment by Stratus3D** [comment]
Interested in everyone's input on the specification I wrote for the plugin `bin/documentation` callback in my open PR - https://github.com/asdf-vm/asdf/pull/757.
