### ISSUE TITLE
`asdf list` shows blank lines instead of version numbers

### ISSUE THREAD

**Issue by knutsenm** [asdf-vm/asdf#513]
### Steps to reproduce

```
[13:15:57 - 19-04-12] /Users/knutsen % asdf list
nodejs
  
ruby
  
  
  
  
  
  
  
[13:16:00 - 19-04-12] /Users/knutsen % 
```

### Expected behavior

```
[13:17:32 - 19-04-12] /Users/knutsen % asdf list
nodejs
  10.9.0
ruby
  2.3.0
  2.3.4
  2.3.5
  2.3.8
  2.4.4
  2.5.1
  2.5.3
[13:17:38 - 19-04-12] /Users/knutsen % 
```

I can get the expected behavior by removing the trailing slash from the `ls` command in `list_installed_versions()`:

```
diff --git a/lib/utils.sh b/lib/utils.sh
index 4be0d79..cd37161 100644
--- a/lib/utils.sh
+++ b/lib/utils.sh
@@ -65,7 +65,7 @@ list_installed_versions() {
 
   if [ -d "$plugin_installs_path" ]; then
     # shellcheck disable=SC2045
-    for install in $(ls -d "${plugin_installs_path}"/*/ 2>/dev/null); do
+    for install in $(ls -d "${plugin_installs_path}"/* 2>/dev/null); do
       basename "$install" | sed 's/^ref-/ref:/'
     done
   fi
```

...but I don't understand why that should matter; `basename` is supposed to ignore trailing slashes in pathnames, and whatever I try manually works as expected.

### Actual behavior

See above in "Steps to reproduce"

### Environment

**OS**: macOS High Sierra 10.13.6 with all available patches as of today

**asdf version**: v0.7.1

Also note, I'm running https://github.com/thoughtbot/laptop and so have zsh as my shell.

**Comment by Stratus3D** [comment]
Thanks for the detailed report @knutsenm. I find it interesting that shellcheck explicitly warns against iterating on the output of `ls` and that check is disabled here (https://github.com/koalaman/shellcheck/wiki/SC2045). It's also interesting that we are using the `-d` flag and also have a trailing slash. We shouldn't need both.

**Comment by Stratus3D** [comment]
Can you give this a try when you get a chance? https://github.com/asdf-vm/asdf/pull/525

**Comment by Stratus3D** [comment]
I've gone ahead and merged my PR. To test out the changes I just merged to master run `asdf update --head`.

**Comment by knutsenm** [comment]
Works for me now; thanks!
