### ISSUE TITLE
Plugins not reading legacy files

### ISSUE THREAD

**Issue by cdfa** [asdf-vm/asdf#516]
Plugins don't seem to read their legacy version file. Tested with nodejs and ruby.

### Steps to reproduce

* Follow the asdf installation instructions for fish.
* `echo "legacy_version_file = yes" > ~/.asdfrc`
* `echo "8.12.0" > .nvmrc`

### Expected behavior

```
$ node -v
v8.12.0
```

### Actual behavior

```
$ node -v
asdf: No version set for command node
you might want to add one of the following in your .tool-versions file:

nodejs 10.15.3
```

### Environment

**OS**: 4.19.34-1-MANJARO GNU/Linux

**asdf version**: 59a9c032676c8d7b2f1bb7d13a2dfe46ee822064

**fish version**: 3.0.2

**Comment by danhper** [comment]
I did not manage to reproduce the issue.
I know it was broken in asdf 0.7.0 but it should be fixed at the commit you are showing.
Does `asdf --version` indeed returns `0.7.1`

**Comment by cdfa** [comment]
I noticed the logs of the earlier issue, but I really am on `0.7.1`. I think it's quite possible something else from my setup is interfering. Do you have any suggestions for debugging `asdf` on my machine?

**Comment by danhper** [comment]
Could you please try to run `asdf reshim` to see if that helps?
If it does not help, could you send the content of  `~/.asdf/shims/node` and the result of `asdf list nodejs` please?
Thanks, and sorry for the trouble.

**Comment by cdfa** [comment]
Sadly, `asdf reshim` didn't help.
`~/.asdf/shims/node`:
```
#!/usr/bin/env bash
# asdf-plugin: nodejs 10.15.3
exec /home/cdfa/.asdf/bin/asdf exec "node" "$@"
```
```
> asdf list nodejs
  10.15.3
  8.12.0
```

I did discover something else interesting. After `echo "10.15.3" > ~/.nvmrc`, running `node -v` just gives `v10.15.3`, so `asdf` does pick up on the legacy version file if it's in my home directory.
Also, running `asdf current` in my project folder does show `8.12.0`.
Somehow, `asdf` does pick up on the file in a project directory, but only uses the node version defined in `~/.nvmrc`

**Comment by danhper** [comment]
For some reason asdf does not seem to detect the node executable for node 8.12.
Could you check that `node` is indeed present in `~/. asdf/installs/nodejs/bin` please?
If it is not, there might have been an issue when installing node 8.12 so uninstalling and reinstalling should help.
Thanks for your help debugging this.

**Comment by cdfa** [comment]
Yes, `node` is present in that directory, but this made me think: should `asdf install nodejs 8.12.0` be in the "step to reproduce" for this issue. What actually is the expected behaviour when it's not installed?
I also tried putting `8.12.0` in `~/.nvmrc` and then `node -v` does say `v8.12.0`.

**Comment by danhper** [comment]
Hmm, given the content of `~/.asdf/shims/node`, I think that it should not work at all with `v8.12.0` no matter the where the `~/.nvmrc` file is placed.
Is there any chance you could try to reproduce this inside Docker, or anything which would be easy to replicate please? It would simplify the debugging process a lot.
Thanks again.

**Comment by cdfa** [comment]
Hmm, I don't have much experience with Docker and I don't really know what to include in the image, because it does work on your machine. Because of this, it might also get very big.

One small correction (but I don't think it makes a difference): `~/. asdf/installs/nodejs/bin` does not exist for two reasons:
1. There's a space in the path
2. I think you meant `~/. asdf/installs/nodejs/<node-version>/bin`

There's 2 other options for debugging I can think of:
1. You provide me with some instructions on how to debug `asdf` itself. I don't mind going with a debugger or something like that.
2. We schedule a `teleconsole` session. I saw you have a twitter account listed on your profile so I could PM you there. I have a backup of most of my stuff and if you would misbehave, I think kicking you out would be quick enough. You still wouldn't have your normal development environment though.

**Comment by cdfa** [comment]
I just updated to `v0.7.3` and everything seems to be working now.
