### ISSUE TITLE
Run command without arguments gives error

### ISSUE THREAD

**Issue by starwing** [asdf-vm/asdf#522]
### Steps to reproduce

Install rust:
```sh
asdf plugin-add rust
asdf install rust stable
```

Run rust without arguments:
```sh
rustc
```

### Expected behavior

print out help messages of `rustc`.

### Actual behavior

```sh
/Users/lilithgames/.asdf/lib/commands/shim-exec.sh: line 21: shim_args[@]: unbound variable
```

### Environment

**OS**: macOS 10.14.4

**asdf version**: v0.7.1, install from git.

P.S. `lua` installed from `asdf` works well without arguments.

**Comment by Stratus3D** [comment]
@starwing so is this only an issue with Rust or the Rust plugin?

**Comment by calebmeyer** [comment]
Opened an issue over there. I believe this can be closed, @starwing you okay with that?

**Comment by starwing** [comment]
okay, I will watch that issue. Thanks!
