### ISSUE TITLE
Plugin shell completions

### ISSUE THREAD

**Issue by trnubo** [asdf-vm/asdf#529]
One of the feature in the main readme is "completion scripts managed by the plugin, not you!" however shell completion doesn't work for any of the plugins I'm currently using and I also can't find any related documentation. (shell completion for the `asdf` command its self works fine).

Is this actually implemented if so could you point me in the direction of documentation, source code or an example plugin that does setup shell completion? Or have a miss interpreted the feature?

### Steps to reproduce

`COMMAND <TAB>`

### Expected behavior

I expected the plugin to setup completion somehow.

### Actual behavior

No completion scripts are installed.

### Environment

**OS**: Fedora 30

**asdf version**: v0.7.2

**Shell**: GNU bash, version 5.0.7(1)-release (x86_64-redhat-linux-gnu)

Thanks,

**Comment by Stratus3D** [comment]
Can you please provide more specifics? `COMMAND <TAB>` is vague. Please provide the command you ran, along with the output you got and the output you expected.

I'm not sure if by "the plugin" you mean asdf itself on an individual asdf plugin.

**Comment by trnubo** [comment]
Maybe not the best example but I use kubectl quite a bit plus it have a bash completion function.

Current behavior

```
kubectl <TAB><TAB>
```

_only the directory contents display_

Expected

```
kubectl <TAB><TAB>
alpha          api-resources  apply          auth           certificate    completion     convert        cp             delete         drain          exec           expose         label          options        plugin         proxy          rollout        scale          taint          uncordon       wait
annotate       api-versions   attach         autoscale      cluster-info   config         cordon         create         describe       edit           explain        get            logs           patch          port-forward   replace        run            set            top            version
```

This can be achieved by

```
. <(kubectl completion bash)
kubectl <TAB><TAB>
alpha          api-resources  apply          auth           certificate    completion     convert        cp             delete         drain          exec           expose         label          options        plugin         proxy          rollout        scale          taint          uncordon       wait
annotate       api-versions   attach         autoscale      cluster-info   config         cordon         create         describe       edit           explain        get            logs           patch          port-forward   replace        run            set            top            version
```

asdf itself has bash completion and that works

```
asdf <TAB><TAB>
current          global           help             install          list             list-all         local            plugin-add       plugin-list      plugin-list-all  plugin-remove    plugin-update    reshim           shell            uninstall        update           where            which
```

One of the items on the asdf README.md is

> Why use asdf-vm?
> ...
> completion scripts managed by the plugin, not you!

However I haven't seen any plugin that actually manages/sets up bash completion or how it is supported by asdf.

Am I misinterpreting the feature or are the plugins I'm using just not doing bash completion or am I doing something else wrong?

**Comment by danhper** [comment]
I was not aware we were making such a claim in the README. I do not think this is currently a feature, although I think it would be something worth considering as we have quite a few plugins which would benefit from this.
Unless I am missing something, I think for now we should remove the line from the README.
@Stratus3D @jthegedus Any opinion?

**Comment by miguel-amaral** [comment]
I am developing a plugin and stumbled into this issue while looking for documentation on how to support shell completion.

Is this a feature? or should it be removed from the README list?

**Comment by Stratus3D** [comment]
@danhper I'd say we should remove that line.

Plugins don't support tab completion for commands they install. That's up to the software they install. If `kubectl` doesn't provide tab completion using the asdf plugin won't change anything.

I also don't think we should support tab completions for arbitrary commands either. We should only support completions for `asdf ...` commands.

**Comment by jthegedus** [comment]
Sorry all, a mistake during the big docs rewrite. I cannot remember exactly what I may have meant when writing it as this is clearly not a feature we support.
