### ISSUE TITLE
Enhancement: asdf plugin-update --all could be parallel

### ISSUE THREAD

**Issue by mattysweeps** [asdf-vm/asdf#530]
Each plugin in `asdf plugin-update --all` could be updated in parallel, making the command much quicker.

Each asdf plugin is a git repository. The same is true for [Plug](https://github.com/junegunn/vim-plug): the vim plugin manager. See [how they update their git repos in parallel](https://raw.githubusercontent.com/junegunn/i/master/vim-plug/40-in-4.gif) which makes for a nice user experience.

**Comment by Stratus3D** [comment]
This seems like a good idea. Only issue we may run into while doing this is handling the output in a sane way. Right now we just send the Git output to STDOUT, but if we've got multiple updates running concurrently we'd get jumbled output. We'll need to figure out how to keep the output sequential while making the updates concurrent. I think it should be easy enough, just capture the output from each update in a variable, once updates are finished print the output from each plugin to STDOUT in order.
