### ISSUE TITLE
asdf populating my .zshrc

### ISSUE THREAD

**Issue by yofriadi** [asdf-vm/asdf#536]
I don't know how this happen, but today when I open my `.zshrc` it has repeated code like this
```
. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash
```
on the bottom of my `.zshrc`

os: Linux
asdf version: v0.7.2

**Comment by Stratus3D** [comment]
How many times was the code repeated? The install commands listed on the website add these lines. If you run the commands multiple times, the lines will get added multiple times. These two lines should not be duplicated in your `.zshrc` or `.bashrc`, but if they are it shouldn't break asdf.

**Comment by yofriadi** [comment]
Ah yeah after reading the code that add 2 lines, it obviously these 2 lines will be added everytime I run asdf. So is it necessary to add this 2 line for echoing ?
because this is somewhat nonsense to me

**Comment by Stratus3D** [comment]
asdf does not add these lines automatically. Only when you run the echo commands in the installation instructions are they added. I would just remove the duplicate lines from your zshrc.

**Comment by danhper** [comment]
@yofriadi I suspect you maybe copy-pasted the instructions containing the `echo` in your `~/.zshrc` instead of simply running them in your shell. Check if you have them, and if so delete them.
