### ISSUE TITLE
Multiple versions of any plugin fail to install with `asdf install`

### ISSUE THREAD

**Issue by kevinkjt2000** [asdf-vm/asdf#540]
### Steps to reproduce

On a brand new install of asdf, I tried to execute `cd ~ && asdf install` with this `~/.tool-versions` file:
```
python 3.7.3 2.7.16
```

### Expected behavior

```
python-build 3.7.3 /home/kevin/.asdf/installs/python/3.7.3
Downloading Python-3.7.3.tar.xz...
-> https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
Installing Python-3.7.3...
Installed Python-3.7.3 to /home/kevin/.asdf/installs/python/3.7.3
python-build 2.7.16 /home/kevin/.asdf/installs/python/2.7.16
Downloading Python-2.7.16.tar.xz...
-> https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tar.xz
Installing Python-2.7.16...
Installed Python-2.7.16 to /home/kevin/.asdf/installs/python/2.7.16
```

### Actual behavior

```
python-build 3.7.3 2.7.16 /home/kevin/.asdf/installs/python/3.7.3 2.7.16
python-build: definition not found: 3.7.3 2.7.16
```

### Environment

**OS**: Arch Linux

**asdf version**: 0.7.2

**Comment by Stratus3D** [comment]
This does not appear to be an issue with asdf itself. Please open an issue on https://github.com/danhper/asdf-python

**Comment by kevinkjt2000** [comment]
Thanks for the prompt feedback!  I have opened an issue there instead: https://github.com/danhper/asdf-python/issues/57

**Comment by danhper** [comment]
I think this is actually more of an issue with asdf than with asdf-python.
I think than when multiple versions are set for a plugin asdf should try to install all of them rather than to pass the raw version string to the plugin.
@Stratus3D What do you think?

**Comment by Stratus3D** [comment]
@danhper you are right. My mistake. Definitely an issue with asdf itself.

There also appears to be an issue with the output of `asdf current` when multiple versions are specified and one version is not installed.
