### ISSUE TITLE
ruby 2.6.3 installation stuck for hours at the readline step

### ISSUE THREAD

**Issue by jagdishadusumalli** [asdf-vm/asdf#542]
Am trying to install ruby 2.6.3 and it gets stuck for hours at the last line of the console output below
I am using the latest asdf 0.7.2 and also the ruby plugin is updated.
readline and all ruby system dependencies are already installed via homebrew

asdf install ruby 2.6.3
Downloading ruby-build...
Cloning into 'ruby-build-source'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 9765 (delta 21), reused 41 (delta 12), pack-reused 9712
Receiving objects: 100% (9765/9765), 2.08 MiB | 708.00 KiB/s, done.
Resolving deltas: 100% (6347/6347), done.
Note: checking out 'v20190615'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ac92ec0 Merge pull request #1306 from olivierlacan/2-7-0-preview1
ruby-build: use openssl from homebrew
Downloading ruby-2.6.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.bz2
Installing ruby-2.6.3...
ruby-build: use readline from homebrew

### Expected behavior

Ruby 2.6.3 should be installed successfully

### Actual behavior

Installation is stuck for more than 2-3 hours and had to CTRL-C

### Environment

**OS**: macOS 10.14.5

**asdf version**: 0.7.2

**Comment by Stratus3D** [comment]
This is not an issue with asdf itself. I've moved this issue to the asdf-ruby repository: https://github.com/asdf-vm/asdf-ruby/issues/125
