### ISSUE TITLE
asdf env adds an empty component to the path (has `:: in it)

### ISSUE THREAD

**Issue by vitaly** [asdf-vm/asdf#543]
### Steps to reproduce

`asdf env ANYTHING` is the easiest way to see it, but the problem is with anything that goes through asdf.  programs running from shims will have "" in the path, resulting in current directory being considered for running programs. this I is a serious security issue.

### Expected behavior

I expect path not to have empty components in it.

### Actual behavior

path contains double colon: `::`

### Environment

**OS**:

Mac, but I also tried it on an Ubuntu docker.

ASDF version : v0.7.2

I tracked the problem down to this line: https://github.com/asdf-vm/asdf/blob/d633db78bc55fec8f07ff5cff4ada111f4496225/lib/utils.sh#L503

`list_plugin_exec_paths` returns several lines. The last line will have an '\n' after it so the `tr` will replace it with a ':'. But `$PATH` already has a `:` before it, so we get 2 as a result.

I'm not sure what would be the right way to fix it, as I'm not sure about all the different ways `list_plugin_exec_paths` can be called.

Home this helps.

**Comment by Stratus3D** [comment]
Thank you for reporting. Definitely a bug with security implications.

**Comment by Stratus3D** [comment]
I've got a PR out for this now. I will merge it later this evening if the tests pass.

**Comment by Stratus3D** [comment]
@vitaly should be fixed now. Try updating to `v0.7.4` - https://github.com/asdf-vm/asdf/releases/tag/v0.7.4
