### ISSUE TITLE
asdf.fish not found

### ISSUE THREAD

**Issue by pablocrivella** [asdf-vm/asdf#545]
### Steps to reproduce

Installed `asdf` using homebrew.

### Expected behavior

Expected to find `~/.asdf/asdf.fish`

### Actual behavior

File not found

### Environment

**OS**:

MacOS Mojave
10.14.5 (18F132)

**asdf version**:

v0.7.2

**Comment by danhper** [comment]
Thanks for reporting. I think this is more an issue with the documentation. I suppose if you installed asdf with brew `asdf.fish` should be somewhere in `/usr/local`. I unfortunately do not have a mac to check so if someone using asdf with homebrew could confirm it would be great.

**Comment by pablocrivella** [comment]
Yeah I worked around this by sourcing `/usr/local/Cellar/asdf/0.7.2/asdf.fish`
But I thought maybe the right solution would be to copy that file to the `asdf` data folder on install.
What do you think?

This is the homebrew formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/asdf.rb

**Comment by lee-dohm** [comment]
I added `source (brew --prefix asdf)/asdf.fish` to my `config.fish` to cope with updates to the asdf version. I would have updated the docs, but I'm not sure if doubling the number of tabs in the "Add to your shell" section or adding a note at the bottom of that section would be the best approach.

**Comment by danhper** [comment]
For now, I would suggest that we do the same as for ZSH: https://github.com/asdf-vm/asdf/pull/537
If somebody could try it for fish and send a PR, it would be great!
