### ISSUE TITLE
Name confusion.

### ISSUE THREAD

**Issue by daveloyall** [asdf-vm/asdf#547]
[asdf](https://common-lisp.net/project/asdf/) started in 2001 and *every* Common Lisp program that is meant to be shared use it.  It is even used in programs that don't need to be shared.

Please reconsider #383.

**Comment by Stratus3D** [comment]
Besides the confusion, are there any other problems caused by this?

Outside of lisp, most people now think of this project when they hear "asdf".

**Comment by daveloyall** [comment]
Really?  Ok, I searched for `asdf` and `asdf software` in private browsing mode (which may reduce 'personalized results').  Ah, your software is now more popular than asdf, according to this method of measurement.  I see.

**Comment by Stratus3D** [comment]
Being that `asdf` is the name, the name of the command, and the name used in the source code I just don't think it would be worth the effort to rename it now. We try to use `asdf-vm` when we can.
