### ISSUE TITLE
Fresh install init script not executable 

### ISSUE THREAD

**Issue by ENG618** [asdf-vm/asdf#548]
### Steps to reproduce

* `brew install asdf`
* try to run init script with `"$(brew --prefix asdf)"/asdf.sh`

### Expected behavior

Should execute the file

### Actual behavior

error output `-bash: /usr/local/opt/asdf/asdf.sh: Permission denied`

### Environment

**OS**: MacOS 10.14.5

**asdf version**: v0.7.2

**Comment by Stratus3D** [comment]
You shouldn't be executing `asdf.sh`, you should be sourcing. The docs (https://asdf-vm.com/#/core-manage-asdf-vm?id=add-to-your-shell) show the script should be sourced like this - `. $(brew --prefix asdf)/asdf.sh`. Alternatively you can use the `source` command instead of the dot.
