### ISSUE TITLE
Add system version

### ISSUE THREAD

**Issue by tuvistavie** [asdf-vm/asdf#55]
> Someday we should support "system" version as a way to use OS-installed stuff. Very useful for Python and other stuff.

**Comment by tuvistavie** [comment]
> In general when "system" we could execute the actual system

This seems to be the simplest way to handle it.
Maybe something like this inside `asdf-exec`

```
cmd_path =$(PATH=$(echo $PATH | sed -e "s|$(asdf_dir)/shims:\?||g") which EXECUTABLE)
```

I am not sure if there is a better way.

Another issue is to have the `list` command working.
I think plugins would need to know at least one binary they should contain,
for example for elixir it could be the `elixir` command, so that we can run `type -a elixir`
or something to know if it is installed.

Maybe for a first implementation, we could just forget about the `list` command and just treat the `system` version as a special case.

What do you think?

**Comment by HashNuke** [comment]
@tuvistavie Yes just the `system` version as a special case for now. The `PATH` modification is what I had in mind too.

**Comment by HashNuke** [comment]
@tuvistavie Been using Python a lot these days. I used the system version along with virtualenv to isolate dependencies for projects. Just realised virtualenv doesn't take me far.

**Comment by tuvistavie** [comment]
I have a working implementation here, I need to add tests before I send a PR. 

https://github.com/asdf-vm/asdf/commit/996a948ab52ac92c8d801456a203601cea43ca3a

**Comment by holmboe** [comment]
The inability to "pass through" to the system Python whenever a global or local asdf version is not set is currently a big problem for me. This feature would be hugely appreciated.

@tuvistavie can I help in any way?

**Comment by tuvistavie** [comment]
@holmboe Hi, I started the work in support-system-version branch, but did not really have time to work on it recently. If you want to give it a try and fix the eventual bugs, it would very welcome.
Thanks!

**Comment by Stratus3D** [comment]
This is the first time reading this issue. I think this will be a huge improvement over what we have now. I'vehad people complain to me they can't use asdf because of the lack of pass-through (I forget the exact scenario they were dealing with), but I think a simple pass-through to system versions as described here would work great. I also think it's safe for us to treat the system version as a special case and say "if you have other versions of X installed on your system, asdf won't be aware of them, but you can still use them if you specify 'system' as the version of X you want to use".

**Comment by PragTob** [comment]
I really gotta sign that this would be AMAZING to have - e.g. as currently with asdf-postgres there are very few places where I totally care about the postgres version and otherwise the system version would be ok to use/better as installing plugins normally is a bit of a pain

**Comment by vic** [comment]
I just did a very *tiny* and dumb plugin for managing vendor tools on my system which have *no asdf installer* https://github.com/vic/asdf-link

**Comment by Stratus3D** [comment]
I picked up where @tuvistavie left off with this, but I didn't get much further. I rebased the changes onto the latest master branch and wrote a few tests, but I still need to finish the tests. The changes are on this branch: https://github.com/Stratus3D/asdf/tree/support-system-version-with-tests
