### ISSUE TITLE
Features for asdf 0.8.0

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#552]
I'm beginning work on some new features that I hope to release in version 0.8.0. These are significant changes that have been needed for a while.

## Features

* Add support for `download` script in plugins. Right now plugins have an install script that download, configure, compile, and install the correct version of the tool. With support for a `download` script, asdf will check for the presence of the script, and when installing a version. It will invoke the `download` script to download the source into a new source directory (with sub directories for each version we have downloaded) and then invoke the `install` script to install the source. This will allow us to easily add flags to allow the user to keep the source for later use or edit it for manual configuration and patching before installation. If the `download` script is not present in a plugin then asdf will fallback to the current behavior and download and install the version all at once by just invoking the `install` script. The `download` script will be optional at first and eventually be required in some later version of asdf. This will address https://github.com/asdf-vm/asdf/issues/74, https://github.com/asdf-vm/asdf/issues/391,  asdf-vm/asdf-ruby#122
* Add another optional plugin callback script. Something named `dependencies` or `prerequisites` or `documentation`. When invoked the script would print some documentation listing the dependencies needed and other things that may be helpful to the user. Additionally this script could take a version as well, and provide version specific documentation. The documentation would only be printed when the user requested it, otherwise it would just clutter up the output. I'm not sure what the asdf command to execute the doc script. Maybe `asdf doc ruby`? And maybe have optional support for a version? `asdf doc ruby 2.6.1`? This will address #512

## Bugfixes

* Allow asdf to run with default configuration when no environment variables are set. asdf should default to `~/.asdf` when no `ASDF_DIR` variable is set. Ideally asdf should just work out of the box on any system that it is installed on without any manual config. This is currently not the case. This will fix https://github.com/asdf-vm/asdf/issues/428

**Comment by Stratus3D** [comment]
FYI @asdf-vm/core

**Comment by HashNuke** [comment]
This feature set looks good - especially the bug fix to make it work without the env var.

**Comment by jthegedus** [comment]
My thoughts on the handling of dependencies of plugins can be read in https://github.com/asdf-vm/asdf/issues/512

**Comment by Stratus3D** [comment]
I have merged #669 which addresses #74. I need to create two more PRs to complete these features - one to add a `downloads` command to asdf for managing downloads. And another for the plugin `documentation` callback script.

**Comment by jthegedus** [comment]
@Stratus3D How are you going with this? Is there anything you need from us/me?

**Comment by Stratus3D** [comment]
@jthegedus I'm going to request feedback on my changes as soon as I can get a WIP PR created. I should have it ready sometime today.

**Comment by Stratus3D** [comment]
I have created https://github.com/asdf-vm/asdf/pull/757, which is the last feature needed for the 0.8.0 release.

**Comment by Stratus3D** [comment]
Closing since these features have been added.
