### ISSUE TITLE
Fix PATH issue when using Ubuntu on Windows

### ISSUE THREAD

**Issue by jonheg** [asdf-vm/asdf#558]
### Steps to reproduce

$ asdf install java openjdk-11.0.1 
$ asdf install maven 3.6.1
$ java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

### Expected behavior
$ mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /home/jhe/.asdf/installs/maven/3.6.1
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /home/jhe/.asdf/installs/java/openjdk-11.0.1
OS name: "linux", version: "4.4.0-43-microsoft", arch: "amd64", family: "unix"

### Actual behavior
$ mvn --version
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

### Environment

**OS**: Windows 10 running Ubuntu 16
$ uname -a
Linux  4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**asdf version**: v0.7.3

**Comment by jonheg** [comment]
A quick fix:

diff --git a/lib/commands/where.sh b/lib/commands/where.sh
index 78420e2..1978722 100644
--- a/lib/commands/where.sh
+++ b/lib/commands/where.sh
@@ -27,7 +27,7 @@ where_command() {
 
   local install_path
   install_path=$(get_install_path "$plugin_name" "$install_type" "$version")
-
+  install_path="$(echo -e "${install_path}" | tr -d '[:space:]')"
   if [ -d "$install_path" ]; then
     echo "$install_path"
     exit 0

**Comment by Stratus3D** [comment]
@jonheg thanks for the diff, it would be great if we could narrow this down to a simple test case. Why is it solved by deleting spaces? Some valid paths do contain spaces, so we need to preserve them. Perhaps we missed quotes somewhere?

**Comment by jthegedus** [comment]
@jonheg A few questions:

- Does this issue still exist for you?
- Are you using WSL1 or WSL2?
- Which Windows Insider ring are you on?
- Did a newer version of `asdf` solve this issue?

I will attempt your reproduction on my own WSL machine, though I am unsure I will be able to reproduce as the permutations of versions between Windows10, WSL 1vs2 and Ubuntu in WSL along with `asdf` are unfathomable 😅 

My reproduction setup will be:

- Win10 19564.1005
- WSL2
- Ubuntu
```
➜ uname -a
➜ Linux e485-win 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
➜ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by jonheg** [comment]
Hi,

issue still persists, have not updated to asdf@latest yet, will do that monday.
I am running Windows 10 build 1909 running  WSL 1 using Ubuntu 16.
Official releases only, no insider builds.

**Comment by jthegedus** [comment]
@jonheg Thanks for getting back to me. Could you let me know how you go after the upgrade? Given WSL2 should replace WSL1 when it is released with the Win10 20H1 release I am uncertain we should spend effort fixing this, unless the fix is trivial. It may be a fix for the particular plugin that installs and set-up JAVA_HOME. I will try to reproduce one of my work machines with WSL1

**Comment by jonheg** [comment]
$ asdf update
Previous HEAD position was 58eaad8 Update version to 0.7.4
HEAD is now at 6207e42 Update version to 0.7.6
Updated asdf to release v0.7.6

# mvn --version
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

So, still fails.

**Comment by jthegedus** [comment]
Thanks for the update @jonheg

**Comment by jthegedus** [comment]
@jonheg Are you able to reproduce with WSL2 now that the Win10 2004 update is out?

**Comment by jonheg** [comment]
Hi,

yes installed WSL2 , using build 2004.
Still fails. 

jhe@DESKTOP-4G9K2Q9:~$ asdf list java
  zulu-musl-11.39.15

jhe@DESKTOP-4G9K2Q9:~$ java
/home/jhe/.asdf/lib/commands/command-exec.bash: line 28: /home/jhe/.asdf/installs/java/zulu-musl-11.39.15/bin/java: No such file or directory
jhe@DESKTOP-4G9K2Q9:~$ ls -al /home/jhe/.asdf/installs/java/zulu-musl-11.39.15/bin/java
-rwxr-xr-x 1 jhe jhe 8464 Apr  3 16:19 /home/jhe/.asdf/installs/java/zulu-musl-11.39.15/bin/java

jhe@DESKTOP-4G9K2Q9:~$ asdf version
v0.7.8-4a3e3d6

**Comment by jonheg** [comment]
Hi,

i installed bats and runned the tests. 
231 tests, 18 failures

So its clear that WSL2/Ubuntu 20  is not quite working.

**Comment by jthegedus** [comment]
I've moved my main machine to Win10 with WSL2 in the last few days and haven't seen any issues.

Details:
- OS: Win 10 Home
- Version: 2004
- WSL Version: 2

Can you show which 18 tests are failing for you?

**Comment by lukasmrtvy** [comment]
Can confirm, PATHs are broken in WSL2, Ubuntu 20.04, Win10 ( 2004 )

**Comment by jthegedus** [comment]
@jonheg Interesting find. On `master` (currently #d37e99a) I am getting `253 tests, 12 failures`:

```shell
 ✗ exports ASDF_DIR
   (in test file test/asdf_fish.bats, line 22)
     `")' failed with status 127
   /tmp/bats.8963.src: line 22: fish: command not found
 ✗ adds asdf dirs to PATH
   (in test file test/asdf_fish.bats, line 37)
     `")' failed with status 127
   /tmp/bats.8963.src: line 37: fish: command not found
 ✗ does not add paths to PATH more than once
   (in test file test/asdf_fish.bats, line 54)
     `")' failed with status 127
   /tmp/bats.8963.src: line 54: fish: command not found
 ✗ defines the asdf function
   (in test file test/asdf_fish.bats, line 69)
     `")' failed with status 127
   /tmp/bats.8963.src: line 69: fish: command not found
...
 ✗ asdf exec should pass all arguments to executable even if shim is not in PATH
   (in test file test/shim_exec.bats, line 42)
     `[ "$output" == "" ]' failed with status 127
...
 ✗ shim exec should fallback to system executable when specified version is system
   (in test file test/shim_exec.bats, line 205)
     `[ "$output" == "System" ]' failed with status 127
...
 ✗ shim exec should execute system if set first
   (in test file test/shim_exec.bats, line 234)
     `[ "$output" == "System" ]' failed with status 127
...
 ✗ shim exec doest not use custom exec-env for system version
   (in test file test/shim_exec.bats, line 278)
     `[ "$output" == "x System" ]' failed with status 127
...
 ✗ shim exec should remove shim_path from path on system version execution
   (in test file test/shim_exec.bats, line 334)
     `[ "$output" == "$ASDF_DIR/shims/dummy" ]' failed with status 127
   127 env: ‘Files/dotnet/:/mnt/c/Users/james/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/james/AppData/Local/Programs/Microsoft’: No such file or directory
...
 ✗ shim exec doesnt execute command if pre-hook failed
   (in test file test/shim_exec.bats, line 435)
     `[ "$output" == "hello no dummy world" ]' failed with status 127
...
 ✗ which should show path of system version
   (in test file test/which_command.bats, line 57)
     `[ "$status" -eq 0 ]' failed with status 127
...
 ✗ which should not return shim path
   (in test file test/which_command.bats, line 106)
     `[ "$status" -eq 1 ]' failed with status 127
```

I'll look into resolving this issue soon. My main machine is now Windows10 with WSL2 Ubuntu 20.04 so more motivation 😅

**Comment by CraigTreptow** [comment]
I don't really know what's going on yet, but I am able to pull this down  and see all the tests pass on my WSL2/Ubuntu 20.04 installation.

In the meantime, I have created a symbolic link to get going again.

```
~> scala --version
Scala code runner version 3.0.1 -- Copyright 2002-2021, LAMP/EPFL
~> ls -ltr .asdf/shims/bin
total 0
lrwxrwxrwx 1 craig craig 7 Aug 19 18:04 java -> ../java
~>
```

**Comment by jthegedus** [comment]
Unfortunately WSL2 in GitHub CI is yet to be available for us to regularly run tests. If anyone has some recent investigations they can share, please do.

**Comment by jthegedus** [comment]
No one has been able to share any new information or reproductions as to how `PATH` has issues in WSL in ~1 year, nor have there been any new commenters on this particular Issue.

As such, I will close this Issue.

If you are still having problems with the latest version of `asdf`, please open a new Issue following the bug Issue template to give us the most information possible, cheers.
