### ISSUE TITLE
support for prerelease versions

### ISSUE THREAD

**Issue by rrevanth** [asdf-vm/asdf#56]
This is kind of a enhancement request.Will it be possible to add support for git projects of elixir such as 1.3 since it's not showing in the vm.

**Comment by HashNuke** [comment]
@rrevanth We already do support installing from git branches/commits/tags
https://github.com/asdf-vm/asdf#the-tool-versions-file

```
# install a tag
asdf install elixir ref:v1.2.5

# install latest master
asdf install elixir ref:master
```
