### ISSUE TITLE
Installed swift on unbuntu but threw segmentation error

### ISSUE THREAD

**Issue by byteshiva** [asdf-vm/asdf#571]
### Steps to reproduce

```
asdf plugin-add swift 5.0.3
asdf install swift 5.0.3
```

### Expected behavior

swift should have installed 

### Actual behavior

Installed swift on ubuntu 19.04 but threw segmentation error, might be an issue with swift, but asdf shouldn't allow installation of any language that isn't compatible with the underlying os.
```
~ 
➜ swift
Segmentation fault
~ 
➜ echo $?
139
```

### Environment

**OS**:
ubuntu 19.04

**asdf version**:
0.7.4

**Comment by danhper** [comment]
Hi,
asdf has no knowledge of what software is compatible with what OS. It's the job of the plugin to ensure that the correct version is installed.
Please reopen this issue in the repository of the asdf-swift plugin.
