### ISSUE TITLE
Have to source ~/.zshrc everytime I switch nodejs versions

### ISSUE THREAD

**Issue by jlurena** [asdf-vm/asdf#572]
### Steps to reproduce

``` bash
$ node --version
v8.9.4
$ cat .tool-versions
nodejs 12.9.0
$ asdf current nodejs
12.9.0   (set by ...)
$ asdf reshim nodejs
$ source ~/.zshrc
$ node --version
v12.9.0
```

### Expected behavior

Shouldn't need to reshim manually. Version should be switched automatically.

### Actual behavior

I have to reshim and re-source zshrc

### Environment

**OS**: Mac Mojave 10.14.6

**asdf version**: 0.7.4

**Comment by jlurena** [comment]
My path only contains nodejs from asdf, no other node.

**Comment by jlurena** [comment]
You are right though, simply sourcing `source ~/.zshrc` again brings my node to the version in the `.tools-version` file

**Comment by Stratus3D** [comment]
@jlurena can you share your `.zshrc`? Or at least part of it?

**Comment by jlurena** [comment]
``` bash
# Path to your oh-my-zsh installation.
export ZSH=/Users/jlurena/.oh-my-zsh

# Source necessary files
source ~/.bash_profile

# STYLING
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="015"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir dir_writable vcs)
POWERLEVEL9K_DIR_PATH_SEPARATOR=$' \uE0B1 '
POWERLEVEL9K_VCS_HIDE_TAGS=true
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
DISABLE_AUTO_TITLE="true"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
# Highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

plugins=(
  git
  warhol
)

# Source for styling
source $ZSH/oh-my-zsh.sh
# Remove for gr plugin
unalias gr
# Remove left prompt
prompt_context() {}
# Change title of tab
setTerminalText () {
    # echo works in bash & zsh
    local mode=$1 ; shift
    echo -ne "\033]$mode;$@\007"
}
stt_both  () { setTerminalText 0 $@; }
stt_tab   () { setTerminalText 1 $@; }
stt_title () { setTerminalText 2 $@; }

export PATH="/Users/jlurena/Android/SDK/platform-tools:$PATH"
export PATH="/usr/local/opt/mysql@5.6/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.pyenv:$PATH"
export PATH="$HOME/bin:$PATH"

# NEEDS TO COME AFTER EXPORTING PYENV
eval "$(pyenv init -)"

# Yarn Version Manager. NEEDS TO COME AFTER ASDF (asdf loads node)

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

export YVM_DIR=/usr/local/opt/yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh
```

**Comment by Stratus3D** [comment]
I don't see any issues with the way you've loaded asdf, but I see you are sourcing `yvm.sh` after asdf. I'm not familiar with `yvm.sh`, but it could be affecting things. Have you tried removing it? Also what does `type -a node` return for you before and after sourcing the `.zshrc`?

**Comment by jlurena** [comment]
[YVM](https://yvm.js.org/docs/overview) is a version manager for Yarn. It needs to come after ASDF because it has a dependency on nodejs. 

But it seems you caught the issue :). YVM seems to be the culrpit! I'll close this

**Comment by jlurena** [comment]
I fixed it. Seems yvm.sh changes the path order and clobbers asdf. I'll create a PR with them

**Comment by Stratus3D** [comment]
Glad you were able to figure it out! Also, if you like asdf you could give asdf-yarn a try - https://github.com/twuni/asdf-yarn

**Comment by jlurena** [comment]
Ha, of course that plugin was created shortly after I migrated to to YVM
