### ISSUE TITLE
Missing Plugin Doesn't Generate a warning

### ISSUE THREAD

**Issue by delmendo** [asdf-vm/asdf#574]
I updated a project. It now includes a tool version for lua.  I haven't installed the lua plugin because I haven't needed it before.  I did an asdf install and it didn't warn me that I was missing the plugin.

### Steps to reproduce

$ cat .tool-versions 
nodejs 10.16.3
python 3.7.3
lua 5.2

$ asdf plugin-list
elixir
erlang
nodejs
python

$ asdf install
nodejs 10.16.3 is already installed
python 3.7.3 is already installed

### Expected behavior
$ asdf install
nodejs 10.16.3 is already installed
python 3.7.3 is already installed
lua  plugin not installed

### Actual behavior

nothing

It doesn't install or warn me about missing plugin

### Environment

**OS**: Linux - Ubuntu 19.04

**asdf version**: v0.7.4

**Comment by Stratus3D** [comment]
Not sure if we should consider this a bug or not, but it is important enough that we should address it as soon as possible. Thank you for reporting.

**Comment by jthegedus** [comment]
Related #968 

As I expressed in #968 I think we should consider this a bug. I think we should at least warn that a plugin is missing, but could be convinced we should hard error.

**Comment by threkk** [comment]
What could be the treatment? If you attempt to install a plugin that is not currently added, it should:

1. Install the missing plugin if available.
2. Give a warning and do nothing.
3. Give an error and stop.

**Comment by jthegedus** [comment]
>     3\. Give an error and stop.

2 or 3.

**Comment by threkk** [comment]
Option 2 is more user friendly: if a plug in is missing, just keep going and fix it later.
Option 3 is more pipeline friendly: if something is wrong, just stop it.

There are good arguments for either of them. Regarding a fix, I have briefly looked into it and I think I can fix it in short time once I have some free time (hopefully soon).
