### ISSUE TITLE
Installation of a non existing version of kubectl fails late (version not found 404)

### ISSUE THREAD

**Issue by qbaze** [asdf-vm/asdf#578]
### Steps to reproduce

asdf plugin-add kubectl
asdf install kubectl 1.14
kubectl

### Expected behavior

If binary with a given version doesn't exist (site returns 404) installation should fail with an appropriate message.

### Actual behavior

Although there is no such version and the site returns 404 the installation succeeds. It downloads a 404 html and fails when one tries to run a binary.

### Environment

**OS**: archlinux

**asdf version**: v0.7.4

**Comment by Stratus3D** [comment]
This issue is with asdf-kubectl, not asdf itself. Please open this issue on the asdf-kubectl issue tracker.
