### ISSUE TITLE
error using git-flow

### ISSUE THREAD

**Issue by yofriadi** [asdf-vm/asdf#581]
when releasing using git flow

```
➜ git-flow release finish 0.3.0
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
/Users/yofri/.asdf/lib/utils.sh: line 606: syntax error near unexpected token `('
/Users/yofri/.asdf/lib/utils.sh: line 606: `    grep -f <(get_shim_versions) <(preset_versions) | head -n 1 | xargs echo'
/Users/yofri/.asdf/lib/commands/shim-exec.sh: line 29: with_shim_executable: command not found
Could not check out master.
```

### Environment

**OS**: macOS catalina

**asdf version**: v0.7.4

**Comment by Stratus3D** [comment]
@yofriadi you'll need to give us more information about what is going on. How did you install asdf? How did you install git-flow? What asdf plugins are you using?

**Comment by yofriadi** [comment]
@Stratus3D yea, I used git-flow for my day to day development software, I did install asdf using either homebrew or curl (sorry I forget), I did install git-flow using homebrew and the plugin I using is go, nodejs and lua.

**Comment by Stratus3D** [comment]
@yofriadi I'm not really sure I understand what is going on. Something on your system seems to be invoking something managed by asdf, but I don't know what. Do you know what that git-flow command actually does? Does it run tests or build your project?

**Comment by yofriadi** [comment]
@Stratus3D git-flow is only for managing git development process, like committing, branching, release, hotfix, https://github.com/nvie/gitflow. in my case it broke in release and hotfix process, could you provide me on where to debug this thing?

**Comment by Stratus3D** [comment]
I don't understand what the issue is. If you installed git-flow via brew then asdf should not interfere with it. Maybe open an issue with git-flow?

**Comment by yofriadi** [comment]
ok, will check on it

**Comment by joelsouza** [comment]
@yofriadi @Stratus3D 

I have the same issue here with the combination of OSX, zsh, git flow and asdf

When running `git flow feature start foo` I get:

```
~/.asdf/lib/utils.sh: line 606: `    grep -f <(get_shim_versions) <(preset_versions) | head -n 1 | xargs echo'
``` 

For some reason that I don't realize, just removing those parenthesis from this line it will work.

There is no test for `with_shim_executable` method so I don't know if removing it will introduce new bugs.

**Comment by joelsouza** [comment]
@yofriadi @Stratus3D 

I have the same issue here with the combination OSX, zsh, git flow and asdf

When running `git flow feature start foo` I get:

```
~/.asdf/lib/utils.sh: line 606: syntax error near unexpected token `('
~/.asdf/lib/utils.sh: line 606: `    grep -f <(get_shim_versions) <(preset_versions) | head -n 1 | xargs echo'
~/.asdf/lib/commands/shim-exec.sh: line 29: with_shim_executable: command not found
``` 

So I change it to

```
grep -f '{<(get_shim_versions) <(preset_versions)}' | head -n 1 | xargs echo
``` 
There is no test for `with_shim_executable` method so I don't know if change it will introduce new bugs. Besides that other tests pass fine.

**Comment by Stratus3D** [comment]
Thanks @joelsouza. I've not had time to investigate this issue, but we definitely need tests for `with_shim_executable`. It may also be a refactoring opportunity as well, although that is pretty low priority right now.

I'd really like to have a test that generates this same error. If we can reproduce this with just asdf tests that will make fixing it pretty easy.

**Comment by joelsouza** [comment]
I will take a look into it further. I'll be back with more info on how to generates it

**Comment by jthegedus** [comment]
@joelsouza @yofriadi can you test the change in the PR from @JohnB in https://github.com/JohnB/asdf/pull/1 ?

**Comment by trinitytakei** [comment]
Hey guys, 

I'm also having this issue (Catalina 10.15.3, asdf v0.7.8-90b1e5d, hubflow) - right now I can't push my branch

`❯ git hf push
Fetching origin
Already up to date.
/Users/miatrinity/.asdf/lib/utils.bash: line 638: syntax error near unexpected token `('
/Users/miatrinity/.asdf/lib/utils.bash: line 638: `  grep -f <(get_shim_versions "$shim_name") <(preset_versions "$shim_name") | head -n 1 | xargs echo'
/Users/miatrinity/.asdf/lib/commands/command-exec.bash: line 31: with_shim_executable: command not found
error: failed to push some refs to 'git@github.com:miatrinity/routeines.git'`

Could you please point me to a temporary solution at least (obviously, it's quite disruptive not being able to `git hf push` - for the time being, I'm just doing 'vanilla' `git push`, but I'm so used to HF that it's still quite disrupting my workflow.

Thanks for your great work on asdf!

**Comment by tejanium** [comment]
I'm able to reproduce the issue, I'm using git-now https://github.com/iwata/git-now

I found that all git extensions setting up `export POSIXLY_CORRECT=1`

https://github.com/nvie/gitflow/blob/develop/git-flow#L78
https://github.com/iwata/git-now/blob/master/git-now#L51
https://github.com/datasift/gitflow/blob/master/git-hf#L84

to reproduce just run `POSIXLY_CORRECT=1 <ASDF_SHIM>` anywhere, in my case I'm using ruby so running `POSIXLY_CORRECT=1 ruby` give me the same error

**Comment by tejanium** [comment]
I'd really like to have a test that generates this same error. If we can reproduce this with just asdf tests that will make fixing it pretty easy.

```bats
@test "asdf exec should not crash when POSIXLY_CORRECT=1" {
  export POSIXLY_CORRECT=1

  echo "dummy 1.0" > $PROJECT_DIR/.tool-versions
  run asdf install

  run asdf exec dummy world hello
  echo $output
  [ "$output" == "This is Dummy 1.0! hello world" ]
  [ "$status" -eq 0 ]
}
```
