### ISSUE TITLE
Updating plugins: cd: /root/.asdf/plugins/*: No such file or directory when 

### ISSUE THREAD

**Issue by android10** [asdf-vm/asdf#582]
### Steps to reproduce

1 - Install asdf, let's say under a regular user: fernando
2 - In Arch Linux or other distros it is possible to run hooks after upgrading the system, in this case with pacman which runs as root, so when executing sudo asdf plugin-update --all
3 - Plugin list cannot be updated. 

### Expected behavior

```bash
Updating java...
Already up to date.
Updating nodejs...
Already up to date.
Updating python...
Already up to date.
Updating ruby...
Already up to date.
Updating sbt...
Already up to date.
Updating scala...
Already up to date.
```

### Actual behavior

An error ocurrs:
```bash
Updating *...
/home/fernando/.asdf/lib/commands/plugin-update.sh: line 11: 
cd: /root/.asdf/plugins/*: No such file or directory
```

### Environment

**OS**: Arch Linux

**asdf version**: v.0.7.4

### Pull Request
Here is the solution to the problem: #583

**Comment by Stratus3D** [comment]
If you are running as another user you'll need to set ASDF_DATA_DIR to the correct directory. e.g. `export ASDF_DATA_DIR=/home/otheruser/.asdf`.
