### ISSUE TITLE
How to get "clean" PATH when run subprocess?

### ISSUE THREAD

**Issue by shir** [asdf-vm/asdf#586]
I have a node.js application (let's call it "main") which starts other application ("child). I use asdf to start main application with node.js version 8.11.2. But for child application, I want to use own node.js version (10.16.3) via asdf. To make everything work I pass all env variables when I start child application including PATH. But after some experiments, I found that in the main application in the PATH env variable path to node.js binaries are before asdf path.

For example:   then I start the main application the PATH variable in shell looks like this:
```
/Users/user/.asdf/shims:/Users/user/.asdf/bin:/usr/local/bin:/usr/bin...
```
But within the main application when I pass env variable to subprocess PATH variable looks like this:
```
/Users/user/.asdf/installs/nodejs/8.11.2/bin:/Users/user/.asdf/installs/nodejs/8.11.2/.npm/bin:/Users/user/.asdf/shims:/Users/user/.asdf/bin:/usr/local/bin:/usr/bin...
```

Is there a way to get a clean PATH? Maybe some asdf utility with which I may call any command without addons to PATH? I've tried to use `asdf exec` but looks like it works only for shims.

My limitations:
- The main application should know nothing about asdf and works in any environment
- The child process command is configured and I may use any command in this configuration.
- But I don't start node directly in the child process, node is called somethere within child process and I can't  modify it.
- When I call child process directly using asdf it works as expected and with expected node.js version.

### Environment

**OS**: Mac OS X 10.15

**asdf version**: v0.7.4

**Comment by Stratus3D** [comment]
Do you have a shell? If so, `asdf shell` might work:

```
# Set the version for this shell
asdf shell nodejs 10.16.3
# then spawn child process in this same shell
exec child-process
```

Generally when working with asdf you shouldn't have to worry too much about PATH. Shims should always be on your PATH, it's just a matter of what version they end up executing.

**Comment by Stratus3D** [comment]
Closing since I don't think there is anything that needs to be done for this issue.
