### ISSUE TITLE
proposal: version change hooks

### ISSUE THREAD

**Issue by itaysk** [asdf-vm/asdf#587]
I'm using asdf with the Go plugin, and running a few Go versions. Go relies on env vars, `GOPATH` among others, to point to a location that is like the home of Go code. This is version dependent so the go asdf plugin creates a GOPATH for each version and sets it correctly in `exec-env`, so if I do `go env` I see that go is seeing the correct GOPATH for it's version.
The problem is that the user, and other programs also need to interact with GOPATH but not via the the Go executable, in which case GOPATH would not be set. Is there a way to update env vars on the shell based on the selected version?
I not, I thought about a generic solution: adding some kind of hook to the version update function, and the plugin developer, or the user can choose to implement it and in my case export env vars to the shell.
Let me know if this makes sense at all, so we can discuss further implementation.

**Comment by vic** [comment]
Checkout the `asdf env` command.

You can for example, print out the environment used for the currently selected go executable:

```bash
asdf env go
```

From there you could extract just the vars you are interested in, and source them in your shell (following example is for bash)

```bash
eval "$(asdf env go | grep GOPATH)"
```

If you want to do that automatically, one approach would be using the `asdf-direnv` plugin which exposes the environment produced by `exec-env` to the running shell.

**Comment by Stratus3D** [comment]
Closing this issue since I don't think this feature is necessary. `asdf env go` should be enough for cases like this. You could even write a wrapper function to do this automatically:

```bash
asgo() {
  $(asdf env go | xargs) $@
}

asgo some-cmd # will get executed with environment variables provided by asdf env
```
