### ISSUE TITLE
asdf latest <name> shows help instead of latest stable version

### ISSUE THREAD

**Issue by jmegs** [asdf-vm/asdf#598]
### Steps to reproduce

* Install asdf via homebrew and add appropriate incantations to `.zshrc`
* Install ruby and nodejs plugins
* In a new shell enter `asdf latest ruby` or `asdf latest nodejs`

### Expected behavior

Returns latest stable version number of the specified language

### Actual behavior

Shows cli help

### Environment

**OS**: macOS 10.15.1

**asdf version**: 0.7.5

**Comment by vic** [comment]
That's a feature added just a few days ago, perhaps you need to `asdf update --head`  to use the master branch ?

**Comment by jmegs** [comment]
ok will give that a try. 

what's the cadence for releasing to homebrew? I'd prefer to manage through there along with all my other software deps.

it might be nice to make that more explicit in the getting started docs. happy to put up a PR
