### ISSUE TITLE
Mark global versions in the output of list command

### ISSUE THREAD

**Issue by maxdanilov** [asdf-vm/asdf#617]
### Expected behavior

Would be user friendly if the list command would somehow mark the currently selected versions of the environments.

```shell
asdf list
```
```
golang
    1.13.2
  * 1.13.4
groovy
    apache-groovy-binary-2.4.12
  * apache-groovy-binary-2.5.8
```

This way it's clear that go 1.13.4 and groovy 2.5.8 would be used.
I'm aware of `asdf current`, but it only shows the currently selected versions, without the context of what else is installed.

### Actual behavior

```shell
asdf list
```
```
golang
  1.13.2
  1.13.4
groovy
  apache-groovy-binary-2.4.12
  apache-groovy-binary-2.5.8
```
### Environment

**OS**: MacOS 10.15.1

**asdf version**: v0.7.5

**Comment by cho-m** [comment]
So there was a PR for this (#761 and duplicate #762), but it didn't get much traction.
It would be nice to get a review on one of those to see if a different aesthetic/solution is needed.

The available PR output looks like a whitespace-lacking `chruby`-style output.
It should also be possibly to extend PR to create `pyenv`/`rbenv`-style output.

One possible demerit would be the fact that `asdf current` is slower than `asdf list`. By running `current` inside `list`, the command will be noticeably slower:
```sh
❯ hyperfine 'asdf list' 'asdf current'
Benchmark #1: asdf list
  Time (mean ± σ):      22.8 ms ±   0.6 ms    [User: 6.6 ms, System: 13.4 ms]
  Range (min … max):    20.8 ms …  25.3 ms    114 runs

Benchmark #2: asdf current
  Time (mean ± σ):     189.8 ms ±   1.7 ms    [User: 57.3 ms, System: 142.6 ms]
  Range (min … max):   188.4 ms … 194.8 ms    15 runs

Summary
  'asdf list' ran
    8.33 ± 0.22 times faster than 'asdf current'


❯ hyperfine --warmup 3 'asdf list ruby' 'asdf current ruby'
Benchmark #1: asdf list ruby
  Time (mean ± σ):      12.6 ms ±   0.3 ms    [User: 4.3 ms, System: 6.7 ms]
  Range (min … max):    11.2 ms …  13.5 ms    205 runs

Benchmark #2: asdf current ruby
  Time (mean ± σ):      61.7 ms ±   0.5 ms    [User: 18.7 ms, System: 45.4 ms]
  Range (min … max):    60.8 ms …  62.8 ms    46 runs

Summary
  'asdf list ruby' ran
    4.88 ± 0.13 times faster than 'asdf current ruby'
```

---

This "marker" feature is available in most other version managers. The exact output is different based on tool, but here is a compilation of examples from some alternatives. It may be worth chiming-in on what output is best:
1. Ruby - [chruby](https://github.com/postmodern/chruby#examples)
    ```sh
    $ chruby 1.9.3
    $ chruby
     * ruby-1.9.3-p392
       jruby-1.7.0
       rubinius-2.0.0-rc1
    ```
1. Ruby - [RVM](https://rvm.io/workflow/examples#rvm-list)
    ```sh
    $ rvm list
    
      rvm rubies
    
       * ruby-1.9.3-p484 [ x86_64 ]
         ruby-2.0.0-p481 [ x86_64 ]
      => ruby-2.1.1 [ x86_64 ]
    
      # => - current
      # =* - current && default
      #  * - default
    ```
1. Ruby - [rbenv](https://github.com/rbenv/rbenv#rbenv-versions)
    ```sh
    $ rbenv versions
      1.8.7-p352
      1.9.2-p290
    * 1.9.3-p327 (set by /Users/sam/.rbenv/version)
    ```
1. Python - [pyenv](https://github.com/pyenv/pyenv#simple-python-version-management-pyenv) - forked from rbenv, so output is similar

    ```sh
    $ pyenv versions
      2.7.10
    * 3.5.0 (set by /Users/yuu/.pyenv/version)
      miniconda3-3.16.0
      pypy-2.6.0
    ```
1. NodeJS - [nvm](https://github.com/nvm-sh/nvm#setting-custom-colors) - also has color-coded output
    ```sh
    $ nvm ls
           v10.15.0
    ->     v11.10.0
           system
    ...
    ```
1. Go - [gvm](https://github.com/moovweb/gvm)
    ```sh
    $ gvm list
    
    gvm gos (installed)
    
       go1.12.8
    => system
    ```
1. Rust - [rustup](https://rust-lang.github.io/rustup/examples.html) - shows active toolchain and lists global default.
    ```
    ❯ rustup show
    Default host: aarch64-apple-darwin
    rustup home:  /Users/cho-m/.local/share/rustup
    
    installed toolchains
    --------------------
    
    stable-aarch64-apple-darwin (default)
    nightly-aarch64-apple-darwin
    
    active toolchain
    ----------------
    
    nightly-aarch64-apple-darwin (directory override for '/Users/cho-m/Workspace/test')
    rustc 1.52.0-nightly (e37a13cc3 2021-02-28)
    ```
