### ISSUE TITLE
[Feature Request] Support multiple language in the same project

### ISSUE THREAD

**Issue by leomao10** [asdf-vm/asdf#642]
In our Rails application, we use nodeJS/yarn/webpack to manage our npm package. Hence, in our Rails application, we actually using both ruby and nodeJS at the same time and have both `.ruby-version` and `.nvmrc` in our repo.

Just wondering if it is feasible to use asdf to manage both programming languages in the same project

**Comment by mikeroll** [comment]
I can't see why not.

```
❯ asdf local python 3.7.0

❯ asdf local nodejs 13.6.0

❯ cat .tool-versions 
python 3.7.6
nodejs 13.6.0

❯ python -V
Python 3.7.6

❯ node -v
v13.6.0
```

**Comment by Stratus3D** [comment]
@leomao10 yes it is possible. In fact I'm working on a legacy project that has a `.ruby-version` file and a `.node-version` file. Everything works fine, you'll just need to legacy version file support in your `.asdfrc` file - https://asdf-vm.com/#/core-configuration?id=homeasdfrc

**Comment by leomao10** [comment]
That is awesome, guess I missed that from the doc. Thanks for letting me know @Stratus3D @mikeroll
