### ISSUE TITLE
Feature: do not create new .tool-versions if it exists in parent dir

### ISSUE THREAD

**Issue by gmile** [asdf-vm/asdf#65]
This is not a bug, but rather a question / suggestion.

Per readme, `asdf`:

> searches recursively in the parent directories until it finds a `.tool-versions` file.

This is great and is working very well. However, now that I am in a nested directory, if I change the version using this command:

```
asdf local my_language my_version
```

it creates a new `.tool-versions` file in this folder, and fairly so.

It would be nice, however, to have a way to write to existing `.tool-versions` in parent directory upon running `asdf local`. Something like a `-p` flag, to indicate that the change should be written to the parent directory:

```
asdf local -p my_language my_version
```

**When this is useful?**

I'm working on a project that has a `.tool-versions` in the root folder. The `.tool-versions` file is checked in CVS. Somewhere deep down the project tree, I need to temporarily switch to an older version of the language and do my stuff (verify whether or not my script is working under an older version of a language). Doing `asdf local` creates a new file that must be removed.

Removing file manually is little work, and yet it's a bit irritating when needed to be done frequently.

**Comment by Stratus3D** [comment]
I don't see any harm in adding a flag like this. The use case makes sense to me, and "read" version of this command already does something similar (`asdf local elixir` crawls up the parent directories until it finds a `.tool-versions` file and prints the Elixir version). I'm definitely open to making this change. 

@asdf-vm/maintainers what do you guys think?

**Comment by tuvistavie** [comment]
I perfectly understand the use case and agree it would be useful.
I often find myself `cd`ing to the directory because of this.
So I am +1 on adding this feature!

**Comment by skotchpine** [comment]
I'll take a stab at this. Should take a day or so
