### ISSUE TITLE
Enhamcement in creating an asdf plugin

### ISSUE THREAD

**Issue by wolfiton** [asdf-vm/asdf#658]
### Steps to reproduce

https://github.com/asdf-vm/asdf/blob/master/docs/plugins-create.md

### Expected behavior

To find clear documentation with an example so I can build my own plugin.  That I can share it with the community afterward.

### Actual behavior

A lot of theory but very little examples of what is needed to create your own custom plugin.

### Environment

**OS**:

Kubuntu 19.10

**Comment by jthegedus** [comment]
I am working on an update to the docs at this time. I will make improvements to this section.

**Comment by wolfiton** [comment]
> I am working on an update to the docs at this time. I will make improvements to this section.

Thank you @jthegedus, for looking over my enhancement proposition and for the fast reply.

**Comment by jthegedus** [comment]
To better understand the problems with this process I created my [own plugin (gcloud cli)](https://github.com/jthegedus/asdf-gcloud) and then created an [asdf-plugin-template](https://github.com/jthegedus/asdf-plugin-template) which should make things a bit easier. I hope to get this template into the official repo.

Documentation updates are yet to come, but will be thorough with my learnings from going through the process myself.

**Comment by wolfiton** [comment]
Thanks for the update, I will take a look when I have some time.

**Comment by vic** [comment]
@jthegedus awesome template! 👏

**Comment by jthegedus** [comment]
I didn't realise I could create repos in the org. So moving the template there

**Comment by Stratus3D** [comment]
Closing this ticket since I think we've done everything we need to for now. Please open a new ticket if there are specific enhancements we need to make to the plugin template.

**Comment by jthegedus** [comment]
For those wondering I still have a WIP rewrite of the plugin section of the docs which will complement the plugin template repo. Will get to finishing it soon(TM)
