### ISSUE TITLE
Already installed plugins throwing stderr

### ISSUE THREAD

**Issue by odelucca** [asdf-vm/asdf#659]
### Steps to reproduce

- Install a new plugin, `asdf plugin-add nodejs`, for example
- Try to install the same plugin again

You should notice that the message that the plugin were already installed was an `stderr`

### Expected behavior

Since this is not actually an error, it should only return the message, without any error status. This is important because some automation scripts can't handle this.

For example, I'm developing an Ansible role that install a bunch of plugins on my workstation, and I need to manually ignore those errors. This can cause a lot of trouble.

### Actual behavior

It is being executed like if it was an error.

**Comment by jthegedus** [comment]
In you reproduction, are you "importing the Node.js release team's OpenPGP keys to main keyring" as in the [plugin's instructions](https://github.com/asdf-vm/asdf-nodejs#install)?

**Comment by odelucca** [comment]
Yes, the error that I ge tis specific regarding that `nodejs` was already installed.

As I've said, on the first install it works smoothly, but in the next one it throws an error saying that `nodejs` was already installed.

I need it not to print anything on `stderr` since this is not actually an error. I'm building my own auomated workstation setup with Ansible and it may try to install those multiple times.

**Comment by jthegedus** [comment]
Fair enough. Thanks.

**Comment by jthegedus** [comment]
@odelucca This is being reverted as the prior discussions from essentially the same question resulted in the exit code of 2 for adding a plugin that already exists - see original issue https://github.com/asdf-vm/asdf/issues/322 and the actual discussion in the PR https://github.com/asdf-vm/asdf/pull/323

**Comment by Stratus3D** [comment]
If you have code that needs to verify that a plugin is installed, and don't care if it was already installed, something like this should do what you need:

```
status_code=$(asdf plugin-add <name> <url>)
if [ $status_code -eq 0 ] || [ $status_code -eq 2 ]; then
    echo "Plugin is installed"
fi
```

**Comment by odelucca** [comment]
Strange.

In my opinion `exit 1` should be only used when an error occur. This is not actually an error and adding `exit 1` makes harder to automated workstation setup.

For example, I use `ansible` to automate the installation of my tools. For every tool that I use, everytime I ran the `install` command it syncs my entire configs. Most of those I try to reinstall.

`asdf-vm` is the only tool that throws `exit 1` when I try to install an already present plugin. For that instance I need to do a condition (like @Stratus3D mentioned) to avoid this messing up with my sync.

The problem with that is, if a **real error** occur, my automate setup will ignore...

**Comment by dideler** [comment]
FYI for anyone following this thread when troubleshooting the same issue, the workaround in [this comment](https://github.com/asdf-vm/asdf/issues/659#issuecomment-606962826) is incorrect.

```
status_code=$(asdf plugin-add <name> <url>)
if [ $status_code -eq 0 ] || [ $status_code -eq 2 ]; then
    echo "Plugin is installed"
fi
```

That'll capture command output, not the return code.

Instead in bash you'll want to check the value of `$?`. And if you have `errexit` set then you'll need to check it in way that ensures your script doesn't prematurely abort. Ideally I'd want asdf to not treat this scenario as an error (w.r.t. to exit code and output stream), so we don't have to write [code like this](https://github.com/dideler/setup-macos/commit/d40b1afe70303f948d36aae9ee55ce19cb2bb175) in our scripts to handle the safe no-op.

**Comment by Stratus3D** [comment]
You are right @dideler . Should be something like:

```
asdf plugin-add <name> <url>
status_code=$?
if [ $status_code -eq 0 ] || [ $status_code -eq 2 ]; then
    echo "Plugin is installed"
fi
```

**Comment by dguo** [comment]
To avoid checking status codes, I did this in a setup script:

```sh
if ! asdf plugin list | grep -q 'nodejs'; then
    asdf plugin add nodejs
fi
```
