### ISSUE TITLE
(ubuntu) column: command not found

### ISSUE THREAD

**Issue by gousern** [asdf-vm/asdf#661]
### Steps to reproduce

1. `docker pull ubuntu:18.04` (also tried in 14.04, 16.04, 18.04)
2. `docker run -it ubuntu:18.04 /bin/bash`
3.  `apt-get install git`
4. install asdf in this container 
3. run `asdf plugin list`

### Expected behavior

```
# asdf plugin list                                                                    
docker-slim
golang
julia
nodejs
python
```
### Actual behavior

```
# asdf plugin list 
/home/user/.asdf/lib/commands/command-plugin-list: line 46: column: command not found
```

### Environment

**OS**: MacOS High Sierra 10.13.6 & Ubuntu {14.04, 16.04, 18.04}

**asdf version**: v0.7.6-6207e42 

This issue started from v0.76 since the following new feature using `column`.  

> Improve output format of asdf plugin list all
> Long plugin names were causing problems with how we used printf. Now we use the column command to properly render output.

**Comment by jthegedus** [comment]
@vic https://github.com/asdf-vm/asdf/pull/604 added this new dependency to the tool. Are we tracking these dependencies anywhere? Are we able to remove this additional dep or implement our own simple column formatting?

**Comment by vic** [comment]
We could have a tiny wrapper that fallbacks to what we used previous to `column` where it's not available.

**Comment by Stratus3D** [comment]
I'd say lets keep it simple and not use `column` if it's not available on operating systems like Ubuntu. Can we not use `printf` for this instead?

**Comment by Stratus3D** [comment]
I also think our list of dependencies in the documentation contains some things asdf core doesn't actually use. I am going to determine which dependencies are not used by core and remove them from the docs.

**Comment by gousern** [comment]
I've updated asdf to `v0.7.8` and tested in `ubuntu:16.04` without seeing this issue again. So I will close this ticket. 

```
(base) z@d90c728c85ec:~$ asdf version
v0.7.8-4a3e3d6
(base) z@d90c728c85ec:~$ asdf plugin list   
Oohes nooes ~! No plugins installed
```

**Comment by jthegedus** [comment]
I don't believe we reverted using column, so would be interested as to how this disappeared. Though, having said this, no one else has raised or 👍 the issue so perhaps it was a phantom issue.

**Comment by gousern** [comment]
> I don't believe we reverted using column, so would be interested as to how this disappeared. Though, having said this, no one else has raised or 👍 the issue so perhaps it was a phantom issue.

Well, you are right. Seeing this issue again. Let me reopen this ticket.

```
(base) user@d90c728c85ec:~/ $ asdf plugin list all
initializing plugin repository...
Cloning into '/home/user/.asdf/repository'...
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 1743 (delta 41), reused 36 (delta 12), pack-reused 1647
Receiving objects: 100% (1743/1743), 391.46 KiB | 277.00 KiB/s, done.
Resolving deltas: 100% (759/759), done.
Checking connectivity... done.
/home/user/.asdf/lib/commands/command-plugin-list-all.bash: line 23: column: command not found

(base) z@d90c728c85ec:~/ $ grep -R "column" ~/.asdf/lib/commands
/home/user/.asdf/lib/commands/command-plugin-list.bash:    ) | column -t -s $'\t'
/home/user/.asdf/lib/commands/command-plugin-list-all.bash:    ) | column -t -s $'\t'
```
