### ISSUE TITLE
asdf "plugin remove" hook for plugin authors

### ISSUE THREAD

**Issue by jthegedus** [asdf-vm/asdf#670]
As with `asdf uninstall <name> <version>` it would be good if plugin authors could perform additional actions on the removal of their plugin.

In my particular instance, I would like to remind users to remove some global config shared across each version of the plugin ([see here for what I mean](https://github.com/jthegedus/asdf-gcloud/blob/0a309723eb2ffccecfb71720f7e2c59cfb576642/bin/uninstall#L7)).

If this exists in the documentation I could not find it. Nor could I with a cursory look through the codebase.

**Comment by vic** [comment]
@jthegedus, now you can!! thanks to @joschi's PR.

**Comment by jthegedus** [comment]
@vic Great, though I have some suggestions for that implementation.
