### ISSUE TITLE
Asdf vue still installed in asd shimm but not in yarn or npm

### ISSUE THREAD

**Issue by wolfiton** [asdf-vm/asdf#672]
### Steps to reproduce

install yarn plugin
setup globally
`yarn global add @vue/cli`

`yarn global remove @vue/cli`

Now open terminal and type `vue`

```shell
which vue
/home/dan/.asdf/shims/vue
```

### Expected behavior
All the vue commands are there but the package is removed already
Tell us what should have happened
vue unrecognized command
### Actual behavior
```shell
vue                                                                                                                                                  ✔ 
Usage: vue <command> [options]

Options:
  -V, --version  output the version number
  -h, --help     output usage information

Commands:
  init           generate a new project from a template
  list           list available official templates
  build          prototype a new project
  create         (for v3 warning only)
  help [cmd]     display help for [cmd]

```
Tell us what happened instead

### Environment

**OS**:Kubuntu 19.10

**asdf version**: v0.7.6-6207e42 , also tried with 0.7.7 version same result

**Comment by Stratus3D** [comment]
I'm not sure I understand. The shim for `vue` is present when it should not be? Or are the `vue` commands that are succeeded when they should not be?

I'm not familiar with Vue so you'll need to provide me with more specifics on what should happen.

**Comment by wolfiton** [comment]
Hi @Stratus3D ,

Thanks for looking at my issue.

The problems get's resolved, if I use `asdf reshim nodejs`

The shims should get updated when you remove Vue or add Vue.

Vue is added with `yarn global add @vue/cli`
Vue is removed with `yarn global remove @vue/cli`

So when you remove vue you shouldn't have access to any of the vue helpers,documentation and 
not be able to see the vue commands.
I hope this comment helps

**Comment by Stratus3D** [comment]
@wolfiton can you try upgrading to the latest versions of asdf and asdf-nodejs?

**Comment by wolfiton** [comment]
> @wolfiton can you try upgrading to the latest versions of asdf and asdf-nodejs?

Thank for reaching out @Stratus3D, but since then I don't use any more vuejs.

**Comment by jthegedus** [comment]
Since no other users have upvoted this issue as a problem, and OP is no longer experiencing, I will close. Thanks @wolfiton
