### ISSUE TITLE
command not found: complete

### ISSUE THREAD

**Issue by bigardone** [asdf-vm/asdf#68]
Hi there!
I've just installed `asdf` for Mac, and every time I start a new zsh it prints the following error:

```
/Users/user/.asdf/completions/asdf.bash:43: command not found: complete
```

What can be going wrong?
Thanks in advance!

**Comment by jswny** [comment]
I'm getting the same error using ZSH on CentOS 7.

**Comment by dbernheisel** [comment]
This pull request on a different project seems to have a solution:
https://github.com/eddiezane/lunchy/pull/59

**Comment by HashNuke** [comment]
Can anyone using zsh confirm which solution is better?

\\cc: @asdf-vm/maintainers

**Comment by tuvistavie** [comment]
It's been a while since I haven't used zsh, but #69 should be good!

**Comment by dbernheisel** [comment]
#69 will work for zsh. When this merges, the readme should also be updated to say that zsh users don't need to source `./completions/asdf.bash` into their profiles since it's auto-loaded via `./asdf.sh`

**Comment by tuvistavie** [comment]
@dbernheisel I think there are two choices:

* Autoload `completions/_asdf`, and avoid sourcing `completions/asdf.bash`, which is what we were doing before
* Forget about `_asdf` and use zsh bash compatibility to load `completions/asdf.bash`

I just merged #69, but I believe we still need to source the file as only `_asdf` would get autoloaded,
and I would rather avoid maintaining bash and zsh completion separately.
The bash completion currently being superior to the zsh one, I don't think it is worth trying to replicate the functionality under `_asdf`.

So, if you think it is ok (not being a zsh user myself, I want to be sure this fits everyone need),
I think that we can safely remove `_asdf` from `completions` and avoid appending the `fpath` as
we are not using autoloading here.

**Comment by dbernheisel** [comment]
Great direction. I like the 2nd option as well. A quick test on my system proves it should work without issue.

**Comment by tuvistavie** [comment]
This should now be fixed :smile:

**Comment by dbernheisel** [comment]
If you're here because of Google, this thread is super old now and the docs have updated. As of 2020-05-05, do this:

```sh
# append completions to fpath 
fpath=(${ASDF_DIR}/completions $fpath) 

# initialise completions with ZSH's compinit 
autoload -Uz compinit && compinit
```

**Comment by bernardo-martinez** [comment]
thanks @dbernheisel , but where should we put that?

**Comment by jthegedus** [comment]
@bernardo-martinez Please check the documentation site as @dbernheisel mentions as it will guide you for your exact OS & Shell combination https://asdf-vm.com/#/core-manage-asdf-vm

**Comment by JohnsinLi** [comment]
Can anyone using zsh confirm which solution is better?

**Comment by jthegedus** [comment]
@JohnsinLi it depends on your setup & whether you are using an ZSH framework & plugin manager. We cannot cater to all permutations of CLI setups. The docs cover the vanilla ZSH setup.
