### ISSUE TITLE
Configuration settings for plugins

### ISSUE THREAD

**Issue by joschi** [asdf-vm/asdf#681]
Is there a way for asdf plugins to access the configuration settings in `$HOME/.asdfrc` except for parsing the file themselves?

It would we great, if plugins were provided with the configuration settings in some way.

One possibility would be via environment variables similar to `ASDF_INSTALL_VERSION`, for example `legacy_version_file` in `.asdfrc` could be mapped to `ASDF_CONFIG_LEGACY_VERSION_FILE`.

**Comment by joschi** [comment]
I found this in the documentation:
> When invoked, if extension commands do not have their executable-bit set, they will be
> sourced as bash scripts, having all of the functions from `$ASDF_DIR/lib/utils.bash` available.
> Also, the `$ASDF_CMD_FILE` resolves to the full path of the file being sourced.
> If the executable bit is set, they are just executed and replace the asdf execution.

This means that plugins can use [`get_asdf_config_value()`](https://github.com/asdf-vm/asdf/blob/3246c26d52f0d0368110ac96f82d60301b8f6bc8/lib/utils.bash#L344). 👍

**Comment by jthegedus** [comment]
@joschi Yes, the documentation for plugins needs much improvement. I am working on an update to the docs atm and will add this to the list of things to make more clear. Thanks for raising this and pointing to the solution 👍
