### ISSUE TITLE
is there a way to distribute multiple plugins via same repo

### ISSUE THREAD

**Issue by cppforlife** [asdf-vm/asdf#691]
i am one of the maintainers of github.com/k14s. we have several CLI projects: vendir, ytt, kapp, etc. is there a way to create a asdf packaging repo that includes multiple of them together (similar to how github.com/k14s/homebrew-tap includes multiple CLIs)?

**Comment by jthegedus** [comment]
The `asdf-hashicorp` plugin achieves something like this as each tool shares the same baseurl etc https://github.com/Banno/asdf-hashicorp

**Comment by johnhamelink** [comment]
Hey @cppforlife, I've made a plugin based on asdf-hashicorp which packages everything together :smile: https://github.com/johnhamelink/asdf-k14s

I remember based on previous conversations that you were keen to have this inside the k14s github org? I can transfer the repository over if you'd like. In the meantime I've submitted a PR to [asdf-plugins](/asdf-vm/asdf-plugins) for my repo.

You can try it out by installing the plugins like so:

```
asdf plugin-add <kwt|ytt|kapp|vendir|kbld|json2k8s> https://github.com/johnhamelink/asdf-k14s.git
```

**Comment by jthegedus** [comment]
@cppforlife of note, you can download any number of CLI tools and perform their setup in a single plugin. When specifying where to find the binaries for each tool you can use a `list-bin-paths` binary to tell asdf where to find all binaries your tool installs. Docs: https://asdf-vm.com/#/plugins-create?id=binlist-bin-paths Example: see how the `asdf-nodejs` plugin allows `.npm/bin` in addition to the plugin's `bin` dir - https://github.com/asdf-vm/asdf-nodejs/blob/master/bin/list-bin-paths
