### ISSUE TITLE
asdf crash with error "sort: unrecognized option '--version-sort'"

### ISSUE THREAD

**Issue by m0ast** [asdf-vm/asdf#698]
Hello,
On osx some commands fails with `sort: unrecognized option '--version-sort'`

**To Reproduce**
On Osx try
`asdf plugin test nodejs https://github.com/asdf-vm/asdf-nodejs.git node --version`
or since after investigating it seems related
`asdf latest nodejs`

**Expected behavior**

In first case should invoke nodejs with `--version` on the second, should list latest for nodejs

**Actual behavior**

```
➜ asdf plugin test nodejs https://github.com/asdf-vm/asdf-nodejs.git node --version
Updating nodejs...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
sort: unrecognized option `--version-sort'
Try `sort --help' for more information.
nodejs  is already installed
unknown command: node. Perhaps you have to reshim?
FAILED: node --version failed with exit code 0
```
or with latest
```
➜ asdf latest nodejs
sort: unrecognized option `--version-sort'
Try `sort --help' for more information.
```

### Environment

**OS**:
```
sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G2136
```

**asdf version**: v0.7.8-4a3e3d6

**asdf plugins installed**: ```elixir
erlang
haxe
neko
nodejs```

Ps: Actually these commands aren't listed for Cli usage

**Comment by jthegedus** [comment]
Good find. This is the line causing the issue https://github.com/asdf-vm/asdf/blob/7cdfc0fa2a5f0f924a4486a971f5110102f58e54/lib/commands/command-latest.bash#L15

We should be using https://github.com/asdf-vm/asdf/blob/8a5c70b2dd43f918c51548a52c150c3c9ff4a547/lib/commands/command-update.bash#L46 instead. I will raise a fix.

**Comment by jthegedus** [comment]
Should be fixed on latest commit and in our next release
