### ISSUE TITLE
Cannot update elixir version

### ISSUE THREAD

**Issue by ORESoftware** [asdf-vm/asdf#701]
I am on asdf version:

```shell
 asdf --version  => v0.5.0
```

I did this:

```bash
asdf install elixir 2

```

I got this:

```shell
oleg@xps:~/codes/ores/phoenix-ML-graphql$ asdf install elixir 2
==> Checking whether specified Elixir release exists...
==> Downloading 2 to /tmp/elixir_build_GvOpYP/elixir-precompiled-2.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243  100   243    0     0   1760      0 --:--:-- --:--:-- --:--:--  1760
==> Copying release into place
[/tmp/elixir_build_GvOpYP/elixir-precompiled-2.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/elixir_build_GvOpYP/elixir-precompiled-2.zip or
        /tmp/elixir_build_GvOpYP/elixir-precompiled-2.zip.zip, and cannot find /tmp/elixir_build_GvOpYP/elixir-precompiled-2.zip.ZIP, period.
```

how do I upgrade my asdf version?

_RECOMMENDATION:_

IF there is an ERROR in an ASDF command sequence AND there is a newer version of ASDF available then _provide a link_ on how to upgrade the version in the error _console output_! That would be too Amazing! 😏

**Comment by ORESoftware** [comment]
anyway, I figured out how to upgrade asdf with:

```
asdf update
```

to version:

```
v0.7.8-4a3e3d6
```

and I got the same error as above :(

**Comment by jthegedus** [comment]
Hi @ORESoftware this issue seems specific to the `elixir` plugin and should probably be reported there.

Performing `asdf list all elixir` doesn't reveal a match for a version number of `2` so I would expect the plugin to error before it attempts the download.

Here are the last 10 versions from `asdf list all elixir`

```
...
1.10.0-rc.0-otp-22
1.10.1
1.10.1-otp-21
1.10.1-otp-22
1.10.2
1.10.2-otp-21
1.10.2-otp-22
master
master-otp-21
master-otp-22
```

Any checks performed for a version to be installed is handled by the plugin itself.

**Comment by Stratus3D** [comment]
I have created https://github.com/asdf-vm/asdf-elixir/pull/81 for this issue.
