### ISSUE TITLE
Add short introductory example to the documentation

### ISSUE THREAD

**Issue by izzues** [asdf-vm/asdf#708]
Nothing serious, but it would be a timesaver to have a small example to tie things together in the docs. For instance, it's not obvious that in order to get something usable you first have to add a plugin, _then_ install a version, _then_ activate it. I was also confused that you can use `latest` in `install` but not in `global`, or that the default behavior of `global` when there's only one version installed isn't to just activate it. (I guess these points are more a suggestion to improve UX than anything, but at least the docs could mention them).

**Comment by jthegedus** [comment]
Great suggestions, cheers @izzues 

I'll draft a proposal soon

**Comment by jthegedus** [comment]
I hope you find this addition to the docs sufficient

![image](https://user-images.githubusercontent.com/20798510/84331771-74d5c200-abce-11ea-82e9-4825d7f72864.png)

Here we list the order each step needs to be taken, how they relate and link to the relevant parts of the documentation (which just happen to be the order in the sidebar menu :smile: )

I didn't directly address the `global`/`local` settings here as they do have different implications depending on where they are executed and with `latest` or not. I think that nuance is best left to the more complete documentation that exists on the other pages in more detail (though they could probably be improved too)
