### ISSUE TITLE
Fish setup documentation is incorrect

### ISSUE THREAD

**Issue by maxwellainatchi** [asdf-vm/asdf#711]
**Describe the bug**
The setup documentation for macOS/fish/homebrew is incorrect

**To Reproduce**
1. Go to https://asdf-vm.com/#/core-manage-asdf-vm?id=add-to-your-shell
2. Set OS to `macOS`, shell to `fish`, and installation method to `homebrew`

**Expected behavior**
It should say 
```fish
source (brew --prefix asdf)/asdf.fish
```

**Actual behavior**
```fish
source "(brew --prefix asdf)"/asdf.fish
```

### Environment
N/A

**Additional context**
https://github.com/fish-shell/fish-shell/issues/159#

**Comment by jthegedus** [comment]
Closed in #709 

Thanks for raising
