### ISSUE TITLE
Completion not working

### ISSUE THREAD

**Issue by tz4678** [asdf-vm/asdf#712]
```zsh
# Type "asdf " and press Tab
$ asdf _arguments:34: bad output format specification
_arguments:366: bad math expression: operator expected at `descrs'
_arguments:34: bad output format specification
_arguments:366: bad math expression: operator expected at `descrs'
_arguments:34: bad output format specification
_arguments:366: bad math expression: operator expected at `descrs'
asdf
```

I use zplug and oh-my-zsh. My `~.zshrc`:

```zsh
#!/usr/bin/env zsh

fpath+=~/.zfunc

source /usr/share/zsh/scripts/zplug/init.zsh

# добавил после того как заметил, что нет привычных мне алиасов
zplug "robbyrussell/oh-my-zsh", as:plugin, use:"lib/*.zsh"

# https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins-Overview
zplug "plugins/archlinux", from:oh-my-zsh
# При установке из репозиторяи нужно задать переменную окружения ASDF_DIR
zplug "plugins/asdf", from:oh-my-zsh
...
```

`~/.zshenv`:

```zsh
...
export ASDF_DIR=/opt/asdf-vm  # for asdf oh-my-zsh plugin
...
```

Version:

```zsh
$ asdf --version 
v0.7.8
```

asdf-vm installed from [AUR](https://aur.archlinux.org/packages/asdf-vm/).

**Comment by jthegedus** [comment]
Hi, thanks for reporting.

The `oh-my-zsh` plugin is still using the older Bash completions for ZSH.

@alecmev is responsible for the Aur. As stated in PR https://github.com/asdf-vm/asdf/pull/704 which updates the installation docs for Aur:
- `bash-completions` is required for Bash completions to work - https://github.com/asdf-vm/asdf/pull/704#discussion_r414114137
- ZSH completions are put in place by the Aur installation, but need to be enabled, probably via 
	```
	# initialise completions with ZSH's compinit
	autoload -Uz compinit
	compinit
	```

I would not recommend using the `oh-my-zsh` asdf plugin with the Aur installation as the plugin tries to perform sourcing of `asdf.sh` which may not work with Aur and is using the old bash completions.

**Comment by tz4678** [comment]
> Hi, thanks for reporting.
> 
> The `oh-my-zsh` plugin is still using the older Bash completions for ZSH.
> 
> @alecmev is responsible for the Aur. As stated in PR #704 which updates the installation docs for Aur:
> 
> * `bash-completions` is required for Bash completions to work - [#704 (comment)](https://github.com/asdf-vm/asdf/pull/704#discussion_r414114137)
> * ZSH completions are put in place by the Aur installation, but need to be enabled, probably via
>   ```
>    # initialise completions with ZSH's compinit
>    autoload -Uz compinit
>    compinit
>   ```
> 
> I would not recommend using the `oh-my-zsh` asdf plugin with the Aur installation as the plugin tries to perform sourcing of `asdf.sh` which may not work with Aur and is using the old bash completions.
> 
> Perhaps @alecmev has some further thoughts here.


```zsh
. /opt/asdf-vm/asdf.sh
. /usr/share/bash-completion/completions/asdf
```

I added these lines in my `~/.zshrc` and it worked

**Comment by jthegedus** [comment]
@tz4678 Given the `oh-my-zsh` plugin just tries sourcing `asdf.sh` you should probably remove that too.

Closing this since the new (but currently unreleased) instructions solved your issue.
