### ISSUE TITLE
asdf shell: set plugin version for shell session only

### ISSUE THREAD

**Issue by noraj** [asdf-vm/asdf#715]
![image](https://user-images.githubusercontent.com/16578570/80313246-07223200-87ea-11ea-9484-4358397b044a.png)

We would like a command to set a version of a plugin for the current shell session only. 

**Describe the solution you'd like**

Add `asdf shell` in addition to `asdf {global, local}` to set a version only for the current shell session.

**Describe similar asdf features and why they are not sufficient**

rbenv is the core project that gave birth to nodenv, pyenv, phpenv, <whateverlangage>env. It seems that asdf is totally inspired from rbenv [using the same principles](https://github.com/rbenv/rbenv/wiki/Why-rbenv%3F) so I'm very surprised [rbenv shell](https://github.com/rbenv/rbenv#rbenv-shell) is not implemented.

**Describe workarounds you've considered**

It's already possible to set a version just for a shell session via environment variables but it's not very handy.

**Comment by Stratus3D** [comment]
This command actually already exists, and does exactly what you are describing.

@jthegedus what do you think about adding documention for `asdf shell` to this section of the website? https://asdf-vm.com/#/core-manage-versions?id=set-current-version We've got a info box that mentions the environment variable, but we don't mention the `asdf shell` command anywhere.

**Comment by jthegedus** [comment]
Yeah no problem :+1: It seems the `asdf` command doesn't list the `asdf shell` command either, so we should add it to that output as well.
