### ISSUE TITLE
[Proposal] Command to get direct path of the binary

### ISSUE THREAD

**Issue by HashNuke** [asdf-vm/asdf#72]
We need a way to expose the path to a binary. For example to debug with `gdb`, we need the direct path of the `ruby` binary and not the shim.

Something like

```
$ asdf bin ruby
/Users/HashNuke/.asdf/installs/ruby/2.3.0/bin/ruby
```
#### As a tangential discussion

Do we rename `asdf which` command to `asdf version` OR `asdf current` instead?

That way this can be in like with the unix `which` command. So we can use `asdf which ruby`

```
# this is currently what the asdf-which command does
# proposing to change it to asdf-current instead
$ asdf current ruby
2.3.0

# and use asdf-which to return the full path of the binary
$ asdf which ruby
/Users/HashNuke/.asdf/installs/ruby/2.3.0/bin/ruby
```

**Comment by rockwood** [comment]
I just switched asdf, and the `which` command through me off at first. I think the most idiomatic api would have `which` mimic the unix command and have a separate command for listing the current version. Just my two cents.

**Comment by HashNuke** [comment]
@rockwood Same opinion. Will make the change.

**Comment by tuvistavie** [comment]
I also agree on renaming the current `which` to `version` and making `which` behave like its UNIX counterpart.

**Comment by rockwood** [comment]
I wonder if it's also worth having the new command print where the current version is being read from. [Rbenv does that](https://github.com/rbenv/rbenv#rbenv-version) and proved helpful on a few occasions. 

Something like:

```
> asdf current elixir
1.3.1 (set by /Users/rockwood/.tool-versions)
```

**Comment by tuvistavie** [comment]
I agree this would also be a good idea.
I personally prefer `asdf version elixir` to  `asdf current elixir`,
what do you guys think?

**Comment by rockwood** [comment]
My only concern with `asdf version ...` is the potential confusion with `asdf --version`. Although I don't feel that strongly either way.
