### ISSUE TITLE
Add support for wildcard in local .tool-versions file

### ISSUE THREAD

**Issue by imbsky** [asdf-vm/asdf#720]
In a particular language, it's hustle to all runtime versions completely matched by all developers during development phase. So I think it would be good to have such support.

**Comment by imbsky** [comment]
For example, Node.js has a very fast release cycle, so it's really hustle to clearly separate 14.0.0 and 14.2.0. and in most cases, there's not much difference between the two.

**Comment by imbsky** [comment]
The following syntax is my idea, but if there is a better idea, I would also like to hear it.

```
nodejs 14.0.0
nodejs 14.0.*
nodejs 14.*.*
```

**Comment by jthegedus** [comment]
Given asdf forces everyone in the project sharing the **exact** same version, users don't end up in the situation where they can disagree on it's use. I personally am not a fan of this feat request. 

Additionally, how would this work with tools with many differing version sources, like Java for instance. How would this syntax work with?

```
adopt-openjdk-11.0.7+10_openj9-0.20.0
adopt-openjdk-11.0.7+10_openj9-0.20.0_large-heap
```

**Comment by Stratus3D** [comment]
Related issues: https://github.com/asdf-vm/asdf/issues/226, https://github.com/asdf-vm/asdf/issues/352

I agree with @jthegedus views on this. I am going to close this issue as I think #352 is similar and already has more discussion on it.

**Comment by jthegedus** [comment]
Notably, I was the one who requested this in #226 but after a few years of projects without `asdf` have come to find the current functionality most desirable.

**Comment by imbsky** [comment]
Indeed. That makes sense.

**Comment by andreif** [comment]
It would really be great if you allow users to choose for themselves by providing this feature. Let us decide what works for us and what not, please.
