### ISSUE TITLE
Updated nodejs by uninstall/install, shims are in the system but do not list as modules

### ISSUE THREAD

**Issue by gabsong** [asdf-vm/asdf#723]
**Describe the bug**
I wanted to update nodejs from 12.16.2 to 12.16.3, and without knowing the best suitable command for it, I uninstalled 12.16.2 and installed 12.16.3.

With 12.16.2, I had the following global packages:
yarn pm2 nodemon eslint

I installed 12.16.3, and these packages do not appear when I run `npm ls -g --depth=0` for top level global packages. However, I can still run yarn, pm2, etc.

I would still like to be able to manage packages using the npm cli. However, installing and uninstalling the packages I had with 12.16.2 does not have any effect.

How can I fully manage my modules again? Currently there's traces left in asdf and not sure how to deal with it.

```
❯ npm ls -g --depth=0
/Users/gabriel/.asdf/installs/nodejs/12.16.3/.npm/lib
├── nodemon@2.0.3 -> /Users/gabriel/.asdf/installs/nodejs/12.16.3/lib/node_modules/nodemon
├── pm2@4.4.0 -> /Users/gabriel/.asdf/installs/nodejs/12.16.3/lib/node_modules/pm2
├── typescript@3.8.3
└── yarn@1.22.4 -> /Users/gabriel/.asdf/installs/nodejs/12.16.3/lib/node_modules/yarn
```

**To Reproduce**

Tell us what actions you performed before the issue occurred

1. Install nodejs 12.16.2 with asdf
2. Install npm packages globally
3. Uninstall nodejs 12.16.2, install 12.16.3
4. Try running the CLI for previously installed packages, i.e. yarn
5. Check the list of packages for 12.16.3, will be empty
6. Try to uninstall or an old npm package or install/uninstall it i.e. live-server -- there is no way to do it

**Expected behavior**

Tell us what should have happened
- asdf could have warned about global packages at the time of uninstall
- asdf could make the global packages that are still in the system to work with the new version of nodejs

**Actual behavior**

Tell us what happened instead
As explained above, unable to manage old packages with cli commands

### Environment

**OS**: MacOS Catalina

**asdf version**: latest

**asdf plugins affected (if relevant)**:

**asdf plugins installed**:

**Screenshots**
live-server still shows up under shims

**Additional context**

For instance, live-server cannot be removed completely:

![image](https://user-images.githubusercontent.com/522076/81743200-2bbb1280-9456-11ea-9688-f53e1fb621ab.png)

![image](https://user-images.githubusercontent.com/522076/81743234-35dd1100-9456-11ea-9456-5d2b93899f64.png)

**Comment by jthegedus** [comment]
This sounds like an issue specific to the `asdf-nodejs` plugin and how it handles cleanup of globally installed npm packages. Can you report there and link to this issue so the nodejs plugin team can look at this?

> I wanted to update nodejs from 12.16.2 to 12.16.3, and without knowing the best suitable command for it, I uninstalled 12.16.2 and installed 12.16.3.

asdf's goal is to manage each version of it's plugins independently, so there's no "updating" from one version to another, you just `asdf install <plugin> <version>` the new one and bump your `.tool-versions`. If you want to remove a previous version than that is done with `asdf uninstall <plugin> <version>`.

**Comment by wsasouza** [comment]
Thank's

**Comment by Stratus3D** [comment]
Closing this issue as I believe it is something that needs to be resolved with asdf-nodejs and not asdf itself. If there is anything that needs to change in asdf core to fix this please leave a comment on this thread.
