### ISSUE TITLE
Extension commands do not work without a bin directory

### ISSUE THREAD

**Issue by andrewthauer** [asdf-vm/asdf#726]
**Describe the bug**

The [extension commands plugin api](https://asdf-vm.com/#/plugins-create?id=extension-commands-for-asdf-cli) does not work if the plugin does not have a `bin` directory.

This seems to be related to https://github.com/asdf-vm/asdf/blob/master/bin/asdf#L51 which checks for the existence of the `bin` directory before looking for a plugin command. This will be misleading for plugins that only have extension commands.

Also see #523 

**To Reproduce**

1. Create a new plugin `foo` with a `lib/commands/command.bash` file that echo's something
2. Symlink the plugin directory into the asdf plugins directory as `foo`
3. Run `asdf foo`
4. You'll see an unknown command error

**Expected behavior**

The plugin command is found and works correctly.

**Actual behavior**

Get the error message `Unknown command: asdf foo` + standard help text

### Environment

**OS**: macOS

**asdf version**: 0.7.8

cc @jthegedus

**Comment by jthegedus** [comment]
I don't believe plugins just for extension commands was a consideration when building the plugin system. The "create plugin" docs currently state:

>   `bin/list-all` - lists all installable versions
    `bin/download` - download source code or binary for the specified version
    `bin/install` - installs the specified version

is why I believe this is the case.

@Stratus3D What are your thoughts on opening up the requirements here to support extension-only plugins?

**Comment by andrewthauer** [comment]
I think the way extension commands are presented in the argument order is a bit confusing in respect to this possible requirement. All of the required `bin` commands are specific to a particular plugin/language. However, the extension command model does not specifically apply to a particular plugin. For example:

```sh
# command may have nothing to do with asdf or any plugins
asdf foo 

# command "may" do something universal across all plugins
asdf foo [plugin]
```

As you can see neither of these need anything to do with `bin/list-all`, `bin/download`, or `bin/install` of a particular plugin. Also, as I pointed out the only actual current restriction for extension only commands to work is the existence of the `bin` directory (not the commands within).

It also feels a little like the extension commands and the plugin model are a little bit at odds with each other. Plugins are meant to handle a specific language/tool. However, the extension command model seems to be something that would be universally used across all plugins. To me they seem like they should be different plugin types entirely. Also see #641.

**Comment by Stratus3D** [comment]
> @Stratus3D What are your thoughts on opening up the requirements here to support extension-only plugins?

It sounds like such a plugin isn't a version management plugin at all, but rather just a shell script (or set of scripts) that gets installed as a plugin. Am I understanding things correctly? If so, it's not clear to me why such scripts would even need to be managed by asdf. @andrewthauer any script on your system is free to invoke `asdf` and do anything you want, what is making this necessary?

Our philosophy is that things that can be done outside of asdf with a couple lines of shell could should be kept outside of asdf.

**Comment by hyperupcall** [comment]
I pushed #1643 because this is a bug.

The [documentation](https://asdf-vm.com/plugins/create.html#extension-commands-for-asdf-cli) doesn't state that the `bin/` directory is a prerequisite for this functionality. And, the fact that it has to be created is not intuitive.

Whether or not the requirements should "open up to support extension-only plugins" is irrelevant because extension-only plugins are already possible: simply the existence of some `bin/.keep` file. Extension-only plugins are useful for many reasons; some include discoverability within the CLI (if it's implemented), a common download and update mechanism. 

The plugin code is already kept outside of asdf and I really don't think it's our role to police how people are able to use the API: these different parts of the plugin interface are conceptually mutually exclusive

So the dependence on the existence of `bin/` is simply confusing to consumers (it's not documented!), and it's conceptually buggy. Which is why I decided to fix this.

**Comment by jthegedus** [comment]
The docs list:
- `bin/list-all`
- `bin/download`
- `bin/install`

as **required** scripts for plugins. The fact that this requirement has/was/is poorly enforced is more of the bug IMO.

The API was designed for a particular use case, of which this use case (non-version managing extension scripts) wasn't a consideration.

Without policing how it is used will lead the tool to be used for purposes that it wasn't intended. For example, people have been using asdf as a system package manager, which then leads to feature requests for enhancing that use case.

In this case, I am inclined to merge, close issues and move on. But this may be something we restrict in future as we redefine and more clearly define the plugin API and plugin repository.
