### ISSUE TITLE
asdf broken after update via asdf update. Syntactic error when sourcing .bashrc

### ISSUE THREAD

**Issue by rogeliozarate** [asdf-vm/asdf#727]
In Ubuntu 18.04.4 LTS ran asdf update then I got:

Order asdf not found, you may want:
''' Orden «asdf» no encontrada. Quizá quiso decir:
  la orden «sdf» del paquete deb «sdf»
  la orden «sadf» del paquete deb «sysstat»
  la orden «asdfg» del paquete deb «aoeui»
  la orden «adsf» del paquete deb «ruby-adsf»
Pruebe con: sudo apt install <nombre del paquete deb>

Then remove ~/.asdf and attempted to install via GIT with:
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8

Same result, not found.

If I source .bashrc I got:

source ~/.bashrc 

bash: /home/cobi/.asdf/asdf.sh: línea 8: error sintáctico cerca del elemento inesperado `elif'
bash: /home/cobi/.asdf/asdf.sh: línea 8: `elif [[ "$_under" == *".sh"']]; then
bash: /home/cobi/.asdf/completions/asdf.bash: línea 1: error sintáctico cerca del elemento inesperado `$'{\r''
'ash: /home/cobi/.asdf/completions/asdf.bash: línea 1: `_asdf() {
bash: /home/cobi/.asdf/plugins/java/set-java-home.sh: No existe el archivo o el directorio

Syntactic error line 8 asdf.sh

**Comment by jthegedus** [comment]
Can you share which version of Bash you are running and the full cat of `/home/cobi/.asdf/asdf.sh`?

**Comment by rogeliozarate** [comment]
BASH version is:
GNU bash, versión 4.4.20(1)-release (x86_64-pc-linux-gnu)

Content of /home/cobi/.asdf/asdf.sh is:
```
# For Korn shells (ksh, mksh, etc.), capture $_ (the final parameter passed to
# the last command) straightaway, as it will contain the path to this script.
# For Bash, ${BASH_SOURCE[0]} will be used to obtain this script's path.
# For Zsh and others, $0 (the path to the shell or script) will be used.
_under="$_"
if [ "${BASH_SOURCE[0]}" != "" ]; then
  current_script_path="${BASH_SOURCE[0]}"
elif [[ "$_under" == *".sh" ]]; then
  current_script_path="$_under"
else
  current_script_path="$0"
fi

export ASDF_DIR
ASDF_DIR="$(dirname "$current_script_path")"
# shellcheck disable=SC2016
[ -d "$ASDF_DIR" ] || echo '$ASDF_DIR is not a directory'

# Add asdf to PATH
#
# if in $PATH, remove, regardless of if it is in the right place (at the front) or not.
# replace all occurrences - ${parameter//pattern/string}
ASDF_BIN="${ASDF_DIR}/bin"
ASDF_USER_SHIMS="${ASDF_DATA_DIR:-$HOME/.asdf}/shims"
[[ ":$PATH:" == *":${ASDF_BIN}:"* ]] && PATH="${PATH//$ASDF_BIN:/}"
[[ ":$PATH:" == *":${ASDF_USER_SHIMS}:"* ]] && PATH="${PATH//$ASDF_USER_SHIMS:/}"
# add to front of $PATH
PATH="${ASDF_BIN}:$PATH"
PATH="${ASDF_USER_SHIMS}:$PATH"

# shellcheck source=lib/asdf.sh
# Load the asdf wrapper function
. "${ASDF_DIR}/lib/asdf.sh"
```

**Comment by rogeliozarate** [comment]
Unable to replicate behaviour in other systems.
Issue may be related to some change in readline.
