### ISSUE TITLE
no Ruby script found in input (LoadError) when asdf called directly

### ISSUE THREAD

**Issue by etcook** [asdf-vm/asdf#729]
The asdf integration in the JetBrains projects calls asdf.sh directly, and periodically, I'll run into the issue below.

`
➜ . /usr/local/Cellar/asdf/0.7.8/asdf.sh && asdf local ruby 2.5.7 && ruby /Users/eugene.cook/.asdf/shims/rails console
Traceback (most recent call last):
/Users/eugene.cook/.asdf/installs/ruby/2.5.7/bin/ruby: no Ruby script found in input (LoadError)
`
I've tried removing the shims directory completely and triggering a reshim, without success.

**Comment by Stratus3D** [comment]
This looks similar to https://github.com/asdf-vm/asdf/issues/64.

**Comment by etcook** [comment]
> This looks similar to #64.

Yes. I did look through there, but the resolution (adding the path) that was merged in didn't resolve it, so I assumed it was a different issue.

**Comment by Stratus3D** [comment]
@etcook are you running the latest version of asdf? Can you post the output of `asdf info`?
