### ISSUE TITLE
Brew install on Mac installs bash scripts instead of zsh 

### ISSUE THREAD

**Issue by pkbyron** [asdf-vm/asdf#732]
When I use `brew install asdf` the install works, but when I go to run asdf I get an error...
```
 ~ % asdf
env: bash\r: No such file or directory
```

I look into the script and see that it's installed bash (!)
```
~ % cat /usr/local/bin/asdf
#!/usr/bin/env bash

# shellcheck source=lib/utils.bash
source "$(dirname "$(dirname "$0")")/lib/utils.bash"

find_cmd() {
  local cmd_dir="$1"
...
```
How can the brew install be updated to do zsh?

**Comment by jthegedus** [comment]
Hey mate, `brew install asdf` is not the complete setup. It looks like you need to complete the setup https://asdf-vm.com/#/core-manage-asdf-vm

A lot of our scripts are suffixed with `.bash` but that doesn't mean they don't work in other shells. Bash, ZSH and Fish are the supported shells of `asdf`

**Comment by pkbyron** [comment]
Hi Jthegedus, 

thanks for your response.
I followed the brew install approach on my new macbook pro (2015) and it worked without a hitch.

But when I did it on this machine (Mac Pro 2014) it failed with brew; and I also tried the asdf-vm approach and also followed the instructions for asdf for oh-my-zsh too. 
Sadly no luck. 

When I run the asdf.sh I get the following...
```
pkbyron@desktop .asdf % ./asdf.sh
./asdf.sh: line 8: syntax error near unexpected token `elif'
'/asdf.sh: line 8: `elif [[ "$_under" == *".sh" ]]; then
```
and when I start a new terminal I get this:
```
/Users/pkbyron/.asdf/asdf.sh:8: parse error near `elif'
```

Here is my ~/.zshrc
```
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
  autoload -Uz compinit
  compinit
fi

plugins=(asdf)
. $HOME/.asdf/asdf.plugin.zsh
```

So am thinking something is wrong under the hood.
I need asdf as working on projects that use elixir 1.10 and 1.7.4.
I might try a reinstall of the OS.

**Comment by jthegedus** [comment]
Hmm, well the `oh-my-zsh` plugin for `asdf` will automatically import the `asdf.sh` script. So that should be fine.

From what I know `. $HOME/.asdf/asdf.plugin.zsh` isn't a file in the repo.

Can you share what version of Bash you're using? You may have to update Bash

**Comment by pkbyron** [comment]
I was using the standard bash version 3.x...; I updated it to version 5.0.17 - but that didn't work either.

Update: In the end I installed the oh-my-zsh, which totally rewrote the .zshrc, and then installed as per it's github readme - and this worked. So no I have it working. thanks for your help.

**Comment by jthegedus** [comment]
Right, the line 
```
plugins=(asdf)
```
in your original `.zshrc` indicated that you were using OMZSH, but if you hadn't installed that then that would be the cause.
