### ISSUE TITLE
setting local version via "plugin path:<path/to/bin>" does not work

### ISSUE THREAD

**Issue by lassepe** [asdf-vm/asdf#735]
I am looking for a way to add own built binaries (i.e. locally build from source)  to be managed by asdf-vm.

That is, if I have some package `xyz` and I have some versions already installed via the official plugin, it would be great to also add some source built binary with something like `asdf install xyz /path/to/local/binary`.

Is there already a way to do this?

**Comment by vic** [comment]
On your `.tool-versions` file, you can specify a `xyz path:MY_XYZ_PATH` where `MY_XYZ_PATH/bin` should contain executables as if they were installed by the `xyz` plugin.


Take a look at https://asdf-vm.com/#/core-configuration?id=tool-versions

**Comment by lassepe** [comment]
Thank you for your quick reply. This does not seem to work though. For example have  a custom julia binary at `/home/lassepe/worktree/julia/usr/bin` but specifying 

`julia path:/home/lassepe/worktree/julia/usr/` in my `.tool-versions` file still results in 
`No julia executable found for julia path:/home/lassepe/worktree/julia/usr`

**Comment by lassepe** [comment]
I guess this is the same issue as described in https://github.com/asdf-vm/asdf/issues/559

**Comment by lassepe** [comment]
Okay, I figured it out. This is due to the fact that `asdf-julia` has a bit of a weird directory layout. When specifying `julia path:MY_JULIA_PATH` the binary has to be located at `MY_JULIA_PATH/julia/bin/julia`

**Comment by jthegedus** [comment]
@lassepe Perhaps raise this as a documentation improvement over at the asdf-julia repo. Thanks for sharing your solution :+1:

**Comment by inoas** [comment]
Is this per plugin or a global thing?
Could it look into the dir specified and THEN into bin?
See: https://github.com/gleam-lang/gleam/issues/3085#issuecomment-2092707586

**Comment by Stratus3D** [comment]
@inoas it's all up to the plugin. The gleam plugin in theory could support that scenario if it wanted.
