### ISSUE TITLE
Problem running on Windows 10 WSL1 Ubuntu 20.04

### ISSUE THREAD

**Issue by ukdoc** [asdf-vm/asdf#736]
Please forgive me if i don't follow the right processes as i am new to github and learning how to do things as i go.

Windows 10 19.09 with WSL1

Installed to Ubuntu 16.04 under wsl1 with no problems, all works as expected.

Just installed Ubuntu 20.04 under wsl1 and installed asdf from a git clone.

Have tried with the latest released version and also the HEAD release to see if it made a difference, unfortunately it did not.

`. $HOME/.asdf/asdf.sh`
```
dave@psiPC7:~$ asdf
/home/dave/.asdf/lib/commands/command-help.bash: line 4: asdf_version: command not found
version:

/home/dave/.asdf/lib/commands/command-help.bash: line 6: asdf_dir: command not found
cat: /help.txt: No such file or directory
/home/dave/.asdf/lib/commands/command-help.bash: line 19: get_plugin_path: command not found
```
From the limited testing i have been able to do it appears to not be loading `lib/utils.bash` which contains the `asdf_version()` and `asdf_dir()` functions.

Why this is different between the 16.04 and 20.04 is unclear.

### Environment
**OS**: Windows 10 19.09 WSL1 Ubuntu 20.04

**asdf version**: Have tried latest release and HEAD versions

**asdf plugins affected (if relevant)**: n/a

**asdf plugins installed**: none, clean install

**Comment by ukdoc** [comment]
I am spinning up  a Ubuntu 20.04 VM to test.

**Comment by jthegedus** [comment]
Hey @ukdoc I would _guess_ this is related to WSL1 difference between 18.04 and 20.04

I've upgraded from 18.04 to 20.04 on native Ubuntu and on WSL2 without issues. All Windows WSL issues reported in this repo are related to **WSL1** which should be deprecated soon as MS just released WSL2 in the latest (late May 2020) Win10 update.

**Comment by ukdoc** [comment]
I will try and force the upgrade to May 2020 release so i can upgrade to WSL2 and then try again. Thanks for coming back to me.

**Comment by jthegedus** [comment]
@ukdoc Let me know how you go and please reopen if your issue persists
