### ISSUE TITLE
[Proposal] Option "-k" to keep source

### ISSUE THREAD

**Issue by HashNuke** [asdf-vm/asdf#74]
Inspired by `ruby-build`'s -k option.

Passing this option should uncompress and compile the package in `~/.asdf/sources/<plugin>/<version>` instead of the tmp dir. This is plugin specific.

```
asdf install ruby 2.3.0 -k
```
- If -k is passed the plugin's `install` script is passed a source-compile path as another argument.
- The plugin's `install` script uses a temp or the source-compile path to compile the package depending on the option passed.

Atleast for now, this would make it possible to use `gdb` with `ruby`. I have this work-in-progress in the `keep-source` branch.

**Comment by HashNuke** [comment]
keep-source support is now in the "keep-source" branch of asdf and asdf-ruby.

setting KEEP_SOURCE=1 when installing a ruby will preserve the source in ~/.asdf/sources/ruby/<version>

This helped with using ruby with gdb.

If I can get getopt working with bash, I'll send a PR after adding the "-k" option.

**Comment by tuvistavie** [comment]
Nice! I think this would make sense for Python too, I will add the option to my plugin when you are done here!

**Comment by jayvdb** [comment]
I think this should actually be the default, and another command is added to cleanup unneeded source & build dirs.

e.g. I just installed Python, but I didnt have `sqlite3-devel` installed, resulting in

```console
Downloading Python-3.6.7.tar.xz...
-> https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tar.xz
Installing Python-3.6.7...
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
```

After installing the devels, asdf needs to refetch everything, and rebuild everything, which is wasted bytes and time.
