### ISSUE TITLE
Add support for nushell

### ISSUE THREAD

**Issue by leesiongchan** [asdf-vm/asdf#745]
https://www.nushell.sh/

Currently I am using the trick suggested by [John](https://github.com/asdf-vm/asdf/issues/576#issuecomment-538018689)

```nu
# in ~/.config/nu/config.toml
path = ["<home_path>/.asdf/bin", "<home_path>/.asdf/shims"]
```

**Comment by lpil** [comment]
Would a PR to the documentation be the solution here?

**Comment by Stratus3D** [comment]
> Would a PR to the documentation be the solution here?

yes, along with any shell completions and a `asdf.<nu shell extension>` file if needed.

**Comment by carlosonrails** [comment]
Hey guys, couldnt find that archive toml, we should create?

**Comment by fwfurtado** [comment]
Hey guys, I opened this [PR](https://github.com/asdf-vm/asdf/pull/1355) to resolve this issue

Let me know if I need to change something

**Comment by jthegedus** [comment]
Thanks @fwfurtado

I think next steps with this is to run similar tests as we have with the other shells: `/test/asdf_elvish.bats` etc

If anyone who is watching this thread wants to chip in, that would be great :)
