### ISSUE TITLE
plugin-test returns false positive when used to test asdf-jq plugin

### ISSUE THREAD

**Issue by AZMCode** [asdf-vm/asdf#756]
**Describe the bug**
Using plugin-test to test the asdf-jq plugin yields a positive result regardless of actual installation status

**To Reproduce**

Tell us what actions you performed before the issue occurred

In a linux box with asdf:
```asdf plugin-test jq https://github.com/focused-labs/asdf-jq.git```

**Expected behavior**

Test returns failure to install jq in linux. See [this](https://github.com/asdf-vm/asdf-plugins/issues/263).

**Actual behavior**
console prints:
```jq is already installed```
Causing asdf-jq's CI to return a false positive.

### Environment

**OS**: Linux

**asdf version**: v0.7.8-4a3e3d6

**asdf plugins affected (if relevant)**: asdf-jq

**asdf plugins installed**: none

**Comment by RafalSkolasinski** [comment]
observed the same today

**Comment by danhper** [comment]
`asdf latest jq` seems to be returning an empty string, which is causing the issue.
This particular issue should be fixed by #772 but I am not sure if `asdf latest jq` fails because of an issue on asdf side or on asdf-jq side so please open a new issue if it seems to be on the asdf side.

**Comment by RafalSkolasinski** [comment]
@danhper would you please ping me once #772 is then merged and part of a release? I could test it then.

**Comment by jthegedus** [comment]
@RafalSkolasinski Once merged to master you can use `asdf update --head` to get the latest commit on `master`

**Comment by RafalSkolasinski** [comment]
@jthegedus Not sure where to actually open another issue if required - I only commented as I spotted the same issue when playing around so you guys have information that happened for other user too.

Anyway, after doing `assdf update --head` as you suggested there still seem to be problem with `jq`:
```bash
rskolasinski@machine42:~$ asdf latest jq
rskolasinski@machine42:~$ asdf install jq latest
jq  is already installed
rskolasinski@machine42:~$ asdf list jq
  No versions installed
rskolasinski@machine42:~$
```

**Comment by danhper** [comment]
`asdf latest` searches for versions that start by a number. All versions return by `jq` start by `jq-`, hence `latest` returns nothing. I would rather open an issue on the jq plugin side of things.

**Comment by AZMCode** [comment]
Already fixed in my PR
