### ISSUE TITLE
Install single tool from .tool-versions

### ISSUE THREAD

**Issue by fajpunk** [asdf-vm/asdf#759]
**Is your feature request related to a problem? Please describe.**
We have a large repo that contains code that uses many different tools.  We'd like to test different things in this repo in different CI jobs, and we don't want to install _all_ of the tools specified in `.tool-versions` for every job, but we do want to install the correct versions of some subset of the tools we need, at the versions specified in  `.tool-versions`.

For example, we have repo containing a ruby app and Terraform config to provision infrastructure for this app.  We want to validate the Terraform config in a CI job, so we want to install the correct version of Terraform, but we don't want to take the time/resources to install Ruby.

**Describe the solution you'd like**
One possible implementation would be to leave the version off of the install command:
```asdf install terraform```
And have that install the version of terraform specified in `.tool-versions`

**Describe workarounds you've considered**
I'm aware that if a plugin is not installed that matches a tool in `.tool-versions` then that tool won't be installed with a bare `asdf install`, but the environment that I'm running these jobs in may have all matching plugins installed.

I've also considered putting different `.tool-versions` files in the different directories containing the different code, but it is nice for development to be able to do a bare `asdf install` and have all the tools that I'll need.  I want to have my cake and eat it too :)

**Comment by jthegedus** [comment]
> I want to have my cake and eat it too :)
Don't we all! 😄 

`asdf install` -> install all versions defined in `.tool-versions`.
🆕 `asdf install <name>` -> install version for tool <name> in `.tool-versions`.
`asdf install <name> <version>` -> install specified version for tool.

This type of behaviour makes sense to me, especially if it speeds up my CI on a large project.

**Comment by jthegedus** [comment]
Thanks @fajpunk !

**Comment by ulwlu** [comment]
@jthegedus 
Hi. I strongly want to `plugin add` automatically as well.

What do you think?

If you are agreed, I will send PR.

**Comment by jthegedus** [comment]
@ulwlu I strongly disagree with automatic install of `plugin add`. I will write up why in a GitHub Discussion and share here as this Issue covers a different feature request which has been implemented.

**Comment by ulwlu** [comment]
I see, ok I will wait for your link.

In the case I understand that reason, I will give up.

**Comment by trothwell** [comment]
Perhaps a better way than: `cut -d\  -f1 .tool-versions|grep -E '^[^#]'|xargs -L1 asdf plugin add`

**Comment by givensuman** [comment]
I'm interested in the feature described here. What would be the reasoning against having a way to automatically `plugin-add` languages referenced in `.tool-versions`?

FWIW, the above line works really well in the meantime. Here is a script built around it

```bash
#!/bin/bash
printf "Installing some programming languages...\n\n"

if [ ! -d "$HOME/.asdf" ]; then
  echo "Downloading asdf..."
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.15.0 &>/dev/null
fi

mapfile -t languages < <(cut -d\  -f1 "$HOME/.tool-versions" | grep -E '^[^#]' | xargs -L1 echo)

for language in "${languages[@]}"; do
  printf "Registering %s plugin..." "$language"
  ~/.asdf/bin/asdf plugin-add "$language" &>/dev/null
  printf "\tDone!\n"
done

printf "\nInstalling languages...\n\n"
~/.asdf/bin/asdf install

printf "\nAll done!\n"

cat ~/.tool-versions

```
