### ISSUE TITLE
plugin-remove without args removes all installed plugins

### ISSUE THREAD

**Issue by duijf** [asdf-vm/asdf#76]
When [`get_plugin_path()`](https://github.com/asdf-vm/asdf/blob/master/lib/utils.sh#L56) is called without arguments, it simply returns the plugin directory.

[`plugin_remove_command()`](https://github.com/asdf-vm/asdf/blob/master/lib/commands/plugin-remove.sh#L1) then `rm -rf`s this plugin directory, as well as all installation directories.

Working on a patch to check args in `plugin_remove_command()`

**Comment by tuvistavie** [comment]
@duijf Thanks for reporting!
That's indeed not a desirable behavior.
Thank you very much, we'll be looking forward to your patch then!

**Comment by duijf** [comment]
Fixed in master.
