### ISSUE TITLE
`asdf latest` command should defer to plugin to determine latest version

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#763]
**Is your feature request related to a problem? Please describe.**

The `asdf latest` command assumes versions listed by the `list-all` command are semantic versions. This assumption is not necessarily correct for all plugins and could cause problems.

**Describe the solution you'd like**

The `asdf latest` should invoke a plugin callback named `latest-stable` when one is present to compute the latest version. If the `latest-stable` script is missing the `asdf latest` command should fallback to computing the latest version as it does now by assuming the versions are semantic versions.

**Describe workarounds you've considered**

None. This seems to be the most straightforward solution to this problem.

**Additional context**

This is actually what was requested for https://github.com/asdf-vm/asdf/issues/216 but was never properly implemented.

* https://github.com/asdf-vm/asdf/pull/575
* https://github.com/asdf-vm/asdf/issues/216

**Comment by jthegedus** [comment]
Will this also resolve https://github.com/asdf-vm/asdf/issues/648 ?

**Comment by threkk** [comment]
I have the same issue here. I am working on a [plugin](https://github.com/threkk/asdf-age) for [age](https://github.com/FiloSottile/age) and even if age is stable enough for being recommended to use with [sops](https://github.com/mozilla/sops) among other use cases, the command `asdf latests` fails (and therefore, the pipeline) as all the versions are tagged with `rc` or `beta`. Having the change of explicitly declaring which one is the latest stable version would allow the plugin to work.
