### ISSUE TITLE
download script ignored in plugin

### ISSUE THREAD

**Issue by jamesstidard** [asdf-vm/asdf#765]
**Describe the bug**

I'm working on splitting [my plugin](https://github.com/jamesstidard/asdf-qt/tree/download-pre-compiled) into the separate `bin/download` and `bin/install` scripts, however, `asdf` doesn't appear to find my new `bin/download` script and instead called `bin/install` as if it was a legacy version.

I've checked the execute bit on the files, which was the first thing that came to mind:

```console
$ ls -la ~/.asdf/plugins/qt/bin/
total 32
drwxr-xr-x  5 james  staff   160 21 Jul 21:24 ./
drwxr-xr-x  7 james  staff   224 21 Jul 21:24 ../
-rwxr-xr-x  1 james  staff  6221 21 Jul 21:24 download*
-rwxr-xr-x  1 james  staff   963 21 Jul 21:24 install*
-rwxr-xr-x  1 james  staff   628 21 Jul 21:24 list-all*
```

**To Reproduce**

```console
$ asdf plugin add qt https://github.com/jamesstidard/asdf-qt.git
$ asdf plugin update qt download-pre-compiled
Updating qt...
From https://github.com/jamesstidard/asdf-qt
 * [new branch]      download-pre-compiled -> download-pre-compiled
Switched to branch 'download-pre-compiled'
$ asdf install qt 5.13.2
ASDF_DOWNLOAD_PATH enviroment variable required
```

The final error on `asdf install qt 5.13.2` comes from my `bin/install` script where it's assuming a $ASDF_DOWNLOAD_PATH directory exists and is populated.

### Environment

**OS**:
macOS 10.15.6 (19G73)

**asdf version**:
v0.7.8

**Comment by Stratus3D** [comment]
Sorry @jamesstidard, that feature has been merged but not released yet. Today I tagged `v0.8.0-rc1`, so if you upgrade to that version you will get the `bin/download` callback script support.

If you want your plugin to work with both versions of asdf (`0.8.*` and `0.7.*`) check for the presence of the `ASDF_DOWNLOAD_PATH` environment variable, and if it is not set download the qt code in the `bin/install` callback, and if it is set then assume the `bin/download` script already downloaded it (sounds like you've already implemented `bin/download` properly).

**Comment by jamesstidard** [comment]
Hi @Stratus3D , I had noticed that it was probably unreleased. I think I spotted the last release to be back in March when I looked. I forgot to come and close this issue.

Though, I'm glad I didn't because now I know about that `ASDF_DOWNLOAD_PATH` env var, thank you, I'll implement that.
