### ISSUE TITLE
system version doesn't get resolved correctly

### ISSUE THREAD

**Issue by vscncls** [asdf-vm/asdf#767]
**Describe the bug**

After installing any version of a package, using the system version will cause asdf to hang.

**To Reproduce**

1. Install the nodejs plugin (other plugins show the same behaviour)
2. Install any version of node
3. `asdf global nodejs system`
4. `node`

**Expected behavior**

The system's version of the nodejs repl should start

**Actual behavior**

It hangs. In https://github.com/asdf-vm/asdf/blob/master/lib/commands/command-exec.bash#L16 the variable `executable_path` is always assigned the value `/home/lucas/.asdf/shims/node`, starting an infinite loop.

### Environment

**OS**: Arch Linux 5.7.7-arch-1-1

**asdf version**: v0.7.8

**asdf plugins installed**: asdf-nodejs, asdf-python

**Comment by danhper** [comment]
It seems to be working for me, I'm also on Arch. Could you please try master branch and see if it works there?
Thanks!

**Comment by vscncls** [comment]
I still have the issue with the master branch, but I've found a workaround

```diff
diff --git a/lib/utils.bash b/lib/utils.bash
index 468b7ef..a8b7e37 100644
--- a/lib/utils.bash
+++ b/lib/utils.bash
@@ -728,6 +728,9 @@ with_shim_executable() {
     run_within_env() {
       local path
       path=$(echo "$PATH" | sed -e "s|$(asdf_data_dir)/shims||g; s|::|:|g")
+      if [ $full_version == "system" ]; then
+        path=$(echo $path | sed -e 's/\.asdf\/shims//g')
+      fi

       executable_path=$(PATH=$path command -v "$shim_name")

```

the problem is that when `command -v` runs, the `.asdf/shims` folder is on `$path` and it finds the `node` executable there, starting an infinite loop. This patch removes the `.asdf/shims` folder from `$path` when using the system version

**Comment by danhper** [comment]
`path=$(echo "$PATH" | sed -e "s|$(asdf_data_dir)/shims||g; s|::|:|g")` should already be doing this.
Is your `ASDF_DATA_DIR` set to some other location? I could not reproduce this with a fresh Arch:

```Dockerfile
FROM archlinux:latest

RUN pacman -Syy && pacman -S git nodejs --noconfirm
RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf
RUN echo -e "-n. ~/.asdf/asdf.sh" >> ~/.bashrc
RUN . ~/.asdf/asdf.sh && asdf plugin add nodejs
RUN bash -c ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
RUN . ~/.asdf/asdf.sh && asdf install nodejs 12.16.1
RUN . ~/.asdf/asdf.sh && asdf global nodejs 12.16.1
RUN . ~/.asdf/asdf.sh && node --version
# prints 12.6.1
RUN . ~/.asdf/asdf.sh && asdf global nodejs system
RUN . ~/.asdf/asdf.sh && node --version
# prints 14.7.0 which is the system version
```

**Comment by vscncls** [comment]
no, ASDF_DATA_DIR is empty

```
> echo $ASDF_DATA_DIR

>
```
---

> `path=$(echo "$PATH" | sed -e "s|$(asdf_data_dir)/shims||g; s|::|:|g")` should already be doing this.

it isn't for me, `$(asdf_data_dir)` returns `/home/lucas//.asdf/shims`, but my `$PATH` contains both `/home/lucas//.asdf/shims` and `/home/lucas/.asdf/shims`, so `/home/lucas/.asdf/shims` is always present in `$path`

---

The Dockerfile worked just fine

**Comment by vscncls** [comment]
one important thing I just noticed, the problem seems to only happen with the fish shell, if I start my terminal using bash and run `~/.asdf/asdf.sh` the problem is not present, because only `/home/lucas//.asdf/shims` is on my $PATH, there's no `/home/lucas/.asdf/shim`.

**Comment by vscncls** [comment]
I managed to solve the problem, if the user's $HOME ends with a `/` and asdf is being used with the fish shell the problem described above happens. The source of the problem is these lines [https://github.com/asdf-vm/asdf/blob/master/asdf.fish#L7-L19](https://github.com/asdf-vm/asdf/blob/master/asdf.fish#L7-L19), when the user's $HOME ends with '/' the shims folder gets appended to $PATH twice (`/home/lucas//.asdf/shims` && `/home/lucas/.asdf/shim`) but only one of these folders is removed in `path=$(echo "$PATH" | sed -e "s|$(asdf_data_dir)/shims||g; s|::|:|g")`. This issue doesn't happen when using bash because of the logic in this line [https://github.com/asdf-vm/asdf/blob/master/asdf.sh#L24](https://github.com/asdf-vm/asdf/blob/master/asdf.sh#L24)

**Comment by danhper** [comment]
Thanks a lot for investigating further.
I guess we might want to fix this.
It would be great if you could send a PR for that.
Thanks again.
