### ISSUE TITLE
Feat: Document plugin `bin/install` callback implementation for backward compatible asdf support

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#768]
> If you want your plugin to work with both versions of asdf (`0.8.*` and `0.7.*`) check for the presence of the `ASDF_DOWNLOAD_PATH` environment variable, and if it is not set download the qt code in the `bin/install` callback, and if it is set then assume the bin/download script already downloaded it (sounds like you've already implemented `bin/download` properly).

This documentation doesn't explain this, but it is conceivable that plugin developers will want to support older versions of asdf.

See: https://github.com/asdf-vm/asdf/issues/765

**Comment by jthegedus** [comment]
Docsify is going to add version history docs support, so I would like to keep the docs for features/bugfixes within the same git tag if possible to allow that experience when the tools support it.
