### ISSUE TITLE
Is it "asdf plugin {cmd}" or "asdf plugin-{cmd}"?

### ISSUE THREAD

**Issue by RafalSkolasinski** [asdf-vm/asdf#773]
Documentation seems to suggest that usage syntax for plugins is
```bash
asdf plugin {cmd here}
```

but fish (and I believe zsh as well) completion suggest that syntax is
```bash
asdf plugin-{cmd here}
```

both seems to work but a small clarification on difference would be nice

**Comment by jthegedus** [comment]
They function the same. Initially it was `asdf plugin-{cmd here}` but `asdf plugin {cmd here}` was added as it is more fluid. The Shell completions should probably be updated to reflect the newer method. Happy to receive a PR?

**Comment by Stratus3D** [comment]
As @jthegedus said, going forward the canonical form is `asdf plugin {cmd}`, without the hyphen.

Looking at our doc site now it appears we are consistent with the use of `asdf {cmd} {sub cmd}` so I am closing this ticket. If you see anything we missed let us know.
