### ISSUE TITLE
not able to install erlang using asdf

### ISSUE THREAD

**Issue by siddhant3030** [asdf-vm/asdf#776]
**Describe the bug**

I'm trying to install erlang version 22.1.8 and I'm using asdf version 0.7.8.
**To Reproduce**

Tell us what actions you performed before the issue occurred

1. I installed asdf using brew install asdf 
2. asdf plugin-add elixir 
2. asdf install erlang 22.1.8

After this, it's giving me this error 

`asdf_22.1.8 is not a kerl-managed Erlang/OTP installation
No build named asdf_22.1.8
Downloading OTP-22.1.8.tar.gz to /Users/siddhant/.asdf/plugins/erlang/kerl-home/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    239      0 --:--:-- --:--:-- --:--:--   239
100 52.4M    0 52.4M    0     0  7346k      0 --:--:--  0:00:07 --:--:-- 9323k
Extracting source code
Building Erlang/OTP 22.1.8 (asdf_22.1.8), please wait...
Build failed.
                             ^
 CC	obj/x86_64-apple-darwin19.6.0/opt/smp/prim_file_nif.o
 CC	obj/x86_64-apple-darwin19.6.0/opt/smp/zlib_nif.o
2 errors generated.
make[4]: *** [obj/x86_64-apple-darwin19.6.0/opt/smp/inet_drv.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [opt] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator] Error 2

Please see /Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.8/otp_build_22.1.8.log for full details.`

I'm kind of stuck here and not able to do anything after this. I tried uninstalling asdf and reinstalling again but this is the error I'm having every time. 

any suggestion?

**Comment by Stratus3D** [comment]
This seems very similar to the other issue you recently opened: https://github.com/asdf-vm/asdf-erlang/issues/160

Closing because this is not an issue with asdf itself but rather the asdf-erlang plugin.
