### ISSUE TITLE
VS Code can't find php executable

### ISSUE THREAD

**Issue by choallin** [asdf-vm/asdf#779]
I have installed the php lsp extension for vscode.
This extension wants to install the lsp server itself but it can't find a php executable.
Even after pointing to the executable with a setting (php.executablePath: ~/.asdf/shims/php) I always get this error:

> Error spawning PHP: Command failed: php --version
> asdf: No version set for command php
> you might want to add one of the following in your .tool-versions file:
> php 7.2.33

**To Reproduce**

Install php intellisense extension in vscode, restart the editor.
Then the error pops up

**Expected behavior**
It should find a php version so that the extension can install the lsp server

**Actual behavior**
Error message appears

### Environment

**OS**:
Ubuntu 20.04
**asdf version**:

**asdf plugins affected (if relevant)**:
v0.7.8-4a3e3d6
**asdf plugins installed**:
elixir
erlang
nodejs
php
ruby

**Comment by jthegedus** [comment]
@choallin Can you update to `asdf 0.8.0` and also run `asdf info` and share that here? Does running `php` from your command line resolve the shim, or is it just VSCode that can't find it?

**Comment by nmay231** [comment]
@choallin I've always had issues with vscode using the wrong version of python. If the PHP extension allows for it, I would set the path to the desired PHP version manually.

For python, I find the path of the desired version of python, e.g. `PYTHON_HOME/bin/python`. Then, I press `ctrl-shift-P` in vscode to execute the command `Python: select python interpreter` and paste the path to that python. If there is not a better solution, you can check if the PHP extension supports a similar feature.

**Comment by Stratus3D** [comment]
Closing due to lack of a response from @choallin.
