### ISSUE TITLE
Consider Banning echo command

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#781]
**Is your feature request related to a problem? Please describe.**

As described in https://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo/65819#65819, `echo` has a lot of disadvantages and should never be passed uncontrolled data, which is something we often do. 

**Describe the solution you'd like**

Banning the `echo` command entirely would be an effective way of avoiding these issues and would force us to be more explicit with `printf` formatting.

**Describe workarounds you've considered**

We can continue use `echo` when it printing controlled data, but the inconsistency may not be caught by reviewers or our code quality tools. Banning the command would ensure these issues are not possible.

**Comment by Stratus3D** [comment]
Related - http://www.etalabs.net/sh_tricks.html

**Comment by jthegedus** [comment]
I was going to suggest banning `echo` on my output refactor/standardisation. `printf` is definitely my preference here.

**Comment by Stratus3D** [comment]
@jthegedus https://github.com/asdf-vm/asdf/pull/806 is ready for review now.
