### ISSUE TITLE
Getting tar: Error opening archive: Unrecognized archive format when downloading istioctl

### ISSUE THREAD

**Issue by danikgan** [asdf-vm/asdf#784]
I am trying to download `istioctl` but getting the following error:
![CleanShot 2020-08-20 at 17 58 37@2x](https://user-images.githubusercontent.com/16155742/90795897-eccb1180-e30e-11ea-88d0-4c17e2c4e9a6.png)

Possible solution: https://stackoverflow.com/questions/42268180/tar-unrecognized-archive-format-error-when-trying-to-unpack-flower-photos-tgz

**Comment by jthegedus** [comment]
The file download and extract occurs in the plugin itself, it seems this Issue is already reported https://github.com/rafik8/asdf-istioctl/issues/1 , though if that Issues doesn't cover your particular case please open a new Issue with the plugin, thanks.

Closing this here.
