### ISSUE TITLE
Common Homebrew issues 🍻

### ISSUE THREAD

**Issue by jthegedus** [asdf-vm/asdf#785]
<details>
<summary>Background information and why this issue exists</summary>

## Background

We regularly see issues raised by Homebrew users where the solution is a missing installation step. I believe this is due to the flow Homebrew users follow which does not include the documentation site:

1. hear about `asdf`
2. install via Homebrew as they do other tools on their system
3. try using `asdf` and it does not work
4. go to GitHub and search/raise an Issue

This is understandable since few Homebrew tools require additional steps, though not considered a caveat to installing `asdf` via Homebrew and so we're unable to use the Homebrew post-install hook to direct users to the documentation site - see https://github.com/Homebrew/homebrew-core/pull/54315

Additionally, the `asdf` core team do not want to edit your Shell configurations with a `curl | bash` install script as used in tools like ZSH or nvm. It is a choice, and it comes with pros and cons.

## Solution

Ideally, we would use the aforementioned post-install log from Homebrew to direct users to complete the setup via our Documentation site. Short of this, we must capture users where they end up, GitHub Issues, before they raise an issue and direct them to the documentation site.

---

</details>

**Please read the documentation at [asdf-vm.com](https://asdf-vm.com/#/core-manage-asdf-vm?id=install) and follow all setup instructions for your OS and Shell combination.**

If we're missing some information or steps let us know and we'll fix ASAP, we want a smooth experience for all!

Note: The Homebrew install differs little from the Git installation. Installation is a `git clone` and `asdf update` performs a `git checkout` on the repo.

## Common Homebrew Issues 🍻

These apply to macOS with Homebrew `asdf` installations.

|Issue|Solution|Information|Original Issue/Sources|
|:--|:--|:--|:--|
|`asdf help` or `asdf <command>` does not work with Homebrew installation|✔ Ensure `asdf` is added to shell config|[docs: add to shell](https://asdf-vm.com/#/core-manage-asdf-vm?id=add-to-your-shell)|https://github.com/asdf-vm/asdf/issues/394, https://github.com/asdf-vm/asdf/issues/607|
|`with_shim_executable: command not found ` after `brew upgrade asdf` on macOS BigSur|✔ Reinstall CLI Tools for XCode Tools and reinstall `asdf`|[Homebrew macOS installation guide](https://docs.brew.sh/Installation#macos-requirements)|https://github.com/asdf-vm/asdf/issues/730#issuecomment-663975814 & https://github.com/Homebrew/brew/issues/7803#issuecomment-648601678|
|`command not found: complete`|✔ Do not use the OMZSH `asdf` plugin with Homebrew installation|OMZSH `asdf` plugin still relies upon the Bash completions. Use the Homebrew installed completions|https://github.com/asdf-vm/asdf/issues/692 discusses `zcompdump` and `compinit` further. Help solving the OMZSH `asdf` plugin issue is welcome, with prior discussion here https://github.com/ohmyzsh/ohmyzsh/pull/8837|

**If you identify an problem not covered here, please open a new Issue!**

**Comment by jthegedus** [comment]
I am going to close this as it's not a new issue, but we will leave it pinned to improve visibility and direct people to the documentation site.

**Comment by actual-size** [comment]
These links are all 404 at the moment, seems like most of the documentation URLs have been renamed from this scheme:
```
https://asdf-vm.com/#/core-manage-asdf-vm?id=add-to-your-shell
```
to this
```
https://asdf-vm.com/#/core-manage-asdf?id=add-to-your-shell
```

**Comment by jthegedus** [comment]
Indeed, I was hoping to fix this before someone noticed ;) Thanks @actual-size

**Comment by seivan** [comment]
I added a fix here https://github.com/Homebrew/homebrew-core/pull/73173 for the first issue.

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/54315 notwithstanding, a caveat that says something like
```
For asdf to work, add the following to your .zshrc:
  source #{prefix}/asdf.h
```
This seems to fit the requirement that caveats must be Homebrew-specific. (Indeed, this is what justifies many other similar caveats.)

**Comment by jthegedus** [comment]
@carlocab I agree, but it was declined. Feel free to PR that change to Homebrew and open up a new discussion there.

**Comment by carlocab** [comment]
Are you sure?

Note that the PR I linked to (https://github.com/Homebrew/homebrew-core/pull/54315) proposes a different change than what I suggested. That change is a caveat linking to the documentation, which isn't considered Homebrew-specific.

**Comment by jthegedus** [comment]
The reason for the _link to the docs_ being proposed is because we don't just have **one** Homebrew specific setup.

If I am on Ubuntu with Fish and using Linuxbrew, and you are on macOS with ZSH using Homebrew, how will we show the correct config for each of use. The Shell configs etc are different, something the docs is good for helping people identify with the drop-down menus.

**Comment by carlocab** [comment]
Zsh is the default shell on macOS, so those are the users who probably need the most help with configuration. Essentially the same instructions seem to work for bash.

But, ok, up to you. Was just trying to suggest a caveat that likely would get accepted. I figured that was better than none at all.

**Comment by jthegedus** [comment]
I am open to the suggestion and further discussion. I am only **one** user of `asdf`, if you PR your idea, a discussion can be had there about the efficacy.

My personal opinion is if we add your proposition, it **may** resolve the issue for the fraction of users who do not read the docs, but will **definitely suggest the wrong thing** (however almost correct) to another set of users.

I ere on the side that we should encourage people to read the docs and become familiar with their systems.

**Comment by carlocab** [comment]
You're right that it'll be the right advice for some, but the wrong advice for others. However, it'll be a signal to those for whom it's the wrong advice that they should be reading the docs to get the right one. At the moment, they don't get this at all.

**Comment by jthegedus** [comment]
I am very keen to find a solution and happy to have your input.

**Comment by carlocab** [comment]
Great. I should mention that this is just my personal opinion, so another maintainer may disagree (but I hope not), but I think a caveat that looks like this would be acceptable in Homebrew:
```
For asdf to work, add the following line at the end of your .zshrc or .bash_profile:
  source #{opt_prefix}/asdf.sh

If you use fish, you need to add this at the end of config.fish:
  source #{opt_prefix}/asdf.fish
```
It may not cover everything, but it covers enough information to be useful to (I think) the vast majority of your users. And, as mentioned, it's a signal that there's more configuration needed, so it may help in preventing duplicate issues from being opened.

**Comment by jthegedus** [comment]
@carlocab That solution looks fine to me. Is `{opt_prefix}` precomputed or computed each shell execution?

**Comment by carlocab** [comment]
`opt_prefix` should be something like `/usr/local/opt/asdf`. The `/usr/local` part will be different if a user has Homebrew installed somewhere else (e.g. `/opt/homebrew` on ARM).

Do you want to open a PR? It'll be easier to merge if I don't open one.

**Comment by jthegedus** [comment]
I would like to soon, time permitting.

**Comment by seivan** [comment]
I don't understand why that is still a discussion, the current installation of Homebrew is broken and causes issues like this https://github.com/asdf-vm/asdf/issues/892 because the instructions are unclear. Those instructions derive from a faulty Homebrew formula and installation.

Don't ask people to source some file that modifies their `$PATH` instead tell them to just add the shim folder there. 
`export PATH="$HOME/.asdf/shims:$PATH"`

Even worse the script also adds the asdf executable into their path as well, which is unnecessary, it's already there.

**Comment by carlocab** [comment]
>Don't ask people to source some file that modifies their `$PATH` instead tell them to just add the shim folder there.
>`export PATH="$HOME/.asdf/shims:$PATH"`

This would now no longer be a Homebrew-specific recommendation and would be unacceptable as a caveat. And we would be back where we started, where users file issues because they didn't read the docs.

**Comment by seivan** [comment]
> This would no longer be a Homebrew-specific recommendation and would be rejected as a caveat for the reasons outlined in [Homebrew/homebrew-core#54315](https://github.com/Homebrew/homebrew-core/pull/54315). And we would be back where we started, where users file issues because they didn't read the docs.

I didn't say it's a caveat, I'm saying the caveat would be redundant if you fixed your installation. 
People can't even run `$ asdf` or do `$ asdf help` when they install it, you could technically just put it in `$ asdf help`. 
Focus on fixing the installation first.

**Comment by carlocab** [comment]
Well, you were a little unclear about what

>tell them to just add the shim folder there

meant exactly, as the discussion was about communicating things to users via caveats. But, fair enough, I'm happy with whatever you think works.

**Comment by jthegedus** [comment]
@seivan I think @carlocab proposition is a good stopgap until your proposed changes in the Homebrew installation are understood and merged.

We need to flesh out the migration for the inevitable influx of Homebrew users who's setups will break and need manual intervention when they update from current Homebrew to your proposed update. I understand you have written about some of these (I am yet to re-read all the discussion on the PR and fully understand), but I would think we would need to update our docs here / create an issue to capture these users when they search for answers as to why their system worked and now does not.

@carlocab could we use caveats to warn users about changes from one version of the formulae to another? Is there a mechanism within Homebrew we can use to communicate this breaking change?

10k installs via Homebrew in the last 30 days isn't much on the scale of Homebrew usage, but it's a lot of users setups to break, and I would like to have something in place before the Homebrew change goes out

**Comment by carlocab** [comment]
>could we use caveats to warn users about changes from one version of the formulae to another? 

Caveats aren't really meant to change regularly, so I think other maintainers may find using them to communicate breaking changes not acceptable.

If it's a one-time thing, however, that might be fine. Note that the caveat would probably have to be crafted as if it were going to become a permanent fixture in the formula (as it's likely to stay there for a very long time).

**Comment by seivan** [comment]
> @seivan I think @carlocab proposition is a good stopgap until your proposed changes in the Homebrew installation are understood and merged.

Again, it proposes something erroneous based on a faulty installation. You've had a discussion since August about how you can justify the caveat because Homebrew requires it be tied to the quirks of the package manager, when in reality its tied to the faulty installation and not Homebrew's fault. 

I totally see why they have that requirement, because everyone would otherwise just ship something broken and demand to shove text into the caveat to justify it. 


> We need to flesh out the migration for the inevitable influx of Homebrew users who's setups will break and need manual intervention when they update from current Homebrew to your proposed update.

That's most unfortunate, but it needs to be done.


>  I understand you have written about some of these (I am yet to re-read all the discussion on the PR and fully understand), but I would think we would need to update our docs here / create an issue to capture these users when they search for answers as to why their system worked and now does not.

I can't speak for Fish, but for Zsh and Bash it's pretty straight forward. 

1. Add the shims path to their `.zshenv`, `.profile`, or `.bashrc`
```shell
export PATH="$HOME/.asdf/shims:$PATH"
```

2.  `$ rm -rf ~/.asdf/shims; asdf reshim`

Could potentially skip step 2 if https://github.com/asdf-vm/asdf/pull/893#issuecomment-800621065 was merged and released a new version at the same time, but I don't fully understand the consequences of that, something you I'm guessing would know better of. 

I took the liberty of adding `asdf reshim` as a post installation hook, but it doesn't really do anything know until it gets fixed. 

Current implementation of `$ asdf reshim` doesn't properly check if the `asdf` path is correct, though my advice is always rewrite the shims instead of whatever is going on now doesn't justify the issues it causes when the `asdf` binary moves for some reason. 

The Homebrew upgrade will change the path, so the shims will be pointing to nothing and `$ asdf reshim` doesn't manage that, hence delete and `$ asdf reshim`.

**Comment by richtong** [comment]
The biggest issue with the documentation is probably too obvious, but after you edit your .bash_profile (or whatever shell), you need to resource it, otherwise the installations will all fail on reshim.

**Comment by jthegedus** [comment]
> The biggest issue with the documentation is probably too obvious, but after you edit your .bash_profile (or whatever shell), you need to resource it, otherwise the installations will all fail on reshim.

The docs currently state in the [3. install asdf section](https://asdf-vm.com/guide/getting-started.html#_3-install-asdf):

>Restart your shell so that PATH changes take effect. Opening a new terminal tab will usually do it.

Is that not enough information? We could include the word "source", but this isn't the root cause of this issue IMO

**Comment by rogeriomq** [comment]
> Brew just updated `asdf` for me and broke my commits in VSCode with Husky.
> 
> I had to run `rm -rf ~/.asdf/shims; asdf reshim` and now it is back to working.
> 
> I know there's another topic on this where I provide a solution, but now I cannot find it 😂 , but I landed here and it's stickied so I'll leave this answer here 🤪 (maybe for myself next time & others).

PERFECT!

**Comment by agrberg** [comment]
I believe I have a pretty off-the-shelf Ruby setup. I'm on the penultimate version of macOS (15.2 — 15.3 will install tonight) using `ohmyzsh` and VSCode with RubyLSP and installed with `brew install asdf`. It looks like the `libexec` path is no more which is where zsh and VSCode were looking for `asdf.sh`. After looking through the docs, these issues, and trying a number of things I have it working again.

### 1. Zsh
replace any previous lines like `. /opt/homebrew/opt/asdf/libexec/asdf.sh` with `export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"` in `~/.zshrc`

### 2. VSCode
Add the following to `settings.json`
```json
"rubyLsp.rubyVersionManager": {
  "asdfExecutablePath": "/Users/{YOUR_NAME}/.asdf/shims",
  "identifier": "auto"
}
```

### 3. Reshim
TBH I'm not sure if this is required but I had already performed it before figuring out step 2 above. My experience also differs slightly from above.
1. remove the shims with `rm -rf ~/.asdf/shims`
2. reshim with `asdf reshim ruby 3.4.1` or whatever version you are using

With this, I'm able to get back to work. I'll update this if `asdf` updates and I'm able to remove additional config and rely on defaults again.
