### ISSUE TITLE
Consider regex validation of plugin names

### ISSUE THREAD

**Issue by jthegedus** [asdf-vm/asdf#789]
**Is your feature request related to a problem? Please describe.**
Currently we allow users to specify anything as a plugin name. We should probably validate plugin names against an allowed list of characters, as in the future with tabular output the parsing may be effected by POSIX character classes appearing within plugin names.

- asdf plugin add nodejs : is valid
- asdf plugin add :rocket::champagne::tada: : is invalid

**Describe the solution you'd like**
Simple regex validation of plugin name in [`lib/commands/command-plugin-add.bash`](https://github.com/asdf-vm/asdf/blob/8ca2af3316be03f980598c5dbcb8152b6b56e96a/lib/commands/command-plugin-add.bash#L9)

**Additional context**
`[:space:]` is probably already one character we should not allow

**Comment by danhper** [comment]
I agree this would be a good idea. I think pretty much any printable character except from spaces should be ok. Or should we stick with ascii?

**Comment by jthegedus** [comment]
>I think pretty much any printable character except from spaces should be ok. Or should we stick with ascii?

I had the same thoughts. People will try using unicode and emojis 😆 

ASCII is the safe bet IMO, especially when considering the environments `asdf` would be run in

**Comment by danhper** [comment]
Agreed, as much as I like emojis, asdf-:rocket::champagne::tada: is probably not a great plugin name :joy: 
So I guess the regexp would be something along the lines of `asdf-[a-zA-Z0-9-]` ?
Do we want to allow `.`,  `_`, `$` or other symbols. I kind of feel dashes are enough and we currently don't have any plugin using such symbols.

**Comment by jthegedus** [comment]
I've no idea of what downstream effects specific chars like `$` ir `.` could have in the codebase, but `[a-zA-Z0-9-]` is plenty IMO.
