### ISSUE TITLE
Unknown command when running Homebrew test

### ISSUE THREAD

**Issue by dnicolson** [asdf-vm/asdf#794]
**Describe the bug**

Running Homebrew tests that require binaries managed by `asdf` can fail, in this instance with this message:
`unknown command: node. Perhaps you have to reshim?`

This appears to be because in the test environment the `HOME` environment variable is [changed](https://github.com/Homebrew/brew/blob/5e5dabcadd38dc62b55e5b541047d926035f4ed8/Library/Homebrew/formula.rb#L1844) by Homebrew. It appears as though `asdf` [depends](https://github.com/asdf-vm/asdf/blob/e9c149ea212cf5bf822bbce8d01aae88caaa30b2/lib/utils.bash#L45) on this.

Homebrew Node.js installations and `nvm` do not have this problem, but as mentioned in https://github.com/asdf-vm/asdf/issues/785 maybe this is unavoidable and should just be added to the Common Homebrew Issues section?

**To Reproduce**

1. brew update
2. brew install emscripten
3. brew test emscripten

**Expected behavior**

The test to run.

**Actual behavior**

The `node` command was not found.

**Comment by jthegedus** [comment]
Thanks for reporting @dnicolson 

If the [`ASDF_DATA_DIR`](https://github.com/asdf-vm/asdf/blob/e9c149ea212cf5bf822bbce8d01aae88caaa30b2/lib/utils.bash#L42) env var was used would this issue be resolved?

Perhaps we should recommend as much to Homebrew users if this is the case? 🤔

**Comment by dnicolson** [comment]
Setting the `ASDF_DATA_DIR` environment variable doesn't seem to have any effect.

There is a predefined list (Java, Go, Rust, CURL) of environment variables that are included in the [Homebrew test environment](https://github.com/Homebrew/brew/blob/5e5dabcadd38dc62b55e5b541047d926035f4ed8/Library/Homebrew/formula.rb#L2153).

Adding `ASDF_DATA_DIR` to that list resolves the issue, but then there is the familiar warning:
 `asdf: No version set for command node`

This is only an issue with locally developing Homebrew `test` methods though (CI works fine), so maybe it should just be documented as a caveat.

**Comment by jthegedus** [comment]
>This is only an issue with locally developing Homebrew test methods
This seems very odd.

asdf only relies upon `$HOME/.asdf` as the default location to lookup shims/plugins etc, so if `ASDF_DATA_DIR` is **set outside of** `$HOME` then Homebrew shouldn't be able to affect this and the lookup of the tool should work.

Can you ensure your test is with `ASDF_DATA_DIR` outside of `$HOME`?

>maybe it should just be documented as a caveat

We should document this, yes, but I would like to investigate and understand the root cause completely

**Comment by dnicolson** [comment]
> Can you ensure your test is with ASDF_DATA_DIR outside of $HOME?

I tried setting `ASDF_DATA_DIR` to `/tmp` but it made no difference.

The environment variables seem to be ignored in the test sandbox. Only by manually adding `ASDF_DATA_DIR` to the Homebrew `formula.rb` file was I able to see any results.

**Comment by jthegedus** [comment]
>was I able to see any results.

But those results were the `asdf: No version set for command node` error you mentioned above? Is this completely resolved if you were to set a [`local`](https://asdf-vm.com/#/core-manage-versions?id=set-current-version) node version in the test environment also?

**Comment by dnicolson** [comment]
Running `asdf local nodejs 12.16.1` didn't change anything.

**Comment by jthegedus** [comment]
Sorry, I wasn't very clear. In the Homebrew test environment, where you added `asdf_data_dir`, can you also have it set the node version there?

**Comment by dnicolson** [comment]
Running `system("asdf local nodejs 12.16.1")` in `formula.rb` results in the following output:

```
asdf local nodejs 12.16.1

sed: /Users/dave/Dropbox/Mackup/.tool-versions: Operation not permitted
rm: /Users/dave/Dropbox/Mackup/.tool-versions.bak: No such file or directory
```

**Comment by jthegedus** [comment]
Okay then, seems like this is going to be an annoying issue to document. So what workarounds should we document that will allow users to get `brew test <xyz>` to work?

**Comment by dnicolson** [comment]
More investigation would be needed on how the Homebrew test environment works. I simply uninstalled `asdf` to get the tests to work.

**Comment by jthegedus** [comment]
>I simply uninstalled `asdf`

Hardly an ideal solution. Interesting that `sed` was not permitted. For documentation purposes, that `sed` call occurs in https://github.com/asdf-vm/asdf/blob/master/lib/commands/version_commands.bash#L44

**Comment by dnicolson** [comment]
Sure, I think that's the best outcome for now.

**Comment by happyfloat** [comment]
Is there any solution to this? I also run into the same issue if I want to run my cloud functions locally:
https://ion.sst.dev/docs/live/
I'm using the git version instead of homebrew for asdf
