### ISSUE TITLE
~/.asdf/completions/asdf.bash:68: command not found: complete

### ISSUE THREAD

**Issue by HMaker** [asdf-vm/asdf#808]
I was using asdf v0.7.6 with ZSH, it was working fine, then I updated asdf to v0.8.0 with `asdf update` and now I get "command not found: complete" error every time I try to run a binary handled by asdf. Is there any special setting to avoid that error?

**Comment by jthegedus** [comment]
Depending on how you have installed `asdf` and the way you're using completions changes the cause and solution to this problem. I would suggest reading the docs site https://asdf-vm.com to see if your setup follows our recommended setup config.

Prior conversation on this issue: https://github.com/asdf-vm/asdf/issues/68

**Comment by HMaker** [comment]
@jthegedus I followed the official docs for [installation](https://asdf-vm.com/#/core-manage-asdf?id=install), as I was it was working as expected in v0.7.6. Why this issue was closed if the problem was not solved? I have asdf installed on Ubuntu and use it with ZSH.

**Comment by jthegedus** [comment]
I'm glad you resolved this :+1:
