### ISSUE TITLE
Using completions on zsh results in "command not found..." 

### ISSUE THREAD

**Issue by sigmavirus24** [asdf-vm/asdf#812]
**Describe the bug**

When I start a new zshell, the following message appears:

```
zsh: complete: command not found...
```

To find where it comes from, I ran `zsh -x` and found that on version `v0.8.0-c6145d0` (and only with `source $HOME/.asdf/completions/asdf.bash` in either my `~/.zshrc` or `~/.zprofile`) I see that message immediately after the last line of the file which on my machine is:

```
$ tail -1 $HOME/.asdf/completions/asdf.bash | tee >(xsel -ib)
complete -F _asdf asdf
```

**To Reproduce**

Tell us what actions you performed before the issue occurred

1. Use zsh
2. Add asdf completions to zshrc or zprofile file
3. Run `exec zsh`

**Expected behavior**

I expect not to see an error about `complete` not being found

**Actual behavior**

I see the error above

### Environment

```shell
OS:
Linux 5.7.15-100.fc31.x86_64 #1 SMP Tue Aug 11 17:18:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
zsh 5.7.1 (x86_64-redhat-linux-gnu)

ASDF VERSION:
v0.8.0-c6145d0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/sigmavirus24/.asdf

ASDF INSTALLED PLUGINS:
golang                       https://github.com/kennyp/asdf-golang.git
python                       https://github.com/danhper/asdf-python.git
```

**asdf plugins affected (if relevant)**: 

**Screenshots**

I'm not sure this would help help but I can add them if necessary

**Additional context**

I looked at the following issues but none of the discussion was helpful:

* https://github.com/asdf-vm/asdf/issues/266
* https://github.com/asdf-vm/asdf/issues/97

They're also slightly different issues (although probably very similar)

**Comment by jthegedus** [comment]
We have native ZSH completions now. So you have two options:
- use Bash completions and install `bash-completion`
- use our native ZSH completions

Our documentation site now has much better guides for completion setups - https://asdf-vm.com/#/core-manage-asdf

Here are related conversations which I suggest reading:
- https://github.com/asdf-vm/asdf/issues/692
- https://github.com/asdf-vm/asdf/issues/68
- https://github.com/asdf-vm/asdf/issues/808

**Comment by sigmavirus24** [comment]
So if I have the `source $HOME/.asdf/asdf.sh` in my `.zshrc` then all's good? Cool. That works for me. Feel free to close
