### ISSUE TITLE
No output on running `asdf plugin-update --all`

### ISSUE THREAD

**Issue by SanchithHegde** [asdf-vm/asdf#813]
**Describe the bug**

`asdf plugin-update --all` (or `asdf plugin update --all`) exits without printing anything to stdout. 

**To Reproduce**

1. Update all `asdf` plugins by running `asdf plugin-update --all`.

**Expected behavior**

Running `asdf plugin-update --all` should update all installed plugins.

```shell
$ asdf plugin-update --all
Updating direnv...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating golang...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating nodejs...
Already on 'master'
Your branch is up to date with 'origin/master'.
```

**Actual behavior**

Running `asdf plugin-update --all` exits without printing anything to stdout.

```shell
$ asdf plugin-update --all
$
```

### Environment

```shell
$ asdf info          
OS:
Linux Vostro-3578 5.8.12-arch1-1 #1 SMP PREEMPT Sat, 26 Sep 2020 21:42:58 +0000 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-pc-linux-gnu)

ASDF VERSION:
v0.8.0-2bf076f3d330

ASDF ENVIRONMENT VARIABLES:


ASDF INSTALLED PLUGINS:
direnv                       git@github.com:asdf-community/asdf-direnv.git
golang                       git@github.com:kennyp/asdf-golang.git
nodejs                       git@github.com:asdf-vm/asdf-nodejs.git
```

**asdf plugins affected (if relevant)**:
N/A

**Screenshots**
N/A

**Additional context**
N/A

### Possible Fix

I was able to fix this by changing:

```shell
read -r -d '' dir
```

to:

```shell
read -r dir
```

on [`command-plugin-update.bash#L13`](https://github.com/asdf-vm/asdf/blob/2bf076f3d33087966cdb4de52cfdf0042eb7c076/lib/commands/command-plugin-update.bash#L13).

---

This is not related to the issue, only a warning and can be ignored. I'm mentioning it so that I can include a fix for this as well in my PR, if necessary. Running `find ~/.asdf/plugins -type d -mindepth 1 -maxdepth 1` emits warnings suggesting to include global options before other options. I've removed the warnings in the output above to include only content relevant to the bug.

```shell
$ find ~/.asdf/plugins -type d -mindepth 1 -maxdepth 1
find: warning: you have specified the global option -mindepth after the argument -type, but global options are not positional, i.e., -mindepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
/home/username/.asdf/plugins/golang
/home/username/.asdf/plugins/nodejs
/home/username/.asdf/plugins/direnv
```

The fix is to change:

```shell
find "$(asdf_data_dir)"/plugins -type d -mindepth 1 -maxdepth 1
```

to:

```shell
find "$(asdf_data_dir)"/plugins -mindepth 1 -maxdepth 1 -type d
```

on [`command-plugin-update.bash#L17`](https://github.com/asdf-vm/asdf/blob/2bf076f3d33087966cdb4de52cfdf0042eb7c076/lib/commands/command-plugin-update.bash#L17).

---

I can make a PR with necessary changes to L13 and L17, but I'm not sure if my "fix" is a proper one.

**EDIT:** I had misunderstood what the `-d` option for the `read` command meant and thought that the source of the problem was something else. Updated my comment after understanding what it actually does.

**Comment by jthegedus** [comment]
Hi @SanchithHegde we're happy to receive PRs, ideally with new test cases covering the existing issue :)

To clarify the `update --all` issue is with the output when all plugins are already updated?

**Comment by SanchithHegde** [comment]
@jthegedus Sure, I'll have to look into how to write tests for bash scripts. I'll give it a try when making the PR.

To debug the issue, I've tried running a simpler version of the relevant code:

```shell
$ set -x  
while IFS= read -r -d '' dir; do
    echo $dir
done < <(find ~/.asdf/plugins -maxdepth 1 -mindepth 1 -type d)
set +x

+zsh:2> IFS='' +zsh:2> read -r -d '' dir
+zsh:2> find /home/sanchith/.asdf/plugins -maxdepth 1 -mindepth 1 -type d
+zsh:5> set +x
```

which didn't echo anything. On removing the `-d ''` from `read`:

```shell
$ set -x  
while IFS= read -r dir; do      
    echo $dir
done < <(find ~/.asdf/plugins -maxdepth 1 -mindepth 1 -type d)
set +x

+zsh:2> IFS='' +zsh:2> read -r dir
+zsh:2> find /home/sanchith/.asdf/plugins -maxdepth 1 -mindepth 1 -type d
+zsh:3> echo /home/sanchith/.asdf/plugins/golang
/home/sanchith/.asdf/plugins/golang
+zsh:2> IFS='' +zsh:2> read -r dir
+zsh:3> echo /home/sanchith/.asdf/plugins/nodejs
/home/sanchith/.asdf/plugins/nodejs
+zsh:2> IFS='' +zsh:2> read -r dir
+zsh:3> echo /home/sanchith/.asdf/plugins/direnv
/home/sanchith/.asdf/plugins/direnv
+zsh:2> IFS='' +zsh:2> read -r dir
+zsh:5> set +x
```

Looks like the parsing when the `-d ''` option is passed to `read` doesn't happen properly. I'm not sure what exactly causes this, as it seems to work fine for others.

**Comment by jthegedus** [comment]
what happens when your plugins do need updating? Can you use `asdf plugin-update <name> <git-ref>` to set a plugin to an older ref and then run the update and show your output here?

**Comment by SanchithHegde** [comment]
@jthegedus Even when the plugins need updating, there's no output. Here's the output you requested for. 

**Setting nodejs plugin to an older ref (ignore the warning emitted by git):**

```shell
$ asdf plugin-update nodejs 946c650a5b92ce72ca1ecf64809d9b388e182a07
Updating nodejs...
From github.com:asdf-vm/asdf-nodejs
 * [new ref]                   946c650a5b92ce72ca1ecf64809d9b388e182a07 -> 946c650a5b92ce72ca1ecf64809d9b388e182a07
warning: refname '946c650a5b92ce72ca1ecf64809d9b388e182a07' is ambiguous.
Git normally never creates a ref that ends with 40 hex characters
because it will be ignored when you just specify 40-hex. These refs
may be created by mistake. For example,

  git switch -c $br $(git rev-parse ...)

where "$br" is somehow empty and a 40-hex ref is created. Please
examine these refs and maybe delete them. Turn this message off by
running "git config advice.objectNameWarning false"
Switched to branch '946c650a5b92ce72ca1ecf64809d9b388e182a07'
```

**Running `asdf plugin update --all` without any changes to `command-plugin-update.bash` file:**

```shell
$ asdf plugin-update --all
$
```

Output of `git branch -vv` in `~/.asdf/plugins/nodejs`
```shell
$ # ~/.asdf/plugins/nodejs
$ git branch -vv
* 946c650a5b92ce72ca1ecf64809d9b388e182a07 946c650a5b92 Merge pull request #159 from mdesantis/patch-1
  master                                   de913469365d [origin/master] Merge pull request #173 from XX-NF-XX/patch-1
```

**Running `asdf plugin update --all` after removing `-d ''` flag from `read` command on L13:**

```shell
$ asdf plugin-update --all                     
Updating direnv...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating golang...
Already on 'master'
Your branch is up to date with 'origin/master'.
Updating nodejs...
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```

Output of `git branch -vv` in `~/.asdf/plugins/nodejs`
```shell
$ # ~/.asdf/plugins/nodejs
$ git branch -vv
  946c650a5b92ce72ca1ecf64809d9b388e182a07 946c650a5b92 Merge pull request #159 from mdesantis/patch-1
* master                                   de913469365d [origin/master] Merge pull request #173 from XX-NF-XX/patch-1
```

---

I think it's to do with parsing the output of the `find` command. Running `find <dir> <options>` prints results separated by newlines, but I believe `read -r -d '' ...` stops reading when it encounters an empty character (`''`) (I can't seem to understand how this would work). Removing the `-d ''` option makes `read` use the default delimiter, which is a newline. Removing the option somehow fixes the parsing for me.

**Comment by smorimoto** [comment]
Indeed, the current set of command and flag doesn't work well.

**Comment by SanchithHegde** [comment]
@jthegedus I was able to reproduce this on NixOS running in a VM and Alpine Linux running in a container. Are Linux systems the only ones affected?

**Comment by jthegedus** [comment]
`find` warning was fixed in https://github.com/asdf-vm/asdf/pull/853

**Comment by SanchithHegde** [comment]
@jthegedus Thank you!
