### ISSUE TITLE
asdf Plugin Capitalization & Silent Failing

### ISSUE THREAD

**Issue by ctsstc** [asdf-vm/asdf#816]
**Describe the bug**

If you add a plugin with different capitalization `asdf` will not function properly.
There are also no warnings for missing/mismatched plugins listed in the `.tool-versions`.

**To Reproduce**

Tell us what actions you performed before the issue occurred

For example if you added the following it would expect `Ruby` instead of `ruby`.

```
asdf plugin-add Ruby https://github.com/asdf-vm/asdf-ruby.git
```

If the `.tool-verions` has `ruby` instead of `Ruby` it will not install.
There's no warning for not having plugins added that are listed in a `.tool-versions`.
Also I think it should be case insensitive.

If you try to add the same plugin with different capitalization it will say it's already been added.

**Expected behavior**

I think it should be case insensitive when you run `asdf install`.

A warning would be nice if there's something listed in `.tool-versions` that you haven't yet added. It would be even nicer if it tried to push you in the right direction or asked you if you wanted to install the associated plugins.

**Actual behavior**

No error, it doesn't say anything installs if there's a capitalization mismatch.

### Environment

```shell
OS:
Darwin Coders-MBP 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

SHELL:
zsh 5.7.1 (x86_64-apple-darwin19.0)

ASDF VERSION:
v0.8.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
php                          https://github.com/asdf-community/asdf-php.git
ruby                         https://github.com/asdf-vm/asdf-ruby.git
```

**asdf plugins affected (if relevant)**:

**Screenshots**

**Additional context**

**Comment by Stratus3D** [comment]
I don't think asdf should be case insensitive, because of the operating systems asdf runs on are case sensitive (OSX is a strange one, but generally things work better if you treat it as case sensitive).

I warning when adding a plugin with an uppercase name should be all that is needed to avoid this issue.

**Comment by jthegedus** [comment]
Currently we're running a regex match over plugin names:

https://github.com/asdf-vm/asdf/blob/e1fd8ad970613b1d9d97d6af6c9890c436226ba5/lib/functions/plugins.bash#L59

Requirements to close this Issue:

- [ ] on plugin add, warn if the user adds an uppercase

Related PRs:
- https://github.com/asdf-vm/asdf/pull/1010
- https://github.com/asdf-vm/asdf/pull/1241
