### ISSUE TITLE
unable to install erlang 19.0.1

### ISSUE THREAD

**Issue by nathany** [asdf-vm/asdf#82]
When I specify Erlang 19.0.1 in my `.tool-versions` file

```
erlang 19.0.1
elixir 1.3.1
```

The following error when running `asdf install`:

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

It works fine with `erlang 18.3`.

**Comment by nathany** [comment]
`erlang 19.0` does work as well, but it doesn't look like it's getting the latest patch release

**Comment by Stratus3D** [comment]
I get the same error as well, but I haven't had any trouble with earlier Erlang versions. 

This issue should probably be moved to the asdf-erlang project as this isn't an issue with asdf.

**Comment by Stratus3D** [comment]
Actually. I'm confused. I don't even see an Erlang 19.0.1 release listed in the available Erlang versions. I also do not see it on erlang.org. Does Erlang 19.0.1 exist? It doesn't appear to.

**Comment by nathany** [comment]
I have Erlang 19.0.1 on my Mac via Homebrew and the official docker images support 19.0.1.

Sorry, I didn't realize their was a separate repo for asdf-erlang.
