### ISSUE TITLE
Linuxbrew WSL2 install bug

### ISSUE THREAD

**Issue by chaffeqa** [asdf-vm/asdf#821]
Installed without failure, however when invoking I get:
```
asdf
cat: /home/linuxbrew/.linuxbrew/VERSION: No such file or directory
version:

cat: /home/linuxbrew/.linuxbrew/help.txt: No such file or directory
```

Don't know what the descrepencies between OSX homebrew and linuxbrew installations, but I have asdf working on my osx using homebrew.

**Comment by jthegedus** [comment]
I'm unsure how Linuxbrew handles the dependencies Brew Formulae when they are platform specific, which I believe they are in this case.

It seems to be reading from the wrong path, as I would expect:

```
/home/linuxbrew/.linuxbrew/VERSION

to be 

/home/linuxbrew/.linuxbrew/asdf/VERSION
```

or something similar.

Do you have any ASDF env vars set in your shell config? can you run `env | grep -E "ASDF_DIR|ASDF_DATA_DIR|ASDF_CONFIG_FILE|ASDF_DEFAULT_TOOL_VERSIONS_FILENAME"`

**Comment by alexanderadam** [comment]
I'm experiencing the same after installing `asdf` via [homebrew](https://docs.brew.sh/Homebrew-on-Linux) (on native GNU/Linux, though):

And I'm also getting things like these when I try to call `asdf`:

![asdf cat: /home/linuxbrew/.linuxbrew/VERSION: No such file or directory
version: cat: /home/linuxbrew/.linuxbrew/help.txt: No such file or directory "Late but latest" -- Rajinikanth](https://user-images.githubusercontent.com/372620/106520441-19e63780-64dd-11eb-89d3-f95ab811bef4.png)

The command
```bash
env | grep -E "ASDF_DIR|ASDF_DATA_DIR|ASDF_CONFIG_FILE|ASDF_DEFAULT_TOOL_VERSIONS_FILENAME"
```
doesn't return anything.

**Comment by taranjlu** [comment]
I am also running into this same issue on Fedora 33 after installing `asdf` via `brew`.

**Comment by jthegedus** [comment]
Can each of you share your `asdf info` output?

**Comment by alexanderadam** [comment]
> Can each of you share your `asdf info` output?

![OS: Linux scathach-9300 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux  SHELL: zsh 5.8 (x86_64-ubuntu-linux-gnu)  cat: /home/linuxbrew/.linuxbrew/VERSION: No such file or directory ASDF VERSION:   ASDF ENVIRONMENT VARIABLES:   Oohes nooes ~! No plugins installed ASDF INSTALLED PLUGINS:](https://user-images.githubusercontent.com/372620/113505262-f02da900-953d-11eb-97b9-532e1af11c95.png)

**Comment by jthegedus** [comment]
As of today, our documentation covers how to setup asdf via Homebrew on non-macOS machines. I am not sure if these instructions came before or after this issue. I am inclined to say the docs came after this issue as no new users have commented or :+1: this issue in ~2 years.

I will close for now.

If you find this Issue, please open a new one to discuss as it will be more clear what instructions you used to setup your system and what version of our docs might have problems.
