### ISSUE TITLE
Add a method to change $PATH on .tools-versions "execution"

### ISSUE THREAD

**Issue by taylan97** [asdf-vm/asdf#823]
**Is your feature request related to a problem? Please describe.**
If I install a binary via `luarocks` (lua's package manager), it's installed into `~/asdf/installs/lua/<version>/luarocks/bin/`. I'd like to be able to run those executables without having to use the full path, but I don't want to pollute my $PATH with "dead" executables unless I actually have the correct runtime enabled.

**Describe the solution you'd like**
I `cd` to a `.tool-versions` folder, and my `$PATH` is altered to include directories I want. 

**Describe similar asdf features and why they are not sufficient**
I don't believe there are any features that can do this. I don't need a specific "set path" function, a more generic "run script after loading <tool> <version>" would do it.

**Describe workarounds you've considered**
Manually setting my path, but it's tedious.

**Comment by taylan97** [comment]
`asdf reshim`

**Comment by ben0x4a** [comment]
see https://direnv.net/ for a tool that will let you create .envrc files that will change environment variables, including PATH, when you cd into and out of directories. It is a great complement to asdf
