### ISSUE TITLE
Disable Certain Commands Provided By A Plugin

### ISSUE THREAD

**Issue by sherl0cks** [asdf-vm/asdf#828]
**Is your feature request related to a problem? Please describe.**
Multiple plugins may offer support for a command (e.g. certain version of java and nodejs offer support for npm). This can lead to a shim file where the incorrect plugin is being used. 

**Describe the solution you'd like**
Disable which plugins are added to a shim. I never want my java to own the path for a npm module.

**Describe similar asdf features and why they are not sufficient**
`asdf shim-versions ` lists the versions, but I have no way (that I can see) to control them via asdf.

**Describe workarounds you've considered**
I can work around this by directly modifying the shim file, but that seems improper.

**Additional context**

**Comment by jthegedus** [comment]
This is an _alternate workaround_:

Explicitly setting one of the tools to a version not in the `shim-versions` list should work. This obviously isn't ideal when your project requires both tools and the parent tools that installed the shim as a dependency.

@sherl0cks can you share:
- the specific combination you encountered?
- any suggestions around API/cmds to disable a shim from a particular plugin? Should this be a plugin API where a config is read at install time, or would you expect an `asdf` core solution that skips creating shims for plugin:tool pairs or plugin:version:tool triplets (eg java adoptopenjdk-15.0.1+9 <some tool>)?

**Comment by sherl0cks** [comment]
@jthegedus I thanks for the detail response. I got this during my vacation. Please let me know if you need more info. Thanks for a great tool!

Versions:
- java graalvm-20.3.0+java11
- nodejs 12.18.4

For context, I think I saw the same issue with SDKman, and I think root cause is that graalvm ships both java and nodejs (why, I do not know), but I don't want the graal nodejs version. Since I need both plugins (java and nodejs) in my project, I do not believe the alternative suggested will work.

As to a supported solution, thank you for asking. I haven't been through the plugin contribution guide. Is there an expectation that tool (e.g. graalvm) only satisfy one plugin (e.g. only java that brought it in, not nodejs)? If so, then this feels like a bug in the java plugin and we should fix this in the plugin system. If there is no such expectation, and a single tool can legally support multiple plugins, then a core solution that gives you control to say "do not use the nodejs from graalvm 20.3.0" would be preferred.

**Comment by Stratus3D** [comment]
@sherl0cks yeah that definitely sounds like something the Java plugin should fix. The Java plugin is free to do whatever it wants with its own NodeJS version under the hood, but it should only put Java executables in the directories that it exposes for asdf shimming. It sounds like it is not, and that is something the plugin maintainers should change. It is not clear what we could do in asdf to improve this, so I'm going to close this.

Perhaps in the future we could report errors when two plugins provide the executables? Certainly that situation is never ideal, maybe we can warn about it?
