### ISSUE TITLE
"Unknown command" error when running any plugin command

### ISSUE THREAD

**Issue by kieraneglin** [asdf-vm/asdf#831]
**Describe the bug**

`asdf` was installed via homebrew a few days ago following the guide and things worked as expected.  However, any `asdf <plugin>` command has stopped working, returning the error `Unknown command: 'asdf <command> <plugin>'`.

There haven't been any obvious updates to asdf/homebrew/OS that have occurred since installation that would explain this.  We don't know when the issue started but we first noticed it today.

**To Reproduce**

1. Run any command in the `asdf <command> <plugin>` format
2. Receive "Unknown command" error message above

### Environment

MacOS version is 11.0

```shell
OS:
Darwin MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.0)

ASDF VERSION:
v0.8.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
```

**asdf plugins affected (if relevant)**:

All plugins

**Additional context**

Troubleshooting steps taken:
- Remove + re-add plugins
  - Adding plugins seemed to succeed, but the issue persisted once commands were run
- brew uninstall + reinstall asdf
- `rm -rf ~/.asdf/` + uninstall + reinstall
- install the github version of asdf via `brew install asdf --HEAD`

Curiously, commands like `asdf which ruby` returned the expected path so there is some level of awareness of the languages.

Running `which asdf` returns the entry function as expected.  `echo $(brew --prefix asdf)` returns the expected path.

**Comment by kieraneglin** [comment]
Closing as this was not reproducible after a reboot

**Comment by mvanderlee** [comment]
Restarting the shell itself fixed it, no reboot needed. 
For zsh, I simple ran `exec zsh`
