### ISSUE TITLE
[Proposal] A way to treat language installed from local sources

### ISSUE THREAD

**Issue by gmile** [asdf-vm/asdf#84]
Oftentimes I have a language source downloaded, make change to it, then compile it and run some code of mine against this newly compiled language binary.

Is there a way I could tell `asdf` where my custom compiled binary reside? This would allow me to quickly switch current version of language to my compiled version, check something, and then switch back to stable version.

Here's the desired API I have in mind right now.
1. Tell `asdf` about a locally compiled `elixir`:
   
   ``` bash
   $ asdf link elixir my_custom_source ~/gmile/elixir/bin
   $ asdf link elixir my_experimental_source ~/gmile/elixir2/bin
   ```
2. Listing all elixir versions now would show two more item in addition to whatever stable versions were already installed:
   
   ``` bash
   $ asdf list elixir
   1.3.2
   my_custom_source (~/gmile/elixir/bin)
   my_experimental_source (~/gmile/elixir2/bin)
   ```
3. Tell `asdf` to use a custom `elixir` version:
   
   ```
   $ asdf local elixir my_custom_source
   ```
4. Tell `asdf` to forget about custom `elixir` versions:
   
   ``` bash
   $ asdf unlink elixir my_custom_source
   $ asdf unlink elixir my_experimental_source
   ```

**Comment by HashNuke** [comment]
@gmile The Elixir plugin supports a `path:/foo/bar` as a version to use.
So having `elixir path:/foo/bar` in your tool versions will assume that you have elixir in that dir.

**Comment by vic** [comment]
@gmile  and once #112 and #110  get merged you will be able to do:

```shell
ASDF_ELIXIR_VERSION="path:/your/experimental/elixir" mix test
```

with any supported tool not just elixir.

**Comment by Stratus3D** [comment]
Closing this issue since it seems like there are several ways of doing this now.
