### ISSUE TITLE
'fatal: invalid gitfile format:  /usr/local/opt/asdf/asdf.sh" returned when sourcing .zshrc

### ISSUE THREAD

**Issue by jessieobeng** [asdf-vm/asdf#857]
**Description**
I installed asdf using Hombrew method: 
`brew install asdf --HEAD`
and added asdf to my .zshrc file using:
`echo -e "\n. $(brew --prefix asdf)/asdf.sh" >> ~/.zshrc`

When I restart my terminal, cd into the directory I am working in and enter the command 
`source ~/.zshrc`

I get this error:
```
fatal: invalid gitfile format: /usr/local/opt/asdf/asdf.sh
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
```
**To Reproduce**
```
brew install asdf
asdf plugin add ruby
asdf plugin add nodejs
asdf plugin add terraform
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
asdf install
echo -e "\n. $(brew --prefix asdf)/asdf.sh" >> ~/.zshrc

*Restart Terminal*
source ~/.zshrc
```

**Expected behavior**

No output and the .zshrc file is sourced 

**Actual behavior**
```
fatal: invalid gitfile format: /usr/local/opt/asdf/asdf.sh
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Environment
asdf version: 0.8.0

**Comment by jthegedus** [comment]
If you installed via Homebrew, then it performed the Git Clone and any permissions for the cloned files. Have you looked for similar issues on Homebrew repo?

**Comment by Stratus3D** [comment]
Closing due to lack of a response from @jessieobeng.
