### ISSUE TITLE
Allow re-installing old/broken tool installations following a plugin update, e.g. via post-plugin-update hook

### ISSUE THREAD

**Issue by nirvana-msu** [asdf-vm/asdf#859]
**Is your feature request related to a problem? Please describe.**
Sometimes you make updates to your plugin that fix something that was broken in the previous installs. In these cases, it would be great to have a way to force re-installation of the old (broken) installs.

**Describe the solution you'd like**
One way to achieve that would be by adding a `post-plugin-update` hook - so that once plugin is updated, it can trigger re-installation of old (broken) installs. One tricky part would be to ensure re-install is only triggered when plugin is updated to a certain revision - e.g. next update may not require re-install. It would have been easy if plugins themselves were versioned, but I suppose it could also be done if we know which git-ref we're upgrading from.

Alternatively, this could be addressed by allowing a plugin to "declare" that a change breaks certain install versions - and then asdf itself could take care of re-installing those versions (if installed).

The hook is more general so can probably cover some other use-cases not described here.

**Describe similar asdf features and why they are not sufficient**
There are already similar hooks `post-plugin-add` and `post-plugin-remove`, but in this case an action needs to be taken on plugin update.

**Describe workarounds you've considered**
At the moment I have to warn users that they need to manually re-install affected tool versions after updating plugin.

**Comment by Stratus3D** [comment]
Hi @nirvana-msu , currently there is no way to indicate that an installed version depends on, or is affected by, a plugin version change. Currently we don't even support plugin versions yet, but we will eventually (see https://github.com/asdf-vm/asdf/issues/166 and related issues for that). As it is currently we don't have a way to support this. Closing this issue now.
