### ISSUE TITLE
[Request] Way to revert to the system version?

### ISSUE THREAD

**Issue by Honeypot95** [asdf-vm/asdf#868]
My workflow is usually changing the version of a runtime to try out some stuff, after which I want to revert to the system version. I did not find a way in the documentation or from toying around with `asdf` itself. For now, I just use the `shell` option, after which I restart the shell.

`pyenv` seems to list a "system" when listing versions, which provides a way to revert to the system version. Is such a thing in the cards for `asdf`?

**Comment by cho-m** [comment]
Have you tried using the `system` keyword?
There is some documentation on it in [core-configuration.md](https://github.com/asdf-vm/asdf/blob/master/docs/core-configuration.md#tool-versions):

> - `system` - this keyword causes asdf to passthrough to the version of the tool on the system that is not managed by asdf.

Based on a quick test, it works for me:
```zsh
❯ asdf shell python 3.9.2

❯ python --version
Python 3.9.2

❯ asdf shell python system

❯ python --version
Python 2.7.16

❯ /usr/bin/python --version
Python 2.7.16
```

Currently, ASDF doesn't seem to show it as part of list of available versions.
This could be either be a design decision or a bug.
```zsh
❯ asdf list python
  3.9.2

❯
```

In terms of shell autocompletion, it looks like only fish-shell has been updated to support tab-completing `system` as option:
- Fish Example:
  ```fish
  ❯ asdf shell python <tab>
  3.9.2  system
  
  ❯ asdf shell ruby <tab>
  3.0.0  system
  ```
- Corresponding code:
  https://github.com/asdf-vm/asdf/blob/0f75c2162944f50120906ba61faa62783cecfcb5/completions/asdf.fish#L131

**Comment by jthegedus** [comment]
Thanks for raising this @Honeypot95 and for the thorough answer @cho-m 

Whether `asdf list <name>` should list `system` is open to interpretation, though I would say it should as it increases the usability a lot.

If someone wants to solve rectify these issues, I would say the requirements are:

1. `asdf list <name>` should append `system` to the output
2. all shell completions should be consistent in their tab completion for listing versions. I suspect if 1. is solved, then the Fish completions referenced by @cho-m would need to remove it's inserting of `system`

**Comment by Honeypot95** [comment]
@cho-m Yes, `system` is there as a possible option, albeit not listed, thank you. It was exactly what I needed, and sorry, I did not read thoroughly.

@jthegedus I can try adding it myself? I guess it is a good first pull request. Maybe also add an example on the front docs of the website, something like "this is how you change the version, and this is how you revert to the system one" example?

**Comment by jthegedus** [comment]
PRs are very welcome :)

We do list `system` on this page - https://asdf-vm.com/#/core-configuration?id=tool-versions

But it should probably also be mentioned on this page too - https://asdf-vm.com/#/core-manage-versions
