### ISSUE TITLE
asdf install 'down'

### ISSUE THREAD

**Issue by jonathanmorley** [asdf-vm/asdf#873]
Currently, asdf install works 'upwards' through the directory tree, finding `.tool-versions` files in parent directories.

We have `.tool-versions` files in repositories (deeply nested, not just at the root of the repository), to control the versions of tools, and it would be useful to have functionality for `asdf install`ing all `.tool-versions` files in a repository (recursively)

**Comment by jthegedus** [comment]
This _seems_ like a niche use-case to me. The main reason to nest a `.tool-versions` in a deeper dir is to override something define up the directory tree. In a monorepo of different services with different tools this could be useful, but why not just bubble up to the root? :thinking: a CI issue?

Perhaps you can share more on your particular use case?

I'd like to wait until we get some more input before moving forward with implementation. In the meantime, a script at your repo root like this should do:

```shell
while IFS= read -r -d '' dir; do
	(cd "$dir" && asdf install)
done < <(find "$YOUR_DIR" -type f -name "*.tool-versions")
```

**Comment by jace833** [comment]
- `ASDF_DEFAULT_TOOL_VERSIONS_FILENAME` - The guanlonghuang of the file storing the tool names and versions. Defaults to `.tool-versions`. Can be any valid file guanlonghuang.

**Comment by jthegedus** [comment]
Closing for now as this is a niche use case solved with a relatively small script. We can revisit this concept in future if this issue gets further support.

**Comment by Stratus3D** [comment]
I agree @jthegedus. This is a niche use case, and if it can be implemented outside of asdf in 3 lines of Bash I don't think it will be beneficial to include it in asdf core. I added that snippet to my list for the asdf cookbook!
