### ISSUE TITLE
Tool invocation prevents asdf expected behaviour

### ISSUE THREAD

**Issue by Aethelflaed** [asdf-vm/asdf#874]
**Describe the bug**

When a tool invokes a command changing directory and using the same tool again, the behaviour is not consistent with what one could expect

**To Reproduce**

```sh
mkdir a b
echo 'ruby 2.7.1' > a/.tool-versions
echo 'ruby 2.5.7' > b/.tool-versions
echo "#\!/usr/bin/env ruby\nsystem('cd ../b && asdf current ruby && ruby --version')" > a/ruby-script
chmod +x a/ruby-script
cd a
./ruby-script
```

**Expected behavior**

> ruby            2.5.7           /home/geoffroy/b/.tool-versions
> ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]

**Actual behavior**

> ruby            2.5.7           /home/geoffroy/b/.tool-versions
> ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

### Environment

```shell
OS:
Linux anarchy 5.10.16-2-lts #1 SMP Tue, 16 Feb 2021 21:11:59 +0000 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-pc-linux-gnu)

ASDF VERSION:
v0.8.0-c6145d0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/geoffroy/.asdf

ASDF INSTALLED PLUGINS:
elixir                       https://github.com/asdf-vm/asdf-elixir.git
erlang                       https://github.com/asdf-vm/asdf-erlang.git
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git
python                       https://github.com/danhper/asdf-python.git
ruby                         https://github.com/asdf-vm/asdf-ruby.git
```

**Additional context**

I have `legacy_version_file = yes` and the actual problem has been discovered with `.ruby-version`.

The problem occurred while trying to remove a `rvm-exec` invocation which is not portable between computers. It appears that it works without `rvm-exec` on rvm computers.

The problem has been tracked to `asdf/lib/utils.bash` in `with_plugin_env()` which says:

> add the plugin listed exec paths to PATH

**Question**

Is it really needed to do this step? Is it possible to add a flag / env to NOT change the PATH this way?

**Comment by Stratus3D** [comment]
@Aethelflaed , thanks for the sequence of commands illustrating the problem. Unfortunately I don't think for that specific case anything should be changed. When a `.tool-versions` file is present in the current directory the version from it will be used, regardless of what directory the parent process is in.

There is a workaround for this however, you can always override what is in the `.tool-versions` file by setting a shell version (which is just specified in an environment variable). For example, in your case, `system` could run `cd ../b && asdf shell ruby  2.5.7 && asdf current ruby && ruby --version` instead.

**Comment by Stratus3D** [comment]
Closing this due to lack of a response.

**Comment by Aethelflaed** [comment]
Sorry, I didn't have time to test directly and totally forgot to get back to you later. Thanks a lot for the answer, I managed to make it work with what you provided
