### ISSUE TITLE
Asdf autocomplete inserting extra backslashes with fish

### ISSUE THREAD

**Issue by squarism** [asdf-vm/asdf#875]
**Describe the bug**

Asdf seems to insert backslashes for autocomplete for certain commands.

**To Reproduce**

Tell us what actions you performed before the issue occurred

1. Run the fish shell
2. Install a plugin (let's just say nodejs)
3. Type these keys: `asdf global nodejs [tab] [tab]`
4. Tab select the version you are interested in.

**Expected behavior**

See the output
`asdf global nodejs 15.6.0`

**Actual behavior**

See the following output:  `asdf global nodejs \ \ 15.6.0`

### Environment

```shell
OS:
Darwin hostname 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

SHELL:
fish, version 3.1.2

ASDF VERSION:
v0.8.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
```

**asdf plugins affected (if relevant)**:
This seems to be happening on many plugins, doesn't seem to be plugin specific.

**Additional context**
This could entirely be a fish shell issue and have nothing to do with asdf in particular.

**Comment by justinmayer** [comment]
For what it's worth, I use the same Fish and `asdf` versions and can't reproduce the reported issue.

**Comment by jthegedus** [comment]
@squarism you may find this resolved with the latest version of `asdf` or even the latest version of our docs. When did you install this setup, was it recently following the current fish setup docs?

**Comment by squarism** [comment]
Ok interesting ... so then I tried on a different machine.  Same habits, same dotfiles, same homebrew install, same os.  But it doesn't do this `\ \ ` thing.  So it's something with my machine probably.  I thought I was reporting a parsing, escaping shell type bug.  I even switched to head/master (and at the same time homebrew->git) and there's no observable difference with autocomplete.  It still works.  So it's one of my machines then.  Thanks.
