### ISSUE TITLE
Ruby "gem" shim seems to always prefer brew installed version of ruby/gem instead of asdf

### ISSUE THREAD

**Issue by taranjlu** [asdf-vm/asdf#878]
**Describe the bug**
Not really a Ruby user (yet), just trying to get it setup via `asdf`. I have an issue where if `ruby` is installed via brew, the command `gem environment` always shows information about the brew version instead of the asdf installed version.

**To Reproduce**
- Install latest `ruby` via `asdf`
- Install `ruby` via `brew`
- Try `gem environment`
- Uninstall `ruby` via `brew`
- Try `gem environment` again

**Expected behavior**
Should use asdf installed version.

**Actual behavior**
Seems to be using brew installed version instead of asdf installed version.

### Environment

```shell
OS:
Linux ---- 5.10.17-200.fc33.x86_64 #1 SMP Wed Feb 17 21:21:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
fish, version 3.1.2

ASDF VERSION:
v0.8.0-07d4ae5

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/----/github.com/asdf-vm/asdf

ASDF INSTALLED PLUGINS:
clojure                      https://github.com/halcyon/asdf-clojure.git
golang                       https://github.com/kennyp/asdf-golang.git
java                         https://github.com/halcyon/asdf-java.git
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
python                       https://github.com/danhper/asdf-python.git
ruby                         https://github.com/asdf-vm/asdf-ruby.git
rust                         https://github.com/code-lever/asdf-rust.git
v                            https://github.com/ndac-todoroki/asdf-v.git
```

**asdf plugins affected (if relevant)**:
- `ruby`

**Additional context**
- On Fedora 33
- Had to install from source because `asdf` brew formula does not work on Linux right now (#821).
- Using `fish` shell and this is my path:
```
/home/----/bin (personal bin, nothing in this dir currently)
/home/----/.local/bin
/home/----/.asdf/shims
/home/----/github.com/asdf-vm/asdf/bin
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/sbin
/usr/local/bin
/usr/local/sbin
/usr/bin
/usr/sbin
/var/lib/snapd/snap/bin
```

**Comment by saraid** [comment]
Try `brew unlink gem` or `brew cleanup`. It may be worth looking at the output for `which -a gem`, too.

**Comment by jthegedus** [comment]
Closing this as @saraid suggest a solve & OP did not return with an update. Also, no other users have :+1: this as being an issue, so it is likely just this one setup.
