### ISSUE TITLE
Scripts with end of line CRLF

### ISSUE THREAD

**Issue by juanxjk** [asdf-vm/asdf#882]
**Describe the bug**

End of line CRLF is breaking on shell startup.

I fixed, on my computer, replacing all CRLF to LF.

**To Reproduce**

I'm using WSL2, but just install asdf normally.

**Expected behavior**

.bashrc or .zshrc runs normally.

**Actual behavior**

![image](https://user-images.githubusercontent.com/11265053/110198001-fd1b8780-7e2d-11eb-8c07-cbc025b05d0c.png)

![image](https://user-images.githubusercontent.com/11265053/110198090-aa8e9b00-7e2e-11eb-8f22-5df7d3eb1ac0.png)

**asdf plugins affected**:
Maybe, all plugins are using CRLF.

**Comment by Kaylebor** [comment]
This is happening to me too as of October 11th, 2022, on MacOS.
Why are we using CRLF?

Example:
```
sh -x $(command -v asdf)
+ $'\r'
: command not foundbin/asdf: line 2:
+++ dirname <$ASDF_DIR>/bin/asdf
++ dirname <$ASDF_DIR>/bin
+ . $'<$ASDF_DIR>/lib/utils.bash\r'
: No such file or directory: line 4: <$ASDF_DIR>/lib/utils.bash
```

Notice the stray `\r` that appear on that output: of course the file does not exist.

Would a PR that replaced the line endings with LF be accepted? I am certainly going to do that locally regardless, but I don't like straying too far from upstream...

**Comment by Kaylebor** [comment]
For future reference: make sure that your git config has the right value.
```git config --global core.autocrlf false```

At the very least, `core.autocrlf` should not be `true`.
If this is `false`, git will check all repo with `LF` instead of `CRLF` by default.

**Comment by jthegedus** [comment]
You shouldn't need to set git config --global core.autocrlf false to false. You just need to clone the repo from a Unix environment and it will get the correct line endings.

From our [FAQ](https://asdf-vm.com/learn-more/faq.html)
>Importantly, WSL2 is only expected to work properly when the current working directory is a Unix drive and not a bound Windows drive.

So you may find that installing to a non-unix location will incorrectly detect the `autocrlf` and thus get the wrong line-endings.

**Comment by Kaylebor** [comment]
Thanks for the information, but I think in my case I had explicitly set autocrlf to true, and I am 100% sure I had asdf installed in the Ubuntu virtual drive.

Still, your clarification will be nice if someone else sees this later.
