### ISSUE TITLE
Where did the name come from?

### ISSUE THREAD

**Issue by leetrout** [asdf-vm/asdf#883]
Is the name `asdf` and homage to Lisp's `ASDF`?

https://common-lisp.net/project/asdf/
https://en.wikipedia.org/wiki/Another_System_Definition_Facility

**Comment by Triple-Z** [comment]
Maybe are the beginning of the second-row keys on the keyboard 🤣 
<kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><kbd>F</kbd>

**Comment by jthegedus** [comment]
I believe it is as @Triple-Z states, left-hand home-row of qwerty keyboard.

**Comment by daveloyall** [comment]
See #383 and #547
