### ISSUE TITLE
Download part of install script does not handle non zero exit codes from download plugin scripts

### ISSUE THREAD

**Issue by laidbackware** [asdf-vm/asdf#886]
**Describe the bug**

Currently plugin download script errors are ignored by the `command-install.bash` script. This makes running plugin development difficult and makes plugins fragile in scenarios such as being behind a proxy which requires authentication.

This is especially problematic for split download/install scripts as if the download script errors it will not halt and continue to run the install script, likely presenting the user with a generic file error.

**To Reproduce**
- At the top of any plugin which is already present on the system, add `exit 1` to the top of the download file.
- Run `asdf install <plugin_name> latest`
- After command completion run `echo $?`

**Expected behavior**

Expected behaviour is to print a non-zero exit code.

**Actual behavior**

Zero is printed.

### Environment

```shell
OS:
Linux a08725a7f1b5 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.8.0-8f5d619

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/tester/.asdf

ASDF INSTALLED PLUGINS:
kubectl                      https://github.com/Banno/asdf-kubectl.git
s5cmd                        git@github.com:laidbackware/asdf-github-tools.git
```

**asdf plugins affected (if relevant)**:
All plugins.

**Screenshots**

**Additional context**

**Comment by Stratus3D** [comment]
Closing as I believe this has been resolved by #881 .
