### ISSUE TITLE
Having issues with folders with spaces in them on OS X El Capitan.

### ISSUE THREAD

**Issue by oktapodi** [asdf-vm/asdf#89]
`asdf local <name> <version>`
seems to fail if i have a folder with spaces in the name. Ive tried using the asdf plugin for nodejs

**Comment by Stratus3D** [comment]
I just tested on my machine (same OS as yours) and I got this error:
```
$ mkdir whitespace\ test
$ cd whitespace\ test
$ asdf local erlang 18.2
/Users/tbrown/.asdf/lib/commands/version_commands.sh: line 70: [: /Users/tbrown/whitespace: binary operator expected
/Users/tbrown/.asdf/lib/commands/version_commands.sh: line 73: $file: ambiguous redirect
```

Is this the error you are getting? What asdf version are you running? (`asdf --version` to find out) I'm creating a PR to fix this issue I'm experiencing. Please let me know if this is the same error as the one you experienced.

**Comment by oktapodi** [comment]
Yes exactly the same issue

**Comment by Stratus3D** [comment]
Created a PR with a fix for this issue. I will wait for feedback from the other maintainers before merging it.
