### ISSUE TITLE
Brew's python conflicts with asdf's python when running `brew doctor`

### ISSUE THREAD

**Issue by dimonnwc3** [asdf-vm/asdf#894]
**Describe the bug**

Homebrew shows warning when running `brew doctor`
```
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  ~/.asdf/shims/python3.9-config
  ~/.asdf/shims/python-config
  ~/.asdf/shims/python3-config
```

On macOS Big Sur I have system python, then python from brew and python from asdf.
I'm using python from asdf. System python is installed by default. Python from the brew is installed automatically if some package requires it as a dependency. e.g
```
❯ brew info thefuck
thefuck: stable 3.30 (bottled), HEAD
Programmatically correct mistyped console commands
https://github.com/nvbn/thefuck
/usr/local/Cellar/thefuck/3.30_1 (1,111 files, 8.8MB) *
  Poured from bottle on 2021-03-13 at 23:32:32
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/thefuck.rb
License: MIT
==> Dependencies
Required: python@3.9 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Add the following to your .bash_profile, .bashrc or .zshrc:

  eval $(thefuck --alias)

For other shells, check https://github.com/nvbn/thefuck/wiki/Shell-aliases
==> Analytics
install: 3,783 (30 days), 13,031 (90 days), 68,221 (365 days)
install-on-request: 3,776 (30 days), 13,019 (90 days), 66,983 (365 days)
build-error: 0 (30 days)
```

**To Reproduce**

Tell us what actions you performed before the issue occurred

1. install brew and asdf
2. run `brew install thefuck`
3. install the python plugin and activate the latest python version as global
4. run `brew doctor`

**Expected behavior**

The warning should not be shown. Conflict should be solved.

**Actual behavior**

The warning is shown.

### Environment

```shell
❯ asdf info
OS:
Darwin macbook-dimonn 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.1.0)

ASDF VERSION:
v0.8.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
python                       https://github.com/danhper/asdf-python.git
ruby                         https://github.com/asdf-vm/asdf-ruby.git
```

**asdf plugins affected (if relevant)**:

**Screenshots**

**Additional context**

**Comment by jthegedus** [comment]
>The warning should not be shown. Conflict should be solved.

Do you have any suggestions? How would you expect this conflict to be resolved? Would you expect Homebrew to use `asdf`? It doesn't make sense to me that you would ignore the `asdf` version, especially if it is present before Homebrew installs it's deps.

As a workaround you can install `thefuck` via `pip3` and not Homebrew.

**Comment by dimonnwc3** [comment]
I've just started using asdf and unfortunately, I'm not sure about suggestions.

there is a similar issue in `pyenv` version manager, where people find some workarounds: https://github.com/pyenv/pyenv/issues/106

As I have more than one dependency in brew, which requires python. As a working solution, I uninstalled python plugin from asdf and fallback to brew's.

**Comment by jthegedus** [comment]
That's unfortunate. `asdf` does support the ability to pass through to a system version with `python system` in your root `~/.tool-versions` perhaps this might recitfy one of the 3 versions reported by `brew doctor`.

What does `brew doctor` do and why is it important for it to pass this check? As the user who knows which version is used where, why does this result from that command matter? (I am not a brew user)

**Comment by dimonnwc3** [comment]
I was also using `asdf global python system` version of python. Despite brew's python binary was correctly resolved, `*-config` scripts were still visible to brew. I believe this is just how shim works.

`brew doctor` - Check your system for potential problems.

The importance of this is in the warning message:
```
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name
```

I created a discussion in brew repo, so maybe someone with better knowledge of brew may comment on this.
https://github.com/Homebrew/discussions/discussions/1057

**Comment by seivan** [comment]
@dimonnwc3. 


Current setup when using asdf from Homebrew makes you source a file that alters your `$PATH`. 
Now correct me if I am wrong @jthegedus but the way it alters it, is by prepending it (as opposed to appending it) putting it higher in the list. 



Essentially removing the shims from your `$PATH` before running brew would solve it. 
Or as the workarounds suggested, just move it lower in priority before running brew. 

Alternative, and I am not sure if this works but asdf could technically have support for `system` so you can set it globally or do something like `asdf shell * system`

**Comment by jthegedus** [comment]
We had appended (instead of prepend) the shims in PATH in the past, I can't recall the issues that were resolved by prepending, but it was the quick fix from memory (I think I wrote the lastest code for that).

I am still not clear on how moving to PATH append of shims would fix this, would asdf not the resolve to the Homebrew python?

**Comment by seivan** [comment]
@jthegedus Sorry, it seems I momentarily forgot grammar.  

I wasn’t stating, I was asking, sorry about that. 

I’m wondering myself how it works.

**Comment by seivan** [comment]
Come to think of it, this actually kinda makes sense. But the warning is annoying. 

I don't want asdf to be supplying the dependencies needed by a package manager.
I want my package manager to install and manage those.

> Or is your suggestion @seivan that it be moved not permanently, but only when running brew

Yes, this. That's one of the suggestions in the issue linked earlier. The error message isn't related to asdf. 
It would go away if shims weren't in the path. 

So **unless** there is a decision to make asdf installed python resolving dependencies for a package manager such as Homebrew, I don't see what asdf can do right now.

**Comment by justinmayer** [comment]
I don't think using the word "conflict" in this issue is appropriate; it seems the only topic mentioned here is the warning, which `asdf` arguably can't (and shouldn't need to) do anything about. I have seen this warning many times, and while I agree it's annoying, it's never caused any noticeable problem for me, and my perception is that the responsibility for it lies entirely on Homebrew's side of the fence.

**Comment by jthegedus** [comment]
>I don't think using the word "conflict" in this issue is appropriate; it seems the only topic mentioned here is the warning, which asdf arguably can't (and shouldn't need to) do anything about. I have seen this warning many times, and while I agree it's annoying, it's never caused any noticeable problem for me, and my perception is that the responsibility for it lies entirely on Homebrew's side of the fence.

I concur. I do not see this as anything we can do. Of note, the Homebrew Formulae is not maintained by `asdf` core.

Please continue discussion https://github.com/asdf-vm/asdf/discussions/869

Feel free to re-open should there be something actionable on our (`asdf`) end.

**Comment by blairham** [comment]
Sorry to necro a closed issue, but you can just add this to your bash/zsh profile

```shell
alias brew="env PATH=${PATH//$(asdf where python)\/shims:/} brew"
```

**Comment by coreygo** [comment]
Updated workaround if `$(asdf where python)` doesn't work, tested using macOS Monterey and `asdf v0.10.2`:

```sh
alias brew="env PATH=\"\${PATH//.asdf/shims:/}\" brew"
```

or single quoted:

```sh
alias brew='env PATH="${PATH//.asdf/shims:/}" brew'
```
