### ISSUE TITLE
"plugin update" broken by recent PR

### ISSUE THREAD

**Issue by peaceful-james** [asdf-vm/asdf#899]
**Describe the bug**

https://github.com/asdf-vm/asdf/pull/800

PR #800 has broken `asdf plugin update` for me.

I can checkout the commit before this PR merge and then my problem goes away. As such, I am pretty sure that this PR is the problem.

I am using Trisquel OS 9.0 and git version 2.29.0

**To Reproduce**

```
asdf plugin update --all
```

**Expected behavior**

Plugins should update

**Actual behavior**

Error message:

```
fatal: couldn't find remote ref f
error: pathspec 'f' did not match any file(s) known to git
```

### Environment

```shell
OS:
Linux my-hostname 5.9.14-gnu #2.0 SMP Tue Sep 27 12:35:59 EST 1983 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

ASDF VERSION:
v0.8.0-456d8e3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/my_home_dir/.asdf
```

**Comment by jthegedus** [comment]
Can you list your entire `asfd info` output? If you run `plugin update` for each of your plugins, can you see which have errors?

**Comment by peaceful-james** [comment]
> Can you list your entire `asfd info` output? If you run `plugin update` for each of your plugins, can you see which have errors?

I get the same error for every plugin.

**Comment by jthegedus** [comment]
I cannot reproduce on the same `asdf` version with the same plugins.

Can you run each of these in a plugin directory:

- `git ls-remote --symref origin HEAD`
- `git ls-remote --symref origin HEAD | awk -F'[[:space:]]*' 'NR == 1 {sub(/refs\/heads\//, "", $2); print $2}'`

How did you add these plugins, `asdf plugin add <name>` or `asdf plugin add <name> <git-url>`?

**Comment by peaceful-james** [comment]
I added all plugins with `asdf plugin-add <name>`

here is what I get in my `elixir` plugin directory:

- `git ls-remote --symref origin HEAD`:
```
ref: refs/heads/master  HEAD
ee5765700c7ff99fa50f2078f2b475ad93384212        HEAD
```
- `git ls-remote --symref origin HEAD | awk -F'[[:space:]]*' 'NR == 1 {sub(/refs\/heads\//, "", $2); print $2}'`: 
```
f
```

**Comment by jthegedus** [comment]
The `awk` should extract `master` from the `refs/heads/master` part. Obviously, the `awk` I wrote isn't as portable as I thought.

Can you check list your awk version with `awk -W version`?

**Comment by peaceful-james** [comment]
My awk version is:

```
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040

```

**Comment by peaceful-james** [comment]
I just saw your suggestion about playing with awk. Sure enough, this command:

```
git ls-remote --symref origin HEAD | awk -F'[ ]*' 'NR == 1 {sub(/refs\/heads\//, "", $2); print $2}'
```

returns

```
master  HEAD
```

**Comment by peaceful-james** [comment]
Would you consider something that doesn't use `awk` at all?

What about this:

```
${$(git symbolic-ref --quiet HEAD)#refs/heads/}
```

**Comment by peaceful-james** [comment]
Actually, ignore that. Here is a better one:

```bash
echo ${${$(git ls-remote --symref origin HEAD):1:1}#refs/heads/} 
```

**Comment by augustobmoura** [comment]
> Would you consider something that doesn't use `awk` at all?

Awk should be more portable than bashisms if using the [posix spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html)

> Actually, ignore that. Here is a better one:
> 
> ```shell
> echo ${${$(git ls-remote --symref origin HEAD):1:1}#refs/heads/} 
> ```
> 
> @jthegedus I think this might be a more portable solution. AFAIK it works in most shells.

This snippet is not working in my bash, it throws a bad substitution error, are you sure that a command substitution inside a variable expression works?

The problem is just the `-F'[[:space:]]*'` switch, awk already splits by multiple spaces by default we should not override this option
This command should work in every awk implementation:

``` bash
git ls-remote --symref origin HEAD | awk '{ sub(/refs\/heads\//, ""); print $2; exit }'
```

You could also remove the $2 argument in the sub invocation, so that it removes refs/heads from the line as a whole

**Comment by peaceful-james** [comment]
> are you sure that a command substitution inside a variable expression should work?

It works for me...

Anyway, your suggestion:

```
git ls-remote --symref origin HEAD | awk '{ sub(/refs\/heads\//, ""); print $2; exit }'
```

works perfectly on my system. I think this is a perfect solution.
