### ISSUE TITLE
Proper way to set the versions outside of $HOME?

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf#91]
Today I fired up prax (https://github.com/ysbaddaden/prax) only to find that it wasn't working and was printing "No version set for ruby". After fiddling with the .praxconfig file (https://github.com/ysbaddaden/prax/wiki/Ruby-Version-Managers) and doing some debugging I found that Prax invokes `ruby` from `/opt/prax/`. I finally just ran `sudo cp ~/.tool-versions /opt/prax/` to make the settings in my tool version file available to prax.

Do we have a recommended way of handling scenarios like this? To me this seems kind of ugly, and I'll probably delete the `.tool-versions` file and replace it with a symlink to the one in my home directory so I can change the versions.

I'll be adding a section on asdf to the prax wiki based on what is decided here.

**Comment by HashNuke** [comment]
@Stratus3D I think I wrote `path:/foo/bar` support for the elixir plugin because a lot of people I came across were using elixir master which was available somewhere in their local.

**Comment by Stratus3D** [comment]
I forgot about that method. Thanks!
