### ISSUE TITLE
asdf plugin update does not reset plugin staging

### ISSUE THREAD

**Issue by seivan** [asdf-vm/asdf#910]
This could be more of a feature request than a bug, but it behaves like a bug. 

If a plugin has a dependency that it installs, like `node-build`, `ruby-install`, `kerl` and sets up a default version on execution, such as: 

```shell
export RUBY_INSTALL_VERSION="${ASDF_RUBY_INSTALL_VERSION:-v0.8.1}"
```

What happens when the plugin designates a new default version? 
I was hoping to rely on `.gitignore` the reset dependencies and reinstall them on any commands after a plugin updates.
So running something like 
`asdf list all ruby` after updating the ruby plugin, should trigger a reinstall of a new version. 

That won't happen because `ruby-install/bin` is still inside the plugin directory. 
That being said, it's also under the `.gitignore` so plugin update should utilize that to reset so the users will get the actual updated dependency instead of opting in `ASDF_RUBY_INSTALL_VERSION=v0.8.1 asdf list all ruby`

**Comment by Stratus3D** [comment]
Closing this as it is a non-issue. Plugins should update tools they manually installed automatically when an inconsistency is found. Refer to the code I referenced in my comment here for an example - https://github.com/asdf-vm/asdf-ruby/issues/207#issuecomment-811134432

**Comment by seivan** [comment]
> Closing this as it is a non-issue. Plugins should update tools they manually installed automatically when an inconsistency is found. Refer to the code I referenced in my comment here for an example - [asdf-vm/asdf-ruby#207 (comment)](https://github.com/asdf-vm/asdf-ruby/issues/207#issuecomment-811134432)

How is this not an issue when it was reported as an issue? 
https://github.com/asdf-vm/asdf-ruby/issues/207#issuecomment-809799632

**Comment by Stratus3D** [comment]
>How is this not an issue when it was reported as an issue?

It was opened in error. There are no problems with the code. The user was using an old version of the plugin. This is a commonly reported issue due to user error.
