### ISSUE TITLE
jace888

### ISSUE THREAD

**Issue by jace833** [asdf-vm/asdf#915]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe similar asdf features and why they are not sufficient**
Describe asdf features you tried to use to accomplish what you wanted. Explain why they are insufficient for the task you were trying to accomplish.

**Describe workarounds you've considered**

**Additional context**
- `ASDF_DEFAULT_TOOL_VERSIONS_FILENAME` - The name of the file storing the tool names and versions. Defaults to `.tool-versions`. Can be any valid file name.

**Comment by Stratus3D** [comment]
Closing since this the fields in this issue template aren't filled out. @jace833 if this is a mistake please correct the issue and I will re-open.
