### ISSUE TITLE
`asdf plugin` commands fail to execute

### ISSUE THREAD

**Issue by CodingAnarchy** [asdf-vm/asdf#919]
**Describe the bug**

`asdf plugin` commands return an error indicating that the command is unknown: 

```
Unknown command: `asdf plugin --update all`
No plugin named plugin
```

To update the `asdf-ruby` plugin (the ultimate goal today), it was required to use `asdf plugin-update ruby`, which is not a documented command.

**To Reproduce**

1. `asdf update`
2. `asdf plugin --update all`

**Expected behavior**

`asdf` should have started to update the associated installed plugins.

**Actual behavior**

```
Unknown command: `asdf plugin --update all`
No plugin named plugin
```

### Environment

```shell
OS:
Darwin RCM-YG1H4JGH8 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

SHELL:
fish, version 3.2.1

ASDF VERSION:
v0.8.0-c6145d0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/mtanous/.asdf

ASDF INSTALLED PLUGINS:
helm                         https://github.com/Antiarchitect/asdf-helm.git
java                         https://github.com/halcyon/asdf-java.git
kubectl                      https://github.com/Banno/asdf-kubectl.git
python                       https://github.com/danhper/asdf-python.git
ruby                         https://github.com/asdf-vm/asdf-ruby.git
shellcheck                   https://github.com/luizm/asdf-shellcheck.git
```

**asdf plugins affected (if relevant)**:

**Screenshots**

**Additional context**

**Comment by arikai** [comment]
I believe this is related: https://github.com/asdf-vm/asdf/issues/899
Seems like portability issue
