### ISSUE TITLE
Question: When will a new tagged version be published?

### ISSUE THREAD

**Issue by clok** [asdf-vm/asdf#921]
> First, this tool is AWESOME. I have integrated it into the SDLC of @GoodwayGroup and we find it very useful. I have written plugins for OSS projects as well. Just wanted to make sure to let you know that this project rocks! 🤘 

**Describe the Concern**

There are some pretty great features and fixes that have been merged since the [last tagged version has been push](https://github.com/asdf-vm/asdf/releases/tag/v0.8.0) (09/07/2020)

I count ~23 merged PRs and many other direct commit fixes committed to the mainline since that last release of v0.8.0.

**Expected behavior**

It would be nice to have a consistent expectation of when a release will occur. 

While I understand I can manage the installation of the tool via git clone of specific commits, I would like to be able to refer to consistent release versions similar to how we write and maintain plugins within the project that use a `list-all` and `install` of specific published versions.

**Additional Thoughts**
- Adhering to a Semantic Versioning system for scoping may help with creating a pattern for lowering the burden of release.
- Ping me if you would like assistance with developing a release cadence and process for the project. I am eager to help.

**Comment by jthegedus** [comment]
At this time @Stratus3D is the main individual releasing new versions via the release script - https://github.com/asdf-vm/asdf/blob/master/release/tag.sh

I have had a lot of success recently using https://semantic-release.gitbook.io/semantic-release/ and if we are going to change the release process I would recommend we go that route. Correctly named PRs with Patch/Feature/Breaking nomenclature is relatively easy to follow. The unfortunate aspect is we would need to introduce some Node.js to the repo.

**Comment by clok** [comment]
Just putting my support behind @jthegedus suggestion of the semantic-release library/tool. We use it on a few projects and really like it.

**Comment by clok** [comment]
Great point by @sergei-ivanov. The `master` to `main` migration is definitely a pain point for my team as well, with regards to the tooling around maintaining updates to tools. 

So, what are the blockers for releasing a tagged version?

I would appreciate hearing from the maintainers on this. @jthegedus @Stratus3D et al.

**Comment by jthegedus** [comment]
Not the same as a release, but for those who are blocked, we have:

```
asdf update --head
```

**Comment by Stratus3D** [comment]
Working on a new version tag. Should be done within a few hours.

**Comment by Stratus3D** [comment]
@jthegedus I have updated the changelog - https://github.com/asdf-vm/asdf/blob/master/CHANGELOG.md. I am not sure if I should include documentation changes there or not. Thoughts?

**Comment by jthegedus** [comment]
I don't think docs changes are should go in there. Tools like semantic release only include changes that affect the version of the tool.

**Comment by Stratus3D** [comment]
Version 0.8.1 has been tagged!

**Comment by Stratus3D** [comment]
@jthegedus can you take a look at the changelog and let me know if I should delete those doc changes or move them somewhere else?

**Comment by jthegedus** [comment]
They can be left there, it's no harm. The utility of having them in the changelog is up for debate, I was merely saying automated release tooling tend not to have docs changes in Changelogs. Changes to the docs *site* should be, but the docs themselves I don't think matter :shrug:

**Comment by clok** [comment]
Thank you!
