### ISSUE TITLE
Alias for non-qwerty users

### ISSUE THREAD

**Issue by bagnaram** [asdf-vm/asdf#930]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
This is more of a one-off thing but an aliased install for Dvorak (Or other layout) users would be a neat addition!
Instead of `asdf`, utilize `aoeu` or `htns` for the command.

**Describe similar asdf features and why they are not sufficient**
typing `asdf` is not as intuitive as `aoeu` or `htns` on the dvorak keyboard

**Describe workarounds you've considered**
```
find $HOME/.asdf/ -type f | xargs sed -i  's/asdf/aoeu/g'
```
As well as renaming all  files from "asdf" to "aoeu" "or htns"

This functionally works! So maybe this is an option to add to the documentation!

**Comment by jthegedus** [comment]
I was waiting years for someone to raise this issue :sweat_smile:

**Comment by rienafairefr** [comment]
anecdotically, for other keyboard layouts, an alias would also be good. `qsdf` for me, on an AZERTY keyboard (damned French people /s)

**Comment by hyperupcall** [comment]
Sorry to butt in here, but doesn't popping something like the following in your .profile/.bashrc Just Work?

```sh
alias aoeu='asdf'
```

**Comment by Stratus3D** [comment]
@jthegedus thoughts on @hyperupcall 's solution? I'm fine closing this issue.

**Comment by bagnaram** [comment]
Sort of works but it doesn't take into consideration the documentation or completions and whatnot. The `sed` replace is the nuclear approach 😄

**Comment by hyperupcall** [comment]
I mean like, in my option, if you're switching to DVORAK, you're kind of asking for it (and is up to you to fix it). I really don't think that software should bend over backwards over configurations that are so rare in practice, sorry to say

**Comment by hyperupcall** [comment]
The find and sed thing is kind of a hack, and definitely go for it if you want to do it, but I don't think it should have a place in the docs. If anyone is looking into this thread trying to solve the general completion alias issue, I would recommend [this](https://github.com/cykerway/complete-alias)

**Comment by Stratus3D** [comment]
I'm going to close this as I don't believe it's an issue - every tool has a name, and while `asdf` has some disadvantages it is the name of the tool. `alias` can be used for those who want something that is easier to type.
