### ISSUE TITLE
How to update nightly version?

### ISSUE THREAD

**Issue by edshamis** [asdf-vm/asdf#931]
I installed neovim nightly version, but can't find a way to update. Can it be done?

**Comment by jthegedus** [comment]
This question should be asked on the plugin repo - https://github.com/richin13/asdf-neovim

**Comment by edshamis** [comment]
@jthegedus  Thanks, I'll ask there. I'm a new asdf user, some things are unclear. 
Can you please explain if there's a proper way to update all plugins to latest version and set it as global without doing it one by one?

**Comment by edshamis** [comment]
@jthegedus Thanks again. The docs explain everything pretty well, I just want to make sure I miss nothing.
