### ISSUE TITLE
Correct docs to delete instructions to add dependencies with Homebrew

### ISSUE THREAD

**Issue by DanielKehoe** [asdf-vm/asdf#936]
**Describe the bug**

The documentation says "Install dependencies for macoS Homebrew `brew install coreutils curl git`". Apparently this is not necessary as curl and git are already pre-installed with Xcode Command Line Tools and coreutils is installed automatically as a dependency by the Homebrew asdf formula.

**To Reproduce**

```
$ brew install asdf
.
.
.
==> Installing dependencies for asdf: m4, autoconf, automake, coreutils, libtool, libyaml, openssl@1.1, readline and unixodbc
.
.
.
```

**Expected behavior**

Asdf installation should have failed because I failed to follow the instructions and install dependencies with Homebrew prior to installing asdf with Homebrew.

**Actual behavior**

I was able to successfully install Homebrew despite the instructions telling me to install dependencies first.

### Environment

```shell
% asdf info
OS:
Darwin mini.local 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.0)

ASDF VERSION:
v0.8.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/homebrew/opt/asdf

Oohes nooes ~! No plugins installed
ASDF INSTALLED PLUGINS:
```

**Comment by DanielKehoe** [comment]
By the way, I've written a guide to [install Ruby on Mac with asdf](https://mac.install.guide/ruby/5.html) that provides updated instructions. Let me know if I got anything wrong, please.

**Comment by jthegedus** [comment]
Happy to accept a PR with the changes to the docs :smile:
