### ISSUE TITLE
Automated Releases

### ISSUE THREAD

**Issue by jthegedus** [asdf-vm/asdf#942]
**Is your feature request related to a problem? Please describe.**

Our release process is currently manual. It should be automated. We should be releasing more often and if errors are found, fix and move forward instead of taking an overly-cautious approach to releases.

People want the releases!! #921 

**Describe the solution you'd like**

Use https://semantic-release.gitbook.io/semantic-release/ to manage our release process.

It uses a semver with `fix`/`feat`/`BREAKING_CHANGE` nomenclature in commit messages to identify which part of semver to increment.

Semantic release will run in a GitHub Action and require a new config file in the repo. It will not require Node.js resources in the repo as previously thought ([guide for non-JS packages](https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-use-semantic-release-to-publish-non-javascript-packages)).

It can run arbitrary shell scripts so we will likley use a slight modification of the current release script.

It can generate additions to the Changelog with links to PRs.

While supporting many release styles, of varying complexity, I would like to keep things simple and just have a new release published on merges to the main repo branch.

**Caveats**

To upload assets of the tagged release to GitHub releases page you need the Semantic Release GitHub plugin which then requires some workarounds for protected branches - https://github.com/semantic-release/github/issues/175

Whether we **need** to upload an archive of assets to GitHub release page is up for discussion.

**Additional context**

I have been using Semantic Release for a few projects of my own with great success. See https://github.com/jthegedus/svelte-adapter-firebase/ for an example.

**Comment by NeoHsu** [comment]
That's good job!
Maybe can use some tools to help this topic,
I usually use [git-cz](https://github.com/commitizen/cz-cli) to do standardized commit message and use [standard-version](https://github.com/conventional-changelog/standard-version) to define release version .
this is my project build & release flow, FYI.

**Comment by jef** [comment]
I prefer https://github.com/google-github-actions/release-please-action. It still uses conventional commits, but I like it's agnostic pattern more. Just my two cents 😁

**Comment by jthegedus** [comment]
I really like [release-please](https://github.com/google-github-actions/release-please-action) as well, except it ends up functionally being the same or ends up making a lot of noise via many PRs if you don't merge immediately.

**Comment by jef** [comment]
> as it closes the release PR to create a new PR instead of updating

I could somewhat agree with this. If it creates a PR with 1.0.0, then a `fix:` gets committed, then 1.0.1 gets created. If a `feat:` gets committed, then it closes that PR and reopens with 1.1.0. If a `feat!:` gets committed, then it closes and opens another for 2.0.0. But if it remains to be `fix:`s and `feat:`s, then it will continually update that one `1.1.0` PR.

> It also doesn't support appending to the Changelog (google-github-actions/release-please-action#232), we would have to format the current Changelog to be the expected format of release-please before using.

This is also true and isn't ideal. Thanks for the perspective!

**Comment by jthegedus** [comment]
release-please is still probably a better fit for this repo than semantic-release.

**Comment by jef** [comment]
It's a shame about the CHANGELOG. I wonder for the first run it builds the CHANGELOG and then in follow up PR, we just update append it. Then from there, it could see its state? Would be worth trying out on a branch.

**Comment by jthegedus** [comment]
I will PR a WIP of this to see. Of note, I would like to pair automated releases with conventional commits enforced on the PR with https://github.com/amannn/action-semantic-pull-request

**Comment by jthegedus** [comment]
So it turns out it did just prepend changelog updates to our existing changelog :tada:

**Comment by jef** [comment]
Sweet! Great work @jthegedus.
