### ISSUE TITLE
Unknown Command: asdf exec ...

### ISSUE THREAD

**Issue by yoonwaiyan** [asdf-vm/asdf#943]
Cross-posting from https://github.com/asdf-vm/asdf-elixir/issues/102 as the repo isn't as active and it seems to be more relevant to report the issue here. Feel free to close either one.

**Describe the bug**

I was trying to start a phoenix server with phx.server or just mix deps.get but I received error messages from asdf:

```shell
$ mix deps.get  
Unknown command: `asdf exec elixir /Users/yoonwaiyan/.asdf/shims/mix deps.get`
/usr/local/bin/asdf: line 82: /Users/yoonwaiyan/.asdf/lib/commands/command-help.bash: No such file or directory
Please help.
```
or
```shell
$ mix phx.server
Unknown command: `asdf exec elixir /Users/yoonwaiyan/.asdf/shims/mix phx.server`
/usr/local/bin/asdf: line 82: /Users/yoonwaiyan/.asdf/lib/commands/command-help.bash: No such file or directory
```

**To Reproduce**

Tell us what actions you performed before the issue occurred

1. Update to/ensure it's the latest version of asdf
2. `cd` to/create a Elixir/Phoenix project
2. Run either of these commands on terminal: `phx.server` or `mix deps.get`
2. Observe the error messages as shown above

**Expected behavior**

Expecting Elixir commands to be run without errors

**Actual behavior**

Received errors, as described in the Description section

### Environment
```shell
$ brew info asdf                                                                                                         127 ↵
asdf: stable 0.8.0 (bottled), HEAD
Extendable version manager with support for Ruby, Node.js, Erlang & more
https://asdf-vm.com/
Conflicts with:
  homeshick (because asdf and homeshick both install files in lib/commands)
/usr/local/Cellar/asdf/0.8.0_1 (116 files, 243.9KB) *
  Poured from bottle on 2021-05-18 at 10:50:59
```

```shell
$ asdf info                                                                                                                 
version: v0.5.0
```

macOS version: 11.2.3

**asdf plugins affected (if relevant)**:
asdf-elixir

**Comment by jthegedus** [comment]
We just published a new version of `asdf`. Can you:
1. update `asdf` to latest
2. update your elixir plugin
3. test the error is still present
4. if so, update your `asdf info` output for us

Thanks.

**Comment by yoonwaiyan** [comment]
Oh I have to update directly from the plugin instead of brew. It works now, thanks.
