### ISSUE TITLE
`asdf info` should show sha's of plugins and distance behind their remotes

### ISSUE THREAD

**Issue by jthegedus** [asdf-vm/asdf#945]
**Is your feature request related to a problem? Please describe.**

`asdf info` is really useful information to debug with, however, the list of plugins is less useful as we do not know any statistics about the plugin state

**Describe the solution you'd like**

I would like to print both:
- the `sha` or `ref` of the checked-out plugin
- the `distance` (commits) behind the default branch of the plugin repo

Distance might suffice, though `ref` would be useful once we have plugin versioning support.

**Describe similar asdf features and why they are not sufficient**

**Describe workarounds you've considered**

We usually ask people to update their plugins and the `asdf` core and investigate if their issue still persists.

**Additional context**

- Notify users of core or plugin updates - #725 
- Add versioning to plugin add command - #916

**Comment by jthegedus** [comment]
I think implementing distance (commits) behind the remote will be a lot of work to implement, especially when we have `--refs` already to leverage and get half of this feature for little dev cost.

**Comment by Stratus3D** [comment]
Yeah, I think just displaying the refs would help us a lot and be very easy to implement.
