### ISSUE TITLE
Remove banned process substitution & force PR base branch merge

### ISSUE THREAD

**Issue by jthegedus** [asdf-vm/asdf#948]
**Describe the bug**

Process substitution was banned in #863 but I merged #881 first which included a process substitution. This was not caught because we do not require PRs to be update with `master` before merge.

**To Reproduce**

Reported: https://github.com/asdf-vm/asdf/commit/a7d3661f6c53b24ae1c21e93f94209f3af243349#r51098840

Code: https://github.com/asdf-vm/asdf/blob/156a82cc494e97955ddf44d801472ca105159338/lib/commands/command-list-all.bash#L45

**Expected behavior**

- [x] no process substitution
- [x] PRs should be required to be up to date with master

**Comment by jthegedus** [comment]
I have added the branch protection rule to enforce branches are synced with `master` before merging:

<details>
<summary>Before & After Images</summary>

![asdf-branch-protection-before](https://user-images.githubusercontent.com/20798510/119058625-15a14400-ba12-11eb-8eea-50a817bdb005.png)

![asdf-branch-protections-after](https://user-images.githubusercontent.com/20798510/119058627-18039e00-ba12-11eb-8547-34e532ee8523.png)

</details>

We can disable this if it becomes a nuisance.

**Comment by Stratus3D** [comment]
Closing this as I have merged a PR to remove the process substitution code from the `list-all` command. 🎉
