### ISSUE TITLE
latest targets for asdf global/local

### ISSUE THREAD

**Issue by BeastyBlacksmith** [asdf-vm/asdf#951]
It seems inconsistent to me that I can do
```
asdf install <lang> latest
```
but not 
```
asdf global <lang> latest
```

**Comment by jthegedus** [comment]
PR for this is in https://github.com/asdf-vm/asdf/pull/633

**Comment by jthegedus** [comment]
This was closed in #633. #994 will include is in the next release, until then `asdf update --head` should give you what you're after.
