### ISSUE TITLE
Installation - asdf.sh and asdf.bash don't work on 20.0.4 LTS - Bash

### ISSUE THREAD

**Issue by Murilo001** [asdf-vm/asdf#953]
**To Reproduce**

Run following commands conform docs
1. sudo apt install curl git
2 . git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1
3. . $HOME/.asdf/asdf.sh
4. . $HOME/.asdf/completions/asdf.bash

Result:
`
bash: /home/user/.asdf/asdf.sh: line 10: syntax error near unexpected token `elif'
'ash: /home/user/.asdf/asdf.sh: line 10: `elif [[ "$_under" == *".sh" ]]; then
: command not found
bash: /home/user/.asdf/completions/asdf.bash: line 3: syntax error near unexpected token `$'{\r''
'ash: /home/user/.asdf/completions/asdf.bash: line 3: `_asdf () {
: command not found
bash: /home/user/.asdf/asdf.sh: line 10: syntax error near unexpected token `elif'
'ash: /home/user/.asdf/asdf.sh: line 10: `elif [[ "$_under" == *".sh" ]]; then
: command not found
bash: /home/user/.asdf/completions/asdf.bash: line 3: syntax error near unexpected token `$'{\r''
'ash: /home/user/.asdf/completions/asdf.bash: line 3: `_asdf () {
`

Sorry for my English

**Comment by jthegedus** [comment]
@Murilo001 This is likley a setup issue as no other users are reporting problems. Can you share your `.bashrc` contents?

**Comment by chipster1234** [comment]
I also have this issue. Just installed 20.0.4 LTS and run 'asdf global ruby 2.3.6' and it says 
No such plugin: ruby

**Comment by jthegedus** [comment]
@chipster1234 Please read the [Getting Started Guide](https://asdf-vm.com/guide/getting-started.html#_1-install-dependencies). `asdf` does not support any tools out of the box, you need to install a plugin for each tool.

**Comment by Stratus3D** [comment]
@Murilo001 your error looks similar to the one posted in this issue - https://github.com/asdf-vm/asdf/issues/732 Are you using bash or ash shell? The shell output you included doesn't appear to be formatted correctly in the ticket.

I am fairly certain I encountered a similar issue somewhat recently but I can't remember what the problem was.

**Comment by tomako** [comment]
@jthegedus I have the same problem as @Murilo001 had earlier.
WSL2 environment: Ubuntu 20.04.3 LTS, bash 5.0.17

```
$ . $HOME/.asdf/asdf.sh
-bash: /home/tamas/.asdf/asdf.sh: line 8: syntax error near unexpected token `elif'
'bash: /home/tamas/.asdf/asdf.sh: line 8: `elif [[ "$_under" == *".sh" ]]; then
```

Here is my `.bashrc`
```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias bat='batcat'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
```

**Comment by holtalanm** [comment]
> @Murilo001 This is likley a setup issue as no other users are reporting problems. Can you share your `.bashrc` contents?

I am getting this exact same error.  

On a completely fresh Xubuntu 20.04 install.

**Comment by Stratus3D** [comment]
@holtalanm I am confused. You said you are on Xubuntu 20.04, but #1187 is for WSL Ubuntu. Which base OS are you running? Windows or Xubuntu?

**Comment by holtalanm** [comment]
Xubuntu.    I thought I made that clear.  My assumption is that #1187 is affecting more than just WSL installs, since my machine was _not_ WSL.

It has been a few weeks since I resolved this, so I can't speak for what the underlying issue was.  I was just trying to install ruby, so I ended up just using rbenv.

**Comment by jthegedus** [comment]
Copied from my comments on #1187

---

So two things to keep in mind when using WSL2 environment:

1. From our [FAQ](https://asdf-vm.com/learn-more/faq.html)
>Importantly, WSL2 is only expected to work properly when the current working directory is a Unix drive and not a bound Windows drive.

2. The error reported shows:
```
bash: /home/USER/.asdf/asdf.sh: line 9: syntax error near unexpected token `elif'
'ash: /home/USER/.asdf/asdf.sh: line 9: `  elif [[ "$_under" == *".sh" ]]; then
bash: /home/USER/.asdf/completions/asdf.bash: line 1: syntax error near unexpected token `$'{\r''
'ash: /home/USER/.asdf/completions/asdf.bash: line 1: `_asdf() {
```

The 3rd line here shows an unexpected token `\r` which is likely due to this repository being cloned to a non-Unix location or by using Git in a Windows environment. Changing your line endings to LF from CRLF might fix this.

Nonetheless, I am going to close this issue as OP has not responded and other participants have used other solutions.

**Comment by hyperupcall** [comment]
@alexey-sh That looks like an issue with the [gitleaks](https://github.com/jmcvetta/asdf-gitleaks) plugin - their code has an unbound variable issue that's exiting the program.
