### ISSUE TITLE
Permission denied on commands

### ISSUE THREAD

**Issue by L3K0V** [asdf-vm/asdf#954]
**Describe the bug**

After latest asdf update, I'm not able to use it at all. It's a homebrew installation and everything worked before.
If any experience this error - is there any workaround or a fix? I have checked and follow some steps from the Homebrew common issues from the pined issue but without any success. 

I tried to reinstall Xcode cli tools and then to reinstall the asdf from homebrew

```
$ asdf current
/usr/local/opt/asdf/bin/asdf: line 74: /usr/local/opt/asdf/lib/commands/command-current.bash: Permission denied
/usr/local/opt/asdf/bin/asdf: line 74: exec: /usr/local/opt/asdf/lib/commands/command-current.bash: cannot execute: Undefined error: 0
```

**To Reproduce**

Run some asdf command

**Expected behavior**

To be able to execute asdf commands

**Actual behavior**

```shell
/usr/local/opt/asdf/bin/asdf: line 74: /usr/local/opt/asdf/lib/commands/command-info.bash: Permission denied
/usr/local/opt/asdf/bin/asdf: line 74: exec: /usr/local/opt/asdf/lib/commands/command-info.bash: cannot execute: Undefined error: 0
```

Whatever asdf command I execute

### Environment

Cannot get the asdf environment

```shell
/usr/local/opt/asdf/bin/asdf: line 74: /usr/local/opt/asdf/lib/commands/command-info.bash: Permission denied
/usr/local/opt/asdf/bin/asdf: line 74: exec: /usr/local/opt/asdf/lib/commands/command-info.bash: cannot execute: Undefined error: 0
```

**asdf plugins affected (if relevant)**:

**Screenshots**

**Additional context**

**Comment by L3K0V** [comment]
I have tried to `chmod +x` the commands but after that when execute `asdf current` there new error:

```
$ cd /usr/local/opt/asdf/lib/commands
$ chmod +x *.bash
$ asdf current
/usr/local/opt/asdf/lib/commands/command-plugin-list.bash: line 5: get_plugin_path: command not found
/usr/local/opt/asdf/lib/commands/command-plugin-list.bash: line 48: display_error: command not found
```

**Comment by jthegedus** [comment]
@L3K0V Can you answer the following questions/share configs:

- How did you update, `asdf update` or via Brew?
- Did you update to HEAD or just the latest tag?
- What version where you on beforehand? Does going back to the previous version fix the issue?
- Have you made other changes to your system that may affect `asdf`?
- Can you share your `zshrc`/`bashrc` file?

**Comment by L3K0V** [comment]
Hey @jthegedus,

Thanks for the response.

- How did you update, asdf update or via Brew?
> via Brew
- Did you update to HEAD or just the latest tag?
> To latest tag, now I tried  with the HEAD and it's working
- What version where you on beforehand? Does going back to the previous version fix the issue?
> Not sure what was the previous version and didn't try to get to previous version, to be honest. I will check and report again.
- Have you made other changes to your system that may affect asdf?
> No
- Can you share your zshrc/bashrc file?
> Everything was working before and is configured following asdf webpage https://github.com/L3K0V/dotfiles/blob/master/.zshrc

**Comment by jthegedus** [comment]
@L3K0V Thanks for sharing. Are you happy to be using `HEAD`?

**Comment by L3K0V** [comment]
@jthegedus short-term yes, but I prefer to use stable tags versions instead. Now I'm stuck with the HEAD as the terminal became unusable because many commands fails even system ones.. 😢 

Is this some known issue on the latest tag?

**Comment by jthegedus** [comment]
>many commands fails even system ones

This is odd behaviour.

>Is this some known issue on the latest tag?

Not at this time. You are the first to report this issue. Given the volume of Homebrew users (~10k installs in the last 30 days) I would expect others to be reporting issues if this was a significant bug with `asdf`.

Of note, we do not maintain the Homebrew Formulae, it is community driven. It may be caused on that end in which case my suggestion would be trying the `git clone` installation.

**Comment by jthegedus** [comment]
@L3K0V Have you tried the tagged versions again? The version causing you issue was `0.8.1` with `0.8.0` being the stable version before that.

**Comment by L3K0V** [comment]
Hello @jthegedus, for now I'm happy with the HEAD version from before two days. I'm actively using the machine for work now and the weekend I will have some time to do some checks and can report then.

**Comment by joekinley** [comment]
So I have this issue too, but only on MacOS and only when I use it in docker, while being in a volume.
Having it NOT in a volume does work, so maybe it is specific to some filesystem magic in MacOS?

Here is my files:
```
# Dockerfile
FROM ubuntu:focal
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install -y curl git
ENTRYPOINT . $HOME/.asdf/asdf.sh && asdf
```

```
# Makefile
default: help

.PHONY: help install run

help:
	@echo 'Run: make install to install the test'
	@echo 'Run: make run to see the result'

install:
	@git clone https://github.com/asdf-vm/asdf.git asdf --branch v0.8.1
	@docker-compose build

run:
	@docker-compose up
```

```
# docker-compose.yml
services:
  asdf: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./asdf:/root/.asdf
```

To test run:
`$ make install && make run`

You will see the following output:
```
Attaching to asdftest_asdf_1
asdf_1  | /root/.asdf/bin/asdf: line 74: /root/.asdf/lib/commands/command-help.bash: Permission denied
asdf_1  | /root/.asdf/bin/asdf: line 74: /root/.asdf/lib/commands/command-help.bash: Success
asdftest_asdf_1 exited with code 126
```

**Comment by joekinley** [comment]
After some research, I assume the behavior described here is what happens: https://stackoverflow.com/questions/53906611/docker-compose-throws-permission-denied-on-mac

**Comment by jthegedus** [comment]
Closing this issue as OP resolved issues using `brew update --HEAD` and it doesn't appear to affect a large number of other users.

**Comment by wilsonsilva** [comment]
```
> $ bundle  install                                                                                                                                                                                                                             
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake 13.0.6
Using public_suffix 5.0.1
Using ast 2.4.2
Using bundler 2.4.9
Using diff-lcs 1.5.0
Using hashdiff 1.0.1
Using rspec-support 3.12.0
Using mini_mime 1.1.2
Using unicode-display_width 2.4.2
Using multi_xml 0.6.0
Using dotenv 2.8.1
Using regexp_parser 2.7.0
Using json 2.6.3
Using method_source 1.0.0
Using ruby-progressbar 1.13.0
Using rainbow 3.1.1
Using rexml 3.2.5
Using rspec-mocks 3.12.5
Using httparty 0.21.0
Using vcr 6.1.0
Using parallel 1.22.1
Using crack 0.4.5
Using ruby-openai 3.7.0
Using senior 0.1.0 from source at `.`
Using addressable 2.8.4
Using rspec-core 3.12.1
Using parser 3.2.2.0
Using webmock 3.18.1
Using rspec-expectations 3.12.2
Using rubocop-ast 1.28.0
Using rspec 3.12.0
Using rubocop 1.49.0
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/fuzzy_match: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/pod: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/sandbox-pod: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/xcodeproj: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/fuzzy_match: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/pod: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/sandbox-pod: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/xcodeproj: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/fuzzy_match: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/pod: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/sandbox-pod: Permission denied
/opt/homebrew/opt/asdf/libexec/lib/commands/reshim.bash: line 104: /Users/wilson/.asdf/shims/xcodeproj: Permission denied
```

`--HEAD` is an invalid option. For future reference, I resolved this problem by running `brew update` and then `brew upgrade asdf`

**Comment by hyperupcall** [comment]
@wilsonsilva For the future, `brew update --head` would work as well

**Comment by devclaire92** [comment]
Hello @azlekov Running this command works for me. 
sudo chown -R $USER /Users/claireannbayoda/.asdf/*
This command changes the owner of all files and directories under /Users/claireannbayoda/.asdf/* and all its subfolder to the current user.
