### ISSUE TITLE
Feat: add post installation hook to import package and install them in new version

### ISSUE THREAD

**Issue by rubiin** [asdf-vm/asdf#955]
**Is your feature request related to a problem? Please describe.**

Something similar to a functionality in NVM(node version manager). While installing a new version, i can install all the packages installed globally on older version,

**Describe the solution you'd like**

Allow a command that lets you specify a post hook to install packages after the new version has been installed

**Describe similar asdf features and why they are not sufficient**

I cannot find anything relatively close to this

**Describe workarounds you've considered**

**Additional context**

**Comment by jthegedus** [comment]
@rubiin The core of `asdf` already supports this type of workflow. Happily, [`asdf-nodejs`](https://github.com/asdf-vm/asdf-nodejs/#default-npm-packages) already implements this. Other plugins also offer this functionality. If a plugin does not, it is the plugin that needs code changes and so your requests should be on those repos.

Closing this as it already is implemented on the associated plugin.
