### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Lewiscowles1986** [asdf-vm/asdf#964]
**Is your feature request related to a problem? Please describe.**
Your site blinds me, even on 0% brightness of my display.

**Describe the solution you'd like**
Either a button or a media query to switch the colors, would be lovely.

**Describe similar asdf features and why they are not sufficient**
I'm actually trying to read up on "why ASDF" and find out what is offered, versus the tools I use, or have used like phpbrew, rvm, nvm, pyenv, goenv, etc.

**Describe workarounds you've considered**
I might actually just use GitHub which has dark-mode.

**Additional context**
As I get older, my eyes are just fussier I guess.

**Comment by jthegedus** [comment]
We may add dark-mode to the site when we migrate to a different tool in #862

**Comment by Stratus3D** [comment]
Closing this ticket as we can handle this under #862.
