### ISSUE TITLE
.asdfrc for macOS java_home not working

### ISSUE THREAD

**Issue by ColtonIdle** [asdf-vm/asdf#972]
I created the asdfrc file and added that key value pair

Proof
```
coltonidle@MacBook-Air ~ % cat ~/.asdfrc 
java_macos_integration_enable = yes

coltonidle@MacBook-Air ~ %
```

Running `java_home` or `/usr/libexec/java_home` greets me with this error

```
coltonidle@MacBook-Air ~ % /usr/libexec/java_home
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```

I'm on a brand new m1 macbook where I just installed zulu. echo $JAVA_HOME shows `/Users/coltonidle/.asdf/installs/java/zulu-11.48.21/zulu-11.jdk/Contents/Home`

Am I doing something wrong?

**Comment by jthegedus** [comment]
Can you please share how you resolved your issue should someone find this after having the same problem?

**Comment by ColtonIdle** [comment]
@jthegedus whoops! I didn't actually resolve this. I just opened the bug in the wrong place but I think I will reopen it as I can see why it would make sense to be open in this repo.

https://github.com/halcyon/asdf-java/issues/149

**Comment by jthegedus** [comment]
> I just opened the bug in the wrong place

Let's see if the `asdf-java` maintainers discover it is an issue in the `asdf` core before opening here then. Thanks for explaining.

**Comment by ColtonIdle** [comment]
@jthegedus no response from the maintainer, but I was able to figure out a solution.

I wonder if this is something `asdf` could solve/prevent?

**Comment by jthegedus** [comment]
It is not clear what the specific issue is with the plugin, so I cannot comment on whether there is a solution possible in the core or if it would be worth the effort
