### ISSUE TITLE
Need to specify branch name for plugin testing

### ISSUE THREAD

**Issue by hickey** [asdf-vm/asdf#974]
**Describe the bug**

Both GitHub and GitLab are moving away from using the `master` branch name. In the `command_plugin_test.bash` script the branch name is hard coded. [ref](https://github.com/asdf-vm/asdf/blob/79dc43fb5ee2210a5e0284b8a3bfce85d4d39e16/lib/commands/command-plugin-test.bash#L9)

**To Reproduce**

Developing a new plugin for [vcluster](https://github.com/loft-sh/vcluster/) and the repo that I am developing in uses `main` as the primary branch. Creating a new repo and committing any plugin should show the same results of unable to check out `master` when `asdf plugin test PLUGIN URL_TO_REPO` is executed. 

I found #385 and attempted to use `./.git` to see if I could _trick_ the plugin test command to use what is already checked out, but as you can see in the output below, `master` is still attempting to be checked out.

**Expected behavior**

Ability to specify the branch name that plugin test will run against.

**Actual behavior**

Branch name is hard coded and developer is forced into using `master` as the branch name. 

### Environment

```shell
❯ asdf info
OS:
Darwin rebo.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.0)

ASDF VERSION:
v0.8.0-c6145d0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/hickey/.asdf

ASDF INSTALLED PLUGINS:
aria2                        https://github.com/asdf-community/asdf-aria2.git
bat                          https://gitlab.com/wt0f/asdf-bat.git
direnv                       https://github.com/asdf-community/asdf-direnv.git
dive                         https://github.com/looztra/asdf-dive.git
dyff                         https://gitlab.com/wt0f/asdf-dyff.git
eksctl                       https://github.com/elementalvoid/asdf-eksctl.git
fd                           https://gitlab.com/wt0f/asdf-fd.git
helm                         https://github.com/Antiarchitect/asdf-helm.git
julia                        https://github.com/rkyleg/asdf-julia.git
k9s                          https://github.com/looztra/asdf-k9s.git
kind                         https://github.com/johnlayton/asdf-kind.git
kubectl                      https://github.com/Banno/asdf-kubectl.git
kubectx                      https://gitlab.com/wt0f/asdf-kubectx.git
kubeval                      https://github.com/stefansedich/asdf-kubeval.git
kustomize                    https://github.com/Banno/asdf-kustomize.git
oc                           https://github.com/sqtran/asdf-oc.git
ripgrep                      https://gitlab.com/wt0f/asdf-ripgrep.git
skaffold                     https://github.com/kristoflemmens/asdf-skaffold.git
sops                         https://github.com/feniix/asdf-sops.git
stern                        https://github.com/looztra/asdf-stern.git
terraform                    https://github.com/Banno/asdf-hashicorp.git
terragrunt                   https://github.com/lotia/asdf-terragrunt.git
tilt                         https://github.com/eaceaser/asdf-tilt.git
vault                        https://github.com/Banno/asdf-hashicorp.git
vcluster                     /Users/hickey/Projects/asdf-vcluster/.
yq                           https://github.com/sudermanjr/asdf-yq.git
```

**Screenshots**

![image](https://user-images.githubusercontent.com/39609/122309766-bf65da80-cec3-11eb-914d-927911f8161a.png)

**Additional context**

I have side stepped the issue temporarily by creating a `master` branch and pushing it back into the repo, but that means that I have to keep `master` in sync with the primary branch for testing to be valid. Not ideal, but it will work until this gets resolved.

**Comment by hickey** [comment]
I realized as I was creating this issue that using `./.git` for the repo location had its own problem where it was a clone of the repo that did not have any other branch references. So `git` was a bit more confused in the screen shot above. 

Here is the original CI job that failed using a URL to point to the repo which is slightly more accurate for this issue.
![image](https://user-images.githubusercontent.com/39609/122311240-998e0500-cec6-11eb-8ec0-bd1fb3bbbc80.png)

**Comment by jthegedus** [comment]
Thanks for raising this. The default should definitely change from `master`. Ideally to the default on the remote as `asdf plugin update` does.

Having said that, this feature exists. The usage is:

```
asdf plugin test <name> <plugin-url> --asdf-plugin-gitref main
```

This is mentioned in the [Testing Plugins](https://asdf-vm.com/#/plugins-create?id=testing-plugins) section of the docs.

**Comment by hickey** [comment]
Ah, very good. Yes, I have not looked at the testing docs in quite some time. Most of the plugins I have created are just iterations on the previous one. I can live with the switch as that is all that I was really looking for. 

Thank you for the info.
