### ISSUE TITLE
Installing `miniconda3-latest` for Python "steals" system binaries

### ISSUE THREAD

**Issue by farzadmf** [asdf-vm/asdf#979]
**Describe the bug**

I have installed Python `3.9.5` and _almost_ everything is good. Now I install `miniconda` using the command `asdf install python miniconda3-latest`.

What's happening is that, for some reason, there's an `xz` executable in `~/.asdf/installs/python/miniconda3-latest/bin` and I think because of that `asdf` is creating a shim for `xz` to point to that binary, and the shim content is this:
```bash
#!/usr/bin/env bash
# asdf-plugin: python miniconda3-latest
exec /opt/asdf-vm/bin/asdf exec "xz" "$@"
```

But the "real" `xz`, being a compression tool used system-wide, is located as `/usr/bin/xz`.

Now, because of the shim being created by `asdf`, since my global Python version is `3.9.5`, I basically lose `xz` and can only run it if I switch to the `miniconda3-latest` environment.

**To Reproduce**

1. Install Python `3.9.5` using `asdf install python 3.9.5`
2. Run `xz --help` and you'd see an output
3. Install `miniconda` using `asdf install python miniconda3-latest`
4. Open a new shell so that the shims are picked up
4. Run `xz --help` and you see the following message:
```
No preset version installed for command xz
Please install a version by running one of the following:

asdf install python 3.9.5

or add one of the following versions in your config file at /home/farzad/.tool-versions
python miniconda3-latest
```

**Expected behavior**

Installing a version using `asdf` shouldn't create shims for system-wide binaries, which will result in those binaries being only accessible in specific environments and versions

**Actual behavior**

The shim created by `asdf` is basically stealing the system binary and making it inaccessible.

Also I think it's worth mentioning that the error message, in my opinion, is confusing and you'd have no idea what to do after you read the message.

### Environment

```shell
OS:
Linux farzadcomp 5.12.10-1-MANJARO #1 SMP PREEMPT Thu Jun 10 15:26:25 UTC 2021 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-pc-linux-gnu)

ASDF VERSION:
v0.8.1

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/asdf-vm

ASDF INSTALLED PLUGINS:
direnv                       git@github.com:asdf-community/asdf-direnv.git
flux2                        git@github.com:tablexi/asdf-flux2.git
nodejs                       git@github.com:asdf-vm/asdf-nodejs.git
please                       git@github.com:asdf-community/asdf-please.git
python                       git@github.com:danhper/asdf-python.git
richgo                       git@github.com:paxosglobal/asdf-richgo.git
ruby                         git@github.com:asdf-vm/asdf-ruby.git
rust                         git@github.com:code-lever/asdf-rust.git
skaffold                     git@github.com:kristoflemmens/asdf-skaffold.git
yarn                         git@github.com:twuni/asdf-yarn.git
```

**asdf plugins affected (if relevant)**:

I think it's possible for this to happen for any plugin that would have some binaries with the same name as system binaries, but in my case, it's Python that's affected.

**Screenshots**

N/A

**Additional context**

I chose `xz` just as an example, but it happens for a lot of system binaries (becoming inaccessible because of the created shims)

**Comment by spywhere** [comment]
You can specify `system` as a version, and ASDF will use a system binary. I haven't use it myself, but that's seems like solution to me.

https://asdf-vm.com/#/core-manage-versions?id=fallback-to-system-version#/core-manage-versions?id=fallback-to-system-version#/core-manage-versions?id=fallback-to-system-version

**Comment by farzadmf** [comment]
Unfortunately, that's not a solution because using `asdf local|shell|... <name> system` seems to only to apply to whole plugins. Quoting the example from the docs: `asdf local python system` is telling to use `python` from system.

What I'm talking about are the shims to binaries installed via plugins.

**Comment by jthegedus** [comment]
Your reproduction is producing the *expected* output because you have not told `asdf` which version of python to use and it is finding both `miniconda3` and your global python. **So you need to tell `asdf` which version of the tool to use.**

Because it doesn't know you want to use the `system` version, `asdf` will try and use the shim for all associated binaries, like `xz`. When it tries to use the shimmed version it then identifies again that it doesn't know which `xz` to use from which python.

If you follow the suggestion by @spyware and tell `asdf` to use your `system` python, then it should use your system `xz` also.

**Comment by Stratus3D** [comment]
@jthegedus perhaps instead of the default behavior being the no version set error messages, perhaps asdf should default to using the system version? I can see pros and cons to both defaults, but for some a default to `system` may be desirable.

**Default to `system` version**

Pros:

* Won't break any existing setups

Cons:

* User might accidentally end up using `system` version without knowing about it

**Default to no version**

Pros:

* Forces the user to be explicit

Cons:

* Will break existing setups when no version is set

**Comment by jthegedus** [comment]
I think the "default to no version" is easier to debug for us. When this issue surfaces it is easy to classify than issues that may arise from "default to system version", and the resolution is documented well enough that even community members like @spywhere can chime in and suggest the fix.

**Comment by farzadmf** [comment]
I totally understand what you guys are saying, but from my experience, it was super confusing. Maybe it's `miniconda`'s fault to include those binaries, but it took me a good while to figure out my system binaries are gone because I've installed a version of Python that's not my main version.

Also, taking `xz` as an example, I see that it's a binary file in `/usr/bin`, and unless I'm missing something, it doesn't have anything to do with Python either, so IMHO, it's very confusing that to be able to use a system binary, I need to do `asdf python system`.

The situation becomes much worse when there's another program expecting to find a binary in the system and it fails, and that happened to me: one of them complained about the binary not being found, but the other one was silently failing.

And I think you guys can agree that the error message is only adding to the confusion

**Comment by Stratus3D** [comment]
@farzadmf I agree that's an unpleasant experience. I haven't looked at any of he python/miniconda code, but I'd blame them for including another program. It's possible there be a good reason for them to include it.

@jthegedus I guess I'd lean more towards default to the `system` version as the issue can easily be diagnosed with a quick call to `asdf current python`

**Comment by farzadmf** [comment]
> but I'd blame them for including another program

I agree, and I'm not sure why they do that :thinking: 

> can easily be diagnosed with a quick call

This one is a bit trickier actually. Even last night that I sent the reply, the second situation was happening to me (a program silently crashing because of a binary it needs), and I needed to reshim everything in `asdf` to make it work (I still don't know what it's searching for)

But I guess I can close the issue now since I don't think any change will be done here (although I think the message can use some love :wink: )

Although I must say I got some insight from the replies, which made me think maybe I shouldn't consider `asdf` as a "global" replacement for all the tools that provide global binaries to the system, because that might result in some issues that are not as sttraightforward to troubleshoot.

**Comment by danhper** [comment]
This is indeed a known issue and I agree, is a bit annoying.
The best workaround for now is to set the system version as a fallback when using non-anaconda Python: `asdf global python 3.9.5 system`
This will allow asdf to use the system binaries when needed.
A probably better fix would be to follow the pyenv blacklist approach, see https://github.com/pyenv/pyenv/blob/master/pyenv.d/rehash/conda.d/default.list
I don't think we have such a feature in asdf currently.
@Stratus3D @jthegedus Any thoughts?

**Comment by Stratus3D** [comment]
@danhper can you elaborate a little on what the pyenv blacklist approach is? I'm not familiar with it. Is the blacklist a list of commands that pyenv won't add to the user's $PATH?
