### ISSUE TITLE
Use node instead of nodejs

### ISSUE THREAD

**Issue by viztor** [asdf-vm/asdf#983]
**Is your feature request related to a problem? Please describe.**
just want to type two less, and be consistent with the command name.

**Describe the solution you'd like**
use node instead of nodejs

**Describe similar asdf features and why they are not sufficient**
nodejs is two letter more than node and inconsistent with the command name

**Describe workarounds you've considered**
alias, but better if they are built in

**Additional context**
there is unlikely anything would take the node name in the future, and that's what it's called commonly.

**Comment by Stratus3D** [comment]
You can use whatever name for the plugin you choose if you add it with the long `plugin add` syntax: 

```
asdf plugin add foobar  https://github.com/asdf-vm/asdf-nodejs.git
```

For backwards compatibility reasons we won't be changing to name when using the shorter `asdf plugin add nodejs` syntax.
